/**
 * M07a CONCERT BASS DRUM — the pages' words (engine/model/copy.ts). The
 * starting-points voice (owner ruling 2026-10-04): no source, brand or model
 * names, no badges; tendencies, never results.
 */
import type { LessonCopy } from '../../engine/model/copy.ts';
import { R } from './model.ts';

export const CBD_COPY: LessonCopy = {
  variantKey: 'STAND',
  variantShort: { set: 'stand locked' },
  sceneSubject: { set: 'a 36 × 16 in concert bass drum hanging in its tilting stand, the heads facing sideways' },
  viewTag: { side: 'SIDE · CUTAWAY', top: 'TOP · CUTAWAY' },
  axes: {
    x: { plus: 'toward the player', minus: 'toward the far head', label: 'ALONG the drum', blurb: 'Toward the player or toward the far head (x). Distance is read from the head the zone names.' },
    y: { plus: 'below centre', minus: 'above centre', label: 'HEIGHT', blurb: 'Up or down (y), from the drum’s centre line.' },
    z: { plus: 'toward the conductor', minus: 'away from the conductor', label: 'ACROSS', blurb: 'Toward or away from the conductor (z): the heads face sideways, so the conductor is off to one side.' },
  },
  instrument: {
    figureBadge: 'A 36 × 16 in concert bass drum, cut open, in its tilting stand',
    figureLabel: 'Side view of a 36 by 16 inch concert bass drum, cut open, hanging on its pivots in a tilting stand on locking casters: the playing head on the right where the player stands with a large felt mallet, the far head on the left.',
    partsBadge: 'A 36 × 16 in concert bass drum, cut open · tap a part to name it',
    partsLooking: { side: 'Side view · the drum cut open · the player at the right', top: 'Top view · the drum cut open · the conductor below' },
    partsIdle: 'The mallet strikes the playing head; the far head, the air inside and the shell ring with it. The stand holds it at the angle the crew set — and only the crew moves it.',
    variantNotes: {},
  },
  sound: {
    strikes: [
      { id: 'c', label: 'CENTRE', mm: 0, blurb: 'The exact centre of the head.' },
      { id: 'mid', label: 'MIDDLE REGION', mm: R * 0.5, blurb: 'Between the centre and the edge — a usual starting area for players.' },
      { id: 'edge', label: 'NEAR THE EDGE', mm: R * 0.85, blurb: 'Close to the hoop — explore what it drives.' },
    ],
    strikeDefault: 'mid',
    striker: 'MALLET',
    strikerPhrase: 'the mallet',
    subject: 'Side view of the concert bass drum, cut open',
    looking: { set: 'Side view · the drum cut open · the player at the right' },
    cells: [
      { k: 'PLAYING', at: ['AT REST', 'PUSHED IN', 'PUSHED IN', 'PUSHED IN'], flex: 1.1 },
      { k: 'FAR HEAD', at: ['AT REST', 'AT REST', 'PUSHED OUT', 'PUSHED OUT'], flex: 1.1 },
      { k: 'SOUND', at: ['—', '—', '—', 'SIDEWAYS'], flex: 1 },
    ],
    reveal: 'The squeezed air pushes the far head OUTWARD — both heads move the same way at that moment. The two heads are coupled through the air inside.',
    after: 'Then both heads keep ringing for a long, low bloom. How long depends on the tuning, the mallet and the player’s damping — the player may stop either head by hand.',
    shapesNotes: [
      'A shape is set moving only as much as the head moves at the strike point in that shape. At the exact centre, every shape with a still line across the head stands still — so a centre strike drives only the ring-shaped ones. Players choose the area for the colour they want.',
      'This is a simplified head in empty space. On a real drum the air inside and the second head pull these numbers around — the next step shows the two heads working together.',
    ],
    coupledSubject: 'Side view of the concert bass drum',
    coupledNote: 'One stroke sets both heads going; the sound you hear is the two together, through the air between them.',
    silentNote: 'This lab never plays a sound and draws no frequency curve for the drum: how a real concert bass drum sounds depends on the drum, its heads, the tuning, the mallet and the player. The pictures show where the sound comes from and where it leaves.',
  },
  setting: {
    kitA11y: 'The percussion section from above, at the back of an orchestra: the concert bass drum in its tilting stand with its heads facing along the row and its player beside the playing head; the timpani, the concert snare, a suspended cymbal and the trap table nearby; a row of brass in front.',
    kitLanding: 'Tap anything around the bass drum — or step through ITEM — to see what it means for a bass-drum mic. There is nothing to answer yet.',
    kitIdle: 'The concert bass drum stands in the percussion row, its heads facing sideways along the stage, its player beside the playing head. Around it: the rest of the percussion, and the brass in front.',
    leftHanded: 'Layouts vary from one orchestra to the next — and which head is played depends on the player. Check the real stage plan and the playing side before placing anything.',
    stageA11y: 'The orchestra on an amplified stage, from above: the percussion at the back, the conductor and the audience at the front, PA stacks at the front corners, and two floor monitors near the percussion.',
    studioA11y: 'The orchestra recorded in a hall, from above: the main pair of microphones over the conductor, the hall’s walls around the stage, no monitors.',
    stageIdle: 'Two floor monitors: one downstage on the conductor’s side of the drum, and the section’s own monitor upstage, facing the players. The PA faces the audience.',
    studioIdle: 'No monitors. The main pair over the conductor hears the whole orchestra — the bass drum’s low end included — and the hall is part of the sound.',
    before: [
      { title: 'ASK THE PLAYER FIRST', text: 'Which head is played, which mallets, rolls, how the drum should bloom — and where both hands go to damp either head. Watch the full passage, the loudest hit included.' },
      { title: 'NEVER MOVE THE DRUM', text: 'Do not unlock, tilt, rotate or lift the drum to suit a mic. Its stand locks on its casters and its angle is set with locking bolts; a falling bass drum can injure someone. The percussion crew alone moves it, following the stand’s own manual.' },
      { title: 'LISTEN TO THE MAIN PICKUP', text: 'In an orchestra the main pickup often carries the drum’s low end already; a spot mostly adds definition. Listen first, and decide how many channels the music needs.' },
    ],
    plan: {
      title: 'In the orchestra',
      badge: 'The percussion from above · a typical concert layout · grey hatch = the players’ space',
      looking: 'Plan · the percussion row, the audience toward the bottom',
      stageBadge: 'From above · an amplified orchestra · two monitors where a stage often puts them',
      studioBadge: 'From above · an orchestra recorded in a hall',
      stageLooking: 'Plan · the orchestra on an amplified stage',
      studioLooking: 'Plan · the orchestra in a recording hall',
      widePrompt: 'Switch STAGE / STUDIO, and tap what is new around the orchestra.',
    },
  },
  placement: {
    workedZone: { set: 'cbd.spot' },
    workedLine: 'This starting point is also read against {line}: the readout says how far above it the mic is.',
    workedAim: 'Look diagonally down at {head} — the starting point counts while the mic looks down at the head between about 20° and {tol}° off its axis. Distance, height and angle are separate things to try.',
    workedClear: 'Clear of the mallet’s whole swing, both damping hands, the stand and the player. Clearance comes first, before any number — about 45 cm is a starting point, not a safety distance — and the player stops before a real mic moves.',
    blocked: {},
    reveal: 'Closer tends to bring more of the drum against the room and the stage — and more of the exact spot and the mallet; farther, more of the whole drum and the hall. Drums, halls and players vary, so “it depends” is fair too.',
    typeNotes: { smallDynCard: 'A dynamic can work too — no type is automatically too fragile or the only safe choice. Choose by response, pattern, maximum level, power and mount. Keep a ribbon mic well away from a bass drum’s air blast.' },
    note: 'Clearance comes first: stop the player before moving a real mic, and never move the drum or its stand. The loudest hit may need a pad — set gain on it, not on the average.',
    availableLead: 'Starting points for this mic',
    learn: {
      intro: 'What you just did, in words. After our research, here is where we recommend you begin: a spot above the playing head, looking diagonally down at it from about 45 cm — or closer, for a loud stage. They are starting points, not rules: move from there and listen — there is no single right answer, and every drum, player and hall is different.',
      separate: 'Height, distance and angle are separate variables: change one at a time with the same passage. A mic on the far head, a side position or a room mic are experiments for a quiet room — compare them alone and together in mono, and leave them out if they add little.',
      clearance: 'Clearance comes first. Have the player show the mallet’s full arc, rolls, other mallets and both hands damping both heads before anything is placed. The grey hatched areas show roughly where to keep clear — leave more room on a real stage.',
      tendencies: 'A spot near the playing head favours the mallet’s transient; the main pickup and farther mics carry more of the low bloom and the hall. A kick-drum mic’s shaped response may not suit an orchestral bass drum — compare it with a more neutral mic by ear. All tendencies.',
    },
  },
  context: {
    zone: 'cbd.spot',
    typeId: 'orchSdc',
    patterns: [
      { id: 'cardioid', label: 'cardioid', typeId: 'orchSdc' },
      { id: 'supercardioid', label: 'supercardioid', typeId: 'orchSdc' },
      { id: 'hypercardioid', label: 'hypercardioid', typeId: 'orchSdc' },
    ],
    micNoun: 'A small condenser',
    shield: ['cbd.shell', 'cbd.playing', 'cbd.far'],
    azMax: 45,
    elMax: 60,
    aimBlurb: 'Swing the front up to 45° either way — it still looks toward the playing head.',
    plan: { u0: -1450, u1: 1000, v0: -1350, v1: 1350 },
    side: { u0: -1450, u1: 1000, v0: -900, v1: 840 },
    target: 'downstage',
    frontIds: ['fill'],
    targetWord: 'monitor',
    looking: 'Top view · the spot above the playing head',
    prompt: 'The monitor stays where the stage needs it. Turn the MIC (AIM) or change its PATTERN until the downstage wedge sits in the rejection.',
    activityDone: 'done — the downstage wedge sat in a null by your aim or pattern',
    deepNull: 'On this simplified pattern a null looks infinitely deep. Real microphones reject far less there, and least at low frequencies — where a bass drum lives. Use the null to aim, not to promise silence.',
    cardioidReveal: 'What you just saw: a cardioid rejects most directly behind (180°). This wedge sits off to the side of a mic looking down at the drum, so a cardioid cannot turn its back to it — try the other patterns.',
    shieldNote: 'Real patterns change with pitch and the stage reflects sound — this is the reasoning, not a prediction. Low-frequency feedback is the bass drum’s risk: check it with the system operator at the intended level.',
    studioId: 'cbd.ctx.studio',
    studioPrompt: 'A recording in a hall has no wedge to reject. The decision changes: what does the main pickup already carry?',
    studioNote: 'In a recording, the main pickup usually carries the drum’s low end; a spot adds the transient and stays low in the mix. Switch back to LIVE for the monitor exercise.',
    learn: {
      intro: 'These are scenario-based comparisons, not rules: an orchestra may need no bass-drum spot at all, and an amplified concert band may need one stable, close spot.',
      points: [
        { title: 'HOW MUCH SPOT', text: 'Recording: the main array first; a spot for the transient, low in the mix, keeping the drum in the orchestra’s space. Live: one stable, directional spot on the playing side, as near as safely useful, with the real PA and monitors on.' },
        { title: 'HOW FAR', text: 'Recording: a quiet hall can reward more distance — the whole drum and the room. Live: a farther position admits more bleed and less gain before feedback.' },
        { title: 'HOW MANY MICS', text: 'A far-head mic or a room mic overlaps the main pickup and the spot; more channels do not automatically sound better, and an added mic can reduce usable gain live.' },
        { title: 'HEADROOM', text: 'Set the mic, preamp and any pad for the strongest real hit — and check the main pickup’s inputs too: they hear the same low end.' },
      ],
      body: 'On an amplified stage the monitors stay where the players need them: turn the mic or choose its pattern so that a null faces a loud unwanted source — knowing real nulls are shallowest in the lows.',
      warn: 'No mic position alone prevents feedback: the monitors and PA, channel gain and EQ, the room and the open mics all matter. Work it out with the system operator, and never drive the system into feedback to prove a placement.',
    },
  },
  twoMic: {
    A: { typeId: 'orchSdc', pattern: 'cardioid', zone: 'cbd.spot' },
    B: { typeId: 'orchSdc', pattern: 'cardioid', pose: { p: { x: 400, y: -700, z: 900 }, az: -66, el: -35 } },
    learn: [
      'A common situation: the spot above the playing head, and a farther mic — here, standing in for the main pickup on the conductor’s side. Both hear the drum, at different times. Bring up the main pickup alone first, then the spot at its intended level.',
      'Compare powerful single hits, quiet strokes, rolls and the decay in mono and stereo. If adding the spot weakens the body or the transient turns hollow, try position, level and polarity. A delay on the spot may help one blend and harm the image or the spill — decide by listening in the whole ensemble.',
    ],
    warn: 'This simplified graph shows one point source and straight paths; a 36 in head is large and the hall reflects, so read the notch depths as illustrative only. The notch POSITIONS follow from the arrival-time difference.',
  },
  practice: {
    gain: 'cbd.prac.gain',
    second: 'cbd.prac.3',
    mixed: ['cbd.mix.1', 'cbd.mix.2', 'cbd.mix.3'],
    mixedIntro: 'Three cards from earlier pages, mixed: a reference head, a pattern’s null, and the delay between a spot and the main pickup.',
  },
};
