/**
 * Load ONE guide's body on first open. Each `require` sits inside a function, so
 * no guide is evaluated at app start or when the hub opens — only the guide
 * being read (perf: test/perfStartTrim caps the start graph). GENERATED by
 * scripts/mixing-guides/convert.py.
 */
import type { MixingGuide } from './types';

/* eslint-disable @typescript-eslint/no-var-requires */
const LOADERS: Record<string, () => MixingGuide> = {
  'pop': () => (require('./guides/g01-pop') as { GUIDE: MixingGuide }).GUIDE,
  'hip-hop-rap': () => (require('./guides/g02-hip-hop-rap') as { GUIDE: MixingGuide }).GUIDE,
  'rock': () => (require('./guides/g03-rock') as { GUIDE: MixingGuide }).GUIDE,
  'contemporary-rnb': () => (require('./guides/g04-contemporary-rnb') as { GUIDE: MixingGuide }).GUIDE,
  'edm-festival-electronic': () => (require('./guides/g05-edm-festival-electronic') as { GUIDE: MixingGuide }).GUIDE,
  'country': () => (require('./guides/g06-country') as { GUIDE: MixingGuide }).GUIDE,
  'latin-pop': () => (require('./guides/g07-latin-pop') as { GUIDE: MixingGuide }).GUIDE,
  'reggaeton': () => (require('./guides/g08-reggaeton') as { GUIDE: MixingGuide }).GUIDE,
  'regional-mexican': () => (require('./guides/g09-regional-mexican') as { GUIDE: MixingGuide }).GUIDE,
  'k-pop': () => (require('./guides/g10-k-pop') as { GUIDE: MixingGuide }).GUIDE,
  'alternative-indie-rock': () => (require('./guides/g11-alternative-indie-rock') as { GUIDE: MixingGuide }).GUIDE,
  'christian-contemporary-worship': () => (require('./guides/g12-christian-contemporary-worship') as { GUIDE: MixingGuide }).GUIDE,
  'bollywood-indian-film-music': () => (require('./guides/g13-bollywood-indian-film-music') as { GUIDE: MixingGuide }).GUIDE,
  'afrobeats': () => (require('./guides/g14-afrobeats') as { GUIDE: MixingGuide }).GUIDE,
  'classical-orchestral': () => (require('./guides/g15-classical-orchestral') as { GUIDE: MixingGuide }).GUIDE,
  'film-video-game-score': () => (require('./guides/g16-film-video-game-score') as { GUIDE: MixingGuide }).GUIDE,
  'trap': () => (require('./guides/g17-trap') as { GUIDE: MixingGuide }).GUIDE,
  'house': () => (require('./guides/g18-house') as { GUIDE: MixingGuide }).GUIDE,
  'heavy-metal': () => (require('./guides/g19-heavy-metal') as { GUIDE: MixingGuide }).GUIDE,
  'gospel': () => (require('./guides/g20-gospel') as { GUIDE: MixingGuide }).GUIDE,
  'jazz': () => (require('./guides/g21-jazz') as { GUIDE: MixingGuide }).GUIDE,
  'soul': () => (require('./guides/g22-soul') as { GUIDE: MixingGuide }).GUIDE,
  'hard-rock': () => (require('./guides/g23-hard-rock') as { GUIDE: MixingGuide }).GUIDE,
  'j-pop': () => (require('./guides/g24-j-pop') as { GUIDE: MixingGuide }).GUIDE,
  'c-pop-mandopop': () => (require('./guides/g25-c-pop-mandopop') as { GUIDE: MixingGuide }).GUIDE,
  'indie-pop': () => (require('./guides/g26-indie-pop') as { GUIDE: MixingGuide }).GUIDE,
  'punk-pop-punk': () => (require('./guides/g27-punk-pop-punk') as { GUIDE: MixingGuide }).GUIDE,
  'reggae': () => (require('./guides/g28-reggae') as { GUIDE: MixingGuide }).GUIDE,
  'sertanejo': () => (require('./guides/g29-sertanejo') as { GUIDE: MixingGuide }).GUIDE,
  'punjabi-pop-bhangra': () => (require('./guides/g30-punjabi-pop-bhangra') as { GUIDE: MixingGuide }).GUIDE,
  'blues': () => (require('./guides/g31-blues') as { GUIDE: MixingGuide }).GUIDE,
  'funk': () => (require('./guides/g32-funk') as { GUIDE: MixingGuide }).GUIDE,
  'techno': () => (require('./guides/g33-techno') as { GUIDE: MixingGuide }).GUIDE,
  'folk-singer-songwriter': () => (require('./guides/g34-folk-singer-songwriter') as { GUIDE: MixingGuide }).GUIDE,
  'brazilian-funk': () => (require('./guides/g35-brazilian-funk') as { GUIDE: MixingGuide }).GUIDE,
  'dancehall': () => (require('./guides/g36-dancehall') as { GUIDE: MixingGuide }).GUIDE,
  'amapiano': () => (require('./guides/g37-amapiano') as { GUIDE: MixingGuide }).GUIDE,
  'salsa': () => (require('./guides/g38-salsa') as { GUIDE: MixingGuide }).GUIDE,
  'bachata': () => (require('./guides/g39-bachata') as { GUIDE: MixingGuide }).GUIDE,
  'cumbia': () => (require('./guides/g40-cumbia') as { GUIDE: MixingGuide }).GUIDE,
  'arabic-pop': () => (require('./guides/g41-arabic-pop') as { GUIDE: MixingGuide }).GUIDE,
  'turkish-pop': () => (require('./guides/g42-turkish-pop') as { GUIDE: MixingGuide }).GUIDE,
  'dangdut': () => (require('./guides/g43-dangdut') as { GUIDE: MixingGuide }).GUIDE,
  'mpb-bossa-nova': () => (require('./guides/g44-mpb-bossa-nova') as { GUIDE: MixingGuide }).GUIDE,
  'drum-and-bass': () => (require('./guides/g45-drum-and-bass') as { GUIDE: MixingGuide }).GUIDE,
  'lo-fi-chillhop': () => (require('./guides/g46-lo-fi-chillhop') as { GUIDE: MixingGuide }).GUIDE,
  'bluegrass-americana': () => (require('./guides/g47-bluegrass-americana') as { GUIDE: MixingGuide }).GUIDE,
  'musical-theatre': () => (require('./guides/g48-musical-theatre') as { GUIDE: MixingGuide }).GUIDE,
  'disco-nu-disco': () => (require('./guides/g49-disco-nu-disco') as { GUIDE: MixingGuide }).GUIDE,
  'french-variete-chanson': () => (require('./guides/g50-french-variete-chanson') as { GUIDE: MixingGuide }).GUIDE,
};

const cache = new Map<string, MixingGuide>();

/** The guide with this id, or null for an id the lab does not have. */
export function loadGuide(id: string): MixingGuide | null {
  const hit = cache.get(id);
  if (hit) return hit;
  const load = LOADERS[id];
  if (!load) return null;
  const g = load();
  cache.set(id, g);
  return g;
}
