/**
 * Mixing guide 01 — Pop. GENERATED by scripts/mixing-guides/convert.py
 * from the owner's guide (assets/Mixing-Guides-50-Styles, read only). Edit the
 * conversion (scripts/mixing-guides/edits.py), not this file.
 */
import type { MixingGuide } from '../types';

export const GUIDE: MixingGuide = {
  "id": "pop",
  "num": 1,
  "title": "Pop",
  "expects": "They expect a voice that sounds intimate yet huge, a chorus that lifts noticeably above the verse, and low end that feels modern without blurring the vocal.",
  "glance": {
    "origin": "US and UK, mid-1950s onward; today a global, producer-driven mainstream (LA, London, Stockholm, Seoul)",
    "tempo": "90–130 BPM (ballads 60–80; dance-pop 118–128)",
    "ensemble": "Solo artist + playback/tracks, often with a 3–6 piece band, 2–4 backing singers and dancers",
    "priority": "The lead vocal: upfront, intelligible, consistent from first word to last chorus",
    "liveSpl": "95–100 dBA LAeq-15 min (common safe-listening cap 100 dBA); 105–115 dBC with sub-heavy material",
    "studioLoudness": "Masters commonly −9 to −7 LUFS-I (range −11 to −6); streaming normalizes to about −14 (some services −16)"
  },
  "purpose": [
    {
      "text": "Pop exists to connect instantly with a broad audience. Songs are short (roughly 2.5–3.5 minutes), built on verse–chorus forms and repeated hooks, and most listeners hear them first on phones, earbuds, car systems and smart speakers. The audience wants to sing along, dance, and feel close to the artist. They expect a voice that sounds intimate yet huge, a chorus that lifts noticeably above the verse, and low end that feels modern without blurring the vocal. Top pop mixers put the song’s emotional impact first and technique second. Listeners will say “that sounded wrong” if the vocal disappears behind the band, the lyrics are unclear, the chorus doesn’t get bigger, or the low end booms and swallows everything. Live, they’ll also notice if the show doesn’t sound like the record."
    }
  ],
  "instruments": [
    {
      "label": "Programmed drums and samples:",
      "text": "kick, snare/clap, hats, percussion loops. Often layered (acoustic + electronic) and treated as the main rhythmic engine.",
      "bullet": true
    },
    {
      "label": "Bass:",
      "text": "synth bass or 808-style sub, sometimes electric bass doubled with a synth.",
      "bullet": true
    },
    {
      "label": "Keys and synths:",
      "text": "pads, plucks, arpeggios, piano (especially in ballads).",
      "bullet": true
    },
    {
      "label": "Guitars:",
      "text": "clean or muted rhythm parts, acoustic strums, occasional lead lines.",
      "bullet": true
    },
    {
      "label": "Ear candy:",
      "text": "risers, reversed cymbals, vocal chops, impacts, FX transitions.",
      "bullet": true
    },
    {
      "label": "Live:",
      "text": "much of this comes from playback stems (playback rigs on redundant computers), with live drums, keys, guitar and bass playing on top. Expect 16–32 track channels plus click and cues.",
      "bullet": true
    }
  ],
  "arrangement": [
    {
      "text": "The artist is center stage with a wireless vocal mic, backing singers on one side, and band risers behind (drums center, keys and guitar on the wings). The drums and bass carry the groove, keys and pads fill in the harmony, and the lead vocal carries the melody. Backing vocals, vocal stacks and synth hooks act as counter-melodies. Arrangements follow a set shape. Verses are sparse (often just kick, bass and a single texture), pre-choruses build with risers and filters, and choruses add stacked vocals, wider synths and fuller drums. Many pop songs strip back for a bridge, then come back in for a final chorus with extra layers. Everything is made to keep space open around the vocal."
    }
  ],
  "dynamics": [
    {
      "text": "Micro-dynamics are tightly controlled. Vocals, bass and drums are compressed and the master is limited, so the waveform looks dense. Macro-dynamics still matter: the chorus should feel about 2–4 dB bigger than the verse, though much of that “size” comes from arrangement and width, not raw level. Ballads tolerate more range. In the studio, keep the section-to-section contrast and control everything else. Live, use the vocal compressor and fader rides to keep the singer on top during choreography, when mic distance changes constantly. Also leave headroom for the crowd singing along, which can raise the room level by several dB."
    }
  ],
  "balance": [
    {
      "label": "Hierarchy (loudest → quietest):",
      "text": "lead vocal → kick and snare/clap → bass/sub → main hook (synth or vocal chop) → backing vocals → keys/guitars/pads → percussion and FX. Low end: pick one element to own the lowest octave. If the 808 or sub carries 40–60 Hz, let the kick live at 60–100 Hz for punch with a clear click at 2–4 kHz. Sidechain the bass from the kick (fast attack, short release) so they take turns. Front vs. back: the vocal, kick and snare sit centered and dry-ish up front. Pads, reverbs and doubles sit behind. Stereo: kick, snare, bass and lead vocal stay in mono at center. Spread doubles and harmonies hard L/R, along with hats/percussion and stereo synths. Check mono compatibility, since phones and many club and venue systems sum the low end to mono."
    }
  ],
  "eq": {
    "rows": [
      {
        "source": "Lead vocal",
        "cut": "HPF 80–100 Hz; −2 to −4 dB at 200–400 Hz if boxy",
        "boost": "+2 dB at 3–5 kHz; +2–3 dB shelf at 10–12 kHz for air",
        "notes": "Tame 1 kHz nasality only if it’s obvious; de-ess before boosting air"
      },
      {
        "source": "Backing vocals",
        "cut": "HPF 150–250 Hz; −3 dB at 300 Hz",
        "boost": "+2 dB shelf at 8–12 kHz",
        "notes": "Thinner and brighter than the lead so they don’t mask it"
      },
      {
        "source": "Kick",
        "cut": "−3 to −5 dB at 250–400 Hz (box)",
        "boost": "+2–3 dB at 60–80 Hz; +2 dB at 3–4 kHz",
        "notes": "HPF at ~30 Hz if the sub owns the bottom"
      },
      {
        "source": "Snare / clap",
        "cut": "−2 to −4 dB at 400–800 Hz (ring)",
        "boost": "+2 dB at 200 Hz body; +2–3 dB at 5–8 kHz snap",
        "notes": "Layered claps: HPF 200–300 Hz"
      },
      {
        "source": "Bass / 808",
        "cut": "HPF 25–30 Hz; notch where it fights the kick",
        "boost": "+2 dB at 700 Hz–1.5 kHz for audibility on small speakers",
        "notes": "Add saturation so phones can “hear” the sub"
      },
      {
        "source": "Synth pads",
        "cut": "HPF 150–250 Hz; −2–3 dB at 400–600 Hz",
        "boost": "Gentle 3 kHz lift if needed",
        "notes": "Dynamic EQ dip at 2–4 kHz keyed from the vocal"
      },
      {
        "source": "Acoustic / electric guitar",
        "cut": "HPF 100–150 Hz; −2 dB at 1–2 kHz if honky",
        "boost": "+2 dB at 5–8 kHz shimmer",
        "notes": "Strummed acoustics are usually a texture, so thin them"
      },
      {
        "source": "Piano",
        "cut": "HPF 60–80 Hz (in a full mix); −2 dB at 200–300 Hz",
        "boost": "+1–2 dB at 3–5 kHz",
        "notes": "Ballads: keep fuller and more natural"
      },
      {
        "source": "Hi-hats / percussion",
        "cut": "HPF 300–500 Hz",
        "boost": "+1–2 dB shelf at 10 kHz",
        "notes": "Watch harshness at 6–8 kHz when compressed"
      }
    ],
    "notes": []
  },
  "compression": {
    "rows": [
      {
        "source": "Lead vocal (stage 1)",
        "use": "Yes",
        "ratio": "4:1–6:1 (FET)",
        "attackRelease": "1–5 ms / 50–100 ms",
        "gainReduction": "3–6 dB on peaks",
        "notes": "Catches transients; fast FET-style"
      },
      {
        "source": "Lead vocal (stage 2)",
        "use": "Yes",
        "ratio": "2:1–3:1 (opto)",
        "attackRelease": "10–20 ms / auto",
        "gainReduction": "2–4 dB",
        "notes": "Opto-style leveling; pre-ride with clip gain or automation"
      },
      {
        "source": "Backing vocal bus",
        "use": "Yes",
        "ratio": "4:1",
        "attackRelease": "5 ms / 80 ms",
        "gainReduction": "4–8 dB",
        "notes": "Heavier is fine; keeps stacks as one block"
      },
      {
        "source": "Bass / 808",
        "use": "Yes",
        "ratio": "4:1",
        "attackRelease": "10–30 ms / 80–150 ms",
        "gainReduction": "3–5 dB",
        "notes": "Plus kick-keyed sidechain: 8:1–12:1, <10 ms attack, 50–150 ms release, 2–6 dB ducking"
      },
      {
        "source": "Drum bus",
        "use": "Yes",
        "ratio": "4:1",
        "attackRelease": "10–30 ms / auto or tempo-timed",
        "gainReduction": "2–4 dB",
        "notes": "Parallel version crushed 10+ dB, blended ~20–30%"
      },
      {
        "source": "Synth pads",
        "use": "Optional",
        "ratio": "Sidechain ducking from kick",
        "attackRelease": "Fast / tempo-timed",
        "gainReduction": "2–6 dB",
        "notes": "Adds groove “pump” in dance-pop"
      },
      {
        "source": "Mix bus",
        "use": "Yes",
        "ratio": "2:1 (VCA bus-style)",
        "attackRelease": "10–30 ms / auto",
        "gainReduction": "1–3 dB (up to 4)",
        "notes": "HPF the sidechain at 30–60 Hz so the kick doesn’t drive it"
      }
    ],
    "notes": [
      {
        "label": "Other dynamics:",
        "text": "De-ess lead vocals at 5–8 kHz (female) or 4–6 kHz (male), 3–6 dB of reduction on “s” sounds. Gate or expand live toms and kick mics. Use a multiband compressor or dynamic EQ on the vocal at 200–400 Hz to control proximity boom. Final limiting belongs to mastering. In the studio, mix into a limiter for client approvals, but bypass it on stems you deliver."
      }
    ]
  },
  "fx": {
    "rows": [
      {
        "effect": "Plate reverb",
        "appliedTo": "Lead vocal",
        "setting": "1.2–1.8 s decay, 40–80 ms pre-delay, HPF 300 Hz / LPF 8 kHz on return",
        "amount": "Subtle–moderate (pop vocals sit fairly dry)"
      },
      {
        "effect": "Tempo delay",
        "appliedTo": "Lead vocal (throws on phrase ends)",
        "setting": "1/4 or dotted 1/8, 2–3 repeats, filtered 300 Hz–6 kHz",
        "amount": "Subtle in verses, automated throws"
      },
      {
        "effect": "Slapback / short delay",
        "appliedTo": "Lead vocal",
        "setting": "80–120 ms, single repeat",
        "amount": "Subtle thickening"
      },
      {
        "effect": "Stereo widener / micro-pitch",
        "appliedTo": "Lead vocal, BVs",
        "setting": "±5–10 cents detune, 10–20 ms offsets",
        "amount": "Subtle on lead, moderate on BVs"
      },
      {
        "effect": "Hall / large room",
        "appliedTo": "BVs, pads, snare",
        "setting": "2–3 s decay, 20–40 ms pre-delay",
        "amount": "Moderate; more in ballads"
      },
      {
        "effect": "Saturation",
        "appliedTo": "Vocal, 808, mix bus",
        "setting": "Tape/tube, 1–3 dB of drive",
        "amount": "Subtle; helps translation on small speakers"
      },
      {
        "effect": "Short room / ambience",
        "appliedTo": "Drums, claps",
        "setting": "0.4–0.8 s",
        "amount": "Moderate"
      }
    ],
    "notes": []
  },
  "vocals": [
    {
      "text": "The lead vocal sits roughly 3–6 dB above the dense part of the arrangement on the meter, but loudness is really about what you hear: it should be clearly on top and read like a close-up. Tone is bright, present and smooth, with a lot of air, little harshness and controlled low-mids. Pitch correction is standard. Use transparent note-by-note (graphical) correction for most pop. Fast-retune, audible pitch correction is a stylistic choice that the artist and producer decide on. Doubles are tucked 6–10 dB under the lead and panned or kept center. Harmony stacks get panned wide. Ad-libs are filtered or panned and often get delay. Intelligibility comes first: consonants must cut through at 2–5 kHz. In the studio, typical mics are large-diaphragm condensers. Live, most artists use handheld dynamics or condensers on wireless chosen for consistency at changing distances. On a headset mic for choreography, expect more gain-before-feedback problems and lean harder on EQ. Make sure the pitch correction can be switched off or adjusted easily."
    }
  ],
  "loudness": [
    {
      "label": "Live:",
      "text": "A typical arena or stadium pop show runs about 95–100 dBA LAeq over 15 minutes at FOH, and some shows peak higher when the crowd sings along. A soundcheck in the low 90s can rise past 110 dB with a packed, singing house. Low end usually measures 105–115 dBC LCeq. Keep the sub energy controlled so the vocal stays clear. A widely used safe-listening limit for venues is 100 dBA LAeq-15 min, and local rules differ in averaging time (for example, 1 minute vs. 60 minutes), so learn the local rule before the show. Offer earplugs, keep the loudest seats away from subs, and remember that many pop audiences include children and teenagers."
    },
    {
      "label": "Studio / streaming:",
      "text": "Commercial pop masters usually land around −9 to −7 LUFS-I (chart pop ranges from about −10.7 to −6 LUFS). Aim for a true peak of −1 dBTP, or −2 dBTP if the master is louder than −14 LUFS, to avoid codec distortion. Most streaming services normalize to about −14 LUFS, some to −16, so very loud masters are turned down and only gain density, not extra volume. A PLR (peak-to-loudness ratio) of around 7–9 dB is typical. Ballads can sit at −11 to −10 LUFS."
    }
  ],
  "liveStudio": {
    "rows": [
      {
        "area": "Low end",
        "live": "Sub arrays and cardioid subs; aim for the feel without masking the vocal; watch dBC",
        "studio": "Translates to earbuds/phones via saturation and upper harmonics"
      },
      {
        "area": "Vocal",
        "live": "Fighting stage bleed, moving singer and wireless; heavier compression and fader rides; gain-before-feedback",
        "studio": "Every word automated; detailed de-essing and clip-gain"
      },
      {
        "area": "Playback",
        "live": "Stems from a redundant rig; check the gain structure on every song; click to IEMs only",
        "studio": "Tracks are the production itself; full control"
      },
      {
        "area": "FX",
        "live": "Tap-tempo or MIDI-synced delays, scene-based reverb; keep tails shorter in reverberant arenas",
        "studio": "Automated throws and precise timing per phrase"
      },
      {
        "area": "Loudness",
        "live": "Governed by SPL limits (dBA/dBC over time)",
        "studio": "Governed by LUFS/true peak and normalization"
      },
      {
        "area": "Stereo",
        "live": "Many seats hear mostly one side; keep key elements center/mono-safe",
        "studio": "Wide stereo image is part of the sound"
      },
      {
        "area": "Consistency",
        "live": "Scenes/snapshots per song to match the record",
        "studio": "Recall and revisions; reference against the release"
      }
    ],
    "notes": []
  },
  "notes": [
    {
      "label": "Start from the vocal.",
      "text": "Build the mix around the lead and check every decision against how well you can understand the lyrics.",
      "bullet": true
    },
    {
      "label": "Check on small speakers.",
      "text": "Use phone, earbuds and a mono single speaker. If the 808 vanishes, add harmonics. Don’t add more sub.",
      "bullet": true
    },
    {
      "label": "Automate, don’t just compress.",
      "text": "Ride the vocal phrase by phrase before compressing. That’s how pop vocals feel loud but natural.",
      "bullet": true
    },
    {
      "label": "Sidechain the bus compressor.",
      "text": "HPF at 30–60 Hz so the kick doesn’t pump the whole mix.",
      "bullet": true
    },
    {
      "label": "Live: gain-stage the playback.",
      "text": "Producers bounce stems hot; trim per song and label everything. Have a backup rig on standby.",
      "bullet": true
    },
    {
      "label": "Mistake:",
      "text": "Too much reverb on the lead. Modern pop is close and dry-sounding; get space from short pre-delayed plates and delays, not long washes.",
      "bullet": true
    },
    {
      "label": "Mistake:",
      "text": "Over-brightening. Stacked air boosts plus compression make harsh “s” sounds and fatigue. De-ess before you boost.",
      "bullet": true
    },
    {
      "label": "Mistake:",
      "text": "Chasing loudness in the mix. Give mastering a mix with 3–6 dB of headroom and let normalization reward dynamics.",
      "bullet": true
    },
    {
      "label": "Mistake:",
      "text": "Live low-end war. Kick and sub both pushed until the vocal disappears; set the sub level by ear relative to the vocal, not the meter.",
      "bullet": true
    }
  ],
  "references": [
    "Michael Jackson — “Billie Jean” (1982)",
    "Taylor Swift — “Shake It Off” (2014)",
    "Bruno Mars — “Uptown Funk” (with Mark Ronson, 2014)",
    "Billie Eilish — “bad guy” (2019)",
    "Dua Lipa — “Levitating” (2020)",
    "The Weeknd — “Blinding Lights” (2019)",
    "Ariana Grande — “7 rings” (2019)",
    "Adele — “Hello” (2015), ballad reference"
  ],
  "empty": []
};
