/**
 * Mixing guide 03 — Rock. GENERATED by scripts/mixing-guides/convert.py
 * from the owner's guide (assets/Mixing-Guides-50-Styles, read only). Edit the
 * conversion (scripts/mixing-guides/edits.py), not this file.
 */
import type { MixingGuide } from '../types';

export const GUIDE: MixingGuide = {
  "id": "rock",
  "num": 3,
  "title": "Rock",
  "expects": "Audiences expect a band that sounds like real people playing together in a room, with the singer’s words understandable and the guitars big but not harsh.",
  "glance": {
    "origin": "United States, mid-1950s (rock and roll from R&B and country); reshaped by British bands in the 1960s and into “classic rock” through the 1970s",
    "tempo": "100–150 BPM (ballads 65–90; shuffles and up-tempo rockers to 160+)",
    "ensemble": "4–6 piece band: drums, bass, 1–2 electric guitars, keys, lead vocal plus 1–3 backing vocals",
    "priority": "The drums-and-bass engine with the lead vocal riding clearly on top",
    "liveSpl": "98–103 dBA Leq (LAeq-15 min); roughly 115–125 dBC; many festivals cap at 100–105 dBA",
    "studioLoudness": "Modern masters commonly −10 to −7 LUFS-I (classic catalog remasters around −12 to −9); streaming normalizes to about −14"
  },
  "purpose": [
    {
      "text": "Rock is music for release and shared energy: singing along in a crowd, driving with the windows down, feeling the kick in your chest. Audiences expect a band that sounds like real people playing together in a room, with the singer’s words understandable and the guitars big but not harsh. The emotional payoff is the chorus lift and the guitar solo. Listeners will say “that sounded wrong” if the vocal is buried under guitars, the snare is thin or clicky, the low end is a muddy blur, or the mix feels sterile and over-quantized. Rock is more forgiving of grit and imperfection than pop, but much less forgiving of lifelessness."
    }
  ],
  "instruments": [
    {
      "label": "Drums:",
      "text": "acoustic kit, close-mic’d plus overheads and room mics; room sound is part of the genre’s identity.",
      "bullet": true
    },
    {
      "label": "Bass:",
      "text": "electric bass (DI and amp mic blended) carrying the roots and most of the low end.",
      "bullet": true
    },
    {
      "label": "Electric guitars:",
      "text": "rhythm (crunch, power chords) and lead (riffs, solos), from clean jangle to moderate overdrive.",
      "bullet": true
    },
    {
      "label": "Keys and acoustic guitar:",
      "text": "tonewheel organ with rotating speaker, piano, strummed acoustic in verses and ballads.",
      "bullet": true
    },
    {
      "label": "Playback:",
      "text": "minimal—click to in-ears, occasional pads or strings on larger tours; drum samples often reinforce kick and snare in the studio.",
      "bullet": true
    }
  ],
  "arrangement": [
    {
      "text": "Classic stage layout: drums center upstage, bass on one side near the drummer, guitars split stage left/right, keys to one side, lead vocal front center. Drums and bass lock the groove; rhythm guitar fills harmonic width; keys glue the mids; lead guitar answers the vocal and takes the solo. Verses are often sparser (single guitar, hi-hat, palm muting), pre-choruses build, and choruses open up with crashes, doubled or added guitars and backing harmonies. Bridges and solos frequently drop out then come back for a final, biggest chorus."
    }
  ],
  "dynamics": [
    {
      "text": "Rock has moderate macro-dynamics: a quiet verse to full chorus can span 6–10 dB in performance, and the arrangement does much of that work. Preserve the section contrast—it is the genre’s drama—while controlling micro-dynamics (snare hits, vocal peaks, bass notes) so everything stays audible. Ride faders rather than over-compressing; small automation moves (chorus up 0.5–1 dB, cymbals nudged up in choruses, guitars slightly wider) create lift without squashing. Loudness-maximized masters that flatten the verse/chorus contrast are a known complaint in this genre."
    }
  ],
  "balance": [
    {
      "text": "Typical hierarchy, loudest to quietest: lead vocal and snare (roughly equal), kick and bass, rhythm guitars, lead guitar/solos (pushed up in their spots), keys, backing vocals, overheads/room, effects returns. Low end: let the bass own the sustained low end (roughly 60–250 Hz) and the kick own the attack and a narrow thump (50–100 Hz); a frequent mistake is too much kick and not enough bass, which makes the bottom feel short and light. Lead vocal, kick, snare and bass sit dead center. Pan double-tracked rhythm guitars hard left and right, a second pair partway in if present; keys and lead guitar off-center opposite each other. Drums panned from the audience or drummer perspective—just be consistent."
    }
  ],
  "eq": {
    "rows": [
      {
        "source": "Kick",
        "cut": "HPF 30–40 Hz; −3 to −6 dB at 250–500 Hz (boxiness)",
        "boost": "+2–4 dB at 50–80 Hz; +2–4 dB at 2–4 kHz (beater)",
        "notes": "Find the fundamental with a narrow sweep; keep it narrower than the bass"
      },
      {
        "source": "Snare",
        "cut": "HPF 80–100 Hz; −2–4 dB narrow at ring (often 400 Hz–1.2 kHz)",
        "boost": "+2–3 dB at 150–240 Hz (body); +2–3 dB at 5 kHz; shelf at 10 kHz for snap",
        "notes": "Parallel snare channel with broad 5 kHz and 100 Hz lifts adds weight"
      },
      {
        "source": "Toms",
        "cut": "HPF 50–80 Hz; −3 dB at 300–500 Hz",
        "boost": "+2–3 dB at 80–120 Hz (floor) / 150–250 Hz (rack); +2 dB at 3–5 kHz",
        "notes": "Gate or edit to cut bleed; roll off top to make room for cymbals"
      },
      {
        "source": "Overheads / room",
        "cut": "HPF 150–300 Hz (overheads), 60–100 Hz (room); dip 2–4 kHz if harsh",
        "boost": "Gentle shelf +1–2 dB at 10–12 kHz",
        "notes": "Rooms bring the “band in a room” feel—compress them hard and tuck under"
      },
      {
        "source": "Bass",
        "cut": "HPF 35–45 Hz; −2–3 dB at 200–300 Hz if boomy",
        "boost": "+2 dB shelf around 60–70 Hz; +2–3 dB at 700 Hz–1 kHz (growl); 2–3 kHz (string definition)",
        "notes": "Blend DI for lows and amp/drive for mids"
      },
      {
        "source": "Rhythm guitars",
        "cut": "HPF 80–120 Hz; LPF 12–15 kHz; −2–3 dB at 200–400 Hz",
        "boost": "+1–3 dB at 2–4 kHz (presence)",
        "notes": "Avoid scooping mids—the 500 Hz–2 kHz body is the rock guitar tone"
      },
      {
        "source": "Lead guitar",
        "cut": "HPF 100–150 Hz; dip 3–4 kHz if fizzy",
        "boost": "+2 dB at 1–1.5 kHz to push forward",
        "notes": "Different tone or mic than rhythm helps it cut without extra level"
      },
      {
        "source": "Lead vocal",
        "cut": "HPF 80–120 Hz; −2–3 dB at 200–400 Hz (mud); notch harsh 2.5–4 kHz if needed",
        "boost": "+2–3 dB at 3–5 kHz (presence); +1–2 dB shelf at 10–12 kHz (air)",
        "notes": "Keep most energy in the midrange; distortion up top sounds harsh"
      },
      {
        "source": "tonewheel organ / piano",
        "cut": "HPF 80–120 Hz; −2 dB at 250–400 Hz",
        "boost": "+2 dB at 2–5 kHz on piano for definition",
        "notes": "Keep keys out of the vocal’s 2–4 kHz zone"
      }
    ],
    "notes": []
  },
  "compression": {
    "rows": [
      {
        "source": "Lead vocal (stage 1, FET)",
        "use": "Yes",
        "ratio": "4:1",
        "attackRelease": "1–5 ms / 50–100 ms",
        "gainReduction": "3–5 dB on peaks",
        "notes": "Catches spikes; needle should return to zero on normal phrases"
      },
      {
        "source": "Lead vocal (stage 2, opto)",
        "use": "Yes",
        "ratio": "~3:1 (program)",
        "attackRelease": "Program-dependent",
        "gainReduction": "2–3 dB steady, up to 5 dB",
        "notes": "Smooths overall level; single compressor live is fine"
      },
      {
        "source": "Kick",
        "use": "Yes",
        "ratio": "4:1",
        "attackRelease": "20–30 ms / 50–80 ms",
        "gainReduction": "3–5 dB",
        "notes": "Slow attack lets the beater through"
      },
      {
        "source": "Snare",
        "use": "Yes",
        "ratio": "4:1",
        "attackRelease": "10–30 ms / 60–100 ms",
        "gainReduction": "4–5 dB",
        "notes": "Plus parallel squash for body"
      },
      {
        "source": "Bass",
        "use": "Yes",
        "ratio": "4:1",
        "attackRelease": "10–20 ms / 100 ms",
        "gainReduction": "4–7 dB",
        "notes": "Rock bass is heavily evened out"
      },
      {
        "source": "Rhythm guitars",
        "use": "Light",
        "ratio": "2:1–3:1",
        "attackRelease": "20–30 ms / auto",
        "gainReduction": "2–3 dB",
        "notes": "Distorted amps are already compressed"
      },
      {
        "source": "Room mics",
        "use": "Yes (heavy)",
        "ratio": "8:1–20:1",
        "attackRelease": "1–5 ms / 50–100 ms",
        "gainReduction": "8–15 dB",
        "notes": "Blend in for size and excitement"
      },
      {
        "source": "Drum bus",
        "use": "Yes",
        "ratio": "2:1–4:1",
        "attackRelease": "10–30 ms / fast or auto",
        "gainReduction": "2–4 dB",
        "notes": "Slow attack keeps punch"
      },
      {
        "source": "Mix bus",
        "use": "Optional",
        "ratio": "2:1",
        "attackRelease": "10–30 ms / auto",
        "gainReduction": "1–2 dB",
        "notes": "“Glue” only; leave loudness to mastering"
      }
    ],
    "notes": [
      {
        "text": "Parallel drum compression (8:1+, 10 dB or more reduction, blended 20–40%) is a rock staple. Gate toms live (30–50 ms hold, 100–200 ms release); edit them in the studio. De-ess bright vocals at 5–8 kHz for 2–4 dB. Keep master limiting to 2–4 dB so the chorus lift survives."
      }
    ]
  },
  "fx": {
    "rows": [
      {
        "effect": "Slap delay",
        "appliedTo": "Lead vocal",
        "setting": "80–130 ms, 0–10% feedback, HPF 200 Hz / LPF 5 kHz",
        "amount": "Subtle–moderate"
      },
      {
        "effect": "Tempo delay",
        "appliedTo": "Vocal phrase ends, lead guitar",
        "setting": "1/4 or 1/8 note, 15–25% feedback",
        "amount": "Subtle, automated per section"
      },
      {
        "effect": "Plate reverb",
        "appliedTo": "Lead vocal, snare",
        "setting": "1.2–2.0 s decay, 20–60 ms pre-delay",
        "amount": "Subtle–moderate (drier verses, more in choruses)"
      },
      {
        "effect": "Room / chamber",
        "appliedTo": "Drums, whole band",
        "setting": "0.6–1.2 s decay",
        "amount": "Moderate—shared “space” for cohesion"
      },
      {
        "effect": "Stereo slap / Haas",
        "appliedTo": "Rhythm & lead guitars",
        "setting": "90 ms one side, ~125 ms other; or 8–15 ms short delay copy",
        "amount": "Subtle"
      },
      {
        "effect": "Hall reverb",
        "appliedTo": "Ballads, strings, big outros",
        "setting": "2.0–3.0 s decay, 30–80 ms pre-delay",
        "amount": "Moderate"
      },
      {
        "effect": "rotating speaker / chorus",
        "appliedTo": "Organ, clean guitars",
        "setting": "Slow/fast rotor; chorus 0.5–1 Hz rate",
        "amount": "As part of the tone"
      }
    ],
    "notes": [
      {
        "text": "Prefer a few shared reverbs over a separate one for every instrument; it makes the band sound like it was in one place."
      }
    ]
  },
  "vocals": [
    {
      "text": "The vocal leads, but sits slightly into the band rather than floating above it as in pop—roughly 1–3 dB above the guitars by perceived level, with every word intelligible. Tone is mid-forward and present, with grit acceptable; avoid excessive air or brittle top. Pitch correction should be light and selective, fixing only obvious problems; audible tuning reads as fake in rock. Doubles are common on choruses (tucked 6–10 dB under the lead, panned center or slightly split), and harmony backing vocals are usually panned wide and compressed harder. Ride the vocal line by line in the studio. Live, use a rugged dynamic mic and a short chain: HPF, EQ, compression, maybe a slap; notch bleed on drummer vocal mics (around 500 Hz and 3 kHz)."
    }
  ],
  "loudness": [
    {
      "label": "Live:",
      "text": "Club and theater rock typically runs 96–102 dBA LAeq-15 at FOH, arenas and festivals 100–105 dBA, with C-weighted levels around 115–125 dBC; a C-minus-A gap of 20 dB or more signals excessive sub. Peaks run 110–115 dBA. Many European festivals enforce limits such as 100 dBA over 60 minutes or 105 dBA LAeq-15 at FOH, with peak caps around 115 dBA. Rock needs moderate sub, not EDM-level sub. By common hearing-safety guidance, 100 dBA is safe for only about 15 minutes—offer earplugs and protect your own ears."
    },
    {
      "label": "Studio / streaming:",
      "text": "Contemporary rock masters typically land at −10 to −7 LUFS-I with true peak at −1 dBTP (−2 dBTP if mastering louder than −14 to avoid codec clipping). Most streaming services normalize to about −14 LUFS, so very loud masters gain nothing on playback and lose punch. Rock tolerates and benefits from a PLR (peak-to-loudness ratio) of roughly 9–12 dB; a loudness range of 5–8 LU keeps verse/chorus contrast alive."
    }
  ],
  "liveStudio": {
    "rows": [
      {
        "area": "Low end",
        "live": "Fight stage wash and room buildup; HPF more aggressively, watch 100–250 Hz",
        "studio": "Fine-tune kick/bass interplay with sidechain or EQ carving"
      },
      {
        "area": "Guitars",
        "live": "Stage amps already loud—often you add little; mic choice shapes tone",
        "studio": "Double-tracked, panned hard, layered for width"
      },
      {
        "area": "Vocals",
        "live": "Gain-before-feedback limits EQ; dynamic mics, minimal effects",
        "studio": "Comping, serial compression, detailed rides, doubles"
      },
      {
        "area": "Drums",
        "live": "Gates on toms, minimal room mics (stage bleed is the room)",
        "studio": "Room mics and parallel compression create size; sample reinforcement"
      },
      {
        "area": "Effects",
        "live": "Fewer, tapped-tempo delays and one or two reverbs",
        "studio": "Multiple delays and reverbs automated by section"
      },
      {
        "area": "Dynamics",
        "live": "Mix by hand in real time; level builds through the set",
        "studio": "Fader automation sculpts every section"
      },
      {
        "area": "Loudness",
        "live": "98–103 dBA Leq, venue limits",
        "studio": "−10 to −7 LUFS-I master, −1 dBTP"
      }
    ],
    "notes": []
  },
  "notes": [
    {
      "text": "Push all faders up for a rough balance first and EQ in context; check at low volume and on small speakers.",
      "bullet": true
    },
    {
      "text": "Make choruses bigger with automation (level, width, cymbals), not more compression.",
      "bullet": true
    },
    {
      "text": "Don’t scoop guitar mids or let the kick overpower the bass.",
      "bullet": true
    },
    {
      "text": "Avoid over-editing and over-tuning: tight is good, robotic is wrong for rock.",
      "bullet": true
    },
    {
      "text": "Live, leave headroom to build through the set rather than peaking in song one.",
      "bullet": true
    }
  ],
  "references": [
    "Bruce Springsteen, “Born in the U.S.A.”, 1984",
    "Tom Petty and the Heartbreakers, “Refugee”, 1979",
    "Fleetwood Mac, “Go Your Own Way”, 1977",
    "The Rolling Stones, “Gimme Shelter”, 1969",
    "Led Zeppelin, “When the Levee Breaks”, 1971",
    "Foo Fighters, “Everlong”, 1997",
    "The Black Crowes, “Hard to Handle”, 1990",
    "The Killers, “Mr. Brightside”, 2004"
  ],
  "empty": []
};
