/**
 * Mixing guide 05 — EDM / Festival Electronic. GENERATED by scripts/mixing-guides/convert.py
 * from the owner's guide (assets/Mixing-Guides-50-Styles, read only). Edit the
 * conversion (scripts/mixing-guides/edits.py), not this file.
 */
import type { MixingGuide } from '../types';

export const GUIDE: MixingGuide = {
  "id": "edm-festival-electronic",
  "num": 5,
  "title": "EDM / Festival Electronic",
  "expects": "The audience wants sub-bass felt in the chest, a singable lead hook, and a chorus to shout back in the breakdown.",
  "glance": {
    "origin": "Europe (Netherlands, Sweden, Belgium, UK) and US festival circuit, late 2000s–2010s; big-room and electro peaked around 2012–2016 and the sound persists in festival-pop crossovers",
    "tempo": "126–132 BPM (big room, electro, progressive house); 124–128 for melodic progressive; occasional 150 BPM “festival trap/hardstyle” switch-ups inside sets",
    "ensemble": "Solo DJ/producer or duo on DJ media players/laptop + stereo or stem playback; sometimes a live vocalist, MC, or guest instrumentalist",
    "priority": "Kick-and-sub relationship: a short, tuned, punchy kick that the bass ducks around, translating to a massive sub array without mud",
    "liveSpl": "About 98–103 dBA LAeq-15 min at FOH, often 115–121 dBC; respect local caps (e.g. 100 or 103 dBA)",
    "studioLoudness": "Club/release masters commonly −7 to −5 LUFS short-term at the drop (−8 to −6 LUFS-I); streaming normalizes to about −14 LUFS"
  },
  "purpose": [
    {
      "text": "Festival EDM is functional euphoria: it exists to move tens of thousands of people at once through shared peak moments — build, riser, silence, drop. The audience wants sub-bass felt in the chest, a singable lead hook, and a chorus to shout back in the breakdown. The mix must make the drop feel bigger than everything before it. What reads as “wrong” to this crowd: a drop that feels smaller or quieter than the build, a soft or flabby kick, a sub that disappears or booms on one note, harsh supersaws that hurt at volume, and gaps or level jumps between tracks in a DJ set."
    }
  ],
  "instruments": [
    {
      "text": "Almost entirely electronic. Kick: layered 909-style kicks with a click layer and a tuned tail carrying a pitched low note, so the kick acts as part of the bassline. Bass: a clean sine sub plus a distorted top bass. Leads: detuned supersaw stacks, plucks, and the big-room drop lead (a gritty mono core plus wide saw and octave layers). Drums/FX: claps, snare rolls, open hats, impacts, white-noise risers, downlifters. Vocals: pop toplines, chopped hooks, MC shouts. On stage it is nearly all playback from DJ media players or a laptop running stems, with an occasional live vocal or instrument."
    }
  ],
  "arrangement": [
    {
      "text": "Live, one or two DJs on a center-stage riser feed FOH from the mixer (digitally where possible), plus an MC or vocalist mic. Records are sectional: DJ-friendly intro, breakdown (pads, chords, vocal), build (snare roll, rising filter, risers, often a short silence), drop (kick, bass, lead hook), repeat. Kick and sub carry rhythm, pads and saw chords carry harmony, and the lead or vocal carries melody. Effective drops are sparse, usually just drums, one main synth idea and maybe a vocal chop, so every layer must justify itself."
    }
  ],
  "dynamics": [
    {
      "text": "Micro-dynamics are tightly controlled (sidechain, limiting, clipping), but macro-dynamics are the point: the drop must feel like the loudest moment. Sit intros, breakdowns and builds 1–2 dB below the drop rather than pushing the limiter harder. Live, FOH effectively masters on the fly, smoothing level jumps between tracks and keeping the system within limits without squashing the drop."
    }
  ],
  "balance": [
    {
      "text": "Hierarchy (loudest to quietest at the drop): kick → sub/bass → lead hook → clap/snare → vocal chop or topline → pads/chords → hats/percussion → FX and reverb returns. In breakdowns the vocal or lead moves to the top. Low end: the kick owns the transient and roughly 50–70 Hz punch for a few tens of milliseconds; the bass is ducked under it by sidechain, then fills in. Tune the kick to the song key. Keep everything below about 120–150 Hz in mono, kick and sub dead center. Pan percussion and doubled saw layers wide; keep the main lead core, clap, and vocal center. Width lives above roughly 200 Hz."
    }
  ],
  "eq": {
    "rows": [
      {
        "source": "Kick",
        "cut": "−2 to −4 dB at 250–400 Hz (boxiness)",
        "boost": "+2 dB at 55–70 Hz (body); +2 dB at 2–5 kHz (beater click); small lift 7–10 kHz",
        "notes": "Tune tail to key; HPF ~25–30 Hz to protect limiter and subs"
      },
      {
        "source": "Sub bass",
        "cut": "LPF ~100–130 Hz; HPF ~25–30 Hz",
        "boost": "Usually none — use a sine or pure low layer",
        "notes": "Keep mono; avoid resonant notes that boom on festival subs"
      },
      {
        "source": "Top bass / reese",
        "cut": "HPF 80–120 Hz; dip −2 to −3 dB around kick punch (100–200 Hz)",
        "boost": "Grit at 1–3 kHz to taste",
        "notes": "Separate distortion from sub so the sub stays clean"
      },
      {
        "source": "Supersaw / lead stack",
        "cut": "HPF 150–250 Hz; −2 to −4 dB at 2.5–4 kHz if harsh; dynamic EQ on resonances",
        "boost": "+1.5 dB air shelf at 10–12 kHz",
        "notes": "Harshness at high SPL is the #1 festival complaint"
      },
      {
        "source": "Clap / snare",
        "cut": "HPF 150–200 Hz; −2 dB at 400–600 Hz",
        "boost": "+2 dB at 1–2 kHz (crack); +2 dB at 8–10 kHz",
        "notes": "Layer with a short room or plate tail"
      },
      {
        "source": "Pads / chords",
        "cut": "HPF 200–300 Hz; cut 2–4 kHz under the vocal",
        "boost": "Gentle air shelf if dull",
        "notes": "Sidechained; keep out of the lead’s lane"
      },
      {
        "source": "Lead vocal",
        "cut": "HPF 90–120 Hz; −2 to −3 dB at 250–400 Hz",
        "boost": "+2 to +3 dB at 3–5 kHz presence; +2 dB at 10–12 kHz air",
        "notes": "De-ess after the air boost"
      },
      {
        "source": "Hats / percussion / FX",
        "cut": "HPF 300–500 Hz (risers: automate HPF upward in builds)",
        "boost": "Shelf at 8–12 kHz sparingly",
        "notes": "Tame cymbals and risers that get piercing on large line arrays"
      }
    ],
    "notes": []
  },
  "compression": {
    "rows": [
      {
        "source": "Bass/pads sidechain from kick",
        "use": "Yes",
        "ratio": "4:1–10:1 (or volume-shaper envelope)",
        "attackRelease": "0.1–1 ms / 80–200 ms, timed to the beat",
        "gainReduction": "6–15 dB on bass; 3–8 dB on pads",
        "notes": "Tight release for clarity; longer for audible pump. Volume-shaper tools give more precise timing"
      },
      {
        "source": "Kick",
        "use": "Optional",
        "ratio": "4:1",
        "attackRelease": "10–30 ms / 50–100 ms",
        "gainReduction": "2–4 dB",
        "notes": "Or transient shaper; parallel heavy compression + saturation for density"
      },
      {
        "source": "Kick + bass bus (glue)",
        "use": "Yes",
        "ratio": "4:1",
        "attackRelease": "3 ms / auto",
        "gainReduction": "1–2 dB",
        "notes": "Locks low end together"
      },
      {
        "source": "Lead / supersaw bus",
        "use": "Yes",
        "ratio": "2:1–4:1",
        "attackRelease": "10–30 ms / auto",
        "gainReduction": "2–3 dB",
        "notes": "Multiband or dynamic EQ on 2–5 kHz harshness"
      },
      {
        "source": "Lead vocal",
        "use": "Yes",
        "ratio": "3:1–4:1, then a fast FET-style stage",
        "attackRelease": "5–15 ms / 50–100 ms",
        "gainReduction": "4–8 dB total",
        "notes": "Heavy but transparent; de-esser 3–4 dB at 5–8 kHz"
      },
      {
        "source": "Drum bus",
        "use": "Yes",
        "ratio": "4:1 parallel",
        "attackRelease": "10 ms / 100 ms",
        "gainReduction": "6–10 dB on parallel, blended in",
        "notes": "Adds weight without dulling transients"
      },
      {
        "source": "Master bus",
        "use": "Yes",
        "ratio": "2:1 glue then clipper + limiter",
        "attackRelease": "3–30 ms / auto",
        "gainReduction": "1–3 dB glue; limiter 2–5 dB at drop",
        "notes": "Low-band multiband at no more than ~2 dB per band"
      }
    ],
    "notes": [
      {
        "text": "Gates are rarely needed (no open mics), except on MC and live vocal mics. Live, run a bus compressor or multiband plus a safety limiter on the DJ mixer input — never rely on the DJ’s red-lined mixer output."
      }
    ]
  },
  "fx": {
    "rows": [
      {
        "effect": "Large hall reverb",
        "appliedTo": "Leads, breakdown pads, vocal",
        "setting": "2.5–4 s decay, 20–40 ms pre-delay, HPF return 300–500 Hz",
        "amount": "Heavy in breakdowns, ducked or pulled back on the drop"
      },
      {
        "effect": "Plate reverb",
        "appliedTo": "Clap/snare, vocal",
        "setting": "1.0–1.6 s decay, 10–30 ms pre-delay",
        "amount": "Moderate"
      },
      {
        "effect": "Tempo-synced delay",
        "appliedTo": "Vocal, plucks, lead throws",
        "setting": "1/4 or dotted 1/8 at 128 BPM (469 / 352 ms), 20–35% feedback, band-passed 300 Hz–5 kHz",
        "amount": "Subtle on lines, heavy throws on phrase ends"
      },
      {
        "effect": "Sidechained reverb/delay returns",
        "appliedTo": "All big returns",
        "setting": "Duck 3–6 dB from the kick or vocal",
        "amount": "Keeps space without washing out the drop"
      },
      {
        "effect": "Riser / filter sweep",
        "appliedTo": "Builds",
        "setting": "8–16 bar automation; HPF swept up to 300–1,000 Hz on music bus",
        "amount": "Heavy, removed instantly at the drop"
      },
      {
        "effect": "Reverse reverb",
        "appliedTo": "Vocal entries, lead pick-ups",
        "setting": "Long decay, reversed, faded in over 1–2 beats",
        "amount": "Occasional"
      },
      {
        "effect": "Stereo widener / chorus",
        "appliedTo": "Saw layers, pads",
        "setting": "Width above 200 Hz only; check mono",
        "amount": "Moderate — never on sub or kick"
      }
    ],
    "notes": []
  },
  "vocals": [
    {
      "text": "In breakdowns the vocal is the feature, about 1–3 dB above the music; on the drop, vocal chops sit as an instrument below the kick and lead. Tone is bright and glossy, and tight (even stylized) tuning is expected. Doubles and stacked harmonies widen choruses; octave-shifted chops are genre staples. Crowds sing the chorus, so keep 2–5 kHz clear by dipping pads and saws there. Studio: large-diaphragm condenser. Live: a tight-pattern handheld near loud stage subs; MC mics need a high-pass at 120–150 Hz, compression and gating. Expect playback vocals blended with live ones."
    }
  ],
  "loudness": [
    {
      "label": "Live:",
      "text": "Big festival main stages typically run around 98–103 dBA LAeq over 15 minutes at FOH, with peaks to 110–115 dBA. Dance music carries far more low end than other genres — a C-minus-A difference of about 18 dB at 98 dBA is typical, so expect roughly 115–121 dBC at FOH. Common caps: a widely used safe-listening limit of 100 dBA LAeq-15 min; 103 dBA LAeq-15 min in some countries (with health bodies pushing for 100 or lower); 100 dBA over 60 min with a 115 dBA peak in others. Some festivals add a dBC cap, and offsite limits often bind first because sub energy travels. Run about 3 dB under the cap, use directional sub arrays, and keep the kick short."
    },
    {
      "label": "Studio / streaming:",
      "text": "Club and commercial EDM masters commonly hit −7 to −5 LUFS short-term at the drop (roughly −8 to −6 LUFS integrated); a “dynamic” approach of −9 to −11 short-term is also used. Streaming services normalize to about −14 LUFS, so over-limiting gives no loudness advantage there. A common streaming recommendation is below −1 dBTP, or below −2 dBTP for masters louder than −14 LUFS. Many club masters run near −0.2 to −0.5 dBFS sample-peak ceilings for DJ use; supply a −1 dBTP version for streaming. The genre tolerates very little short-term dynamic range (PLR ~6–8 dB at the drop) but needs macro contrast between sections."
    }
  ],
  "liveStudio": {
    "rows": [
      {
        "area": "Low end",
        "live": "Subs reach below 30 Hz with huge headroom; tame resonant tracks with dynamic EQ around 40–60 Hz",
        "studio": "Must translate on earbuds and car; add harmonics so bass is heard on small speakers"
      },
      {
        "area": "Source",
        "live": "Stereo mixer output — you can’t rebalance stems",
        "studio": "Full control of every layer and sidechain"
      },
      {
        "area": "Level consistency",
        "live": "Tracks vary by 3–6 dB in loudness; ride a bus compressor/multiband to “live master” the set",
        "studio": "Mastered to a single target per track"
      },
      {
        "area": "High mids",
        "live": "2–5 kHz harshness magnified by line arrays at 100+ dBA; cut more",
        "studio": "Brighter is accepted; avoid harsh resonances"
      },
      {
        "area": "Stereo image",
        "live": "Mono-compatible; much of the crowd hears one side; center fills and delays",
        "studio": "Wide saw and pad layers, but mono check"
      },
      {
        "area": "Loudness ceiling",
        "live": "SPL caps (dBA/dBC) and offsite limits",
        "studio": "LUFS targets and true-peak ceilings"
      },
      {
        "area": "Signal chain",
        "live": "Use the DJ mixer’s digital output, keep headroom, limiter as safety",
        "studio": "Gain-stage kick/bass around −10 dBFS before buss processing"
      }
    ],
    "notes": []
  },
  "notes": [
    {
      "text": "Start the mix with kick and sub alone; set them around −10 dBFS on the faders and build everything else around them.",
      "bullet": true
    },
    {
      "text": "Tune the kick to the key and make sure its tail doesn’t fight the bass note — mismatched pitch is the main cause of muddy big-room drops.",
      "bullet": true
    },
    {
      "text": "High-pass everything that isn’t kick or bass, usually anywhere from 100–150 Hz up.",
      "bullet": true
    },
    {
      "text": "Reduce section levels before the drop instead of pushing the master harder — contrast is louder than limiting.",
      "bullet": true
    },
    {
      "text": "Mistake: stacking too many supersaws. Mute layers one by one; anything you don’t miss goes.",
      "bullet": true
    },
    {
      "text": "Mistake: stereo or phasey sub — collapses on mono festival sub arrays.",
      "bullet": true
    },
    {
      "text": "Mistake: leaving reverb tails un-ducked on the drop, which smears the kick.",
      "bullet": true
    },
    {
      "text": "Mistake: chasing −4 LUFS masters; they distort on streaming conversion and get turned down anyway.",
      "bullet": true
    },
    {
      "text": "Live: watch dBC as well as dBA; turning sub down 2–3 dB often fixes an offsite complaint with little crowd impact.",
      "bullet": true
    }
  ],
  "references": [
    "Swedish House Mafia — “Don’t You Worry Child” (2012)",
    "Avicii — “Levels” (2011)",
    "Martin Garrix — “Animals” (2013)",
    "Hardwell — “Spaceman” (2012)",
    "Alesso — “Calling (Lose My Mind)” (2012)",
    "Zedd ft. Foxes — “Clarity” (2012)",
    "Dimitri Vegas & Like Mike vs Tujamo & Felguk — “Fireworks” (2013)",
    "Martin Garrix & Brooks — “Byte” (2017)"
  ],
  "empty": []
};
