/**
 * Mixing guide 08 — Reggaeton. GENERATED by scripts/mixing-guides/convert.py
 * from the owner's guide (assets/Mixing-Guides-50-Styles, read only). Edit the
 * conversion (scripts/mixing-guides/edits.py), not this file.
 */
import type { MixingGuide } from '../types';

export const GUIDE: MixingGuide = {
  "id": "reggaeton",
  "num": 8,
  "title": "Reggaeton",
  "expects": "Crowds expect to feel the dembow in their body, hear every word clearly enough to shout along, and get a drop or “beat switch” that sends the floor up.",
  "glance": {
    "origin": "Panama’s Spanish-language reggae (late 1980s) and Puerto Rico’s “underground” scene (early–mid 1990s), built on the Jamaican Dem Bow riddim; global from 2004, with Latin trap rising out of Puerto Rico from the mid-2000s",
    "tempo": "Reggaeton 88–100 BPM (classic perreo 90–96; “romántico” 80–90; Dominican dembow 110–130); Latin trap 60–80 BPM, often felt in double time (120–160)",
    "ensemble": "Solo artist or duo + DJ and full playback; arena tours add a drummer/percussionist, keys, guitar, 2–4 backing vocalists and dancers",
    "priority": "The dembow pulse (kick, sub and snare/timbal) locked and huge, with a clear, upfront Spanish lead vocal riding on it",
    "liveSpl": "98–103 dBA LAeq-15 min in clubs and arenas; 118–128 dBC; C-minus-A gap often 18–22 dB",
    "studioLoudness": "Masters commonly −8 to −5 LUFS-I (Latin trap −9 to −6); streaming normalizes to about −14"
  },
  "purpose": [
    {
      "text": "Reggaeton is dance music first: perreo, the close, hip-led dance that grew out of Caribbean and Afro-diasporic social dance, is the point of a reggaeton night. It also carries identity and pride for Puerto Rican, Panamanian, Dominican, Colombian and wider Latin audiences; it began as marginalized “underground” cassette music that authorities tried to censor, and its stars now headline stadiums. Crowds expect to feel the dembow in their body, hear every word clearly enough to shout along, and get a drop or “beat switch” that sends the floor up. Listeners say “that sounded wrong” when the boom of the kick is weak or blurred with the bass, the snare pattern is buried (the groove disappears), the vocal is muddy or masked, or the sub is so loud it feels like rumble with no pitch. Latin trap fans expect the 808 to be felt as notes, with the vocal dark, close and heavily tuned."
    }
  ],
  "instruments": [
    {
      "label": "Dembow drums:",
      "text": "a short, round, low kick on every quarter note; snare/clap or the “timbal” hits on the “3+3+2” offbeats; hi-hats and shakers driving 8ths and 16ths; machine-gun rolls and pitched fills into sections. Usually programmed and sample-based.",
      "bullet": true
    },
    {
      "label": "Sub bass / 808:",
      "text": "simple root or root-fifth lines, often lightly saturated; in Latin trap a long, gliding 808 carries the harmony.",
      "bullet": true
    },
    {
      "label": "Synths and keys:",
      "text": "plucks, pads, bell leads, filtered chords; moombahton and house elements on newer records.",
      "bullet": true
    },
    {
      "label": "Guitar:",
      "text": "nylon-string or reggaeton-pop guitar hooks (the “Despacito” lineage), sometimes electric rock textures.",
      "bullet": true
    },
    {
      "label": "Caribbean and Latin color:",
      "text": "congas, bongos, güiro, timbales, plena panderos, bomba barriles, cuatro, marimba and ukulele, which have all appeared on major records.",
      "bullet": true
    },
    {
      "label": "Live:",
      "text": "stems and click from a playback rig, a DJ, and on bigger tours an acoustic kit with a trigger doubling the electronic dembow kick.",
      "bullet": true
    }
  ],
  "arrangement": [
    {
      "text": "Most shows are artist plus DJ and tracks, often on a thrust or B-stage; tours add a drummer and percussionist upstage, keys and guitar to the sides, backing vocalists stage left or right, and frequent guest vocalists. The drums and sub own the groove, synths and guitar give harmony and hooks, and the lead vocal carries melody and rhythm (fast rap flows as well as sung coros). Arrangements are loop-based: an intro with filtered or no drums, a verse with the full dembow, a pre-coro that strips back or adds risers, and a coro that adds layers, doubles and ad-libs. Breakdowns drop the kick entirely before a big return; modern productions change the beat pattern or tempo halfway through, and Latin trap sections can sit inside a reggaeton song."
    }
  ],
  "dynamics": [
    {
      "text": "Macro-dynamics come from arrangement drops (kick and sub removed, then back) rather than from playing softer; a breakdown can sit 6–10 dB below a full coro. Micro-dynamics are tightly controlled: the dembow should be relentless and even. Preserve the drop contrast, since that is where the crowd reacts, while keeping the vocal and kick consistent. Live, playback stems arrive already mastered-sounding, so the engineer’s job is mostly balance, vocal control and riding the drops, not adding density."
    }
  ],
  "balance": [
    {
      "text": "Hierarchy, loudest to quietest: lead vocal and kick (near equal), sub/808, snare/timbal pattern, ad-libs and doubles, hi-hats and percussion, synth/guitar hooks, pads and effects. The low end is a kick-versus-sub negotiation: the kick should own a short punch around 50–70 Hz and the sub fills the space between hits. Sidechain or dynamic EQ (ducking the bass by 2–4 dB around 60 Hz when the kick hits) keeps the boom readable; on 808-led trap songs often the 808 is the kick and gets a top click layer. Keep kick, sub, snare and lead vocal mono and centered. Hats, shakers and percussion spread 20–50% left and right; doubles split wide; ad-libs placed off-center or bounced with panning delays. Synth pads and chorus layers can be wide, but check mono for club and phone playback."
    }
  ],
  "eq": {
    "rows": [
      {
        "source": "Dembow kick",
        "cut": "HPF 25–30 Hz; −3 to −5 dB at 200–400 Hz",
        "boost": "+2–3 dB at 50–70 Hz (thump); +1–2 dB at 2–4 kHz if it needs to read on small speakers",
        "notes": "Choose short, tight kicks; avoid long tails that collide with the sub"
      },
      {
        "source": "Sub / 808",
        "cut": "HPF 25–30 Hz; −2–3 dB at 150–250 Hz",
        "boost": "+1–3 dB at fundamental (40–60 Hz); harmonic saturation for 100–200 Hz presence",
        "notes": "Tune the 808 to the key; keep it mono below ~120 Hz"
      },
      {
        "source": "Snare / clap / timbal",
        "cut": "HPF 120–200 Hz; notch ring if any",
        "boost": "+2–3 dB at 200–400 Hz (the boxy reggaeton body); +2 dB at 1–3 kHz for snap",
        "notes": "The pattern carries the genre identity—make it audible but not piercing"
      },
      {
        "source": "Hi-hats / shakers",
        "cut": "HPF 300–500 Hz; dip 3–6 kHz if harsh",
        "boost": "Gentle shelf +1–2 dB at 10–12 kHz",
        "notes": "Hats should sparkle, not dominate the vocal’s sibilance"
      },
      {
        "source": "Congas / bongos / güiro",
        "cut": "HPF 80–150 Hz; −2 dB at 400–600 Hz",
        "boost": "+2 dB at 3–5 kHz (slap)",
        "notes": "Tuck behind programmed drums; pan for width"
      },
      {
        "source": "Synth plucks / pads",
        "cut": "HPF 150–250 Hz; −2–3 dB at 2–4 kHz on pads",
        "boost": "+1–2 dB air on leads",
        "notes": "Carve pads around the vocal presence band"
      },
      {
        "source": "Guitar (nylon/electric)",
        "cut": "HPF 100–150 Hz; −2 dB at 250–400 Hz",
        "boost": "+2 dB at 2–4 kHz for pluck",
        "notes": "Often the main hook—keep it bright but behind the vocal"
      },
      {
        "source": "Lead vocal",
        "cut": "HPF 80–120 Hz; −2–3 dB at 250–400 Hz; dynamic cut 600–700 Hz if boxy",
        "boost": "+2–3 dB at 3–5 kHz; +2 dB shelf at 10–12 kHz",
        "notes": "Spanish consonants (s, r, ch) need presence without sibilance"
      },
      {
        "source": "Ad-libs / doubles",
        "cut": "HPF 150–250 Hz; −3 dB at 1–5 kHz on backing parts",
        "boost": "Telephone/band-pass (300 Hz–3 kHz) as an effect",
        "notes": "Keep backing parts duller than the lead so the lead stays in front"
      }
    ],
    "notes": []
  },
  "compression": {
    "rows": [
      {
        "source": "Lead vocal (stage 1)",
        "use": "Yes",
        "ratio": "4:1",
        "attackRelease": "1–5 ms / 50–80 ms",
        "gainReduction": "3–6 dB",
        "notes": "Catch peaks on rapid rap flows"
      },
      {
        "source": "Lead vocal (stage 2)",
        "use": "Yes",
        "ratio": "2:1–3:1",
        "attackRelease": "Opto / program",
        "gainReduction": "2–4 dB",
        "notes": "Smooth level; parallel FET/opto-style blend 10–25%"
      },
      {
        "source": "Kick",
        "use": "Light",
        "ratio": "3:1–4:1",
        "attackRelease": "15–30 ms / 40–60 ms",
        "gainReduction": "2–3 dB",
        "notes": "Transient shaper often better than compression"
      },
      {
        "source": "Sub / 808",
        "use": "Yes",
        "ratio": "4:1",
        "attackRelease": "10–20 ms / 80–150 ms",
        "gainReduction": "3–6 dB",
        "notes": "Plus sidechain from kick, 2–4 dB duck"
      },
      {
        "source": "Snare / timbal",
        "use": "Yes",
        "ratio": "4:1",
        "attackRelease": "Fast attack / fast release",
        "gainReduction": "3–5 dB",
        "notes": "Tames transient and lifts decay for the boxy tone"
      },
      {
        "source": "Backing vocals / coros",
        "use": "Yes",
        "ratio": "4:1–6:1",
        "attackRelease": "5–10 ms / auto",
        "gainReduction": "5–8 dB",
        "notes": "Denser than the lead, sits behind"
      },
      {
        "source": "Drum / beat bus",
        "use": "Yes",
        "ratio": "2:1–4:1",
        "attackRelease": "10–30 ms / auto",
        "gainReduction": "2–3 dB",
        "notes": "Keep release short so the dembow doesn’t pump"
      },
      {
        "source": "Mix bus",
        "use": "Yes",
        "ratio": "2:1",
        "attackRelease": "10–30 ms / auto",
        "gainReduction": "1–3 dB",
        "notes": "Followed by clipper/limiter in mastering"
      }
    ],
    "notes": [
      {
        "text": "Avoid overcompressing drums: dembow depends on short, crisp tails. On live vocals, an expander (threshold around −55 to −60 dBFS, 4 dB range) cuts stage noise from IEM-less, running artists. De-ess at 5–8 kHz for 3–5 dB; Spanish “s” sounds are frequent. Mastering commonly uses soft clipping plus 3–5 dB of limiting."
      }
    ]
  },
  "fx": {
    "rows": [
      {
        "effect": "Slap delay",
        "appliedTo": "Lead vocal",
        "setting": "80–120 ms, 0–10% feedback, HPF 200 Hz / LPF 6 kHz",
        "amount": "Subtle–moderate"
      },
      {
        "effect": "Tempo delay (1/4, dotted 1/8)",
        "appliedTo": "Phrase ends, hook words, ad-libs",
        "setting": "15–35% feedback, ping-pong on ad-libs",
        "amount": "Moderate, thrown per phrase"
      },
      {
        "effect": "Plate / short hall",
        "appliedTo": "Lead vocal, coros",
        "setting": "1.0–1.8 s decay, 30–60 ms pre-delay",
        "amount": "Subtle in verses, more in coros"
      },
      {
        "effect": "Long dark reverb",
        "appliedTo": "Snare rolls, transitions",
        "setting": "3–6 s decay, LPF 4–6 kHz",
        "amount": "Heavy, automated into drops"
      },
      {
        "effect": "Doubler / chorus / pitch spread",
        "appliedTo": "Claps, snares, backing vocals",
        "setting": "±5–15 cents, 10–25 ms",
        "amount": "Moderate for width"
      },
      {
        "effect": "Filter sweeps / risers",
        "appliedTo": "Full mix or beat bus into drops",
        "setting": "HPF 200 Hz–1 kHz sweep over 1–4 bars",
        "amount": "As arrangement effect"
      },
      {
        "effect": "Tape / tube saturation",
        "appliedTo": "Sub, 808, vocals",
        "setting": "Low drive, adding 2nd/3rd harmonics",
        "amount": "Subtle to moderate"
      }
    ],
    "notes": []
  },
  "vocals": [
    {
      "text": "The lead vocal is loud and forward, closer to pop and hip-hop than to rock: roughly 2–4 dB above the beat by perceived level, with every syllable intelligible because the audience sings along and fast Spanish flows lose meaning quickly when masked. Tone is bright and close, with controlled 200–400 Hz and strong 3–5 kHz presence; Latin trap vocals sit darker and more intimate. Pitch correction (real-time or graphical) is standard and often audible as a stylistic choice, especially in Latin trap and modern romántico; set retune speed fast for the effect, slower for natural singers. Hooks are stacked with doubles 6–10 dB under the lead and harmonies; ad-libs (“yeh”, producer and artist tags) are short, often filtered and placed off-center. Live, artists use handheld wireless dynamic or condenser capsules; expect rapping off-mic, crowd shouting and multiple guest vocalists, so build snapshots for each guest and keep the lead on a VCA for fast rides. Many artists sing over a lead guide or vocal stem: confirm with the playback tech which parts are live so you can balance the stem against the live mic."
    }
  ],
  "loudness": [
    {
      "label": "Live:",
      "text": "Club and arena reggaeton runs about 98–103 dBA LAeq-15 at FOH, with peaks at drops of 108–112 dBA and C-weighted levels of 118–128 dBC; the genre’s sub expectations sit between hip-hop and EDM. A C-minus-A gap above 20 dB at 100+ dBA signals sub-heavy exposure, worth tracking. Large tours use cardioid sub arrays (flown and ground-stacked) to deliver musical, pitched low end to the audience and keep it off a thrust stage. HPF the subs around 30 Hz to save headroom. By common hearing-safety guidance, 100 dBA is safe for only about 15 minutes; offer earplugs, respect venue limits (often 100 dBA over 60 minutes or 102–103 dBA LAeq-15 at festivals) and protect your own ears across long sets."
    },
    {
      "label": "Studio / streaming:",
      "text": "Commercial reggaeton masters typically land at −8 to −5 LUFS-I, with short-term loudness of −6 to −4 LUFS in the coros; Latin trap is a little more open (−9 to −6). Use −1 dBTP for masters at or below −14 LUFS and −2 dBTP for louder ones, since dense, limited dembow overshoots in lossy codecs. Most streaming services normalize to −14 LUFS, so extreme loudness buys nothing there. The genre tolerates a low PLR (6–9 dB; at −2 dBTP that means a master at about −8 LUFS-I or quieter) and a loudness range of 3–6 LU, but keep the drop contrast."
    }
  ],
  "liveStudio": {
    "rows": [
      {
        "area": "Low end",
        "live": "Cardioid subs, HPF ~30 Hz, dynamic EQ ducking bass at ~63 Hz under the kick",
        "studio": "Kick/808 sidechain, tuning and saturation fine-tuned for phones and clubs"
      },
      {
        "area": "Drums",
        "live": "Stems plus acoustic kit and trigger; phase-align kick in, kick out and trigger",
        "studio": "Fully programmed, layered samples; transient shaping and parallel crunch"
      },
      {
        "area": "Vocals",
        "live": "Playback guide vs live mic balance, guests on snapshots, expander for stage noise",
        "studio": "Comped, tuned, stacked; detailed automation and ad-lib placement"
      },
      {
        "area": "Effects",
        "live": "Tapped delays and one or two reverbs; throws on hooks",
        "studio": "Many automated delays, filters and risers per section"
      },
      {
        "area": "Dynamics",
        "live": "Ride vocal and drops by hand on VCAs",
        "studio": "Automation sculpts every drop and beat switch"
      },
      {
        "area": "Mix approach",
        "live": "Small touches, keep PA tonality consistent across a large thrust and bowl",
        "studio": "Commercial, loud, club-ready balance"
      },
      {
        "area": "Loudness",
        "live": "98–103 dBA LAeq-15, venue limits",
        "studio": "−8 to −5 LUFS-I, −1 to −2 dBTP"
      }
    ],
    "notes": []
  },
  "notes": [
    {
      "text": "Get the kick-sub relationship right first; dembow without a clean boom loses the dance floor.",
      "bullet": true
    },
    {
      "text": "Keep the snare/timbal pattern clearly audible—it is the genre’s signature, not decoration.",
      "bullet": true
    },
    {
      "text": "Don’t let 808 or synth-bass harmonics mask the vocal in the 150–400 Hz range; saturate for small-speaker translation instead of boosting lows.",
      "bullet": true
    },
    {
      "text": "Tuning is expected, but don’t let a fast retune garble fast Spanish consonants; intelligibility wins.",
      "bullet": true
    },
    {
      "text": "Live, phase-align kick mics and triggers, and confirm stem levels and vocal-guide content with the playback operator before doors.",
      "bullet": true
    },
    {
      "text": "Avoid overcompressing the beat bus; pumping and smeared tails kill the dembow’s bounce.",
      "bullet": true
    }
  ],
  "references": [
    "Daddy Yankee, “Gasolina”, 2004",
    "Don Omar, “Dale Don Dale”, 2003",
    "Luis Fonsi feat. Daddy Yankee, “Despacito”, 2017",
    "J Balvin & Willy William, “Mi Gente”, 2017",
    "Bad Bunny, “Tití Me Preguntó”, 2022",
    "Karol G & Bad Bunny, “Ahora Me Llama”, 2017",
    "Rauw Alejandro, “Todo de Ti”, 2021",
    "Bad Bunny, “Soy Peor” (Latin trap), 2016"
  ],
  "empty": []
};
