/**
 * Mixing guide 09 — Regional Mexican. GENERATED by scripts/mixing-guides/convert.py
 * from the owner's guide (assets/Mixing-Guides-50-Styles, read only). Edit the
 * conversion (scripts/mixing-guides/edits.py), not this file.
 */
import type { MixingGuide } from '../types';

export const GUIDE: MixingGuide = {
  "id": "regional-mexican",
  "num": 9,
  "title": "Regional Mexican",
  "expects": "Fans sing every line, shout gritos in the gaps, and expect the singer’s voice to be big, close and fully intelligible.",
  "glance": {
    "origin": "Mexico and the US borderlands: banda from Sinaloa brass bands (1880s onward), mariachi from Jalisco and western Mexico (19th century, standardized by the 1950s), norteño from Nuevo León/Texas (late 1800s–1930s), corridos tumbados from Sinaloa, Sonora and Los Angeles (late 2010s)",
    "tempo": "Polka/norteño 2/4 at 100–130 BPM (felt in 2); cumbia 90–105; rancheras and boleros 60–90; sones and huapangos in 6/8 (dotted quarter ≈ 60–80); tumbados mostly 6/8 or 3/4 around 120–150 BPM",
    "ensemble": "Norteño/tumbado 4–6 piece; mariachi 7–12; banda sinaloense 14–20 plus 1–3 singers; stadium acts 17–24 on stage",
    "priority": "The lead singer’s words and emotion on top of a firmly locked low end (tuba, tololoche, guitarrón or bass)",
    "liveSpl": "Mariachi/norteño 92–98 dBA LAeq-15; banda and arena shows 98–103 dBA, about 112–120 dBC",
    "studioLoudness": "Banda and norteño masters commonly −10 to −8 LUFS-I; tumbados −9 to −7; mariachi −14 to −11; streaming normalizes to about −14"
  },
  "purpose": [
    {
      "text": "Regional Mexican music is music for dancing, drinking, mourning and remembering, often all in one night. Bandas play quinceañeras, weddings, jaripeos and palenques; mariachi is serenade, celebration and national identity (UNESCO listed it as intangible heritage in 2011); norteño and corridos carry stories of the border, migration and, in many corridos, the drug trade. Corridos tumbados brought the narrative form to a young streaming audience with trap swagger. Fans sing every line, shout gritos in the gaps, and expect the singer’s voice to be big, close and fully intelligible. They will say “that sounded wrong” if the vocal is buried under brass, the tuba or bass is weak or boomy so the 2/4 bounce is lost, the trumpets are painfully bright, or the violins disappear. Volume itself is part of the culture: banda’s loudness is a point of pride and has even sparked noise-regulation fights in Mazatlán."
    }
  ],
  "instruments": [
    {
      "label": "Banda sinaloense:",
      "text": "3–4 trumpets, 3–4 Bb clarinets (singing melodic lines that often double the voice), 2–3 valve trombones, 2 Eb alto horns (charchetas, playing off-beat chord “chucks”), sousaphone/tuba carrying the walking, arpeggiated bass line, tambora (20–26 in bass drum with a cymbal on top, played by one person) and tarola (snare, timbales, cowbell, hats).",
      "bullet": true
    },
    {
      "label": "Mariachi:",
      "text": "3–8 violins, 2 trumpets, vihuela (small, bright, round-backed strummed guitar), guitarrón (large acoustic bass), guitar, sometimes Mexican folk harp.",
      "bullet": true
    },
    {
      "label": "Norteño:",
      "text": "diatonic button accordion (melody and fills), bajo sexto (12-string bass-register rhythm guitar), electric bass or tololoche, drum kit; some groups add sax.",
      "bullet": true
    },
    {
      "label": "Corridos tumbados / sierreño:",
      "text": "requinto (fast, bright lead acoustic, often 6-string steel), 12-string “armonía” rhythm guitar, tololoche or electric bass; newer tracks add charcheta, trombone, tuba and occasional 808s or trap percussion.",
      "bullet": true
    },
    {
      "label": "Playback:",
      "text": "limited; tecnobanda and grupero use keys and drum machines, and tumbado tours may run 808 or percussion stems.",
      "bullet": true
    }
  ],
  "arrangement": [
    {
      "text": "Banda stages put percussion center-rear, tuba beside the tambora, brass in a line or riser behind the singers with clarinets on one side. Mariachi stands in a front line (violins one side, trumpets the other, rhythm strings in the middle) and often moves. Norteño is compact: accordion and singer front, bajo sexto beside, bass and drums behind. The arrangement roles are consistent: low instrument plus tambora/kick plays the downbeat, off-beat chords come from charchetas, vihuela or bajo sexto, and melody passes between voice and instruments. Intros and instrumental breaks feature tutti brass or violin/trumpet unisons; verses thin out under the voice; clarinets or requinto play adornos (short fills) between vocal lines; the last chorus brings everybody back."
    }
  ],
  "dynamics": [
    {
      "text": "Acoustic ensembles here have real section dynamics, often 10–15 dB from a quiet vocal verse to a full brass tutti. The mix’s main job is to keep the vocal on top when the band jumps: brass hits can run 20 dB above the average and microphones must handle 140 dB+ peaks at the bell. Ride brass group faders down under the vocal and up in the instrumental breaks rather than compressing the brass hard. Boleros and rancheras need room to breathe; let the singer’s long held notes swell. Tumbados are steadier and more compressed, closer to hip-hop dynamics."
    }
  ],
  "balance": [
    {
      "text": "Hierarchy, loudest to quietest: lead vocal, tuba/bass and tambora/kick, lead melodic instrument for the section (trumpets, accordion, requinto or violins), off-beat harmony (charchetas, vihuela, bajo sexto), clarinets and trombones, snare/tarola, backing vocals and effects. Low end: in banda the tuba owns 40–120 Hz (fundamentals roughly 40–90 Hz) while the tambora is a punch around 60–100 Hz plus cymbal splash; keep the tambora shorter and let the tuba sustain. In tumbados, decide whether tololoche or 808 owns the sub and don’t let both fight. Center: lead vocal, tuba/bass, tambora/kick, accordion or requinto. Pan sections as they stand: trumpets slightly one way, clarinets or violins the other, charchetas and trombones inside them. Keep the image moderate live so the whole crowd hears the full section."
    }
  ],
  "eq": {
    "rows": [
      {
        "source": "Tuba / sousaphone",
        "cut": "HPF 30–35 Hz; −2–4 dB at 200–300 Hz (honk/boom)",
        "boost": "+2 dB at 60–80 Hz; +1–2 dB at 600–900 Hz (note definition)",
        "notes": "Mic 15–30 cm off the bell rim, or clip mic; the definition boost makes the bass line audible on small speakers"
      },
      {
        "source": "Tambora",
        "cut": "HPF 35 Hz; −3–5 dB at 300–500 Hz",
        "boost": "+2–3 dB at 60–90 Hz; +2 dB at 2–3 kHz (beater)",
        "notes": "Separate mic or overhead for the mounted cymbal; keep it shorter than the tuba"
      },
      {
        "source": "Tarola / snare",
        "cut": "HPF 100 Hz; notch ring 600 Hz–1 kHz",
        "boost": "+2 dB at 200 Hz; +2–3 dB at 4–6 kHz",
        "notes": "Timbales: HPF 150 Hz, +2 dB at 3–5 kHz"
      },
      {
        "source": "Trumpets",
        "cut": "HPF 150–200 Hz; −2–4 dB at 2.5–4 kHz if piercing",
        "boost": "+1–2 dB at 1–1.5 kHz (body)",
        "notes": "Mic 30–50 cm and off-axis to warm; avoid presence-peak vocal mics"
      },
      {
        "source": "Clarinets",
        "cut": "HPF 120–150 Hz; −2 dB at 400 Hz",
        "boost": "+2 dB at 2–3 kHz; gentle shelf at 8–10 kHz",
        "notes": "They carry melody; don’t let trumpets mask them"
      },
      {
        "source": "Trombones / charchetas",
        "cut": "HPF 80–100 Hz; −2 dB at 300–400 Hz",
        "boost": "+1–2 dB at 1 kHz",
        "notes": "Charcheta “chucks” need 1–2 kHz definition, not low end"
      },
      {
        "source": "Accordion",
        "cut": "HPF 80–100 Hz (treble side); −2–3 dB at 300–500 Hz; dip 2–4 kHz if reedy",
        "boost": "+1–2 dB at 1–2 kHz",
        "notes": "Separate bass-side mic, HPF 60 Hz; dynamics pick up less button noise"
      },
      {
        "source": "Bajo sexto / 12-string / vihuela",
        "cut": "HPF 100–120 Hz (vihuela 150 Hz); −2–3 dB at 200–300 Hz",
        "boost": "+2 dB at 3–5 kHz (strum attack); shelf at 10 kHz",
        "notes": "Keep these out of the tuba/bass range"
      },
      {
        "source": "Requinto",
        "cut": "HPF 120–150 Hz; dip 2.5 kHz if spiky",
        "boost": "+2 dB at 5–8 kHz (sparkle)",
        "notes": "Bright and forward is the style"
      },
      {
        "source": "Violins",
        "cut": "HPF 200–250 Hz; −2 dB at 2–3 kHz if scratchy",
        "boost": "+1–2 dB at 5–7 kHz; small lift at 300 Hz for warmth",
        "notes": "Clip-on condensers; watch feedback around 1–3 kHz"
      },
      {
        "source": "Guitarrón / tololoche",
        "cut": "HPF 35–40 Hz; −2–3 dB at 150–250 Hz",
        "boost": "+2 dB at 70–90 Hz; +2 dB at 700 Hz–1 kHz (pluck)",
        "notes": "Pickup plus mic blend; the pluck must read"
      },
      {
        "source": "Lead vocal",
        "cut": "HPF 80–100 Hz (male), 120 Hz (female); −2 dB at 250–350 Hz",
        "boost": "+2–3 dB at 2.5–4 kHz; shelf +1–2 dB at 10 kHz",
        "notes": "Space for the vocal at 2–4 kHz by dipping brass 1–2 dB there"
      }
    ],
    "notes": []
  },
  "compression": {
    "rows": [
      {
        "source": "Lead vocal",
        "use": "Yes",
        "ratio": "3:1–4:1",
        "attackRelease": "5–10 ms / 80–150 ms",
        "gainReduction": "3–6 dB",
        "notes": "Belted ranchera notes jump 15 dB; add an opto stage in the studio"
      },
      {
        "source": "Tuba / tololoche / guitarrón",
        "use": "Yes",
        "ratio": "4:1",
        "attackRelease": "15–30 ms / 100–150 ms",
        "gainReduction": "3–6 dB",
        "notes": "Evens note-to-note level so the walking line stays steady"
      },
      {
        "source": "Tambora / kick",
        "use": "Light",
        "ratio": "3:1",
        "attackRelease": "20–30 ms / 60–100 ms",
        "gainReduction": "2–4 dB",
        "notes": "Keep the attack; gate a closed kick, not an open tambora"
      },
      {
        "source": "Brass group",
        "use": "Light",
        "ratio": "2:1",
        "attackRelease": "20–30 ms / auto",
        "gainReduction": "1–3 dB",
        "notes": "Prefer fader rides; heavy compression makes horns harsh"
      },
      {
        "source": "Accordion",
        "use": "Yes",
        "ratio": "3:1",
        "attackRelease": "10–20 ms / 100 ms",
        "gainReduction": "2–4 dB",
        "notes": "Bellows changes cause level jumps"
      },
      {
        "source": "Violin group",
        "use": "Light",
        "ratio": "2:1–3:1",
        "attackRelease": "10–20 ms / auto",
        "gainReduction": "2–3 dB",
        "notes": "Helps them survive next to trumpets"
      },
      {
        "source": "808 (tumbados)",
        "use": "Yes",
        "ratio": "4:1 + limiter",
        "attackRelease": "10 ms / 50–80 ms",
        "gainReduction": "3–5 dB",
        "notes": "Sidechain 2–4 dB from kick if both are present"
      },
      {
        "source": "Mix bus",
        "use": "Optional",
        "ratio": "2:1",
        "attackRelease": "30 ms / auto",
        "gainReduction": "1–2 dB",
        "notes": "Glue; leave loudness to mastering"
      }
    ],
    "notes": [
      {
        "text": "De-ess the lead at 5–8 kHz for 2–4 dB. Avoid gating clip-on brass mics; mute them in the console between songs instead. Master limiting of 3–5 dB is common on banda and tumbado releases; mariachi sounds better with 1–3 dB."
      }
    ]
  },
  "fx": {
    "rows": [
      {
        "effect": "Plate reverb",
        "appliedTo": "Lead vocal",
        "setting": "1.4–2.2 s decay, 30–60 ms pre-delay",
        "amount": "Moderate; heavier on rancheras and boleros"
      },
      {
        "effect": "Hall reverb",
        "appliedTo": "Violins, trumpets, mariachi ensemble",
        "setting": "1.8–2.6 s, 20–40 ms pre-delay",
        "amount": "Moderate; simulates the concert-hall sound of classic records"
      },
      {
        "effect": "Slap / tempo delay",
        "appliedTo": "Lead vocal, grito, phrase ends",
        "setting": "90–140 ms slap or 1/4 note, 15–25% feedback",
        "amount": "Subtle; automate on final words"
      },
      {
        "effect": "Short room",
        "appliedTo": "Brass section, tambora",
        "setting": "0.6–1.0 s",
        "amount": "Subtle–moderate; blends close mics into one band"
      },
      {
        "effect": "Pitch correction",
        "appliedTo": "Tumbado and modern banda vocals",
        "setting": "Fast retune (10–30 ms) on tumbados; slow/transparent elsewhere",
        "amount": "Audible on tumbados is genre-appropriate; inaudible on mariachi"
      },
      {
        "effect": "Saturation",
        "appliedTo": "808, tololoche, requinto",
        "setting": "Light tape/tube, 1–3 dB of drive",
        "amount": "Subtle; helps lows translate to phones"
      }
    ],
    "notes": []
  },
  "vocals": [
    {
      "text": "The singer is the star and sits clearly in front, often 3–6 dB above the band by perceived level, closer to pop than rock. Rancheras and banda ballads feature huge sustained notes, sobbing vibrato and falsetto breaks (huapango); leave headroom and ride the fader so climaxes are thrilling but not painful. Spanish diction must be clear: consonants live at 2–5 kHz, so carve that space out of the trumpets. Gritos from the band or singer are part of the music; keep a channel or ambient mic open to catch them. Multiple featured singers are common (big tours can carry seven); set each one’s gain and EQ individually. Tumbado vocals are delivered in a laid-back, conversational flow, often doubled and tuned. Live, use a robust dynamic or handheld condenser on wireless; singers often walk to the stage edge, so watch feedback at 2–4 kHz."
    }
  ],
  "loudness": [
    {
      "label": "Live:",
      "text": "Mariachi restaurants and weddings run 88–95 dBA; theater mariachi and norteño 92–98 dBA LAeq-15; banda, palenque and arena shows 98–103 dBA with 112–120 dBC and peaks of 110–115 dBA. The low end is tuba-and-tambora driven, not EDM sub; a C-minus-A gap over about 18 dB means too much sub. A banda horn line on stage is already loud, so in small rooms you may be reinforcing only the vocal and tuba. Cardioid sub arrays help monitor engineers working with 17-plus musicians. Common hearing-safety guidance sets 85 dBA over 8 hours as the hazard threshold with a 3 dB exchange rate, so 100 dBA is safe for only about 15 minutes; offer earplugs and wear your own."
    },
    {
      "label": "Studio / streaming:",
      "text": "Banda and norteño masters typically land at −10 to −8 LUFS-I, tumbados −9 to −7, mariachi and traditional recordings −14 to −11, all at −1 dBTP (−2 dBTP for louder masters a common streaming recommendation). Streaming normalizes to about −14 LUFS, so excess limiting only dulls the brass. Aim for a PLR of 9–12 dB on acoustic styles to keep horn transients alive."
    }
  ],
  "liveStudio": {
    "rows": [
      {
        "area": "Brass",
        "live": "Clip-on mics (small clip-on condensers) on each horn; heavy stage bleed, group to 2–4 VCAs",
        "studio": "Distant section mics (1–3 m) plus spots for a fuller, smoother tone"
      },
      {
        "area": "Low end",
        "live": "Tuba and tambora plus room buildup; HPF other sources hard",
        "studio": "Fine tune tuba/tambora or 808/tololoche relationship, sidechain if needed"
      },
      {
        "area": "Vocals",
        "live": "Gain-before-feedback limits; many singers and scene changes",
        "studio": "Comping, tuning, doubles and detailed rides"
      },
      {
        "area": "Strings",
        "live": "Violins and vihuela fight trumpets and wedges; clip-ons, careful EQ",
        "studio": "Room or spot mics, hall reverb, space to shine"
      },
      {
        "area": "Effects",
        "live": "One plate, one hall, a tapped delay",
        "studio": "Several reverbs and delays automated by section"
      },
      {
        "area": "Loudness",
        "live": "95–103 dBA LAeq, venue limits",
        "studio": "−10 to −8 LUFS-I typical, −1 dBTP"
      }
    ],
    "notes": []
  },
  "notes": [
    {
      "text": "Learn the 2/4 bounce: tuba or bass on the beat, charchetas, vihuela or bajo sexto on the off-beat. If the off-beat chord disappears, the music stops dancing.",
      "bullet": true
    },
    {
      "text": "Don’t let the tambora’s boom swamp the tuba; the bass line is the harmony.",
      "bullet": true
    },
    {
      "text": "Tame trumpets with mic angle and a 2.5–4 kHz dip before reaching for compression.",
      "bullet": true
    },
    {
      "text": "Clarinets and violins are melodic voices, not pads; keep them audible.",
      "bullet": true
    },
    {
      "text": "Leave gaps for gritos, and keep the vocal on top in brass tutti with fader rides.",
      "bullet": true
    },
    {
      "text": "Tumbados: requinto bright and forward, tololoche punchy, vocal intimate; don’t make it sound like a rock band.",
      "bullet": true
    },
    {
      "text": "Large bandas run 60–90 inputs; build VCAs by section before soundcheck.",
      "bullet": true
    }
  ],
  "references": [
    "Los Tigres del Norte, “Contrabando y traición”, 1972",
    "Vicente Fernández, “Volver, volver”, 1972",
    "Linda Ronstadt, Canciones de mi padre, 1987",
    "Jenni Rivera, La Gran Señora, 2009",
    "Christian Nodal, “Adiós amor”, 2017",
    "Natanael Cano, Corridos Tumbados, 2019",
    "Grupo Firme and Carin León, “El tóxico”, 2020",
    "Eslabon Armado and Peso Pluma, “Ella baila sola”, 2023"
  ],
  "empty": []
};
