/**
 * Mixing guide 10 — K-pop. GENERATED by scripts/mixing-guides/convert.py
 * from the owner's guide (assets/Mixing-Guides-50-Styles, read only). Edit the
 * conversion (scripts/mixing-guides/edits.py), not this file.
 */
import type { MixingGuide } from '../types';

export const GUIDE: MixingGuide = {
  "id": "k-pop",
  "num": 10,
  "title": "K-pop",
  "expects": "On record they expect a dense, glossy, hyper-polished mix where every member gets a recognizable moment; live, the record’s impact plus real voices and their own fandom chanting back.",
  "glance": {
    "origin": "South Korea (Seoul); modern form from Seo Taiji and Boys (1992) and the agency “idol” system of SM, YG and JYP from the mid-1990s; global “Hallyu” wave from the 2010s",
    "tempo": "95–130 BPM for most title tracks (ballads 60–80; hip-hop cuts 80–100 half-time; EDM and dance-break sections 120–140)",
    "ensemble": "Idol group of 4–13 vocalists/rappers on headset or handheld wireless, plus playback tracks; larger tours add a 4–6 piece live band and 10–20 dancers",
    "priority": "Every member’s voice identifiable and on top of a hard, bright, fully produced track, with the low end punching underneath",
    "liveSpl": "Arena/stadium 100–106 dBA LAeq-15; peaks to 108–109 dBA and roughly 125–130 dBC on large tours; crowd screams alone can exceed 100 dBA",
    "studioLoudness": "Title-track masters commonly −8 to −5 LUFS-I (B-sides and ballads −10 to −8); streaming normalizes to about −14"
  },
  "purpose": [
    {
      "text": "K-pop is pop built as a total package: song, choreography, visual concept and fandom are designed together by an entertainment agency. It is music for dancing, watching and belonging. Fans (“ARMY”, “BLINK”, “ONCE”, “CARAT”) follow every comeback, buy official light sticks, learn fanchants and treat concerts as shared ritual. On record they expect a dense, glossy, hyper-polished mix where every member gets a recognizable moment; live, the record’s impact plus real voices and their own fandom chanting back. Fans say “that sounded wrong” if a member’s line disappears, if playback obviously overpowers live singing, if the dance break lacks punch, or if the mix is harsh enough to fatigue a young crowd over a three-hour show."
    }
  ],
  "instruments": [
    {
      "label": "Programmed drums:",
      "text": "layered kicks, 808s, claps and snares drawn from hip-hop, trap, EDM, house and moombahton; frequent kit changes inside one song.",
      "bullet": true
    },
    {
      "label": "Bass:",
      "text": "808 sub, synth bass or slap/fingered bass on funk and city-pop-styled tracks.",
      "bullet": true
    },
    {
      "label": "Synths and samples:",
      "text": "big supersaw leads, plucks, brass stabs, vocal chops, orchestral hits, risers and impacts.",
      "bullet": true
    },
    {
      "label": "Live band (on tour):",
      "text": "drums, bass, guitar, 1–2 keyboards reinforcing the tracks (BTS, SEVENTEEN, DAY6-style band acts).",
      "bullet": true
    },
    {
      "label": "Occasional Korean colour:",
      "text": "gayageum, daegeum, buk drums or janggu samples appear in “Korean-concept” songs (traditional-fusion stages); treat as featured textures.",
      "bullet": true
    },
    {
      "label": "Playback:",
      "text": "the backbone of nearly every K-pop show—instrument stems, backing vocals, sometimes a guide or full “AR” vocal.",
      "bullet": true
    }
  ],
  "arrangement": [
    {
      "text": "Groups divide roles: main, lead and sub vocals, main rapper, lead dancer and “center.” Lines are distributed so every member sings or raps, often only a few bars each, while rotating across the stage. A title track is a collage: intro hook, rap verse over a stripped beat, pre-chorus build, chorus “drop” in unison or stacked harmony, a second verse in a new groove, a bridge for the main vocal’s high note, and a dance break. Genre and tempo can switch mid-song (trap verse into house chorus). Members move in formations with dancers behind; a band sits on side or rear risers. Fans shout member names in intros and verse gaps, and songs leave room for these chants."
    }
  ],
  "dynamics": [
    {
      "text": "Macro-dynamics come from arrangement: a near-empty rap verse can drop 8–12 dB in density before the chorus slams back. Micro-dynamics are tightly controlled—K-pop masters are among pop’s loudest. In the studio, keep section contrast with automation (filter sweeps, a beat drop before the hook). Live, playback is already dense, so the dynamic work is on vocals: headset levels swing 15–20 dB between whispered intros and belting while dancing. Ride every vocal fader; don’t rely on compression alone."
    }
  ],
  "balance": [
    {
      "text": "Hierarchy, loudest to quietest: the active lead vocal line, kick/808, the chorus group vocal stack, snare/clap, lead synth or hook element, bass, pads and backing-vocal playback, effects returns. The kick provides the click and short punch (50–80 Hz thump, 2–5 kHz attack); the 808 or sub owns 35–60 Hz sustain—sidechain the sub to the kick 2–4 dB. Keep everything below about 120 Hz mono. Lead vocals and raps sit dead center no matter where the member is standing on stage; don’t pan by position. Backing-vocal stacks and harmonies go wide (doubles 60–100% L/R), synth layers and guitars spread wide, and ad-libs float slightly off-center. The track should feel wide and expensive; the vocal should feel close."
    }
  ],
  "eq": {
    "rows": [
      {
        "source": "Kick (programmed)",
        "cut": "HPF 30 Hz; −2–4 dB at 250–400 Hz",
        "boost": "+2–3 dB at 55–70 Hz; +2–3 dB at 3–5 kHz",
        "notes": "Pick a kick that already fits the 808 before EQ"
      },
      {
        "source": "808 / sub bass",
        "cut": "HPF 25–30 Hz; dip 2–3 dB at the kick’s fundamental",
        "boost": "Saturation for 100–200 Hz harmonics; +1–2 dB at 700 Hz–1 kHz",
        "notes": "Harmonics let small speakers and phones hear the bass"
      },
      {
        "source": "Snare / clap",
        "cut": "HPF 120–150 Hz; −2 dB at 400–600 Hz",
        "boost": "+2–3 dB at 200 Hz (body); +2–4 dB shelf at 8–10 kHz",
        "notes": "Often several layers; check phase"
      },
      {
        "source": "Synth leads / plucks",
        "cut": "HPF 150–250 Hz; −2–3 dB at 2–4 kHz when vocals sing",
        "boost": "+1–2 dB at 6–10 kHz",
        "notes": "Dynamic EQ keyed from vocal bus works well"
      },
      {
        "source": "Pads / chords",
        "cut": "HPF 200–300 Hz; −3 dB at 1–3 kHz",
        "boost": "Gentle air shelf at 10–12 kHz",
        "notes": "Push behind vocals, keep width"
      },
      {
        "source": "Live keys / guitar",
        "cut": "HPF 100–150 Hz; −2 dB at 250–400 Hz",
        "boost": "+1–2 dB at 2–3 kHz only in solos",
        "notes": "Doubles the tracks—often low-cut more live"
      },
      {
        "source": "Lead vocal (each member)",
        "cut": "HPF 90–150 Hz (higher for female voices); −2–3 dB at 250–400 Hz; notch harsh 2.5–4 kHz",
        "boost": "+2–3 dB at 3–5 kHz; +3–5 dB high shelf from 10–12 kHz",
        "notes": "Bright, airy top is the house sound"
      },
      {
        "source": "Rap vocal",
        "cut": "HPF 80–100 Hz; −2 dB at 300 Hz",
        "boost": "+2 dB at 150–200 Hz (chest); +2–3 dB at 3–4 kHz",
        "notes": "Fuller and slightly darker than sung lines"
      },
      {
        "source": "Backing vocal stack",
        "cut": "HPF 150–250 Hz; −3 dB at 300–500 Hz",
        "boost": "+2 dB at 8–12 kHz",
        "notes": "Thin the lows so the stack doesn’t muddy"
      },
      {
        "source": "Playback stems (live)",
        "cut": "High shelf −2–3 dB above 6 kHz on BV stems",
        "boost": "—",
        "notes": "Leaves room for live voices to cut"
      }
    ],
    "notes": []
  },
  "compression": {
    "rows": [
      {
        "source": "Lead vocal (stage 1, FET)",
        "use": "Yes",
        "ratio": "4:1–8:1",
        "attackRelease": "10–30 ms / 50–80 ms",
        "gainReduction": "4–7 dB",
        "notes": "Slower attack keeps consonants; a FET-style unit works well this way"
      },
      {
        "source": "Lead vocal (stage 2, opto)",
        "use": "Yes",
        "ratio": "3:1",
        "attackRelease": "Program",
        "gainReduction": "2–4 dB",
        "notes": "Optical compression at tracking is common in Korean studios"
      },
      {
        "source": "Headset vocals (live)",
        "use": "Yes",
        "ratio": "4:1–6:1",
        "attackRelease": "3–10 ms / 80–150 ms",
        "gainReduction": "6–10 dB on belts",
        "notes": "Catches huge swings while dancing"
      },
      {
        "source": "Rap vocal",
        "use": "Yes",
        "ratio": "4:1–6:1",
        "attackRelease": "5–15 ms / 60–100 ms",
        "gainReduction": "5–8 dB",
        "notes": "Even and upfront"
      },
      {
        "source": "Backing vocal bus",
        "use": "Yes",
        "ratio": "4:1",
        "attackRelease": "5 ms / auto",
        "gainReduction": "4–6 dB",
        "notes": "Plus saturation for “crunch”"
      },
      {
        "source": "808 / bass",
        "use": "Yes",
        "ratio": "4:1 + sidechain from kick",
        "attackRelease": "10 ms / 80–120 ms",
        "gainReduction": "3–5 dB",
        "notes": "Sidechain duck 2–4 dB"
      },
      {
        "source": "Music (non-drum) parallel bus",
        "use": "Yes",
        "ratio": "4:1–8:1",
        "attackRelease": "FET-style fast / medium",
        "gainReduction": "6–10 dB, blended 20–30%",
        "notes": "Density without killing transients"
      },
      {
        "source": "Mix bus",
        "use": "Yes",
        "ratio": "2:1",
        "attackRelease": "10–30 ms / auto",
        "gainReduction": "1–3 dB",
        "notes": "Analog-style glue before mastering"
      }
    ],
    "notes": [
      {
        "text": "De-ess every member separately at 5–8 kHz for 3–6 dB; bright vocals plus heavy top shelf make sibilance the most common flaw. Live, gate or expand headset mics (−10 to −15 dB range) when members aren’t singing to cut stage noise and breath. Mastering limiters typically work 4–8 dB on title tracks."
      }
    ]
  },
  "fx": {
    "rows": [
      {
        "effect": "Pitch-shift doubler (micro-shift type)",
        "appliedTo": "Lead vocal",
        "setting": "±8–12 cents, 10–20 ms",
        "amount": "Subtle–moderate (send)"
      },
      {
        "effect": "Hall reverb",
        "appliedTo": "Lead vocals",
        "setting": "1.5–2.5 s decay, 30–60 ms pre-delay, HPF 300 Hz",
        "amount": "Moderate; more in ballads and bridges"
      },
      {
        "effect": "1/8-note delay",
        "appliedTo": "Vocal phrase ends, hook lines",
        "setting": "Tempo-synced, 20–30% feedback, LPF 5 kHz",
        "amount": "Moderate, automated per section"
      },
      {
        "effect": "Short plate",
        "appliedTo": "Raps, backing vocals",
        "setting": "0.8–1.2 s, 10–20 ms pre-delay",
        "amount": "Subtle"
      },
      {
        "effect": "Distortion / saturation",
        "appliedTo": "Backing vocals, 808",
        "setting": "Light drive for edge and harmonics",
        "amount": "Subtle–moderate"
      },
      {
        "effect": "Filter sweeps / risers",
        "appliedTo": "Pre-chorus, dance-break transitions",
        "setting": "LPF/HPF automation over 4–8 bars",
        "amount": "As arranged"
      },
      {
        "effect": "Vocal throws (live)",
        "appliedTo": "Hook ends, member intros",
        "setting": "Tapped 1/4 or 1/8 delay, 2–3 repeats",
        "amount": "Spot effect"
      }
    ],
    "notes": [
      {
        "text": "Live, many tours run reverbs and delays from the playback rig or match the studio settings closely; keep one console reverb and one tapped delay for live vocals so they blend with the recorded ones."
      }
    ]
  },
  "vocals": [
    {
      "text": "Vocals are the product: clearly above the track (roughly 2–4 dB more than in rock by perceived level), bright, airy and close, with each member’s timbre distinct. Korean studios record each member line by line on a tube condenser, often into a transformer-coupled preamp and an optical compressor; an in-house vocal director then comps and tunes every phrase. Tight tuning and grid-edited timing are expected, not hidden. Start with the main hook vocal and match every member to it, riding so a quiet sub-vocal line reads as clearly as the main vocal’s high note. Process backing vocals differently (more compression and saturation, crunchier) so leads stay in front. Korean’s soft consonants and final stops need presence at 3–5 kHz and careful de-essing, especially around English hooks."
    },
    {
      "text": "Live, members use headsets or handheld wireless. Expect a blend of fully live vocals, “MR” (live singing over a track with backing vocals) and recorded vocal support during heavy choreography. Agree which lines are live, keep the vocal-support stem on its own fader, and ride it down as live voices carry—fans notice heavy “AR.”"
    }
  ],
  "loudness": [
    {
      "label": "Live:",
      "text": "Theatre shows run 96–102 dBA LAeq-15; arenas and stadiums 100–106 dBA. Stadium K-pop shows have run 108–109 dBA and about 130 dBC from 50-plus subs—a target few venue limits allow. Screams and fanchants hit 100–110 dBA at FOH, so measure during songs and remember the crowd adds to exposure. Many fans are teenagers: offer earplugs, keep C-minus-A under about 20 dB, and avoid fatiguing 2–5 kHz. Some tours skip ultra-deep EDM sub in favour of punch and vocal clarity in the back rows."
    },
    {
      "label": "Studio / streaming:",
      "text": "Title tracks often land at −8 to −5 LUFS-I, true peak −1 dBTP; chart pop generally measures −9 to −7. Most streaming services normalize to about −14 LUFS (some −16), so very loud masters get turned down; keep PLR around 7–9 dB to protect kick and vocal transients. Loudness range is only 3–6 LU; contrast lives in the arrangement."
    }
  ],
  "liveStudio": {
    "rows": [
      {
        "area": "Vocals",
        "live": "4–13 wireless/headset mics, constant movement, huge level swings; ride by member and line",
        "studio": "Line-by-line comps, tuning, timing edits, serial compression"
      },
      {
        "area": "Playback",
        "live": "Stems (drums, bass, music, BVs, vocal support) mixed at FOH; ride BV/vocal stems against live voices",
        "studio": "The track is the arrangement; 150+ tracks are common"
      },
      {
        "area": "Low end",
        "live": "Big sub arrays, coverage and coupling matter; end-fire or cardioid subs to control stage",
        "studio": "Kick/808 sidechain and saturation for phone translation"
      },
      {
        "area": "Crowd",
        "live": "Fanchants and screams are part of the show—leave gaps, mic the audience for IEMs",
        "studio": "No audience; leave space where chants will go"
      },
      {
        "area": "Effects",
        "live": "One reverb and tapped delay for live voices; match the record",
        "studio": "Doublers, multiple reverbs, delays automated by section"
      },
      {
        "area": "Translation",
        "live": "Consistent tone and level to the last stadium row",
        "studio": "Must sound bright and full on earbuds and phones"
      },
      {
        "area": "Loudness",
        "live": "100–106 dBA arena average, local limits",
        "studio": "−8 to −5 LUFS-I title-track masters"
      }
    ],
    "notes": []
  },
  "notes": [
    {
      "text": "Split stems properly: vocal-support and BV stems separate from music, so you can balance live against recorded.",
      "bullet": true
    },
    {
      "text": "Label channels by member and keep a line-distribution lyric sheet; know who sings next before they open their mouth.",
      "bullet": true
    },
    {
      "text": "Don’t pan vocals by stage position; keep lead lines centered.",
      "bullet": true
    },
    {
      "text": "Tame 2.5–5 kHz and sibilance more at arena level than on headphones.",
      "bullet": true
    },
    {
      "text": "Leave headroom for the dance break and final chorus.",
      "bullet": true
    },
    {
      "text": "Check phase and latency between layered kicks, claps and live drums.",
      "bullet": true
    },
    {
      "text": "Let fanchants breathe in intros, then bring vocals up decisively when the line starts.",
      "bullet": true
    },
    {
      "text": "Check studio mixes on phones and earbuds—where most fans listen.",
      "bullet": true
    }
  ],
  "references": [
    "BTS, “Dynamite”, 2020",
    "BLACKPINK, “DDU-DU DDU-DU”, 2018",
    "TWICE, “Scientist”, 2021",
    "NewJeans, “Hype Boy”, 2022",
    "Stray Kids, “God’s Menu”, 2020",
    "SEVENTEEN, “Super”, 2023",
    "EXO, “Growl”, 2013",
    "aespa, “Supernova”, 2024"
  ],
  "empty": []
};
