/**
 * Mixing guide 11 — Alternative / Indie Rock. GENERATED by scripts/mixing-guides/convert.py
 * from the owner's guide (assets/Mixing-Guides-50-Styles, read only). Edit the
 * conversion (scripts/mixing-guides/edits.py), not this file.
 */
import type { MixingGuide } from '../types';

export const GUIDE: MixingGuide = {
  "id": "alternative-indie-rock",
  "num": 11,
  "title": "Alternative / Indie Rock",
  "expects": "Audiences expect the band’s recorded personality: the specific fuzz pedal, the jangly chord, the off-kilter vocal.",
  "glance": {
    "origin": "US and UK, late 1970s–1980s (post-punk, college radio, independent labels); went mainstream 1991–96 with Nirvana and the “alternative” boom; 2000s indie revival (Strokes, Arctic Monkeys) to today’s bedroom-indie scene",
    "tempo": "90–140 BPM (slowcore and ballads 60–85; post-punk and garage revival 140–170)",
    "ensemble": "3–5 piece band: drums, bass, 1–2 guitars, often synth/keys, singer-guitarist; larger collectives (6–10) with strings, horns, multi-instrumentalists",
    "priority": "Character and texture of the guitars and the singer’s voice, with a natural-sounding drum kit holding it together",
    "liveSpl": "94–100 dBA Leq (LAeq-15 min) in clubs and theaters; roughly 110–120 dBC; outdoor ordinances often cap at 95 dBA",
    "studioLoudness": "Masters commonly −11 to −8 LUFS-I (lo-fi and folk-leaning records −14 to −11); streaming normalizes to about −14"
  },
  "purpose": [
    {
      "text": "Alternative and indie rock grew out of punk’s do-it-yourself ethic: bands on small labels, played on student-run college radio, tracked by CMJ charts and MTV’s 120 Minutes. The music is for close listening, identification and catharsis—fans know every lyric and value authenticity and quirk over polish. Audiences expect the band’s recorded personality: the specific fuzz pedal, the jangly chord, the off-kilter vocal. They will say “that sounded wrong” if the mix sounds like generic arena rock (scooped guitars, triggered drums, glossy vocal), if the words vanish when the band wants them heard, or if a raw, roomy record comes out sterile. Conversely, a shoegaze or noise-pop act may want the vocal to sit inside the guitars—know the band’s records before you start."
    }
  ],
  "instruments": [
    {
      "label": "Drums:",
      "text": "acoustic kit, frequently vintage or lightly damped; open, roomy sound with fewer close mics is part of the aesthetic. Drum machines and samples appear in post-punk and synth-indie.",
      "bullet": true
    },
    {
      "label": "Bass:",
      "text": "electric bass, often picked and driven (a passive bass into a tube bass amp), sometimes melodic and high on the neck (post-punk), sometimes fuzz-overdriven.",
      "bullet": true
    },
    {
      "label": "Electric guitars:",
      "text": "the genre’s signature—jangle (bright 12-string or single-coil clean with compression and chorus), fuzz (classic fuzz-pedal style), offset guitars with tremolo, heavy reverb and delay pedals, alternate tunings and feedback.",
      "bullet": true
    },
    {
      "label": "Keys and synths:",
      "text": "analog-style synths, combo organs, reed electric piano, tape-replay keyboard sounds, and occasional glockenspiel or toy instruments.",
      "bullet": true
    },
    {
      "label": "Extras:",
      "text": "strings, horns, banjo, acoustic and lap steel in orchestral or folk-leaning indie; some acts run pads, but many play everything live.",
      "bullet": true
    }
  ],
  "arrangement": [
    {
      "text": "A typical stage has drums center upstage, bass beside the drummer, guitarist(s) on either side with pedalboards, a keys/synth position, and a singer who often also plays guitar—meaning the vocal mic picks up a loud amp a few meters away. Rhythm is shared between drums and bass; guitars carry both harmony and much of the “hook” through riffs or textures rather than solos. Indie arrangements favor the quiet-loud contrast popularized by Pixies and Nirvana: a hushed, sparse verse explodes into a distorted chorus. Other subgenres build gradually (post-rock, shoegaze) or ride one steady groove (garage and post-punk revival); codas may end in feedback."
    }
  ],
  "dynamics": [
    {
      "text": "Macro-dynamics are wide by rock standards: quiet-loud songs can jump 10–15 dB between verse and chorus, and a full set may span whispered solo numbers to fuzz-drenched closers. Preserve that contrast—it is often the point of the song. Control micro-dynamics with fader rides and moderate compression; crushing the loud sections makes the chorus feel smaller. Many indie producers record live to tape with minimal editing, and that push and pull of tempo and level should survive the mix."
    }
  ],
  "balance": [
    {
      "text": "Typical hierarchy, loudest to quietest: lead vocal and the main guitar (often near-equal), snare, kick and bass, second guitar or synth, overheads/room, keys and extras, backing vocals, effects returns. Indie mixes frequently sit the vocal slightly lower than pop or classic rock, but it must stay intelligible unless the band’s style is explicitly a wash. Low end: let the bass carry warmth (60–200 Hz) and the kick provide a rounder, less clicky punch than in metal or pop-punk. Pan double-tracked guitars wide; with two distinct guitarists, pan each 60–100% to their stage side, keys off-center opposite. Overheads and room mics carry much of the kit image and sit louder than in mainstream rock."
    }
  ],
  "eq": {
    "rows": [
      {
        "source": "Kick",
        "cut": "HPF 30–40 Hz; −3 to −5 dB at 300–500 Hz",
        "boost": "+2–3 dB at 60–90 Hz; +1–2 dB at 2–3 kHz",
        "notes": "Keep it rounder and less clicky than modern rock; front-head mic adds resonance"
      },
      {
        "source": "Snare",
        "cut": "HPF 80–100 Hz; narrow cut at ring (400 Hz–1 kHz)",
        "boost": "+2 dB at 180–250 Hz; +2 dB at 4–6 kHz",
        "notes": "Top dynamic plus small condenser or bottom mic blended for crack and body"
      },
      {
        "source": "Overheads / room",
        "cut": "HPF 100–150 Hz (overheads); broad −2–3 dB at 350 Hz",
        "boost": "+1–2 dB shelf at 10 kHz",
        "notes": "Ribbon overheads (classic figure-8 ribbons) give a dark, natural kit picture"
      },
      {
        "source": "Bass",
        "cut": "HPF 35–40 Hz; −2 dB at 250 Hz if woolly",
        "boost": "+2 dB around 60 Hz; +2–3 dB at 800 Hz–1.2 kHz (pick/grind)",
        "notes": "Blend DI and amp; drive the amp or preamp for grit"
      },
      {
        "source": "Clean / jangle guitar",
        "cut": "HPF 100–150 Hz; −2 dB at 250–400 Hz",
        "boost": "+1–3 dB at 3–6 kHz for chime",
        "notes": "Compress lightly so arpeggios ring evenly"
      },
      {
        "source": "Fuzz / distorted guitar",
        "cut": "HPF 80–100 Hz; LPF 10–12 kHz; dip 3–5 kHz if fizzy",
        "boost": "+1–2 dB at 600 Hz–1.5 kHz (body)",
        "notes": "Don’t scoop mids; fuzz already has a lot of low-mid weight, so trim 200–300 Hz first"
      },
      {
        "source": "Synth / organ",
        "cut": "HPF 100–200 Hz",
        "boost": "+1–2 dB at 1–3 kHz if it needs to cut",
        "notes": "Make room for vocal and guitar; a combo organ can be harsh around 2–4 kHz"
      },
      {
        "source": "Lead vocal",
        "cut": "HPF 80–120 Hz; −2–3 dB at 200–400 Hz; notch amp bleed resonances live",
        "boost": "+2 dB at 2–4 kHz; small air shelf at 10–12 kHz",
        "notes": "Mid-forward, not glossy; deliberately lo-fi records may band-limit to 200 Hz–6 kHz"
      },
      {
        "source": "Backing vocals",
        "cut": "HPF 150–200 Hz; −2 dB at 300 Hz",
        "boost": "Slight 5 kHz lift",
        "notes": "Thinner than lead so harmonies sit behind it"
      },
      {
        "source": "Strings / horns / acoustic",
        "cut": "HPF 80–150 Hz; −2 dB at 200–300 Hz",
        "boost": "+1–2 dB at 5–8 kHz for bow/breath detail",
        "notes": "Treat as texture; level matters more than EQ"
      }
    ],
    "notes": []
  },
  "compression": {
    "rows": [
      {
        "source": "Lead vocal (FET stage)",
        "use": "Yes",
        "ratio": "4:1",
        "attackRelease": "3–10 ms / fast",
        "gainReduction": "3–6 dB",
        "notes": "Medium-fast attack keeps excitement; can be pushed hard for a slammed, gritty vocal"
      },
      {
        "source": "Lead vocal (vari-mu/opto stage)",
        "use": "Yes",
        "ratio": "2:1–3:1",
        "attackRelease": "Slow / program",
        "gainReduction": "2–4 dB",
        "notes": "Smooths and thickens; live, a single compressor is usually enough"
      },
      {
        "source": "Kick",
        "use": "Yes",
        "ratio": "4:1",
        "attackRelease": "20–30 ms / 80 ms",
        "gainReduction": "2–4 dB",
        "notes": "Lighter than mainstream rock to keep the natural feel"
      },
      {
        "source": "Snare",
        "use": "Yes",
        "ratio": "3:1–4:1",
        "attackRelease": "10–20 ms / 80–100 ms",
        "gainReduction": "3–5 dB",
        "notes": "Parallel compression adds body without losing dynamics"
      },
      {
        "source": "Bass",
        "use": "Yes",
        "ratio": "4:1",
        "attackRelease": "10–20 ms / 100 ms",
        "gainReduction": "3–6 dB",
        "notes": "Valve or vari-mu style for smooth leveling"
      },
      {
        "source": "Clean guitars",
        "use": "Yes",
        "ratio": "3:1–4:1",
        "attackRelease": "5–15 ms / auto",
        "gainReduction": "3–5 dB",
        "notes": "Compression is part of the jangle sound"
      },
      {
        "source": "Distorted guitars",
        "use": "Little or none",
        "ratio": "2:1",
        "attackRelease": "20–30 ms / auto",
        "gainReduction": "0–2 dB",
        "notes": "Fuzz is already squashed"
      },
      {
        "source": "Drum bus (parallel)",
        "use": "Yes",
        "ratio": "6:1–10:1",
        "attackRelease": "5–10 ms / 50–100 ms",
        "gainReduction": "8–12 dB, blended 20–40%",
        "notes": "vari-mu tube-style colour on the parallel path is common"
      },
      {
        "source": "Mix bus",
        "use": "Optional",
        "ratio": "2:1",
        "attackRelease": "30 ms / auto",
        "gainReduction": "1–2 dB",
        "notes": "Tape emulation or real tape saturation often replaces heavy limiting"
      }
    ],
    "notes": [
      {
        "text": "Gate toms live with gentle settings (range 10–15 dB, 50 ms hold, 150 ms release) so the kit still breathes; in the studio edit or leave bleed in. De-ess at 5–8 kHz for 2–3 dB—recording to tape can soften sibilance enough that less is needed. Keep final limiting to 2–3 dB."
      }
    ]
  },
  "fx": {
    "rows": [
      {
        "effect": "Tape echo / slap",
        "appliedTo": "Lead vocal",
        "setting": "90–140 ms, 5–15% feedback, filtered 200 Hz–4 kHz, slight wow/flutter",
        "amount": "Moderate—a signature indie vocal sound"
      },
      {
        "effect": "Spring reverb",
        "appliedTo": "Vocal, guitars, snare",
        "setting": "1.5–2.5 s, short pre-delay",
        "amount": "Subtle–moderate; vintage character"
      },
      {
        "effect": "Plate reverb",
        "appliedTo": "Vocal, snare",
        "setting": "1.4–2.2 s decay, 20–50 ms pre-delay",
        "amount": "Subtle in verses, more in choruses"
      },
      {
        "effect": "Large hall / shimmer",
        "appliedTo": "Shoegaze and dream-pop guitars and vocals",
        "setting": "3–6 s decay, 0–30 ms pre-delay, darkened above 6 kHz",
        "amount": "Heavy—the wash is the arrangement"
      },
      {
        "effect": "Tempo delay",
        "appliedTo": "Vocal tails, lead guitar lines",
        "setting": "1/4 or dotted 1/8 note, 20–35% feedback",
        "amount": "Moderate, automated"
      },
      {
        "effect": "Chorus / vibrato / tremolo",
        "appliedTo": "Clean guitars, keys, backing vocals",
        "setting": "0.5–1.5 Hz rate, low depth",
        "amount": "As part of the tone"
      },
      {
        "effect": "Saturation / amp re-amping",
        "appliedTo": "Vocals, drums, synths",
        "setting": "Drive a tube preamp or amp to edge of breakup",
        "amount": "Subtle–moderate; adds mid-range bite"
      }
    ],
    "notes": [
      {
        "text": "Leaving a few elements fully dry makes the wet ones feel deliberate."
      }
    ]
  },
  "vocals": [
    {
      "text": "Indie vocals are personal and characterful—breathy, deadpan, conversational or yelped—and the mix should flatter the singer’s quirks rather than standardize them. Sit the lead roughly level with the main guitar and slightly into the band; in shoegaze, tuck it further and let reverb carry it. Pitch correction should be minimal and inaudible; some producers avoid heavy comping altogether because syllable-level editing kills the performance. Doubles and harmonies, sometimes sung by two people around one mic, are tucked 6–10 dB under the lead or panned wide. A distinctive trick is splitting the vocal to a guitar amp and blending it back for midrange bite. Live, singer-guitarists stand close to loud amps: use a tight-pattern mic (a supercardioid dynamic or condenser capsule chosen for background rejection), work the HPF, and keep EQ narrow to protect gain-before-feedback."
    }
  ],
  "loudness": [
    {
      "label": "Live:",
      "text": "Club and theater shows typically run 94–100 dBA LAeq-15 at FOH, with louder fuzz and noise acts reaching 100–103 dBA and C-weighted levels around 110–120 dBC. Indie needs moderate sub—most energy is in the guitars and midrange; a C-minus-A gap above roughly 18–20 dB means the sub is too hot for the genre. Outdoor city parks commonly enforce limits around 95 dBA, and crowd singalongs can measure louder than the band. Shoegaze and noise-rock crowds expect volume as an experience; offer earplugs and watch your own exposure."
    },
    {
      "label": "Studio / streaming:",
      "text": "Modern indie masters typically land at −11 to −8 LUFS-I, with lo-fi, folk-leaning or audiophile releases at −14 to −11. Use −1 dBTP for masters near −14 LUFS and around −2 dBTP for louder ones, a common streaming recommendation. The genre tolerates and rewards dynamics: aim for a PLR of 10–13 dB (at −2 dBTP that means a master at about −12 LUFS-I or quieter) and a loudness range of 6–10 LU so quiet-loud songs keep their impact after normalization. Tape saturation is often preferred to hard digital limiting."
    }
  ],
  "liveStudio": {
    "rows": [
      {
        "area": "Guitars",
        "live": "Loud stage amps and pedalboards dominate; FOH often adds little guitar and fights bleed into vocal mics",
        "studio": "Double-tracked, re-amped, layered textures; guitar tone shaped by mic choice and amp blending"
      },
      {
        "area": "Drums",
        "live": "Fewer inputs, light gating, rely on stage room; plate on snare and toms",
        "studio": "Minimal-mic, roomy setups with ribbons; parallel colour; live-to-tape takes"
      },
      {
        "area": "Vocals",
        "live": "Gain-before-feedback limits; tight-pattern mic, narrow EQ, slap and one reverb",
        "studio": "Characterful chains (FET plus vari-mu), amp-split vocals, tape echoes"
      },
      {
        "area": "Effects",
        "live": "Tap-tempo delays and two or three reverbs; replicate signature washes from the records",
        "studio": "Hardware springs, tape echo, chambers, re-amping, creative routing"
      },
      {
        "area": "Dynamics",
        "live": "Ride faders for quiet-loud jumps; avoid peaking early in the set",
        "studio": "Automation and section-by-section moves; preserve contrast in master"
      },
      {
        "area": "Loudness",
        "live": "94–100 dBA Leq, ordinance limits outdoors",
        "studio": "−11 to −8 LUFS-I, −1 to −2 dBTP"
      },
      {
        "area": "Playback",
        "live": "Many bands play everything live; some run pads and click",
        "studio": "Overdubs, strings, synth layers, deliberate lo-fi elements"
      }
    ],
    "notes": []
  },
  "notes": [
    {
      "text": "Listen to the band’s records before soundcheck; the “right” sound varies hugely between jangle-pop, shoegaze, garage revival and orchestral indie.",
      "bullet": true
    },
    {
      "text": "Ask the guitarists to set stage volumes that let you mix; a loud amp beside the vocal mic is the most common live problem.",
      "bullet": true
    },
    {
      "text": "Don’t impose a glossy pop or metal template: no scooped guitars, over-triggered drums or heavily tuned vocals.",
      "bullet": true
    },
    {
      "text": "Keep the room sound and some imperfection—bleed and tape grit are part of the style.",
      "bullet": true
    },
    {
      "text": "Keep the vocal intelligible unless the band clearly wants it buried.",
      "bullet": true
    },
    {
      "text": "Leave headroom for the loudest chorus or feedback coda.",
      "bullet": true
    }
  ],
  "references": [
    "Pixies, “Debaser”, 1989",
    "R.E.M., “Radio Free Europe”, 1983",
    "Nirvana, “Smells Like Teen Spirit”, 1991",
    "My Bloody Valentine, “Only Shallow”, 1991",
    "The Strokes, “Last Nite”, 2001",
    "Arctic Monkeys, “Do I Wanna Know?”, 2013",
    "Arcade Fire, “Wake Up”, 2004",
    "The National, “Bloodbuzz Ohio”, 2010"
  ],
  "empty": []
};
