/**
 * Mixing guide 12 — Christian Contemporary / Worship. GENERATED by scripts/mixing-guides/convert.py
 * from the owner's guide (assets/Mixing-Guides-50-Styles, read only). Edit the
 * conversion (scripts/mixing-guides/edits.py), not this file.
 */
import type { MixingGuide } from '../types';

export const GUIDE: MixingGuide = {
  "id": "christian-contemporary-worship",
  "num": 12,
  "title": "Christian Contemporary / Worship",
  "expects": "People expect every lyric to be clear, a bridge that lifts as it repeats, and space in quiet moments of prayer.",
  "glance": {
    "origin": "United States, late 1960s–1970s Jesus movement (Calvary Chapel, Maranatha! Music, 1971); modern worship shaped by Vineyard, Integrity, Delirious? (UK) and Hillsong (Australia) in the 1990s, then Passion, Bethel, Elevation and Maverick City in the 2000s–2020s",
    "tempo": "68–80 BPM for ballads and “intimate” songs; 120–145 BPM for up-tempo openers, often played in 6/8 or half-time feel",
    "ensemble": "5–8 piece band: drums, bass, 1–2 electric guitars, acoustic guitar, keys/pads, worship leader plus 2–4 vocalists, with click and tracks",
    "priority": "A clear, intelligible lead vocal that invites the room to sing, without burying the congregation’s own voices",
    "liveSpl": "88–94 dBA LAeq over the worship set (large churches often target about 92–94 dBA slow, peaks under about 100 dBA); youth and conference events 95–100 dBA",
    "studioLoudness": "CCM radio singles commonly −10 to −8 LUFS-I, live worship albums −12 to −10; streaming normalizes to about −14, church livestreams around −16 to −14"
  },
  "purpose": [
    {
      "text": "Worship music exists to help a gathered congregation sing, pray and respond together; CCM recordings extend that into car radios, earbuds and Christian radio formats. In a service, the band is a guide and the congregation is the real choir, so the engineer serves participation more than performance. People expect every lyric to be clear, a bridge that lifts as it repeats, and space in quiet moments of prayer. A worship audience will say “that sounded wrong” when it is too loud to hear themselves sing, when the lead is unintelligible, when a click or count-in leaks into the house, when feedback breaks a quiet moment, or when transitions between songs and speaking are abrupt."
    }
  ],
  "instruments": [
    {
      "label": "Drums:",
      "text": "acoustic kit, usually behind a drum shield or replaced by an electronic kit in smaller rooms; floor toms, mallets on cymbals and big swells are signature moves.",
      "bullet": true
    },
    {
      "label": "Bass:",
      "text": "electric bass DI, often doubled or replaced by a synth bass from keys or tracks for sub weight.",
      "bullet": true
    },
    {
      "label": "Electric guitar:",
      "text": "ambient, delay-heavy lead (dotted-eighth delays, volume swells, shimmer reverbs) via modelers or pedalboards, often going straight to the desk.",
      "bullet": true
    },
    {
      "label": "Acoustic guitar:",
      "text": "strummed by the worship leader; usually the rhythmic and harmonic anchor in verses.",
      "bullet": true
    },
    {
      "label": "Keys:",
      "text": "piano and electric piano, plus constant ambient pads that fill the space under prayer and transitions.",
      "bullet": true
    },
    {
      "label": "Tracks:",
      "text": "a playback app or DAW supplying click, spoken guide cues, pads, strings, synths, percussion and extra BGVs.",
      "bullet": true
    }
  ],
  "arrangement": [
    {
      "text": "Typical layout: worship leader front center (often on acoustic or keys), BGVs beside or behind, drums center upstage, bass, keys and electric guitar to the sides, nearly everyone on in-ears. Arrangements follow the “worship set” arc: a fast opener, a mid-tempo song, then one or two slower songs that open into long bridge repetitions. A common structure is soft verse (acoustic, pad, light kick), fuller chorus, a bridge that starts sparse and repeats while the drums build into floor-tom gallops and the full band, then a “drop” back to just keys and vocal for a final quiet chorus or spontaneous singing. Pads often run between songs so the room never goes silent."
    }
  ],
  "dynamics": [
    {
      "text": "Worship is arranged around large macro-dynamics: a stripped bridge to a full final chorus can span 10–15 dB of perceived level. Preserve this—the build is the emotional and spiritual point—but cap the top so the loudest chorus still lets people hear their own voices. Start lower than you think, ramp through walk-in and the build, and drop back for prayer and speaking. Ride the mix by section rather than compressing it flat; sub rides on the build and BGV pushes in the big chorus sell the moment."
    }
  ],
  "balance": [
    {
      "text": "Hierarchy, loudest to quietest: lead vocal, kick and bass (a felt foundation), BGVs as a choir block, keys/piano, acoustic guitar, electric guitar, pads and tracks, snare and toms (louder in builds), cymbals and FX returns. Carve 2–4 kHz in guitars and keys rather than just pushing the vocal. Let synth bass or the tracks sub carry 30–60 Hz and bass guitar own roughly 60–200 Hz. Lead vocal, kick, snare and bass center; BGVs spread; electric guitar and keys opposite each other; pads wide. Many sanctuaries cannot deliver stereo to every seat, so check the mix summed to mono."
    }
  ],
  "eq": {
    "rows": [
      {
        "source": "Lead vocal",
        "cut": "HPF 100–120 Hz; −2–3 dB at 250–500 Hz; −2 dB at 4–5 kHz if harsh",
        "boost": "+2 dB at 2.5–3.5 kHz (intelligibility); +1–2 dB shelf at 10 kHz (air)",
        "notes": "Clear words are non-negotiable; watch feedback rings in quiet sets"
      },
      {
        "source": "BGVs",
        "cut": "HPF 150–200 Hz; −3 dB at 300–500 Hz",
        "boost": "Small dip at 3 kHz relative to the lead",
        "notes": "Make them a pad behind the leader, not competitors"
      },
      {
        "source": "Kick",
        "cut": "HPF 35–40 Hz; −4 dB at 300–400 Hz",
        "boost": "+2–3 dB at 60–80 Hz; +2 dB at 3–4 kHz",
        "notes": "Rounder and softer beater than rock"
      },
      {
        "source": "Snare",
        "cut": "HPF 100 Hz; notch ring 600 Hz–1 kHz",
        "boost": "+2 dB at 180–220 Hz; +2 dB at 5 kHz",
        "notes": "Drum shields add boxiness—cut 400–800 Hz on overheads"
      },
      {
        "source": "Toms (floor)",
        "cut": "HPF 60 Hz; −3 dB at 400 Hz",
        "boost": "+3 dB at 80–100 Hz",
        "notes": "Floor-tom builds are a hallmark; let them speak"
      },
      {
        "source": "Bass guitar",
        "cut": "HPF 40 Hz; dynamic EQ at 70–120 Hz to tame boomy notes",
        "boost": "+2 dB at 700 Hz–1 kHz for definition",
        "notes": "Make room for synth bass below"
      },
      {
        "source": "Synth bass / tracks sub",
        "cut": "HPF 25–30 Hz; LPF 2–4 kHz",
        "boost": "Small shelf at 40–50 Hz if the system allows",
        "notes": "Ride the sub for builds"
      },
      {
        "source": "Acoustic guitar",
        "cut": "HPF 100–150 Hz; LPF 12 kHz; −3 dB at 200–300 Hz",
        "boost": "+2 dB at 5–8 kHz for strum sparkle",
        "notes": "Piezo DIs need a cut near 1–2 kHz to lose the quack"
      },
      {
        "source": "Electric guitar (ambient)",
        "cut": "HPF 100–150 Hz; LPF 8–10 kHz",
        "boost": "+1–2 dB at 1–1.5 kHz",
        "notes": "Long delays and reverb trails stack up mud—filter returns"
      },
      {
        "source": "Keys / pads",
        "cut": "HPF 150–250 Hz (pads); −2–3 dB at 300–500 Hz",
        "boost": "Gentle shelf at 8–10 kHz on piano",
        "notes": "Pads should fill, never mask the vocal"
      }
    ],
    "notes": []
  },
  "compression": {
    "rows": [
      {
        "source": "Lead vocal",
        "use": "Yes",
        "ratio": "3:1–4:1",
        "attackRelease": "10–20 ms / 80–150 ms or auto",
        "gainReduction": "4–8 dB (some go 10–15 dB with slow attack)",
        "notes": "Leaders move from whisper to belt; keep in-ear feed lightly compressed"
      },
      {
        "source": "BGV group",
        "use": "Yes",
        "ratio": "4:1",
        "attackRelease": "10 ms / auto",
        "gainReduction": "4–6 dB",
        "notes": "Glue the block, ride the group fader"
      },
      {
        "source": "Kick",
        "use": "Yes",
        "ratio": "4:1",
        "attackRelease": "20–30 ms / 60 ms",
        "gainReduction": "3–5 dB",
        "notes": "Keep it soft and round"
      },
      {
        "source": "Bass guitar",
        "use": "Yes",
        "ratio": "3:1–4:1",
        "attackRelease": "10–20 ms / 100 ms",
        "gainReduction": "3–6 dB",
        "notes": "Volunteer players vary—even it out"
      },
      {
        "source": "Acoustic guitar",
        "use": "Yes",
        "ratio": "4:1",
        "attackRelease": "5–10 ms / 100 ms",
        "gainReduction": "4–8 dB",
        "notes": "Heavier squeeze lets it sit back"
      },
      {
        "source": "Drum bus",
        "use": "Yes",
        "ratio": "2:1–3:1",
        "attackRelease": "20–30 ms / auto",
        "gainReduction": "2–3 dB",
        "notes": "Preserve the swells and builds"
      },
      {
        "source": "Pastor / speaking mic",
        "use": "Yes",
        "ratio": "3:1–4:1",
        "attackRelease": "5 ms / 150 ms",
        "gainReduction": "4–8 dB",
        "notes": "Plus a gate or downward expander between phrases"
      },
      {
        "source": "Main bus",
        "use": "Light",
        "ratio": "2:1",
        "attackRelease": "30 ms / auto",
        "gainReduction": "1–2 dB",
        "notes": "Safety only; never kill the build"
      }
    ],
    "notes": [
      {
        "text": "Group processing (vocals, band, tracks) simplifies volunteer mixing and adds glue. De-ess vocals at 5–8 kHz for 2–4 dB. Gate toms gently live (or leave them open on electronic kits). On the stream bus, add a final true-peak limiter with a −1 dBTP ceiling."
      }
    ]
  },
  "fx": {
    "rows": [
      {
        "effect": "Plate / hall reverb",
        "appliedTo": "Lead vocal, BGVs",
        "setting": "1.8–2.5 s decay, 30–40 ms pre-delay, HPF 200 Hz / LPF 6–8 kHz",
        "amount": "Moderate; more on slow songs"
      },
      {
        "effect": "Dotted-eighth delay",
        "appliedTo": "Lead vocal phrase ends",
        "setting": "Tempo-synced (tap or MIDI from tracks), 15–25% feedback",
        "amount": "Subtle, thrown on key lines"
      },
      {
        "effect": "Snare/drum reverb",
        "appliedTo": "Snare, toms",
        "setting": "1.5–2 s plate, filtered",
        "amount": "Subtle–moderate"
      },
      {
        "effect": "Ambient “shimmer” / long hall",
        "appliedTo": "Electric guitar, pads",
        "setting": "4–8 s decay, often from the player’s rig",
        "amount": "Part of the sound; filter so it doesn’t wash vocals"
      },
      {
        "effect": "Short room",
        "appliedTo": "Drums, acoustic",
        "setting": "0.6–1 s",
        "amount": "Subtle; cohesion"
      },
      {
        "effect": "Speaking mic",
        "appliedTo": "Pastor",
        "setting": "No reverb, or a tiny short room",
        "amount": "None to subtle"
      }
    ],
    "notes": [
      {
        "text": "Pull vocal FX for prayer and spoken moments; excess reverb in a reflective room is the most common worship over-indulgence."
      }
    ]
  },
  "vocals": [
    {
      "text": "The worship leader’s vocal is the conductor of the congregation: it must be clear, warm and confident, sitting about 2–4 dB above the band by perception, but not so dominant that the room listens instead of sings. Lyrics on screens help, yet intelligibility at 2–4 kHz still matters most. BGVs act as a choir pad, often tight unison or thirds; keep them compressed and slightly below and behind the lead, and lift the group in big choruses. Watch the leader for spontaneous singing and spoken moments mid-song. Pitch correction live is increasingly common on large stages and sparing at most churches; on records, CCM uses tight pop-style tuning while live worship albums keep more natural tuning. Live mics are usually rugged dynamics or handheld condensers. For in-ears, give the leader a flat, clear vocal with little reverb and light compression so they do not over-sing, plus ambient or crowd mics so they hear the congregation."
    }
  ],
  "loudness": [
    {
      "label": "Live:",
      "text": "Many churches settle on 88–94 dBA slow, averaged over the worship set; one large multisite church measures about 93–94 dBA over roughly 18 minutes of worship with quick peaks capped at 99–100 dBA. Guidance from church tech trainers suggests keeping an hour-long service at or under about 94 dBA, and newer volunteer mixers are often limited to the mid-to-high 80s. Soft songs land near 80–85 dBA. C-weighted levels of 105–112 dBC are typical when synth sub is in play; a C-minus-A gap above about 15–18 dB means too much sub for a mixed-age room. Measure at the loudest seats and walk the room during the service; offer earplugs, since children and elderly members attend."
    },
    {
      "label": "Studio / streaming:",
      "text": "CCM singles mastered for Christian radio typically land around −10 to −8 LUFS-I with −1 dBTP; live worship albums are more open at −12 to −10 LUFS-I and a loudness range of 6–10 LU to keep the build alive. Most streaming services normalize to −14 LUFS, and −2 dBTP or lower is recommended for masters louder than that. For church livestreams, aim for about −16 to −14 LUFS-I, a −1 dBTP ceiling, and keep quiet moments from falling more than 6–10 dB below the loud ones."
    }
  ],
  "liveStudio": {
    "rows": [
      {
        "area": "Purpose",
        "live": "Support congregational singing; room level and comfort first",
        "studio": "Personal listening and radio; lead vocal and hook upfront"
      },
      {
        "area": "Low end",
        "live": "Sub rides for builds; synth bass from tracks needs careful level",
        "studio": "Tightly carved kick, bass guitar and synth bass; sidechain common"
      },
      {
        "area": "Vocals",
        "live": "Gain-before-feedback limits EQ; quiet sets ring easily",
        "studio": "Comped, tuned, doubled, heavily processed"
      },
      {
        "area": "Tracks",
        "live": "Click and guide cues to in-ears only; pads/strings blended into FOH",
        "studio": "Programmed parts replaced or layered with real players"
      },
      {
        "area": "Audience",
        "live": "Crowd mics are part of the stream, live album and in-ears",
        "studio": "Live worship albums blend audience mics as a feature (often 10–20% of the mix)"
      },
      {
        "area": "Stream / broadcast",
        "live": "Separate post-fader bus or matrix with more band, more crowd, less vocal than the room mix",
        "studio": "Not applicable; mastered deliverables"
      },
      {
        "area": "Loudness",
        "live": "88–94 dBA average, peaks near 100 dBA",
        "studio": "−10 to −8 LUFS-I (radio CCM), −12 to −10 (live albums)"
      }
    ],
    "notes": []
  },
  "notes": [
    {
      "text": "Learn the songs and the set order; know where the bridge builds and where the band drops out.",
      "bullet": true
    },
    {
      "text": "Never send click or guide cues to the house—triple-check the tracks routing at every rehearsal.",
      "bullet": true
    },
    {
      "text": "Keep stage volume low: drum shields, IEMs, amps offstage or modelers. Stage wash is the enemy of clarity in reflective sanctuaries.",
      "bullet": true
    },
    {
      "text": "Use groups, scenes and a written gain chart so volunteers can recover quickly.",
      "bullet": true
    },
    {
      "text": "The stream needs its own mix with more band and crowd than the room.",
      "bullet": true
    },
    {
      "text": "Don’t max out SPL in the first song; leave room for the climax.",
      "bullet": true
    },
    {
      "text": "Prepare speaking transitions: pastor mic up and FX off before the last note fades.",
      "bullet": true
    }
  ],
  "references": [
    "Hillsong Worship, “Shout to the Lord”, 1994",
    "Chris Tomlin, “How Great Is Our God”, 2004",
    "Hillsong United, “Oceans (Where Feet May Fail)”, 2013",
    "Bethel Music, Jonathan David & Melissa Helser, “No Longer Slaves”, 2015",
    "Lauren Daigle, “You Say”, 2018",
    "Elevation Worship & Maverick City Music, “Jireh”, 2021",
    "Phil Wickham, “Battle Belongs”, 2020",
    "Brandon Lake, “Gratitude”, 2022"
  ],
  "empty": []
};
