/**
 * Mixing guide 14 — Afrobeats. GENERATED by scripts/mixing-guides/convert.py
 * from the owner's guide (assets/Mixing-Guides-50-Styles, read only). Edit the
 * conversion (scripts/mixing-guides/edits.py), not this file.
 */
import type { MixingGuide } from '../types';

export const GUIDE: MixingGuide = {
  "id": "afrobeats",
  "num": 14,
  "title": "Afrobeats",
  "expects": "Audiences sing every hook and expect a relaxed, warm, bouncy groove, never an aggressive one.",
  "glance": {
    "origin": "Lagos, Accra and the London diaspora, 2000s–2010s; the umbrella term “Afrobeats” was popularized by UK DJ Abrantee around 2011. Related to, but not the same as, Fela Kuti’s 1970s Afrobeat",
    "tempo": "100–115 BPM (median around 108–110; mellow Ghanaian and R&B-leaning cuts 93–100)",
    "ensemble": "Solo artist + tracks (most common); touring headliners carry 6–10 piece bands plus percussion section, horns, BVs and sometimes a choir",
    "priority": "The percussion groove (rimshot, shakers, clave pattern) bright and forward, with the lead vocal hook riding on it",
    "liveSpl": "96–102 dBA LAeq-15 min; roughly 115–124 dBC in clubs and arenas",
    "studioLoudness": "Masters commonly −10 to −7 LUFS-I; streaming normalizes to about −14"
  },
  "purpose": [
    {
      "text": "Afrobeats is dance and celebration music: owambe parties, weddings, clubs, Detty December concerts in Lagos and Accra, and diaspora nights in London and Houston. Lyrics (Nigerian or Ghanaian English, Pidgin, Yoruba, Igbo, Twi) cover love, joy and hustle. Audiences sing every hook and expect a relaxed, warm, bouncy groove, never an aggressive one."
    },
    {
      "text": "Note the link and the gap with Afrobeat (no “s”). Fela Kuti’s Afrobeat was a big live band (horns, interlocking guitars, Tony Allen’s drums) playing long, political, jazz-funk pieces. Afrobeats is a commercial pop umbrella, mostly assembled in a DAW, three-to-four-minute songs, vocal-led from the first bar, fusing highlife, jùjú, fuji, hiplife, dancehall, R&B and house. Many artists (Burna Boy especially) sample and honor Fela, but a guide for one does not fit the other. Amapiano’s log-drum sound has crossed over heavily since about 2020; it has its own guide (Amapiano)."
    },
    {
      "text": "What sounds wrong to this audience: percussion buried behind the vocal, a muddy or boomy low end that hides the bass melody, a harsh 6–8 kHz shaker that fatigues, or a vocal that is dry and stuck on top instead of floating in the groove."
    }
  ],
  "instruments": [
    {
      "label": "Programmed drums:",
      "text": "short, dry kick (often on a syncopated or four-on-the-floor pattern), snare or rimshot playing the 3-2 / 2-3 clave figure that defines the style, claps and snaps.",
      "bullet": true
    },
    {
      "label": "Percussion layers:",
      "text": "continuous 16th-note shakers, shekere (bead-netted gourd), congas and djembe, cowbell/agogo, and the talking drum (dùndún/gángan) used for fills and calls.",
      "bullet": true
    },
    {
      "label": "Bass:",
      "text": "melodic synth bass or 808 moving with the chords, sometimes live electric bass; increasingly a log drum borrowed from amapiano.",
      "bullet": true
    },
    {
      "label": "Highlife-style guitar:",
      "text": "clean, staccato, muted single-note or two-note patterns.",
      "bullet": true
    },
    {
      "label": "Keys and synths:",
      "text": "electric piano, soft pads, plucks, bells, marimba and kalimba-like mallets.",
      "bullet": true
    },
    {
      "label": "Horns:",
      "text": "sax lines and stabs, a nod to Afrobeat and highlife.",
      "bullet": true
    },
    {
      "label": "Playback:",
      "text": "live shows usually run stems for programmed drums, pads and stacked BVs under the live band.",
      "bullet": true
    }
  ],
  "arrangement": [
    {
      "text": "In the studio the producer’s beat is the arrangement: intro (4–8 bars, often with a producer tag), verse (16), hook (8), verse, hook, sometimes a “dance break,” outro. Percussion carries the rhythm and is often the lead character; bass carries much of the harmony; guitar and keys fill gaps; the vocal hook carries melody. Sections change by adding or muting percussion layers and dropping the kick, not by big dynamic swings."
    },
    {
      "text": "On stage, a headline show is large: a stadium setup can run about 120 inputs (core band of drums, bass, guitar, two keys and sax; three-piece brass; three BVs; a choir; eight to ten percussionists on talking drums and omele). Typical layout: drums center, percussion riser to one side, horns on the other, BVs upstage, dancers downstage. Live arrangements extend dance breaks and medley hits."
    }
  ],
  "dynamics": [
    {
      "text": "Studio Afrobeats has small macro-dynamics: hooks are usually only 1–3 dB bigger than verses, with energy coming from added layers and vocal stacks. Micro-dynamics are critical: the percussion lives on sharp transients, so don’t flatten them with heavy bus compression. Live, the band adds more contrast (breakdowns, percussion solos, crowd sing-backs), so leave 6 dB of headroom for crowd-participation moments and the “dance break” lift."
    }
  ],
  "balance": [
    {
      "text": "Typical hierarchy, loudest to quietest: lead vocal and rimshot/snare roughly level, then kick and bass, shakers and percussion (often brighter and more forward than Western pop would place them), guitar and keys, pads, BVs and ad-libs, FX returns. This audience wants fast, upper-mid percussion upfront, at times even above the vocal. Western engineers often bury it; resist that."
    },
    {
      "text": "Low end: the kick is short and punchy (50–80 Hz thump, quick decay), while the bass or 808 is melodic and sustained. Sidechain bass from kick for 2–4 dB of ducking, and keep bass harmonics at 100–200 Hz audible, since a bass that exists only at 40 Hz vanishes on phones. Pan shakers and secondary percussion off-center (20–60%), with congas and talking drum placed opposite each other; guitar off-center opposite keys; kick, snare/rim, bass and lead vocal centered; BV stacks wide."
    }
  ],
  "eq": {
    "rows": [
      {
        "source": "Kick",
        "cut": "HPF 30–35 Hz; −3 to −5 dB at 250–400 Hz",
        "boost": "+2–3 dB at 55–75 Hz; +2 dB at 3–5 kHz click",
        "notes": "Keep decay short so the bass melody reads"
      },
      {
        "source": "Snare / rimshot",
        "cut": "HPF 150–200 Hz; −2–3 dB at 400–800 Hz (box)",
        "boost": "+2–3 dB at 2.5–5 kHz; shelf +2 dB at 10 kHz",
        "notes": "Carries the clave figure; must cut through on phones"
      },
      {
        "source": "Claps / snaps",
        "cut": "HPF 200–300 Hz; dip 2–3 kHz if clashing with vocal",
        "boost": "+1–2 dB at 8–10 kHz",
        "notes": "Removing 2–3 kHz on snaps and widening them works well"
      },
      {
        "source": "Shakers / shekere",
        "cut": "HPF 300–500 Hz; −1–3 dB at 5–8 kHz if harsh",
        "boost": "Gentle air +1 dB at 12 kHz",
        "notes": "Bright but not fatiguing; check after 20 minutes"
      },
      {
        "source": "Congas / talking drum",
        "cut": "HPF 60–80 Hz; −2 dB at 300–500 Hz",
        "boost": "+2 dB at 150–250 Hz (tone); +2 dB at 3–5 kHz (slap)",
        "notes": "Talking drum pitch glides need body around 150–400 Hz"
      },
      {
        "source": "Bass / 808",
        "cut": "HPF 25–35 Hz (about 60 Hz on a busy track)",
        "boost": "+2 dB at 60–80 Hz; saturation or +2 dB at 700 Hz–1 kHz for phone translation",
        "notes": "Melody must survive small speakers"
      },
      {
        "source": "Highlife guitar",
        "cut": "HPF 150–200 Hz; −2 dB at 300–500 Hz",
        "boost": "+2–3 dB at 2–4 kHz",
        "notes": "Clean and plucky; keep it narrow"
      },
      {
        "source": "Keys / pads",
        "cut": "HPF 150–250 Hz; dip 2–4 kHz",
        "boost": "Small shelf at 10 kHz on electric piano",
        "notes": "Pads sit behind the percussion"
      },
      {
        "source": "Lead vocal",
        "cut": "HPF 80–100 Hz; −2 dB at 250–400 Hz; notch resonances",
        "boost": "+2–3 dB at 4–5 kHz; +1–2 dB at 12–14 kHz",
        "notes": "Common vocal lifts sit around 4–5 kHz and 12–14 kHz"
      }
    ],
    "notes": []
  },
  "compression": {
    "rows": [
      {
        "source": "Lead vocal",
        "use": "Yes",
        "ratio": "3:1–4:1",
        "attackRelease": "3–10 ms / 50–100 ms",
        "gainReduction": "3–5 dB",
        "notes": "Clip-gain rides first, then compress lightly"
      },
      {
        "source": "BV stacks",
        "use": "Yes",
        "ratio": "4:1",
        "attackRelease": "5 ms / auto",
        "gainReduction": "4–6 dB",
        "notes": "Group and compress the bus, keep stacks steady"
      },
      {
        "source": "Kick",
        "use": "Light",
        "ratio": "3:1",
        "attackRelease": "20–30 ms / 50 ms",
        "gainReduction": "2–3 dB",
        "notes": "Preserve the click; parallel saturation adds weight"
      },
      {
        "source": "Bass / 808",
        "use": "Yes",
        "ratio": "4:1",
        "attackRelease": "10–30 ms / 100 ms",
        "gainReduction": "3–5 dB",
        "notes": "Plus kick sidechain, 2–4 dB duck"
      },
      {
        "source": "Percussion bus",
        "use": "Light",
        "ratio": "2:1",
        "attackRelease": "15 ms / 100 ms",
        "gainReduction": "1–2 dB",
        "notes": "Slow enough to keep transients sharp"
      },
      {
        "source": "Drum bus (parallel)",
        "use": "Optional",
        "ratio": "8:1+",
        "attackRelease": "1–5 ms / fast",
        "gainReduction": "8–10 dB, blend 15–25%",
        "notes": "Adds thickness without dulling hits"
      },
      {
        "source": "Mix bus",
        "use": "Yes",
        "ratio": "2:1–3:1",
        "attackRelease": "10–30 ms / auto",
        "gainReduction": "1–2 dB",
        "notes": "Groove glue; keep bus compression at 1–2 dB"
      }
    ],
    "notes": [
      {
        "text": "De-ess the lead at 5–8 kHz for 2–4 dB, and watch the shaker/sibilance pile-up in the same region. Gates are rarely needed on programmed parts; live, gate toms and expand talking drum and conga mics gently (−10 dB range) to tame percussion-riser bleed. A slow multiband on the master around 60 Hz (attack/release slow enough to follow the tempo) keeps subs breathing with the groove."
      }
    ]
  },
  "fx": {
    "rows": [
      {
        "effect": "Tempo delay",
        "appliedTo": "Lead vocal, ad-libs",
        "setting": "1/8 or 1/4 note (at 108 BPM: 278 ms / 556 ms), 15–25% feedback, HPF 250 Hz / LPF 6 kHz",
        "amount": "Moderate; often more than reverb"
      },
      {
        "effect": "Plate reverb",
        "appliedTo": "Lead vocal, snare/rim",
        "setting": "1.2–1.8 s, 30–60 ms pre-delay",
        "amount": "Subtle–moderate"
      },
      {
        "effect": "Ping-pong delay",
        "appliedTo": "BVs, hook stacks",
        "setting": "1/16 to 1/8 note, 20–30% feedback",
        "amount": "Moderate"
      },
      {
        "effect": "Pitch-shift widener",
        "appliedTo": "Lead vocal, snaps",
        "setting": "±6–10 cents, 10–20 ms",
        "amount": "Subtle"
      },
      {
        "effect": "Short delay / chorus",
        "appliedTo": "Highlife guitar",
        "setting": "1/16 delay 10–15% fb; chorus 0.5 Hz, 15% depth",
        "amount": "Subtle"
      },
      {
        "effect": "Gated / room reverb",
        "appliedTo": "Snare, fills",
        "setting": "0.4–0.8 s",
        "amount": "Subtle, tucked"
      },
      {
        "effect": "Hard-tune pitch correction (effect)",
        "appliedTo": "Lead and BVs",
        "setting": "Fast retune (5–20 ms) when the artist uses it as a sound",
        "amount": "As produced"
      }
    ],
    "notes": [
      {
        "text": "Delays feeding a reverb give the airy “ocean of space” these records have without washing out the vocal or the percussion."
      }
    ]
  },
  "vocals": [
    {
      "text": "The lead vocal is mid-forward, warm and intimate, sitting into the groove: roughly level with the rimshot and only 1–2 dB above percussion. Intelligibility matters, but accents, Pidgin and code-switching are features, not problems; don’t EQ them thin. Pitch correction is standard and often audible as an effect; match the demo, which is usually the intended sound. Hooks are stacked with doubles, octaves and harmonies, with call-and-response BVs and ad-libs panned wide. Keep producer tags. Live, drop the lead 3–6 dB when the crowd takes the hook and keep a tempo-synced delay on a tap."
    }
  ],
  "loudness": [
    {
      "label": "Live:",
      "text": "Club and diaspora party shows run about 96–100 dBA LAeq-15 at FOH; arena and festival headliners 100–102 dBA, with C-weighted levels around 115–124 dBC. Afrobeats wants solid but warm sub, less than EDM, more than rock; a C-minus-A gap above 20 dB signals excessive low end. Many UK/EU venues cap around 100 dBA LAeq-15. By common hearing-safety guidance, 100 dBA is safe for about 15 minutes; where no limits are enforced, self-police and protect your ears. Plan for unstable mains power at some venues (UPS on consoles and racks)."
    },
    {
      "label": "Studio / streaming:",
      "text": "Commercial masters typically land at −10 to −7 LUFS-I, true peak −1 dBTP (−2 dBTP for masters louder than −14, a common streaming recommendation). Platforms normalize to about −14 LUFS, so extra loudness buys nothing and costs percussion snap. Aim for a PLR of roughly 8–10 dB (about −10 to −12 LUFS-I at −2 dBTP) and a loudness range of 3–6 LU. Stack several small clip and limiting stages (each 0.5–2 dB) rather than one heavy limiter."
    }
  ],
  "liveStudio": {
    "rows": [
      {
        "area": "Percussion",
        "live": "8–10 live players plus stems; manage bleed, group by type, keep the clave figure clear",
        "studio": "Programmed loops layered and placed precisely; very forward"
      },
      {
        "area": "Low end",
        "live": "Kick/bass on stems plus live bass; tight HPFs on percussion mics; watch room buildup at 80–200 Hz",
        "studio": "Sidechain and multiband shaping; saturation for phone translation"
      },
      {
        "area": "Vocals",
        "live": "Wireless handheld, minimal chain, crowd sing-backs, BV and choir mic management",
        "studio": "Comping, tuning, stacks, detailed clip-gain rides"
      },
      {
        "area": "Input count",
        "live": "Up to 100–120 inputs on large consoles",
        "studio": "Stems from producer; often 100+ BV tracks to group and print"
      },
      {
        "area": "Effects",
        "live": "One or two tapped delays and reverbs",
        "studio": "Many automated delays, wideners, creative throws"
      },
      {
        "area": "Monitoring",
        "live": "Dozens of IEM mixes; personal-mix apps for band",
        "studio": "Nearfields plus phone and earbud checks"
      },
      {
        "area": "Loudness",
        "live": "96–102 dBA LAeq-15",
        "studio": "−10 to −7 LUFS-I, −1 dBTP"
      }
    ],
    "notes": []
  },
  "notes": [
    {
      "text": "Learn the clave figure in the song first; if it is not obvious in your mix, the groove is lost.",
      "bullet": true
    },
    {
      "text": "Don’t treat percussion as background. Bring shakers and rims forward, then manage harshness with EQ, not level.",
      "bullet": true
    },
    {
      "text": "Keep the kick short and give the bass melody room; check the bass on a phone speaker.",
      "bullet": true
    },
    {
      "text": "Avoid heavy bus compression that dulls transients; protect the bounce.",
      "bullet": true
    },
    {
      "text": "Respect the demo’s vocal sound, including deliberate hard-tuned pitch correction.",
      "bullet": true
    },
    {
      "text": "Live, label and group the percussion section carefully.",
      "bullet": true
    },
    {
      "text": "Don’t confuse the brief: an Afrobeat (Fela-style) band needs a live-funk mix with horns and long dynamics; Afrobeats needs a pop-club groove mix.",
      "bullet": true
    }
  ],
  "references": [
    "Wizkid feat. Tems, “Essence”, 2020",
    "Burna Boy, “Ye”, 2018",
    "Burna Boy, “Last Last”, 2022",
    "Wizkid, “Ojuelegba”, 2014",
    "Davido, “Fall”, 2017",
    "Rema, “Calm Down”, 2022",
    "D’banj, “Oliver Twist”, 2011",
    "Drake feat. Wizkid and Kyla, “One Dance”, 2016 (crossover reference)"
  ],
  "empty": []
};
