/**
 * Mixing guide 16 — Film & Video Game Score. GENERATED by scripts/mixing-guides/convert.py
 * from the owner's guide (assets/Mixing-Guides-50-Styles, read only). Edit the
 * conversion (scripts/mixing-guides/edits.py), not this file.
 */
import type { MixingGuide } from '../types';

export const GUIDE: MixingGuide = {
  "id": "film-video-game-score",
  "num": 16,
  "title": "Film & Video Game Score",
  "expects": "The listener rarely focuses on it directly, so the score has to work emotionally while sitting under dialogue and effects. In concert the relationship flips: fans come for the themes they grew up with and want the full orchestral sweep behind the footage.",
  "glance": {
    "origin": "Hollywood studio orchestras from the 1930s; hybrid orchestra-plus-synth scoring grew out of Los Angeles and London from the 1980s–2000s; game scores went orchestral from the late 1990s",
    "tempo": "Follows picture, not a dance pulse: 60–90 BPM for drama, 120–160 BPM for action cues; tempo maps often shift bar to bar to hit cuts",
    "ensemble": "40–100-piece orchestra plus choir, overdubbed percussion (taiko, toms, anvils), synths and sound-design layers; live “in concert” shows 45–100 players plus band and playback",
    "priority": "Serving the picture: clarity of the main theme without masking dialogue, and stems that the dub stage or game engine can actually use",
    "liveSpl": "Film-in-concert 85–92 dBA Leq with crescendos to about 100 dBA; arena hybrid score shows average near 90 dBA",
    "studioLoudness": "Theatrical and streaming mixes are dialogue-anchored (a major streaming spec: −27 LKFS dialogue-gated, −2 dBTP); games −24 LUFS console / −16 to −18 mobile, −1 dBTP; soundtrack albums −16 to −10 LUFS-I, streaming normalizes to about −14"
  },
  "purpose": [
    {
      "text": "Score is functional music: it tells the audience how to feel about what is on screen, carries themes that identify characters and places, and in games reacts to the player. The listener rarely focuses on it directly, so the score has to work emotionally while sitting under dialogue and effects. In concert the relationship flips: fans come for the themes they grew up with and want the full orchestral sweep behind the footage. Audiences say “that sounded wrong” when brass masks a line of dialogue, the hybrid low end turns to mush on a TV, or the live orchestra sounds like a thin copy of the album."
    }
  ],
  "instruments": [
    {
      "label": "Strings:",
      "text": "the emotional core—long legato lines, ostinatos (Zimmer-style spiccato cells), tremolo for tension.",
      "bullet": true
    },
    {
      "label": "Brass:",
      "text": "horns for heroic themes, trombones and tubas for weight, trumpets for fanfares.",
      "bullet": true
    },
    {
      "label": "Woodwinds, harp, celeste, piano:",
      "text": "color and solos.",
      "bullet": true
    },
    {
      "label": "Choir:",
      "text": "from a 12-voice chamber group to 60+ voices; often Latin or invented-language text.",
      "bullet": true
    },
    {
      "label": "Percussion:",
      "text": "timpani, orchestral bass drum, cymbals, plus “epic” ensembles—taiko, toms, anvils, metal hits.",
      "bullet": true
    },
    {
      "label": "Electronics:",
      "text": "analog and soft synths (pads, pulsing bass, arps), “braams” and risers, processed sound-design hits, distorted cellos and guitars.",
      "bullet": true
    },
    {
      "label": "Playback (live shows):",
      "text": "timecode-locked dialogue and effects stems from the film, click and streamers for the conductor, synth and pre-recorded layers that the orchestra cannot reproduce.",
      "bullet": true
    }
  ],
  "arrangement": [
    {
      "text": "On the scoring stage the orchestra sits in a classical layout—violins left, violas and cellos center-right, basses back right, winds center, brass behind, percussion at the rear—so the three-omni tree captures a natural image. Arrangement is driven by picture: sparse pads and solo instruments under dialogue scenes, full tutti for action or emotional climaxes, and stingers at hard cuts. In games, music is built in vertical layers (the same cue with ambient, tension and combat stems that fade in) or horizontal segments that branch on gameplay, so each layer must sound complete on its own and in any combination."
    }
  ],
  "dynamics": [
    {
      "text": "Score has the widest dynamic range of any commercial music—from a solo flute at pianissimo to 100-piece tutti with taiko is easily 30–40 dB acoustically. In film the dub stage controls the final dynamics, so the score mixer should preserve range and deliver stems with headroom rather than limiting them; a squashed stem forces the re-recording mixer to fight it. Games need moderated dynamics because players hear the music for hours on TV speakers; aim for a loudness range of 10–15 LU on mobile and under about 20 LU on console."
    }
  ],
  "balance": [
    {
      "text": "For the soundtrack album: melody (horns, high strings or choir carrying the theme) first, then rhythm engine (string ostinato, percussion), then harmony beds (low brass, pads), then color (harp, celeste, risers). Under dialogue the theme drops to the background and the score lives in the lows, high strings and sides. Low end: decide who owns the sub—synth bass and sub hits usually sit 30–60 Hz, timpani and bass drum 60–100 Hz, celli and basses 80–250 Hz. Sidechain the orchestra’s lows (0–300 Hz band of a multiband compressor) to big hits so they don’t stack. In surround, follow the film mixer’s rule of not building the mix in the middle: keep the center channel mostly clear for dialogue, put the orchestra’s main image across left and right, and use the surrounds for room and reverb, never primary instruments."
    }
  ],
  "eq": {
    "rows": [
      {
        "source": "three-omni tree / room mics",
        "cut": "HPF 25–40 Hz; −1–2 dB at 250 Hz if the hall is thick",
        "boost": "+1–2 dB shelf at 8 or 12 kHz",
        "notes": "The tree is the mix; spots only add detail"
      },
      {
        "source": "Violins / violas (spots)",
        "cut": "HPF 80–120 Hz; −2–3 dB around 200 Hz; narrow dips at 2.5, 4.6 or 7 kHz if strident",
        "boost": "+1–2 dB at 2.2–3.3 kHz (articulation)",
        "notes": "Sample strings often carry a bump near 2.5 kHz—cut it"
      },
      {
        "source": "Celli / basses",
        "cut": "HPF 30–40 Hz (basses), 60 Hz (celli); −2 dB at 250–400 Hz",
        "boost": "+1–2 dB at 80–120 Hz; +1 dB at 1–2 kHz for bow detail",
        "notes": "Watch overlap with synth bass"
      },
      {
        "source": "French horns",
        "cut": "HPF 60–80 Hz; −2 dB around 3 kHz if blatty",
        "boost": "+1–2 dB at 300–500 Hz (warmth); gentle shelf at 10 kHz",
        "notes": "Horns radiate backward—most tone is in the room mics"
      },
      {
        "source": "Trumpets / trombones",
        "cut": "HPF 80 Hz (tpt), 50 Hz (tbn); −2–3 dB at 2–4 kHz if harsh",
        "boost": "+1–2 dB at 1–1.5 kHz (bite)",
        "notes": "Keep brass out of the dialogue band in quiet scenes"
      },
      {
        "source": "Choir",
        "cut": "HPF 100–150 Hz; −2 dB at 300 Hz",
        "boost": "+1–2 dB at 3–5 kHz (diction); air shelf at 12 kHz",
        "notes": "Diction matters less than blend unless text is featured"
      },
      {
        "source": "Taiko / epic toms",
        "cut": "HPF 30–35 Hz; −3–4 dB at 300–500 Hz (box)",
        "boost": "+2–4 dB at 50–80 Hz; +2 dB at 3–5 kHz (stick)",
        "notes": "Keep below synth sub or carve with dynamic EQ"
      },
      {
        "source": "Timpani",
        "cut": "HPF 30 Hz; −2 dB at 200–300 Hz",
        "boost": "+2 dB at 80–100 Hz; +1 dB at 3 kHz",
        "notes": "Tuned notes—check they don’t clash with sub hits"
      },
      {
        "source": "Synth pads / bass",
        "cut": "HPF pads 150–250 Hz; dip 1–4 kHz under dialogue",
        "boost": "Bass +2 dB at 40–60 Hz; pads +1 dB at 8–10 kHz",
        "notes": "Give synths the extremes, leave mids to the orchestra"
      },
      {
        "source": "Braams / sound-design hits",
        "cut": "HPF 25 Hz; −3 dB in 2–4 kHz in dialogue scenes",
        "boost": "+2 dB at 40–60 Hz",
        "notes": "Sidechain orchestral lows to these"
      }
    ],
    "notes": []
  },
  "compression": {
    "rows": [
      {
        "source": "Orchestra stems (strings, brass, winds)",
        "use": "Rarely",
        "ratio": "1.5:1–2:1",
        "attackRelease": "30 ms / auto",
        "gainReduction": "0–2 dB",
        "notes": "Ride faders instead; preserve the swells"
      },
      {
        "source": "Percussion stem",
        "use": "Yes",
        "ratio": "4:1",
        "attackRelease": "10–30 ms / 100 ms",
        "gainReduction": "3–6 dB",
        "notes": "Keep as its own stem so bus compression stays intact"
      },
      {
        "source": "Parallel percussion",
        "use": "Yes",
        "ratio": "8:1–10:1",
        "attackRelease": "1–5 ms / 50 ms",
        "gainReduction": "8–12 dB, blended 20–30%",
        "notes": "Adds weight without killing transients"
      },
      {
        "source": "Synth bass / sub",
        "use": "Yes",
        "ratio": "3:1–4:1",
        "attackRelease": "10 ms / 80 ms",
        "gainReduction": "3–5 dB",
        "notes": "Even out notes so sub energy is predictable"
      },
      {
        "source": "Orchestral lows (multiband, 0–300 Hz)",
        "use": "Yes, sidechained",
        "ratio": "3:1",
        "attackRelease": "5 ms / 150–250 ms",
        "gainReduction": "3–6 dB on hits",
        "notes": "Keyed from braams and taiko"
      },
      {
        "source": "Choir",
        "use": "Light",
        "ratio": "2:1",
        "attackRelease": "20 ms / auto",
        "gainReduction": "1–3 dB",
        "notes": "Opto style; leave dynamics to the singers"
      },
      {
        "source": "Score mix bus (album)",
        "use": "Optional",
        "ratio": "1.5:1–2:1",
        "attackRelease": "30 ms / auto",
        "gainReduction": "1–2 dB",
        "notes": "No limiting on film stems"
      },
      {
        "source": "Live playback bus",
        "use": "Yes",
        "ratio": "2:1 + limiter",
        "attackRelease": "auto",
        "gainReduction": "2–4 dB",
        "notes": "Separate chain from the live orchestra"
      }
    ],
    "notes": [
      {
        "text": "Skip gates on orchestral mics; edit bleed instead. Live, upward compression that lifts quiet passages works well for hybrid score shows. Soundtrack albums tolerate mastering limiting of 2–4 dB; film stems should peak no hotter than about −6 dBFS so the dub stage has room."
      }
    ]
  },
  "fx": {
    "rows": [
      {
        "effect": "Hall reverb",
        "appliedTo": "Orchestra spots, per section",
        "setting": "2.0–3.0 s decay, 20–40 ms pre-delay; separate reverb per stem",
        "amount": "Subtle–moderate (the room mics do most of the work)"
      },
      {
        "effect": "Surround reverb",
        "appliedTo": "Rear channels / height objects",
        "setting": "Same algorithm as front, longer pre-delay (40–80 ms)",
        "amount": "Moderate—creates envelopment"
      },
      {
        "effect": "Short room / chamber",
        "appliedTo": "Overdubbed percussion, choir",
        "setting": "0.8–1.4 s decay",
        "amount": "Moderate, to place studio overdubs in the hall"
      },
      {
        "effect": "Long “epic” reverb",
        "appliedTo": "Braams, synth hits, solo vocal",
        "setting": "4–8 s decay, 50–100 ms pre-delay",
        "amount": "Heavy, but tucked and HPF’d at 200 Hz"
      },
      {
        "effect": "Haas/delay widening",
        "appliedTo": "Synths, surround spread",
        "setting": "10–25 ms offset between channels",
        "amount": "Subtle—moves energy off center without panning"
      },
      {
        "effect": "Tempo delay",
        "appliedTo": "Synth arps, solo vocal",
        "setting": "1/8 or dotted 1/8 synced to the cue’s tempo map",
        "amount": "Subtle"
      },
      {
        "effect": "Saturation / tape",
        "appliedTo": "Synth bass, percussion stem, celli",
        "setting": "1–3 dB of drive",
        "amount": "Subtle—adds harmonics audible on small speakers"
      }
    ],
    "notes": [
      {
        "text": "Give each stem its own reverb return so the dub stage can drop a stem without leaving orphan reverb behind."
      }
    ]
  },
  "vocals": [
    {
      "text": "Most score vocals are choir or wordless soloists. Treat choir as an orchestral section: tree or pair plus section spots, light compression, shared hall. Solo voices sit inside the orchestra rather than on top, typically with a long pre-delayed reverb for a “distant” effect; pitch correction is rare and should be inaudible. The critical “vocal” in film is dialogue, which belongs to the re-recording mixer—your job is to avoid competing with it: thin the score in 1–4 kHz during speech and keep music out of the center channel (some broadcasters forbid music there). In live-to-picture shows, dialogue and effects come from playback stems; engineers often push extra dialogue level to the front of the audience to counter the acoustic orchestra, and ride each line because source levels vary."
    }
  ],
  "loudness": [
    {
      "label": "Live:",
      "text": "Film-in-concert and game-music shows usually average 85–92 dBA Leq at FOH, with tutti peaks near 100 dBA and sub-heavy cues touching 110–115 dBC; a C-minus-A gap above 20 dB signals too much sub. Time-align fills to the orchestra (big arena shows have used 15–17 delay zones) so the PA reinforces rather than replaces the acoustic sound."
    },
    {
      "label": "Studio / streaming:",
      "text": "Cinema is calibrated to 85 dBC per channel at reference; mixes rely on dialogue level, and many theaters play below reference. A major streaming delivery spec asks for −27 LKFS dialogue-gated (±2 LU) with −2 dBTP and a mix loudness range of 4–18 LU, mixed near-field at around 79 dB SPL. Games target −24 LUFS integrated (±2 LU) on console and −16 to −18 LUFS on mobile, −1 dBTP, measured over at least 30 minutes of representative play. Soundtrack albums commonly land −16 to −12 LUFS-I (hybrid action scores up to about −10); streaming normalizes to about −14 LUFS with −1 dBTP recommended."
    }
  ],
  "liveStudio": {
    "rows": [
      {
        "area": "Microphones",
        "live": "Clip-on condensers on every player; few room mics",
        "studio": "three-omni tree, outriggers, room and surround mics carry the sound; spots for detail"
      },
      {
        "area": "Low end",
        "live": "Sub arrays for feel; watch hall buildup at 80–200 Hz",
        "studio": "Clean sub management via sidechain and multiband; checked on TV speakers"
      },
      {
        "area": "Dialogue",
        "live": "Playback stem ridden live, extra to front fills",
        "studio": "Belongs to the dub stage; score leaves space"
      },
      {
        "area": "Synths & playback",
        "live": "Timecode-locked playback with separate bus and processing",
        "studio": "Printed stems from composer’s rig, often pre-EQ’d on returns"
      },
      {
        "area": "Monitoring",
        "live": "Click and streamers to conductor; IEM or personal mixes for players",
        "studio": "Calibrated surround/immersive room (79–85 dB SPL reference)"
      },
      {
        "area": "Format",
        "live": "Stereo/LCR PA, sometimes surround zones",
        "studio": "5.1, 7.1, 7.1.2 bed plus objects, stereo fold-down, stems"
      },
      {
        "area": "Loudness",
        "live": "85–92 dBA Leq",
        "studio": "Dialogue-anchored spec or −24 LUFS game target"
      }
    ],
    "notes": []
  },
  "notes": [
    {
      "text": "Organize stems by “food group” (strings, brass, winds, percussion, choir, synths, FX), each with its own reverb, and print a stereo fold-down and dialogue reference slug.",
      "bullet": true
    },
    {
      "text": "In immersive formats, deliver a 7.1.2 bed plus object stems per section; keep percussion as a 7.1 stem so bus compression stays coherent.",
      "bullet": true
    },
    {
      "text": "Leave headroom in stems so the re-recording mixer works near unity rather than pulling faders down 10 dB.",
      "bullet": true
    },
    {
      "text": "Listen to the temp dialogue and effects while mixing—a cue that sounds great alone may mask key lines.",
      "bullet": true
    },
    {
      "text": "Don’t bury primary instruments in the surrounds; rears are for size, not melody.",
      "bullet": true
    },
    {
      "text": "Live, mix in eight-bar moves to steer focus with the picture rather than setting one static balance.",
      "bullet": true
    }
  ],
  "references": [
    "John Williams, “Star Wars: Main Title”, 1977",
    "Hans Zimmer, “Time” from Inception, 2010",
    "Howard Shore, “The Bridge of Khazad-dûm” from The Fellowship of the Ring, 2001",
    "Junkie XL, “Brothers in Arms” from Mad Max: Fury Road, 2015",
    "Hans Zimmer, “Paul’s Dream” from Dune, 2021",
    "Hildur Guðnadóttir, “Bathroom Dance” from Joker, 2019",
    "Bear McCreary, “God of War” main theme from God of War, 2018",
    "Nobuo Uematsu, “One-Winged Angel” from Final Fantasy VII, 1997"
  ],
  "empty": []
};
