/**
 * Mixing guide 22 — Soul. GENERATED by scripts/mixing-guides/convert.py
 * from the owner's guide (assets/Mixing-Guides-50-Styles, read only). Edit the
 * conversion (scripts/mixing-guides/edits.py), not this file.
 */
import type { MixingGuide } from '../types';

export const GUIDE: MixingGuide = {
  "id": "soul",
  "num": 22,
  "title": "Soul",
  "expects": "Listeners expect the singer’s breath and grit, a bass line they can follow, a backbeat in the pocket, and horns that punch without stabbing.",
  "glance": {
    "origin": "United States, late 1950s–1970s: Detroit (Motown), Memphis and Muscle Shoals (Stax, southern soul), Philadelphia (Philly soul); neo-soul from mid-1990s New York/Philadelphia; retro-soul revival from Brooklyn (Daptone) in the 2000s",
    "tempo": "60–130 BPM (ballads 60–75; neo-soul grooves 70–95; Motown stompers and Philly dance tracks 110–125)",
    "ensemble": "6–12 piece: drums, bass, guitar, keys, 2–4 horns, lead vocal plus 2–3 backing singers; Philly-style shows add strings; neo-soul often a 5–6 piece with keys and backing vocals",
    "priority": "The lead vocal, warm and fully intelligible, riding a pocket of drums and bass that feels human",
    "liveSpl": "92–98 dBA Leq (LAeq-15 min); roughly 108–115 dBC; theaters and supper clubs often 90–95 dBA",
    "studioLoudness": "Masters commonly −11 to −8 LUFS-I (retro-soul and catalog nearer −13 to −10); streaming normalizes to about −14"
  },
  "purpose": [
    {
      "text": "Soul is music of testimony: gospel fervor carried into secular love songs, heartbreak and social messages. It is for dancing, slow-dancing and catharsis; audiences often know every word and horn line. Neo-soul (D’Angelo, Erykah Badu, Jill Scott) added hip-hop timing and a looser, more introspective mood. Listeners expect the singer’s breath and grit, a bass line they can follow, a backbeat in the pocket, and horns that punch without stabbing. Wrong to this crowd: a buried or over-tuned vocal, a quantized or sample-replaced drum feel on a live band, harsh brass, a hyped modern low end on a vintage-style tune, and a mix that batters the audience—the aim is to immerse fans, not pummel them."
    }
  ],
  "instruments": [
    {
      "label": "Drums:",
      "text": "acoustic kit with a dead, muffled kick (Motown stuffed blankets inside) and a fat, dark snare; neo-soul favors dry, close sounds and behind-the-beat Questlove/J Dilla timing.",
      "bullet": true
    },
    {
      "label": "Bass:",
      "text": "electric bass, classically recorded direct (Motown’s custom DI under James Jamerson’s melodic lines); neo-soul adds synth and sub bass.",
      "bullet": true
    },
    {
      "label": "Guitar:",
      "text": "clean, chicken-scratch rhythm and double-stop fills (Steve Cropper at Stax), often on the 2 and 4 with the snare.",
      "bullet": true
    },
    {
      "label": "Keys:",
      "text": "Hammond organ with rotating speaker, piano, tine and reed electric pianos (essential to neo-soul), clavinet; vibraphone in Philly soul.",
      "bullet": true
    },
    {
      "label": "Horns:",
      "text": "trumpet, tenor and baritone sax, trombone—section hits and pads, the Memphis Horns template.",
      "bullet": true
    },
    {
      "label": "Strings and orchestra:",
      "text": "Philly soul and late Motown use full string sections, plus oboe, bassoon, glockenspiel.",
      "bullet": true
    },
    {
      "label": "Percussion:",
      "text": "tambourine, handclaps, finger snaps, congas, shaker—tambourine on the backbeat is a Motown fingerprint.",
      "bullet": true
    },
    {
      "label": "Playback:",
      "text": "rare in retro-soul; neo-soul shows may run tracks for pads, extra vocals or programmed drums.",
      "bullet": true
    }
  ],
  "arrangement": [
    {
      "text": "Stage layout: drums upstage center, bass beside the kit, keys and guitar on opposite sides, horns in a row or on a riser, backing singers opposite the horns, lead vocal downstage center. Drums, bass and guitar lock a repeating groove; keys supply chords and fills; horns punctuate and swell into choruses; backing vocals answer the lead in call-and-response, a direct gospel inheritance. Verses tend to be sparse (rhythm section only), pre-choruses add horn pads or strings, choruses bring the full band and stacked backing vocals. Many songs end in a long vamp while the singer ad-libs and builds."
    }
  ],
  "dynamics": [
    {
      "text": "Soul has wide dynamics for popular music. A ballad can run from a near-whispered verse to a full-throated belt 15–20 dB louder at the mic, and a ten-piece band swings from a hi-hat-and-bass breakdown to a full horn shout. Preserve this contrast: it is where the emotion lives. Control peaks with compression; shape the arc with fader rides. The classic soul engineers rode faders by hand at mixdown, and good FOH engineers “perform” the dynamics with the band. Over-limited masters that flatten the vamp’s build are a common complaint."
    }
  ],
  "balance": [
    {
      "text": "Typical hierarchy, loudest to quietest: lead vocal; snare and bass; kick; horns (pushed up for hits and solos); backing vocals; keys and guitar; tambourine/percussion; strings; reverb returns. The bass is a lead voice in soul—let it be slightly louder and more melodic than in rock, owning roughly 60–250 Hz with clear upper-mid definition, while the kick is a short, round thump around 60–90 Hz that sits under it. Neo-soul runs a deeper sub, but the bass line must still read on small speakers. Modern mixes center vocal, kick, snare and bass; horns go slightly off-center or split across, backing vocals wide, keys and guitar opposite. For a retro sound, consider bold, static panning: classic Motown stereo mixes such as “I Heard It Through the Grapevine” (1968) put drums on one side and bass, keys and strings on the other, and modern retro-soul records use drums-left/bass-right layouts too. Check every retro mix in mono."
    }
  ],
  "eq": {
    "rows": [
      {
        "source": "Kick",
        "cut": "HPF 30–40 Hz; −3 to −6 dB at 300–500 Hz",
        "boost": "+2–3 dB at 60–80 Hz; small lift at 2–3 kHz only if needed",
        "notes": "Retro kicks are dead and round—little beater click"
      },
      {
        "source": "Snare",
        "cut": "HPF 80–100 Hz; −2–3 dB at 400 Hz if boxy; notch ring",
        "boost": "+2–3 dB at 150–200 Hz (body); +1–2 dB at 4–5 kHz",
        "notes": "Keep it fat and slightly dark; skip 10 kHz sizzle for retro"
      },
      {
        "source": "Overheads / single drum mic",
        "cut": "HPF 100–150 Hz; dip 2–4 kHz if splashy",
        "boost": "LPF 8–12 kHz for vintage tone",
        "notes": "Daptone often uses one or two mics on the whole kit"
      },
      {
        "source": "Bass (DI + amp)",
        "cut": "HPF 35–40 Hz; −2 dB at 200–250 Hz if woofy",
        "boost": "+2 dB at 80–100 Hz; +2–3 dB at 700 Hz–1 kHz (note definition)",
        "notes": "Flatwounds lack top—don’t force it above 4 kHz"
      },
      {
        "source": "Clean guitar",
        "cut": "HPF 100–150 Hz; −2 dB at 250–400 Hz",
        "boost": "+2 dB at 2–3 kHz (chop)",
        "notes": "Keep it small and percussive; it lives with the snare"
      },
      {
        "source": "Electric piano (tine / reed)",
        "cut": "HPF 60–80 Hz; −2–3 dB at 200–300 Hz (mud)",
        "boost": "+1–2 dB at 1–2 kHz (tine bark)",
        "notes": "LPF 10–12 kHz; avoid masking the vocal’s 2–4 kHz"
      },
      {
        "source": "Hammond (rotating speaker)",
        "cut": "HPF 60–80 Hz (top rotor mics 150 Hz)",
        "boost": "+1–2 dB at 2–3 kHz to cut through",
        "notes": "Mic top rotor left/right for width"
      },
      {
        "source": "Horn section",
        "cut": "HPF 100–150 Hz (bari 60–80 Hz); −2–3 dB at 2–4 kHz if piercing",
        "boost": "+1–2 dB at 200–300 Hz (body)",
        "notes": "Ribbon mics or a high-cut tame bite"
      },
      {
        "source": "Strings",
        "cut": "HPF 80–120 Hz (violins 150 Hz); dip 2–3 kHz if steely",
        "boost": "Gentle shelf +1–2 dB above 8 kHz (air)",
        "notes": "Seat them behind the vocal, not competing"
      },
      {
        "source": "Lead vocal",
        "cut": "HPF 80–100 Hz (male), 100–120 Hz (female); −2–3 dB at 250–400 Hz; notch resonances",
        "boost": "+2 dB at 3–5 kHz; air shelf +1–3 dB at 10–12 kHz (modern)",
        "notes": "Retro mixes roll top off above 6–8 kHz instead"
      }
    ],
    "notes": []
  },
  "compression": {
    "rows": [
      {
        "source": "Lead vocal (stage 1, FET)",
        "use": "Yes",
        "ratio": "4:1",
        "attackRelease": "1–5 ms / 50–100 ms",
        "gainReduction": "3–6 dB on peaks",
        "notes": "Catches belts; famous retro-soul vocals took about 10 dB from a fast FET compressor"
      },
      {
        "source": "Lead vocal (stage 2, opto/vari-mu)",
        "use": "Yes",
        "ratio": "2:1–3:1",
        "attackRelease": "Program / slow",
        "gainReduction": "2–4 dB",
        "notes": "Optical or vari-mu tube-style smoothing; tube compression flatters soul voices"
      },
      {
        "source": "Bass",
        "use": "Yes",
        "ratio": "4:1",
        "attackRelease": "10–30 ms / 100–200 ms",
        "gainReduction": "3–6 dB",
        "notes": "Even out notes but keep the player’s touch"
      },
      {
        "source": "Kick",
        "use": "Light",
        "ratio": "3:1–4:1",
        "attackRelease": "20–30 ms / 60–100 ms",
        "gainReduction": "2–4 dB",
        "notes": "Often unnecessary on a dead, muffled kick"
      },
      {
        "source": "Snare",
        "use": "Yes",
        "ratio": "3:1–4:1",
        "attackRelease": "10–25 ms / 80–120 ms",
        "gainReduction": "3–5 dB",
        "notes": "Neo-soul: parallel drum squash adds weight"
      },
      {
        "source": "Horn bus",
        "use": "Yes",
        "ratio": "3:1",
        "attackRelease": "10–20 ms / 100 ms",
        "gainReduction": "2–4 dB",
        "notes": "Tames stabs; vari-mu tube-style group comp in retro mixes"
      },
      {
        "source": "Backing vocal bus",
        "use": "Yes",
        "ratio": "4:1",
        "attackRelease": "5–10 ms / auto",
        "gainReduction": "4–6 dB",
        "notes": "Locks harmonies into one blended block"
      },
      {
        "source": "Mix bus",
        "use": "Optional",
        "ratio": "2:1",
        "attackRelease": "10–30 ms / auto",
        "gainReduction": "1–2 dB",
        "notes": "Glue only; protect the vamp’s build"
      }
    ],
    "notes": [
      {
        "text": "Parallel drum compression (8:1 or higher, 8–12 dB reduction, blended 15–30%) suits neo-soul and modern soul; retro-soul usually leans on tape saturation instead. Gate toms live gently (range 10–15 dB rather than full mute) so ghost notes and room feel survive. De-ess at 5–8 kHz for 2–4 dB; around 5.5 kHz suits many soul voices. Keep master limiting to 2–4 dB."
      }
    ]
  },
  "fx": {
    "rows": [
      {
        "effect": "Chamber reverb (Motown style)",
        "appliedTo": "Vocals, drums, horns, tambourine (not bass)",
        "setting": "1.2–2.0 s, bright decay, 10–30 ms pre-delay",
        "amount": "Moderate—a defining color in retro mixes"
      },
      {
        "effect": "Plate reverb",
        "appliedTo": "Lead vocal, snare",
        "setting": "1.5–2.5 s, 20–40 ms pre-delay",
        "amount": "Subtle–moderate; more on ballads"
      },
      {
        "effect": "Spring reverb",
        "appliedTo": "Vocals, guitar, drums (retro)",
        "setting": "Short, boingy, HPF 200 Hz / LPF 6 kHz",
        "amount": "Moderate; Daptone and “Rehab” both lean on it"
      },
      {
        "effect": "Tape slap",
        "appliedTo": "Lead vocal",
        "setting": "100–140 ms (~140 ms at 15 ips), single repeat",
        "amount": "Subtle–moderate"
      },
      {
        "effect": "Tempo delay",
        "appliedTo": "Vocal ad-libs, phrase ends",
        "setting": "1/4 or dotted 1/8, 15–25% feedback",
        "amount": "Subtle, automated"
      },
      {
        "effect": "rotating speaker / chorus",
        "appliedTo": "Organ, electric piano, occasionally vocals",
        "setting": "Slow/fast rotor; chorus 0.3–0.8 Hz",
        "amount": "As part of the tone; neo-soul has even run vocals through a rotating speaker"
      },
      {
        "effect": "Tape saturation",
        "appliedTo": "Drums, bass, whole mix",
        "setting": "Drive 1–3 dB into a tape emulation",
        "amount": "Subtle; the “warm” glue"
      }
    ],
    "notes": [
      {
        "text": "Ride reverb sends by section: keep a drum spring dry in verses and push it in choruses."
      }
    ]
  },
  "vocals": [
    {
      "text": "The lead vocal sits in front, roughly 2–4 dB above the band by perceived level, with every word clear and every breath and growl intact. Serial compression plus steady fader riding is standard. Tone should be warm and midrange-rich; let grit and rasp through rather than EQing them away. Pitch correction is light or absent in retro-soul—audible tuning destroys credibility—while neo-soul and modern soul accept transparent correction. Backing vocals are gospel-style stacks: three or more parts, compressed as a group, panned wide, and tucked 4–8 dB under the lead, with call-and-response lines pushed up when answering. Doubles are rare; harmonies do that job. Live mics: a rugged dynamic or a quality condenser handheld. Retro studio choices include ribbons and vintage dynamics; neo-soul favors tube condensers and more air."
    }
  ],
  "loudness": [
    {
      "label": "Live:",
      "text": "Club and theater soul shows typically run 92–98 dBA LAeq-15 at FOH, with C-weighted levels around 108–115 dBC; supper clubs, jazz-soul rooms and seated theaters often 90–95 dBA. Horn-shout peaks reach 105–110 dBA. A C-minus-A gap above about 15–18 dB usually means too much sub for soul. By common hearing-safety guidance, 94 dBA is safe for about one hour—offer earplugs and protect the band’s ears."
    },
    {
      "label": "Studio / streaming:",
      "text": "Modern soul and neo-soul masters typically land at −11 to −8 LUFS-I; retro-soul and catalog reissues often sit at −13 to −10. Keep true peak at or below −1 dBTP, or −2 dBTP for masters louder than −14 LUFS, a common streaming recommendation. Services normalize to about −14 LUFS, so extra loudness buys nothing. Soul benefits from a PLR of 10–13 dB and a loudness range of 6–9 LU so ballads breathe and vamps build."
    }
  ],
  "liveStudio": {
    "rows": [
      {
        "area": "Horns",
        "live": "One dynamic or clip-on per player (small dynamics or clip-on condensers), tame bleed and stage wash",
        "studio": "Single section mic about 4 ft back (Daptone) or close ribbons plus a room pair"
      },
      {
        "area": "Drums",
        "live": "Close mics with gentle gates; stage wash adds room",
        "studio": "Retro: one to three mics and tape; neo-soul: dry close sound with parallel compression"
      },
      {
        "area": "Vocals",
        "live": "Gain-before-feedback limits; dynamic mics; rides through every song",
        "studio": "Whole-take or pilot vocals often kept; serial compression, de-essing, reverb rides"
      },
      {
        "area": "Low end",
        "live": "Control 100–250 Hz buildup; bass rig and kit bleed",
        "studio": "Carve kick/bass; choose vintage-narrow or modern-deep low end deliberately"
      },
      {
        "area": "Stereo",
        "live": "Mostly mono-compatible center image",
        "studio": "Bold LCR panning possible for retro authenticity"
      },
      {
        "area": "Effects",
        "live": "One plate, one tempo delay, maybe spring for retro acts",
        "studio": "Chambers, springs, tape slap, rotating speaker, saturation automated by section"
      },
      {
        "area": "Loudness",
        "live": "92–98 dBA Leq; build through the set",
        "studio": "−11 to −8 LUFS-I, −1 dBTP"
      }
    ],
    "notes": []
  },
  "notes": [
    {
      "text": "Get the vocal right first, then build the pocket around it.",
      "bullet": true
    },
    {
      "text": "Don’t quantize, sample-replace or over-gate a live soul drummer—ghost notes and late snares are the feel.",
      "bullet": true
    },
    {
      "text": "Let the bass be melodic and audible on small speakers; add 700 Hz–1 kHz definition instead of more lows.",
      "bullet": true
    },
    {
      "text": "Horns should hit, not hurt: tame 2–4 kHz and compress the section as one instrument.",
      "bullet": true
    },
    {
      "text": "For retro-soul, filter rather than boost: high-cut around 6–10 kHz and low-cut 80–100 Hz create the vintage frame.",
      "bullet": true
    },
    {
      "text": "Leave headroom for the vamp—it should be the biggest moment.",
      "bullet": true
    },
    {
      "text": "Live, use virtual soundcheck when possible.",
      "bullet": true
    },
    {
      "text": "Don’t make neo-soul too clean: saturation, dry intimacy and loose timing are the identity.",
      "bullet": true
    }
  ],
  "references": [
    "Marvin Gaye, “What’s Going On”, 1971",
    "Otis Redding, “Try a Little Tenderness”, 1966",
    "The O’Jays, “Love Train”, 1972",
    "Aretha Franklin, “Respect”, 1967",
    "D’Angelo, “Untitled (How Does It Feel)”, 2000",
    "Amy Winehouse, “Rehab”, 2006",
    "Sharon Jones & the Dap-Kings, “100 Days, 100 Nights”, 2007",
    "Leon Bridges, “Coming Home”, 2015"
  ],
  "empty": []
};
