/**
 * Mixing guide 23 — Hard Rock. GENERATED by scripts/mixing-guides/convert.py
 * from the owner's guide (assets/Mixing-Guides-50-Styles, read only). Edit the
 * conversion (scripts/mixing-guides/edits.py), not this file.
 */
import type { MixingGuide } from '../types';

export const GUIDE: MixingGuide = {
  "id": "hard-rock",
  "num": 23,
  "title": "Hard Rock",
  "expects": "Fans come for swagger, guitar heroics and a singer who can belt over a wall of amps.",
  "glance": {
    "origin": "UK and USA, mid-to-late 1960s (from blues rock, garage and psychedelia); arena rock peak in the 1970s–80s; post-grunge and “active rock” radio from the mid-1990s on",
    "tempo": "90–140 BPM (power ballads 60–80; shuffles and fast rockers 150–170)",
    "ensemble": "4–5 piece band: drums, bass, 1–2 electric guitars, lead vocal (keys optional) plus 1–3 backing vocals; modern acts often add click and backing tracks",
    "priority": "The riff: big, mid-forward guitars locked to kick, snare and bass, with a lead vocal that cuts through without being buried",
    "liveSpl": "98–103 dBA Leq (LAeq-15 min); about 115–125 dBC; regulated venues often 99–102 dBA",
    "studioLoudness": "Masters commonly −9 to −6 LUFS-I (classic-era remasters −12 to −9); streaming normalizes to about −14"
  },
  "purpose": [
    {
      "text": "Hard rock is music for physical release: fists in the air, the chorus shouted back by an arena, the riff felt in the chest. Fans come for swagger, guitar heroics and a singer who can belt over a wall of amps. Compared with general rock the guitars are louder and more saturated; compared with metal the tuning is standard or slightly down, the gain lower and the groove more blues-based. An audience will say “that sounded wrong” if the guitars are fizzy and thin, the vocal is lost in the chorus, the kick is a papery click, the solo does not jump out, or the mix is so polished it loses its grit."
    }
  ],
  "instruments": [
    {
      "label": "Drums:",
      "text": "often a large kit (multiple toms and crashes, sometimes double kick); close mics, overheads, room. Modern active rock blends kick and snare samples or triggers.",
      "bullet": true
    },
    {
      "label": "Bass:",
      "text": "electric, pick or fingers, DI plus amp; modern productions add distorted and sub layers.",
      "bullet": true
    },
    {
      "label": "Electric guitars:",
      "text": "the core. Humbuckers into overdriven tube amps (British-style tube crunch is the archetype), power chords, pentatonic riffs, solos with wah, delay and whammy.",
      "bullet": true
    },
    {
      "label": "Keys and acoustic guitar:",
      "text": "Hammond organ (the Deep Purple lineage), ballad piano, 1980s synth pads; acoustic for intros and power ballads.",
      "bullet": true
    },
    {
      "label": "Playback:",
      "text": "click, backing vocals and pads on modern tours; classic acts often run none.",
      "bullet": true
    }
  ],
  "arrangement": [
    {
      "text": "Drums center upstage on a riser, bass beside the drummer, guitars stage left and right, singer front center, often with a thrust. Classic acts (AC/DC) split two contrasting guitarists across the stereo field, one on rhythm, one on lead; modern post-grunge quad-tracks the rhythm part in the studio. The song shape is riff intro, palm-muted verse, pre-chorus build, huge chorus with crashes and stacked harmonies, solo after the second chorus, quiet bridge, then a final chorus. Big 1980s-style arena productions stack backing vocals into a choir and add extra chorus stages to keep escalating."
    }
  ],
  "dynamics": [
    {
      "text": "Macro-dynamics are modest but structural: verse to full chorus is roughly 4–8 dB, power ballads more. Preserve section contrast with automation (chorus +1–2 dB, guitars wider, room up) and control micro-dynamics firmly so vocal, bass and snare stay steady. Distorted guitars arrive already compressed. Live, the stage sets the dynamics; your job is keeping the vocal on top with fader rides of 5–10 dB."
    }
  ],
  "balance": [
    {
      "text": "Loudest to quietest: lead vocal, snare, rhythm guitar pair, kick and bass, lead guitar (near vocal level in solos), toms, backing vocals, overheads/room, keys, effects returns. Low end: kick owns 50–80 Hz thump and 2–5 kHz click; bass owns sustained 60–200 Hz and its 700 Hz–1.5 kHz growl; guitars are high-passed to stay out of both. Kick, snare, bass and lead vocal dead center. Rhythm guitars hard left and right; one strong mono take per side often beats heavy layering, and quad-tracked parts go hard plus 70–80%. Solos center or slightly off; backing stacks wide."
    }
  ],
  "eq": {
    "rows": [
      {
        "source": "Kick",
        "cut": "HPF 30–35 Hz; −4 to −6 dB at 300–500 Hz",
        "boost": "+3 dB at 55–70 Hz; +3–5 dB at 3–5 kHz (beater)",
        "notes": "Sample blend for consistency in modern styles; keep the tail short"
      },
      {
        "source": "Snare",
        "cut": "HPF 80–100 Hz; narrow −3 dB at ring (500 Hz–1 kHz)",
        "boost": "+2–4 dB at 180–250 Hz (body); +2–3 dB at 4–6 kHz (crack)",
        "notes": "Bottom mic phase-flipped, 6–10 dB under top for rattle"
      },
      {
        "source": "Toms",
        "cut": "HPF 50–70 Hz; −4 dB at 300–500 Hz",
        "boost": "+3 dB at 80–100 Hz (floor) / 120–200 Hz (rack); +2–3 dB at 4 kHz",
        "notes": "Big tom fills are a feature; gate or edit, then let them ring"
      },
      {
        "source": "Overheads / room",
        "cut": "HPF 150–250 Hz on overheads; dip 2–3 kHz if splashy",
        "boost": "+1–2 dB shelf at 10–12 kHz",
        "notes": "Lots of cymbals; keep overheads for cymbal decay, rooms for size"
      },
      {
        "source": "Bass",
        "cut": "HPF 35–40 Hz; −2–3 dB at 200–300 Hz",
        "boost": "+2 dB at 60–80 Hz; +2–4 dB at 800 Hz–1.2 kHz; 2–3 kHz for pick",
        "notes": "DI for lows, amp or drive layer for the midrange that glues to guitars"
      },
      {
        "source": "Rhythm guitars",
        "cut": "HPF 80–100 Hz; LPF 8–12 kHz; −2–3 dB at 200–300 Hz; narrow notch for fizz 3.5–5 kHz",
        "boost": "+1–3 dB at 1–2 kHz (crunch); +1–2 dB at 2.5–4 kHz (bite)",
        "notes": "Do not scoop the mids—hard rock tone lives at 500 Hz–2 kHz"
      },
      {
        "source": "Lead guitar / solos",
        "cut": "HPF 100–150 Hz; dip 4–6 kHz if fizzy",
        "boost": "+2–3 dB at 1–1.5 kHz",
        "notes": "More mids than rhythm tone; level and delay do the rest"
      },
      {
        "source": "Lead vocal",
        "cut": "HPF 80–120 Hz; −2–3 dB at 250–400 Hz; dynamic dip 2.5–5 kHz on belted notes",
        "boost": "+2–3 dB at 2–4 kHz (presence); +2 dB shelf at 10 kHz (air)",
        "notes": "Belting singers get harsh at top of range—use a dynamic EQ, not a static cut"
      },
      {
        "source": "Backing vocal stack",
        "cut": "HPF 150–200 Hz; scoop −3 dB at 400–800 Hz",
        "boost": "+2–3 dB shelf at 8–10 kHz",
        "notes": "Thinned and brightened so the stack sits behind but above the guitars"
      },
      {
        "source": "Hammond / keys",
        "cut": "HPF 100 Hz; −2 dB at 250–400 Hz",
        "boost": "+2 dB at 1–3 kHz on organ grit",
        "notes": "Keep out of the vocal’s 2–4 kHz zone"
      }
    ],
    "notes": []
  },
  "compression": {
    "rows": [
      {
        "source": "Lead vocal (stage 1, FET)",
        "use": "Yes",
        "ratio": "4:1–8:1",
        "attackRelease": "1–3 ms / 50–80 ms",
        "gainReduction": "4–7 dB on belts",
        "notes": "Fast FET-style catches screams; studio often adds a limiter before it"
      },
      {
        "source": "Lead vocal (stage 2, opto/VCA)",
        "use": "Yes",
        "ratio": "3:1",
        "attackRelease": "10–20 ms / auto",
        "gainReduction": "2–4 dB",
        "notes": "Live, a single tube leveler plus fader rides is common"
      },
      {
        "source": "Kick",
        "use": "Yes",
        "ratio": "4:1",
        "attackRelease": "20–30 ms / 50 ms",
        "gainReduction": "3–5 dB",
        "notes": "Slow attack keeps the beater"
      },
      {
        "source": "Snare",
        "use": "Yes",
        "ratio": "4:1",
        "attackRelease": "10–30 ms / 80–100 ms",
        "gainReduction": "4–6 dB",
        "notes": "Plus parallel crush"
      },
      {
        "source": "Bass",
        "use": "Yes (firm)",
        "ratio": "4:1–6:1",
        "attackRelease": "10–20 ms / 100 ms",
        "gainReduction": "5–8 dB",
        "notes": "Bass must be dead even under the riff"
      },
      {
        "source": "Rhythm guitars",
        "use": "Light / none",
        "ratio": "2:1",
        "attackRelease": "20–30 ms / auto",
        "gainReduction": "0–3 dB",
        "notes": "Amp saturation already compresses; ride levels instead"
      },
      {
        "source": "Room mics",
        "use": "Yes (heavy)",
        "ratio": "10:1–20:1",
        "attackRelease": "1 ms / 50–100 ms",
        "gainReduction": "10–15 dB",
        "notes": "Blend 10–20% for arena size"
      },
      {
        "source": "Drum bus",
        "use": "Yes",
        "ratio": "4:1",
        "attackRelease": "30 ms / fast",
        "gainReduction": "3–5 dB",
        "notes": "Glues the kit into one instrument"
      },
      {
        "source": "Mix bus",
        "use": "Yes",
        "ratio": "2:1",
        "attackRelease": "10–30 ms / auto",
        "gainReduction": "2–3 dB",
        "notes": "VCA bus-style comp is standard in this genre"
      }
    ],
    "notes": [
      {
        "text": "Parallel drum compression (8:1+, 10+ dB reduction, 20–40% blend) is a staple. Gate toms live (hold 40–60 ms, release 150–250 ms) and mute backing vocal mics between phrases. De-ess at 5–8 kHz for 3–5 dB. Master limiting: 3–5 dB for modern active rock, 2–3 dB for classic styles."
      }
    ]
  },
  "fx": {
    "rows": [
      {
        "effect": "Slap delay",
        "appliedTo": "Lead vocal",
        "setting": "100–140 ms, single repeat, HPF 300 Hz / LPF 4 kHz",
        "amount": "Moderate—a classic hard rock signature"
      },
      {
        "effect": "Tempo delay",
        "appliedTo": "Guitar solos, vocal phrase ends",
        "setting": "1/4 or dotted 1/8, 20–35% feedback",
        "amount": "Moderate on solos, thrown on vocal tails"
      },
      {
        "effect": "Plate reverb",
        "appliedTo": "Snare, lead vocal",
        "setting": "1.2–1.8 s decay, 20–40 ms pre-delay",
        "amount": "Subtle on vocals (0.8–1.2 s is enough), moderate on snare"
      },
      {
        "effect": "Room / ambience",
        "appliedTo": "Drums",
        "setting": "0.8–1.2 s, gated or short",
        "amount": "Moderate—arena size without washing riffs"
      },
      {
        "effect": "Hall reverb",
        "appliedTo": "Power ballads, big intros, solos’ last notes",
        "setting": "2.0–3.5 s, 40–80 ms pre-delay",
        "amount": "Moderate, automated"
      },
      {
        "effect": "Stereo widener / short delay",
        "appliedTo": "Rhythm guitars, BV stacks",
        "setting": "10–20 ms offset or pitch ±5–10 cents",
        "amount": "Subtle; check mono"
      },
      {
        "effect": "Modulation",
        "appliedTo": "Clean guitars, 1980s arena tones",
        "setting": "Chorus 0.5–1 Hz, flanger on effects throws",
        "amount": "Part of the tone"
      }
    ],
    "notes": [
      {
        "text": "Keep rhythm guitars bone dry; space comes from drums and vocal. Recall effects per song with snapshots, as arena-era racks did with program changes."
      }
    ]
  },
  "vocals": [
    {
      "text": "Hard rock singers belt, rasp and scream at the top of their range, so the chain is about control and cut. Sit the lead 1–3 dB above the guitar pair in choruses, every hook word clear. Tone is mid-forward with bite at 2–4 kHz and grit allowed; tame belted peaks with dynamic EQ. Pitch correction is common but transparent in modern active rock, minimal in blues-based hard rock. Choruses get doubles (6–10 dB under) and harmony stacks, up to the huge choirs of 1980s arena records; thin and brighten them so they do not cloud the guitars. Live, use a rugged dynamic or high-SPL condenser handheld, a 10–12 kHz low-pass when the singer works the thrust, a slap delay and constant fader riding. Notch backing-vocal mics at cymbal (3–6 kHz) and amp (200–500 Hz) bleed."
    }
  ],
  "loudness": [
    {
      "label": "Live:",
      "text": "Club and theater hard rock commonly runs 98–102 dBA LAeq-15 at FOH; arena tours 100–104 dBA, with peaks around 110–115 dBA and C-weighted levels of 115–125 dBC. Backline can exceed 120 dB on stage, so in small rooms the PA may add only vocals, kick and low end. Sub is moderate: a C-minus-A gap above 20 dB is too much. German rules set 99 dBA over 30 minutes and 135 dBC peak; UK and EU festivals often run 100–105 dBA LAeq-15. Some top FOH engineers mix near 98 dBA and rely on compression and clarity for power. Offer earplugs; by common hearing-safety guidance, 100 dBA is safe for about 15 minutes a day."
    },
    {
      "label": "Studio / streaming:",
      "text": "Modern active rock masters land around −9 to −6 LUFS-I; a recent rock/alternative chart analysis averaged about −8 LUFS-I with loudness range under 5 LU. Classic-styled hard rock suits −11 to −9 LUFS-I. Aim for −1 dBTP (−2 dBTP if louder than −14 LUFS); services normalize to about −14, so extra loudness only costs punch. A PLR of 8–11 dB keeps drums hitting."
    }
  ],
  "liveStudio": {
    "rows": [
      {
        "area": "Guitars",
        "live": "Stage amps already loud; mic choice (dynamic, ribbon, or large-diaphragm) shapes tone; add only what’s missing",
        "studio": "Double or quad-tracked, panned hard, layered clean and driven, sculpted with EQ"
      },
      {
        "area": "Vocals",
        "live": "Fight stage wash; dynamic mic, LPF near 10 kHz on thrust, heavy fader rides",
        "studio": "Comping, serial compression, tuning, dense stacks, automation every line"
      },
      {
        "area": "Drums",
        "live": "Gates on toms, triggers on large kits, minimal rooms",
        "studio": "Sample reinforcement, room mics, parallel crush, editing to grid"
      },
      {
        "area": "Bass",
        "live": "DI-heavy, compression to hold it steady",
        "studio": "DI, amp, distortion and sub layers, automated by section"
      },
      {
        "area": "Effects",
        "live": "Slap and tapped delays, one plate, scene-recalled per song",
        "studio": "Multiple delays and reverbs automated per section"
      },
      {
        "area": "Loudness",
        "live": "98–103 dBA Leq within venue limits",
        "studio": "−9 to −6 LUFS-I master, −1 dBTP target"
      }
    ],
    "notes": []
  },
  "notes": [
    {
      "text": "Get the vocal in early, then drums and rhythm guitars; push all faders up and balance before reaching for EQ.",
      "bullet": true
    },
    {
      "text": "A great mono guitar take per side beats a fizzy stack; fix tone at the amp and mic, not with 10 dB of console EQ.",
      "bullet": true
    },
    {
      "text": "Never scoop guitar mids—it makes the riff vanish in a full band and on phones.",
      "bullet": true
    },
    {
      "text": "Don’t let bass hide under the guitars; a drive layer or 1 kHz lift helps on small speakers.",
      "bullet": true
    },
    {
      "text": "Over-quantized drums and robotic tuning kill blues-based swagger.",
      "bullet": true
    },
    {
      "text": "Live, start with headroom and ride the lead vocal all night.",
      "bullet": true
    },
    {
      "text": "Make the solo an event: +3–4 dB, a touch of delay, second rhythm guitar pulled back slightly.",
      "bullet": true
    }
  ],
  "references": [
    "AC/DC, “Back in Black”, 1980",
    "Led Zeppelin, “Whole Lotta Love”, 1969",
    "Van Halen, “Panama”, 1984",
    "Def Leppard, “Pour Some Sugar on Me”, 1987",
    "Guns N’ Roses, “Welcome to the Jungle”, 1987",
    "Foo Fighters, “The Pretender”, 2007",
    "Shinedown, “Sound of Madness”, 2008",
    "Greta Van Fleet, “Highway Tune”, 2017"
  ],
  "empty": []
};
