/**
 * Mixing guide 24 — J-pop. GENERATED by scripts/mixing-guides/convert.py
 * from the owner's guide (assets/Mixing-Guides-50-Styles, read only). Edit the
 * conversion (scripts/mixing-guides/edits.py), not this file.
 */
import type { MixingGuide } from '../types';

export const GUIDE: MixingGuide = {
  "id": "j-pop",
  "num": 24,
  "title": "J-pop",
  "expects": "The words matter enormously—songs are tied to drama themes, anime storylines and commercials—so the audience expects to hear every syllable.",
  "glance": {
    "origin": "Japan; grew out of kayōkyoku, 1970s “new music” and city pop, and YMO-era technopop; the term “J-pop” took hold around 1990, with idol, anison (anime song) and band-style J-rock branches",
    "tempo": "120–180 BPM for up-tempo idol and anime openings (many sit around 160–180); ballads 65–90; band J-pop 130–160",
    "ensemble": "Solo singer + 5–7 piece band (often with strings or horns on tour); idol groups of 3–20+ singers over tracks; 4–5 piece bands with sequenced synths and strings",
    "priority": "A big, bright, fully intelligible lead vocal on top of a dense arrangement",
    "liveSpl": "Halls 92–98 dBA LAeq-15; arenas/domes 96–102 dBA; roughly 110–118 dBC; J-rock and anison festivals push toward the upper end",
    "studioLoudness": "Masters commonly −8 to −5 LUFS-I (among the loudest in the world); streaming normalizes to about −14; Japanese TV uses −24 LKFS"
  },
  "purpose": [
    {
      "text": "J-pop is music for identification and devotion: fans follow a singer, group or anime franchise for years, buy physical singles, learn every lyric, and treat concerts as communal celebrations. The words matter enormously—songs are tied to drama themes, anime storylines and commercials—so the audience expects to hear every syllable. The Japanese market demands a “big vocal” even over a huge backing track. Idol audiences participate actively: penlights coloured for each member, shouted “calls,” and rhythmic “mix” chants in intros and instrumental breaks, all traditionally avoided in slow, emotional songs. Anison crowds sing along to choruses and expect the record-exact sound of the TV opening. The fastest way to hear “that sounded wrong” is a vocal buried under guitars and synths, harsh sibilance, a dull or muffled top end, or a live show that sounds nothing like the bright, polished CD."
    }
  ],
  "instruments": [
    {
      "label": "Drums:",
      "text": "acoustic kit live (often a session-level player), frequently reinforced with samples; programmed drums in idol and technopop.",
      "bullet": true
    },
    {
      "label": "Bass:",
      "text": "electric bass, often busy and melodic (slap and fast eighth-note runs are common), sometimes doubled by synth bass.",
      "bullet": true
    },
    {
      "label": "Guitars:",
      "text": "clean funk-style cutting, crunchy rhythm and fast shred-style leads; J-rock and anison use dense, layered distorted guitars.",
      "bullet": true
    },
    {
      "label": "Keys and synths:",
      "text": "piano (central to ballads), bright supersaw pads, arpeggiators, chiptune and EDM elements (the electro-idol lineage).",
      "bullet": true
    },
    {
      "label": "Strings and brass:",
      "text": "real or sampled string sections and horn stabs are standard in arrangements and on large tours.",
      "bullet": true
    },
    {
      "label": "Playback:",
      "text": "extensive—click, synths, string beds, backing vocals and, for idols, often full instrumental and partial vocal tracks. Vocaloid-derived songs may carry heavily processed or synthetic vocal lines.",
      "bullet": true
    }
  ],
  "arrangement": [
    {
      "text": "J-pop songs follow a recognisable form: intro, A-melo (verse), B-melo (pre-chorus), sabi (chorus), with a key change and a final “ochi-sabi” (stripped chorus) before the last big chorus. Arrangements are notoriously dense—strings, synths, guitars and countermelodies can all play at once—and frequently modulate. Anime openings are written around a roughly 89–90-second TV edit, so the full version front-loads hooks. On stage, solo artists use a band with keys and a manipulator (playback operator) position; idol groups of many members sing and dance across wide stages and long runways over tracks; bands keep a classic rock layout with sequenced extras."
    }
  ],
  "dynamics": [
    {
      "text": "Recorded J-pop has small micro-dynamics and moderate macro-dynamics: the arrangement thins in the ochi-sabi and swells into the last chorus, but the master itself is heavily limited. Live, preserve the section contrast (a 4–8 dB lift from ochi-sabi to final chorus) and ride the lead vocal constantly, since idol singers’ levels change with choreography and breath. Ballads with piano and strings need real dynamic room; do not run them at the same level as the dance numbers."
    }
  ],
  "balance": [
    {
      "text": "Hierarchy, loudest to quietest: lead vocal (clearly on top, more than in rock), kick and snare, bass, main synth/guitar hook, strings and pads, backing vocals and harmonies, cymbals and effects. Low end is tight rather than huge: kick owns 50–80 Hz punch, bass owns 80–250 Hz and its melodic mids; sub should support, not dominate. Keep the top bright and clear—J-pop mixes typically carry more 3–12 kHz energy than Western rock. Vocal, kick, snare and bass in the centre; double rhythm guitars hard left/right; strings and pads wide; synth arps panned or stereo. For idol groups, keep all members near centre with slight spreads so the unison sounds like one voice."
    }
  ],
  "eq": {
    "rows": [
      {
        "source": "Kick",
        "cut": "HPF 30–40 Hz; −3–5 dB at 300–500 Hz",
        "boost": "+2–3 dB at 60–80 Hz; +2–4 dB at 3–5 kHz",
        "notes": "Short, punchy kick suits fast tempos"
      },
      {
        "source": "Snare",
        "cut": "HPF 80–100 Hz; notch ring 500 Hz–1 kHz",
        "boost": "+2 dB at 180–220 Hz; +2–3 dB at 5–8 kHz",
        "notes": "Bright, crisp snare is the norm; samples often layered"
      },
      {
        "source": "Bass",
        "cut": "HPF 35–40 Hz; −2–3 dB at 200–300 Hz",
        "boost": "+2 dB at 80–100 Hz; +2–3 dB at 800 Hz–2 kHz",
        "notes": "Mids let busy lines and slap read at speed"
      },
      {
        "source": "Distorted guitars",
        "cut": "HPF 90–120 Hz; LPF 10–12 kHz; −2–3 dB at 2.5–4 kHz if fighting vocal",
        "boost": "+1–2 dB at 1–1.5 kHz",
        "notes": "Dynamic EQ ducking 2–4 kHz under vocal helps dense J-rock"
      },
      {
        "source": "Clean cutting guitar",
        "cut": "HPF 150–200 Hz",
        "boost": "+2 dB at 3–5 kHz",
        "notes": "Keep thin and percussive"
      },
      {
        "source": "Piano",
        "cut": "HPF 60–80 Hz; −2 dB at 250–400 Hz",
        "boost": "+1–2 dB at 4–6 kHz",
        "notes": "Ballad piano can be fuller; cut more in band songs"
      },
      {
        "source": "Synth pads / supersaws",
        "cut": "HPF 150–250 Hz; −2–3 dB at 2–4 kHz",
        "boost": "Shelf +1–2 dB at 10 kHz",
        "notes": "Carve space for the vocal’s presence band"
      },
      {
        "source": "Strings (track or live)",
        "cut": "HPF 100–150 Hz; −2 dB at 300–500 Hz",
        "boost": "+1–2 dB at 6–10 kHz",
        "notes": "Live strings need high-mid lift to cut through band"
      },
      {
        "source": "Lead vocal",
        "cut": "HPF 90–120 Hz (higher for light female voices); −2–3 dB at 250–400 Hz",
        "boost": "+2–4 dB at 3–5 kHz; +2–3 dB shelf at 10–12 kHz",
        "notes": "Bright and forward; tame 6–9 kHz sibilance before adding air"
      },
      {
        "source": "Idol group vocals",
        "cut": "HPF 120–150 Hz; −2 dB at 300 Hz",
        "boost": "+2 dB at 4 kHz",
        "notes": "Match tone across members’ headset mics"
      }
    ],
    "notes": []
  },
  "compression": {
    "rows": [
      {
        "source": "Lead vocal (stage 1)",
        "use": "Yes",
        "ratio": "4:1–6:1",
        "attackRelease": "1–5 ms / 50–80 ms",
        "gainReduction": "3–6 dB",
        "notes": "Catches peaks from belted choruses"
      },
      {
        "source": "Lead vocal (stage 2)",
        "use": "Yes",
        "ratio": "2:1–3:1",
        "attackRelease": "10–20 ms / auto",
        "gainReduction": "2–4 dB",
        "notes": "Sustains the “always on top” level"
      },
      {
        "source": "Idol member vocals",
        "use": "Yes",
        "ratio": "4:1",
        "attackRelease": "3–5 ms / 60 ms",
        "gainReduction": "4–8 dB",
        "notes": "Heavy, as breath and movement vary level"
      },
      {
        "source": "Kick / snare",
        "use": "Yes",
        "ratio": "4:1",
        "attackRelease": "10–25 ms / 50–80 ms",
        "gainReduction": "3–5 dB",
        "notes": "Keep transient clicks for fast grooves"
      },
      {
        "source": "Bass",
        "use": "Yes",
        "ratio": "4:1",
        "attackRelease": "10–20 ms / 80–100 ms",
        "gainReduction": "4–6 dB",
        "notes": "Even out slap peaks"
      },
      {
        "source": "Drum bus",
        "use": "Yes",
        "ratio": "2:1–4:1",
        "attackRelease": "10–30 ms / fast",
        "gainReduction": "2–4 dB",
        "notes": "Parallel blend 20–30% for energy"
      },
      {
        "source": "Mix bus",
        "use": "Yes",
        "ratio": "2:1",
        "attackRelease": "10–30 ms / auto",
        "gainReduction": "1–3 dB",
        "notes": "Studio mixes often hit a limiter for client approvals"
      }
    ],
    "notes": [
      {
        "text": "De-ess lead vocals at 6–9 kHz for 3–6 dB; Japanese “s,” “sh” and “ts” sounds pile up in fast phrases. Multiband or dynamic EQ on the vocal at 200–400 Hz keeps proximity-heavy headset and handheld mics clean. Gate toms live; use a dynamic EQ or sidechain to dip pads and guitars 1–3 dB in the 2–5 kHz band when the vocal is present. Mastering often applies 6–10 dB of limiting—avoid baking that into the mix."
      }
    ]
  },
  "fx": {
    "rows": [
      {
        "effect": "Plate reverb",
        "appliedTo": "Lead vocal",
        "setting": "1.4–2.2 s decay, 30–60 ms pre-delay, HPF 300 Hz",
        "amount": "Moderate; generous on ballads"
      },
      {
        "effect": "Hall reverb",
        "appliedTo": "Ballads, strings, piano",
        "setting": "2.0–2.8 s decay, 40–80 ms pre-delay",
        "amount": "Moderate–heavy"
      },
      {
        "effect": "Tempo delay",
        "appliedTo": "Lead vocal phrase ends",
        "setting": "1/8 or dotted 1/8, 20–30% feedback, filtered 300 Hz–5 kHz",
        "amount": "Subtle–moderate, automated"
      },
      {
        "effect": "Short room",
        "appliedTo": "Drums, group vocals",
        "setting": "0.6–1.0 s",
        "amount": "Subtle"
      },
      {
        "effect": "Pitch correction",
        "appliedTo": "Lead and idol vocals",
        "setting": "Natural to fast retune; hard tune as an effect",
        "amount": "Transparent by default; obvious in technopop"
      },
      {
        "effect": "Chorus / doubler",
        "appliedTo": "Backing vocals, clean guitars, synths",
        "setting": "10–25 ms, slow rate",
        "amount": "Subtle"
      },
      {
        "effect": "Vocoder / formant",
        "appliedTo": "Technopop leads",
        "setting": "As the artistic sound",
        "amount": "Heavy where part of the style"
      }
    ],
    "notes": [
      {
        "text": "Live, rely on one plate, one hall and one tap-tempo delay; dome and arena reflections add their own long tail, so pull reverb returns down 3–6 dB versus a hall."
      }
    ]
  },
  "vocals": [
    {
      "text": "The lead vocal sits clearly above the band—roughly 3–5 dB louder in perceived level than it would in a rock mix—with every mora intelligible. Tone is bright and clean; many leads are light, high voices, so high-pass more and watch 2–4 kHz harshness. Pitch correction is expected and usually tight but natural on ballads; hard-tuned vocals are an aesthetic choice in technopop (Perfume) and some idol material. Chorus vocals are doubled and stacked with harmony parts; idol songs alternate solo lines and unison, so balance members to equal loudness and ride solo lines up 1–2 dB. Live, solo artists use high-end handhelds (often condenser or premium dynamic capsules); dancing idols use headset or handheld wireless, sometimes over a backing vocal track—keep the live mic audibly on top so it reads as live. Anison singers belt hard; leave 6–10 dB of headroom on the input."
    }
  ],
  "loudness": [
    {
      "label": "Live:",
      "text": "Hall shows typically run 92–98 dBA LAeq-15 at FOH; arenas and domes 96–102 dBA with C-weighted levels around 110–118 dBC and peaks to about 110 dBA. Tokyo Dome reaches 150–160 m to the upper tier, with notorious reflections; recent tours use long line arrays, flown subs and immersive systems rather than delay towers. Outdoor festivals near Tokyo Bay and residential Chiba face strict neighbourhood noise management. Idol crowds often include young fans—keep levels moderate and encourage ear protection. By common hearing-safety guidance, 100 dBA is safe for only about 15 minutes."
    },
    {
      "label": "Studio / streaming:",
      "text": "Japanese CD masters are among the loudest anywhere, often −8 to −5 LUFS-I with very small PLR. Streaming normalizes to about −14 LUFS (−11 on some services’ loud setting), so extreme loudness just costs punch; keep true peak at −1 dBTP, or −2 dBTP for masters louder than −14. A loudness range of 4–6 LU is typical. Deliver a separate TV-size edit for anime use, which Japanese broadcasters normalize to −24 LKFS."
    }
  ],
  "liveStudio": {
    "rows": [
      {
        "area": "Vocal",
        "live": "Ride every line; separate channels per idol member, wireless headsets with heavy compression",
        "studio": "Comped, tuned and stacked; detailed rides and harmonies"
      },
      {
        "area": "Playback",
        "live": "Multitrack stems from manipulator; strings, synths and BV tracks to match the record",
        "studio": "All parts are the arrangement—carve with EQ and automation"
      },
      {
        "area": "Density",
        "live": "Thin pads and doubled guitars 2–4 dB so vocal survives the room",
        "studio": "Dense layering is the signature sound"
      },
      {
        "area": "Low end",
        "live": "Tight subs; domes and arenas build up 100–300 Hz",
        "studio": "Controlled, punchy, less sub than Western pop"
      },
      {
        "area": "Effects",
        "live": "One plate, one hall, tap delay; less reverb in reflective arenas",
        "studio": "Many automated sends; hard tune or vocoder where stylistic"
      },
      {
        "area": "Space",
        "live": "Runways put singers ahead of PA—watch feedback; immersive systems increasingly common",
        "studio": "Wide stereo strings and synths"
      },
      {
        "area": "Loudness",
        "live": "92–102 dBA by venue size",
        "studio": "−8 to −5 LUFS-I CD masters; streaming at −14"
      }
    ],
    "notes": []
  },
  "notes": [
    {
      "text": "Build the mix around the vocal first; if the lyric is not clear, the mix has failed for this audience.",
      "bullet": true
    },
    {
      "text": "Get the stem split from the manipulator in advance (drums, bass, synths, strings, BVs separately) so you can fight density live.",
      "bullet": true
    },
    {
      "text": "Do not let supersaw pads and distorted guitars occupy 2–5 kHz with the vocal—use dynamic EQ or sidechain ducking.",
      "bullet": true
    },
    {
      "text": "Leave space in intros and instrumental breaks: idol fans shout calls and mixes there, and that crowd energy is part of the show.",
      "bullet": true
    },
    {
      "text": "Watch runway positions for feedback; ring out the extended stage, not just the main stage.",
      "bullet": true
    },
    {
      "text": "Don’t mix the full song to −5 LUFS before mastering; leave headroom and let the mastering stage decide the loudness.",
      "bullet": true
    }
  ],
  "references": [
    "Hikaru Utada, “First Love”, 1999",
    "Morning Musume, “Love Machine”, 1999",
    "Perfume, “Polyrhythm”, 2007",
    "Yoko Takahashi, “A Cruel Angel’s Thesis”, 1995",
    "LiSA, “Gurenge”, 2019",
    "Official Hige Dandism, “Pretender”, 2019",
    "Kenshi Yonezu, “Kick Back”, 2022",
    "YOASOBI, “Idol”, 2023"
  ],
  "empty": []
};
