/**
 * Mixing guide 25 — C-pop / Mandopop. GENERATED by scripts/mixing-guides/convert.py
 * from the owner's guide (assets/Mixing-Guides-50-Styles, read only). Edit the
 * conversion (scripts/mixing-guides/edits.py), not this file.
 */
import type { MixingGuide } from '../types';

export const GUIDE: MixingGuide = {
  "id": "c-pop-mandopop",
  "num": 25,
  "title": "C-pop / Mandopop",
  "expects": "At concerts, fans wave synchronized lightsticks, sing whole choruses back (the “big chorus,” 大合唱) and judge live vocals harshly; post-show complaints often say the singer could not be heard.",
  "glance": {
    "origin": "Shanghai shidaiqu of the 1920s–40s; moved to Hong Kong after 1949; Taiwan became the Mandopop hub in the 1970s–90s; Cantopop grew in Hong Kong from the mid-1970s; today mainland China, Taiwan, Hong Kong, Singapore and Malaysia",
    "tempo": "Ballads 60–80 BPM (the core of the repertoire); mid-tempo pop/R&B 85–110; dance and idol pop 110–128",
    "ensemble": "Solo singer with 5–8 piece band (drums, bass, 2 guitars, 2 keys) plus 2–4 backing vocalists; arena shows add strings and 1–3 Chinese instrumentalists; TV and smaller shows run on backing tracks",
    "priority": "A clear, intimate, fully intelligible lead vocal; every lyric must be understood",
    "liveSpl": "94–100 dBA LAeq-15 for arenas and stadiums (ballad sections lower, 88–94); about 110–118 dBC",
    "studioLoudness": "Ballads commonly −11 to −9 LUFS-I, dance and idol pop −8 to −6; streaming normalizes to about −14"
  },
  "purpose": [
    {
      "text": "C-pop is above all a singer’s and a lyricist’s music. Its emotional center is the love ballad (qingge): songs of longing, regret and nostalgia that listeners sing in KTV rooms, in the car and at concerts. Teresa Teng’s soft, close-mic’d delivery set a template of intimacy that still defines the genre, and lyricists such as Vincent Fang and Lin Xi are stars in their own right. Mandarin and Cantonese are tonal, so a muffled consonant or buried vowel can change meaning, not just tone."
    },
    {
      "text": "At concerts, fans wave synchronized lightsticks, sing whole choruses back (the “big chorus,” 大合唱) and judge live vocals harshly; post-show complaints often say the singer could not be heard. The audience will say “that sounded wrong” if the vocal is buried, sibilant, or swimming in reverb; if the ballad sections are loud and harsh; or if a famous intro (a piano figure, an erhu line) is missing or thin."
    }
  ],
  "instruments": [
    {
      "label": "Piano:",
      "text": "the backbone of ballads, often solo for the first verse; a grand miked in stereo or a high-quality sampled piano.",
      "bullet": true
    },
    {
      "label": "Strings:",
      "text": "real section or samples; swelling pads and countermelodies in choruses and final key changes.",
      "bullet": true
    },
    {
      "label": "Rhythm section and synths:",
      "text": "acoustic kit live, programmed or hybrid in the studio; electric or synth/808 bass; acoustic guitar in verses, electric in choruses (bands like Mayday push guitars harder); synths dominate idol and dance tracks.",
      "bullet": true
    },
    {
      "label": "Chinese instruments (zhongguofeng, “China wind” style):",
      "text": "erhu (bowed, voice-like, 400 Hz–3 kHz core), guzheng (plucked zither with long resonance and glissandi), pipa (bright plucked lute with sharp attack), dizi and xiao (bamboo flutes, dizi with its buzzing membrane), yangqin (hammered dulcimer), sheng (mouth organ), suona (very loud double reed), plus gongs, woodblocks and Chinese cymbals.",
      "bullet": true
    },
    {
      "label": "Playback:",
      "text": "common. TV and award shows often use full tracks; arena tours run strings, choirs and ethnic-instrument stems from timecode.",
      "bullet": true
    }
  ],
  "arrangement": [
    {
      "text": "The singer works a catwalk or B-stage in front of the PA; band upstage on risers, featured erhu or guzheng player on a riser. Arrangements build: intro hook (piano or Chinese instrument), sparse piano verse, pre-chorus adding bass and strings, full chorus, drop-out bridge, then often a half- or whole-step key change into a final double chorus. Zhongguofeng tracks pair pentatonic melodies and traditional timbres with R&B or hip-hop beats. Drums and bass carry rhythm, piano and strings harmony, and the voice the melody, with Chinese instruments answering between vocal phrases."
    }
  ],
  "dynamics": [
    {
      "text": "Ballads have wide macro-dynamics: a piano-and-voice verse can sit 10–14 dB below the final chorus. That contrast is the emotional arc and must be preserved, but the soft verse still has to be heard over crowd noise and, in arenas, over the audience singing. Ride by section live rather than compressing flat; in the studio, automate so whispered phrases stay intelligible and the climax opens up without shrillness. Dance and idol tracks are denser and more controlled, closer to K-pop in dynamics."
    }
  ],
  "balance": [
    {
      "text": "Loudest to quietest: lead vocal (often 2–4 dB more forward than in rock), piano or main harmonic instrument, featured Chinese instrument in its spots, kick and bass, strings, drums and guitars, backing vocals, effects. In ballads the kick is soft and rounded; bass provides warmth from 50–150 Hz without boom. In dance tracks the 808 or synth bass carries the sub (35–60 Hz) and the kick sits on top at 60–90 Hz. Lead vocal, kick, snare and bass are centered; piano is a wide but not hard-panned stereo image; strings wide; erhu or dizi slightly off-center or centered when it carries a melody; guzheng and yangqin in stereo with modest width. Backing vocals spread wide and tucked under the lead."
    }
  ],
  "eq": {
    "rows": [
      {
        "source": "Lead vocal",
        "cut": "HPF 80–100 Hz (male), 100–140 Hz (female); −2–3 dB at 250–400 Hz",
        "boost": "+1–3 dB at 2.5–4 kHz (clarity); +1–2 dB shelf at 10–12 kHz (air)",
        "notes": "Watch 5–8 kHz: Mandarin retroflexes (zh, ch, sh) and Cantonese s and c add sibilance"
      },
      {
        "source": "Piano",
        "cut": "HPF 40–60 Hz; −2–3 dB at 200–400 Hz",
        "boost": "+1–2 dB at 3–5 kHz; gentle shelf at 10 kHz",
        "notes": "Dip 2–4 kHz slightly if it competes with the vocal"
      },
      {
        "source": "Erhu",
        "cut": "HPF 150–200 Hz; −2–4 dB at 2.5–3.5 kHz if nasal or scratchy",
        "boost": "+1–2 dB at 600 Hz–1 kHz (warmth/voice)",
        "notes": "Close mics pick up bow and snake-skin resonator noise; mic the soundbox"
      },
      {
        "source": "Guzheng",
        "cut": "HPF 50–70 Hz; −2–3 dB at 200–300 Hz (boom from body)",
        "boost": "+2 dB at 3–6 kHz (pluck); shelf at 10 kHz for shimmer",
        "notes": "Fullness comes from the soundholes under the body; long sustain fills space"
      },
      {
        "source": "Pipa",
        "cut": "HPF 100–120 Hz; −2–4 dB at 2–4 kHz if pick attack is spiky",
        "boost": "+1–2 dB at 400–800 Hz (body)",
        "notes": "Miking too close gives all pluck and no resonance; ~60 cm works in studio"
      },
      {
        "source": "Dizi / xiao",
        "cut": "HPF 200–300 Hz (dizi), 120–150 Hz (xiao); dip 3–5 kHz if the membrane buzz is harsh",
        "boost": "+1 dB at 8–10 kHz (breath)",
        "notes": "Dizi is very loud and piercing in its upper register; keep it out of the vocal band"
      },
      {
        "source": "Kick (ballad / dance)",
        "cut": "HPF 30–40 Hz; −3–5 dB at 300–500 Hz",
        "boost": "+2–3 dB at 60–80 Hz; +1–2 dB at 3–4 kHz",
        "notes": "Ballad kicks are soft; do not add aggressive click"
      },
      {
        "source": "Snare",
        "cut": "HPF 80–100 Hz; notch ring 400 Hz–1 kHz",
        "boost": "+2 dB at 180–220 Hz; +1–2 dB at 5–6 kHz",
        "notes": "Ballad snares are often brushed or soft; keep the body"
      },
      {
        "source": "Bass / 808",
        "cut": "HPF 30–35 Hz; −2 dB at 200–300 Hz",
        "boost": "+2 dB at 60–80 Hz; +1–2 dB at 700 Hz–1 kHz",
        "notes": "Sidechain lightly to kick in dance tracks"
      },
      {
        "source": "Strings",
        "cut": "HPF 80–120 Hz (violins 150 Hz); −2 dB at 2–4 kHz under the vocal",
        "boost": "Shelf +1–2 dB at 10 kHz",
        "notes": "Strings should support, not cover, the vocal’s presence band"
      }
    ],
    "notes": []
  },
  "compression": {
    "rows": [
      {
        "source": "Lead vocal (stage 1)",
        "use": "Yes",
        "ratio": "3:1–4:1",
        "attackRelease": "3–10 ms / 50–100 ms",
        "gainReduction": "2–4 dB on peaks",
        "notes": "Catch belts in the final chorus; leave whispered verses natural"
      },
      {
        "source": "Lead vocal (stage 2, opto)",
        "use": "Yes",
        "ratio": "~3:1",
        "attackRelease": "Program-dependent",
        "gainReduction": "2–3 dB",
        "notes": "Smooth, transparent; ballads need warmth not grab"
      },
      {
        "source": "Backing vocals",
        "use": "Yes",
        "ratio": "4:1",
        "attackRelease": "5–10 ms / 80 ms",
        "gainReduction": "4–6 dB",
        "notes": "Keep stacks even and behind the lead"
      },
      {
        "source": "Piano",
        "use": "Light",
        "ratio": "2:1",
        "attackRelease": "20–30 ms / auto",
        "gainReduction": "1–3 dB",
        "notes": "Too much kills the expressive touch in ballads"
      },
      {
        "source": "Erhu / dizi",
        "use": "Light",
        "ratio": "2:1–3:1",
        "attackRelease": "10–20 ms / 100 ms",
        "gainReduction": "2–3 dB",
        "notes": "Controls sudden swells; volume rides are better"
      },
      {
        "source": "Bass",
        "use": "Yes",
        "ratio": "4:1",
        "attackRelease": "10–20 ms / 100 ms",
        "gainReduction": "3–5 dB",
        "notes": "Even and warm"
      },
      {
        "source": "Drum bus",
        "use": "Yes",
        "ratio": "2:1–4:1",
        "attackRelease": "10–30 ms / auto",
        "gainReduction": "2–3 dB",
        "notes": "Gentler in ballads, more glue in dance tracks"
      },
      {
        "source": "Mix bus",
        "use": "Optional",
        "ratio": "1.5:1–2:1",
        "attackRelease": "30 ms / auto",
        "gainReduction": "1–2 dB",
        "notes": "Preserve section contrast"
      }
    ],
    "notes": [
      {
        "text": "De-essing is essential: start at 5–6 kHz for male singers and 6–8 kHz for female singers, 2–5 dB on the worst consonants, sometimes in two stages of 1–2 dB each. Gate toms live (hold 30–50 ms, release 150 ms); avoid gating Chinese instruments, whose decay is part of the sound."
      }
    ]
  },
  "fx": {
    "rows": [
      {
        "effect": "Plate reverb",
        "appliedTo": "Lead vocal (ballads)",
        "setting": "1.8–2.6 s decay, 40–80 ms pre-delay, HPF 250 Hz / LPF 7–8 kHz on return",
        "amount": "Moderate; more in choruses"
      },
      {
        "effect": "Hall reverb",
        "appliedTo": "Strings, piano, final chorus, guzheng",
        "setting": "2.2–3.0 s decay, 30–60 ms pre-delay",
        "amount": "Moderate–heavy on ballad climaxes"
      },
      {
        "effect": "Tempo delay",
        "appliedTo": "Lead vocal phrase ends",
        "setting": "1/4 or dotted 1/8, 15–25% feedback, filtered 300 Hz–5 kHz",
        "amount": "Subtle, automated throws"
      },
      {
        "effect": "Short room / ambience",
        "appliedTo": "Drums, Chinese instruments",
        "setting": "0.6–1.0 s decay",
        "amount": "Subtle; places dry close-miked instruments in a space"
      },
      {
        "effect": "Doubler / chorus",
        "appliedTo": "Backing vocal stacks, idol pop chorus",
        "setting": "10–20 ms, slight detune ±5–10 cents",
        "amount": "Subtle–moderate"
      },
      {
        "effect": "Long ambient reverb / shimmer",
        "appliedTo": "Dizi, xiao, erhu intro lines",
        "setting": "3–4 s decay",
        "amount": "Moderate; a classic “misty landscape” zhongguofeng texture"
      }
    ],
    "notes": [
      {
        "text": "Listeners raised on KTV echo accept more ballad reverb than Western pop; duck the vocal reverb 2–4 dB under active singing to keep words clear."
      }
    ]
  },
  "vocals": [
    {
      "text": "The lead vocal sits in front, clean and intimate, with the lyric always understandable. Tone is warm and smooth; avoid a harsh 3 kHz bump or brittle air, since the consonants already add high-mid energy. Pitch correction is standard in the studio but expected to be invisible on ballads; audible tuning is accepted only on dance, idol and R&B-flavored tracks. Doubles are sparing on ballad choruses (6–10 dB under) and heavy on idol pop. Backing harmonies swell on the last chorus, where ad-libs after the key change need headroom."
    },
    {
      "text": "Live, RF handhelds on catwalks in front of the PA need tight patterns, a firm HPF and notches around 250 Hz and 2–3 kHz. In bilingual Mandarin/Cantonese sets, adjust de-essing per song."
    }
  ],
  "loudness": [
    {
      "label": "Live:",
      "text": "Arena and stadium C-pop typically runs 94–100 dBA LAeq-15 at FOH, with ballad sections 88–94 dBA and up-tempo encores to about 102 dBA, around 110–118 dBC. Some tours run loud and bass-rich, but sub should never mask the vocal. Fans singing famous choruses can rival the PA; pull the band slightly rather than push the vocal into feedback. In Hong Kong, outdoor events are limited to 10 dBA above background at nearby residences (LAeq-15) before 11 p.m. and must be inaudible after; cardioid subs help. By common hearing-safety guidance, 100 dBA is safe for about 15 minutes."
    },
    {
      "label": "Studio / streaming:",
      "text": "Ballads master around −11 to −9 LUFS-I, which at −2 dBTP allows a PLR of about 7–9 dB; dance and idol tracks −8 to −6 LUFS-I. Aim for −1 dBTP, or −2 dBTP when mastering louder than −14 LUFS, as streaming services advise."
    }
  ],
  "liveStudio": {
    "rows": [
      {
        "area": "Vocal",
        "live": "RF handheld on catwalk in front of PA; feedback is the main limit; ride against crowd sing-alongs",
        "studio": "Close condenser, detailed comping, invisible tuning, line-by-line rides"
      },
      {
        "area": "Chinese instruments",
        "live": "Pickups or clip-on condensers for isolation; often playback stems",
        "studio": "Large-diaphragm or small condensers at 30–60 cm; under the guzheng, at the erhu soundbox"
      },
      {
        "area": "Low end",
        "live": "Cardioid sub arrays and noise limits; avoid bass masking soft ballads",
        "studio": "Precise kick/bass/808 balance per song style"
      },
      {
        "area": "Effects",
        "live": "One plate and one hall, tapped delay, snapshot per song",
        "studio": "Multiple automated reverbs and throws"
      },
      {
        "area": "Dynamics",
        "live": "Mix by section; leave headroom for key changes and encores",
        "studio": "Fader automation sculpts the ballad arc"
      },
      {
        "area": "Playback",
        "live": "Timecoded strings, choirs and ethnic stems; check blend with live band",
        "studio": "Real sessions or sample libraries mixed as one space"
      },
      {
        "area": "Loudness",
        "live": "94–100 dBA LAeq-15",
        "studio": "−11 to −6 LUFS-I by style, −1 dBTP"
      }
    ],
    "notes": []
  },
  "notes": [
    {
      "text": "Build the mix around the vocal: set the voice first, then fit the band around it.",
      "bullet": true
    },
    {
      "text": "Do not use a bright English-language vocal chain unchanged; Mandarin and Cantonese sibilance sits differently and can become fatiguing.",
      "bullet": true
    },
    {
      "text": "Respect the quiet verse; don’t bring it up to chorus level with compression.",
      "bullet": true
    },
    {
      "text": "Treat a featured erhu or dizi like a second vocalist, and don’t mic plucked Chinese instruments too close.",
      "bullet": true
    },
    {
      "text": "Plan the key change: headroom, vocal ride, strings up.",
      "bullet": true
    },
    {
      "text": "Live, check the vocal from the far seats and delay zones; “couldn’t hear the singer” is the most common complaint.",
      "bullet": true
    }
  ],
  "references": [
    "Teresa Teng, “The Moon Represents My Heart”, 1977",
    "Jacky Cheung, “Kiss Goodbye”, 1993",
    "Faye Wong, “Red Bean”, 1998",
    "Jay Chou, “Blue and White Porcelain”, 2007",
    "Eason Chan, “Ten Years”, 2003",
    "Mayday, “Stubborn”, 2004",
    "JJ Lin, “Practice Love”, 2013",
    "G.E.M., “Light Years Away”, 2016"
  ],
  "empty": []
};
