/**
 * Mixing guide 27 — Punk / Pop-Punk. GENERATED by scripts/mixing-guides/convert.py
 * from the owner's guide (assets/Mixing-Guides-50-Styles, read only). Edit the
 * conversion (scripts/mixing-guides/edits.py), not this file.
 */
import type { MixingGuide } from '../types';

export const GUIDE: MixingGuide = {
  "id": "punk-pop-punk",
  "num": 27,
  "title": "Punk / Pop-Punk",
  "expects": "They expect relentless drive, a guitar wall, a cracking snare and a singer they can shout along with.",
  "glance": {
    "origin": "New York and London, 1975–80 (Ramones, Sex Pistols, The Clash); US hardcore from 1979–81 (DC, Southern California); pop-punk from the Bay Area and SoCal scenes into the 1990s mainstream; emo-pop and the Warped Tour era 1995–2010s",
    "tempo": "140–200 BPM (classic punk 150–180; skate punk and hardcore 180–240+; pop-punk choruses often 160–200 with half-time breakdowns)",
    "ensemble": "3–5 piece: drums, bass, 1–2 electric guitars, lead vocal, with band members singing backing and gang vocals",
    "priority": "A tight, driving drums-guitars wall with the lead vocal and its hooks always intelligible on top",
    "liveSpl": "98–104 dBA Leq (LAeq-15 min) in clubs; roughly 112–122 dBC; common safe-listening guidance and many festivals cap at 100 dBA LAeq-15",
    "studioLoudness": "Masters commonly −9 to −6 LUFS-I (1990s CD-era records around −10 to −8); streaming normalizes to about −14"
  },
  "purpose": [
    {
      "text": "Punk is music for release, defiance and belonging. It began as a mid-1970s DIY reaction against bloated rock; hardcore made it faster and all-ages, while pop-punk and emo-pop added big melodic choruses about suburban life and heartbreak. The audience does not stand and listen: they sing every word, crowd-surf, stage-dive and circle-pit. They expect relentless drive, a guitar wall, a cracking snare and a singer they can shout along with. “That sounded wrong” means a vocal lost under guitars, fizzy or thin guitars, a soft or boomy kick that blurs at 190 BPM, or—at the pop-punk end—a polished mix that has lost its aggression. Punk forgives sloppiness; it does not forgive lack of energy."
    }
  ],
  "instruments": [
    {
      "label": "Drums:",
      "text": "simple acoustic kit. Defining patterns: the fast “skate” beat (snare on every upbeat, kick doubles), hardcore’s D-beat, sloshy open hats, and pop-punk half-time breakdowns.",
      "bullet": true
    },
    {
      "label": "Bass:",
      "text": "electric bass played with a pick, often driven through an overdriven amp or an amp-simulator DI pedal; it doubles guitar roots and supplies grind as much as low end.",
      "bullet": true
    },
    {
      "label": "Electric guitars:",
      "text": "humbucker or single-coil guitars into crunchy British-style amps with medium (not metal) gain, often tuned down a half step. Power chords, palm-muted verses and open choruses.",
      "bullet": true
    },
    {
      "label": "Lead vocal and gang vocals:",
      "text": "shouted, sung or nasal-melodic; the whole band often joins on “whoa-oh” hooks.",
      "bullet": true
    },
    {
      "label": "Extras:",
      "text": "occasional keys or strings on pop-punk records; arena acts run playback. Classic punk and DIY shows use none.",
      "bullet": true
    }
  ],
  "arrangement": [
    {
      "text": "Stage layout is standard rock: drums center upstage on a riser in bigger rooms, bass and guitars to either side, singer front center (often also the guitarist or bassist). Arrangements are compact: intro riff, verse (palm-muted, hats closed), pre-chorus build, chorus with open chords and crashes, often a bridge or breakdown, then a double chorus. Guitar parts in modern pop-punk are often interlocking or complementary between two players rather than identical."
    }
  ],
  "dynamics": [
    {
      "text": "Macro-dynamics are narrow: most songs run near full tilt, with contrast created by palm-muting, a guitar dropping out, a half-time breakdown or a quiet intro. Expect perhaps 3–6 dB between verse and chorus. Micro-dynamics on drums are wide (hard-hitting players with fast fills), so control peaks while keeping the snare crack. Preserve the arrangement drops—a stop before the last chorus is the genre’s drama—and use automation (chorus up 1 dB, gang vocals up) instead of more limiting; over-squashed mixes at 200 BPM lose their pulse."
    }
  ],
  "balance": [
    {
      "text": "Hierarchy, loudest to quietest: lead vocal and snare, guitars (as a combined wall), kick, bass, gang/backing vocals, toms, overheads, room and effects. Kick and bass: at fast tempos the kick must be short and punchy (attack around 2–5 kHz, thump near 60–100 Hz) so each hit is distinct; the bass owns the sustained 80–250 Hz region and the midrange grind around 800 Hz–1.5 kHz that lets it be heard under guitars. Avoid long, boomy kicks that smear double-time patterns. Kick, snare, bass and lead vocal sit center. Double-tracked rhythm guitars pan hard left and right; in two-guitar bands each player takes a side. Gang vocals spread wide, harmonies split left and right."
    }
  ],
  "eq": {
    "rows": [
      {
        "source": "Kick",
        "cut": "HPF 35–45 Hz; −4 to −6 dB at 300–450 Hz (box)",
        "boost": "+2–4 dB at 70–100 Hz; +3–5 dB at 2.5–5 kHz (beater)",
        "notes": "Keep it tight; a sample blended under the close mic is common in studio"
      },
      {
        "source": "Snare",
        "cut": "HPF 80–100 Hz; narrow −3 dB at ring (often 500 Hz–1 kHz)",
        "boost": "+2–3 dB at 180–250 Hz (body); +2–4 dB at 2–4 kHz (crack); shelf +2 dB at 8–10 kHz",
        "notes": "Bottom mic for wire snap, flipped polarity, tucked under"
      },
      {
        "source": "Toms",
        "cut": "HPF 60–80 Hz; −3 dB at 250–400 Hz",
        "boost": "+2–3 dB at 90–130 Hz (floor); +2–3 dB at 3–4 kHz",
        "notes": "Gate live; fills are fast so use short hold"
      },
      {
        "source": "Overheads / hats",
        "cut": "HPF 200–400 Hz; dip 2–4 kHz if harsh; LPF 15 kHz",
        "boost": "Slight +1–2 dB at 10–12 kHz",
        "notes": "Open-hat wash builds quickly at fast tempos—keep cymbals controlled"
      },
      {
        "source": "Bass",
        "cut": "HPF 35–40 Hz; −2–3 dB at 200–300 Hz if muddy",
        "boost": "+1.5–3 dB at 60–80 Hz; +2–4 dB at 800 Hz–1.5 kHz (grind); +2 dB at 2–3 kHz (pick)",
        "notes": "Blend DI, amp mic and a distortion channel; push mids in choruses"
      },
      {
        "source": "Rhythm guitars",
        "cut": "HPF 80–110 Hz; LPF 10–13 kHz; −2–3 dB at 200–350 Hz",
        "boost": "+1–3 dB at 500 Hz–1 kHz (body) and 2–4 kHz (bite)",
        "notes": "Do not scoop mids; reduce amp gain before reaching for EQ if fizzy"
      },
      {
        "source": "Lead / hook guitar",
        "cut": "HPF 120–150 Hz; dip 6–8 kHz fizz",
        "boost": "+2 dB around 550–600 Hz and 4 kHz to cut through",
        "notes": "A different amp or pickup from the rhythm wall helps it speak"
      },
      {
        "source": "Lead vocal",
        "cut": "HPF 100–150 Hz; −2–3 dB at 200–400 Hz; notch harsh 2.5–4 kHz if shouting",
        "boost": "+2–3 dB at 2–5 kHz (presence); +1–2 dB shelf at 8–10 kHz",
        "notes": "Shouted vocals get harsh fast—use dynamic EQ on 3 kHz"
      },
      {
        "source": "Gang / backing vocals",
        "cut": "HPF 150–250 Hz; −3 dB at 300–500 Hz",
        "boost": "+1–2 dB at 3–5 kHz",
        "notes": "Thinner than the lead so they sit behind it"
      }
    ],
    "notes": []
  },
  "compression": {
    "rows": [
      {
        "source": "Lead vocal (stage 1, FET)",
        "use": "Yes",
        "ratio": "4:1–8:1",
        "attackRelease": "1–3 ms / 50–80 ms",
        "gainReduction": "4–8 dB on peaks",
        "notes": "Shouts jump 10 dB or more; catch them hard"
      },
      {
        "source": "Lead vocal (stage 2, opto)",
        "use": "Yes",
        "ratio": "~3:1",
        "attackRelease": "Program-dependent",
        "gainReduction": "2–4 dB",
        "notes": "FET-into-optical chain is a live and studio standard"
      },
      {
        "source": "Kick",
        "use": "Yes",
        "ratio": "4:1",
        "attackRelease": "15–30 ms / 40–60 ms",
        "gainReduction": "3–5 dB",
        "notes": "Fast release so it recovers between rapid hits"
      },
      {
        "source": "Snare",
        "use": "Yes",
        "ratio": "4:1",
        "attackRelease": "5–20 ms / 50–80 ms",
        "gainReduction": "3–6 dB",
        "notes": "Plus parallel squash for weight"
      },
      {
        "source": "Bass",
        "use": "Yes",
        "ratio": "4:1–6:1",
        "attackRelease": "5–15 ms / 80–120 ms",
        "gainReduction": "5–8 dB",
        "notes": "Pick attack is spiky; keep it a steady floor"
      },
      {
        "source": "Rhythm guitars",
        "use": "Light/none",
        "ratio": "2:1",
        "attackRelease": "20–30 ms / auto",
        "gainReduction": "0–2 dB",
        "notes": "Driven amps are already compressed"
      },
      {
        "source": "Drum bus / parallel",
        "use": "Yes",
        "ratio": "4:1 (bus) / 10:1+ (parallel)",
        "attackRelease": "10–30 ms / fast",
        "gainReduction": "2–4 dB / 10–15 dB",
        "notes": "Blend parallel 20–40% for size without losing transients"
      },
      {
        "source": "Mix bus",
        "use": "Optional",
        "ratio": "2:1",
        "attackRelease": "30 ms / auto",
        "gainReduction": "1–3 dB",
        "notes": "Glue; leave the last loudness to mastering"
      }
    ],
    "notes": [
      {
        "text": "Gate toms live (hold 20–40 ms, release 80–150 ms) but avoid hard-gating the snare on dynamic drummers; a gentle expander or a notch for cymbal bleed works better. De-ess at 5–8 kHz for 2–4 dB. Sidechain a few dB of bass to the kick (or multiband duck around 60–100 Hz) to keep the low end clear at speed."
      }
    ]
  },
  "fx": {
    "rows": [
      {
        "effect": "Plate reverb",
        "appliedTo": "Snare, toms",
        "setting": "0.8–1.4 s decay, 10–30 ms pre-delay, HPF 300 Hz",
        "amount": "Subtle; mostly heard on stops and fills"
      },
      {
        "effect": "Short room / ambience",
        "appliedTo": "Whole kit",
        "setting": "0.4–0.8 s",
        "amount": "Subtle–moderate; adds “band in a room” feel"
      },
      {
        "effect": "Slap delay",
        "appliedTo": "Lead vocal",
        "setting": "90–130 ms, 0–10% feedback, HPF 250 Hz / LPF 4–5 kHz",
        "amount": "Subtle"
      },
      {
        "effect": "Tempo delay",
        "appliedTo": "Vocal throws, last words of lines",
        "setting": "1/4 or dotted 1/8 note, 15–25% feedback",
        "amount": "Automated throws only"
      },
      {
        "effect": "Vocal plate",
        "appliedTo": "Lead and harmonies (pop-punk)",
        "setting": "1.0–1.6 s decay, 30–60 ms pre-delay",
        "amount": "Subtle in verses, slightly more in choruses"
      },
      {
        "effect": "Pitch-shift widener",
        "appliedTo": "Backing / gang vocals",
        "setting": "±6–10 cents, 10–20 ms delay, split L/R",
        "amount": "Subtle"
      },
      {
        "effect": "Tape / saturation",
        "appliedTo": "Guitar bus, drum bus, bass",
        "setting": "1–3 dB drive, roll off top",
        "amount": "Moderate; adds grit and glue"
      }
    ],
    "notes": [
      {
        "text": "Classic punk runs dry—Dookie was first mixed with almost no reverb at the band’s request. Long tails turn fast songs to mush."
      }
    ]
  },
  "vocals": [
    {
      "text": "The vocal leads and must be understood, but it sits slightly into the guitar wall rather than floating above it, roughly 1–3 dB louder in perceived level. Tone is mid-forward and present; nasal, raw or shouted delivery is part of the style and should not be smoothed away. Pitch correction is rare in classic punk and hardcore but normal in modern pop-punk, where tuned doubles and pitch-edited harmonies are common. Choruses typically carry a double tucked 6–10 dB under the lead, stacked harmonies panned wide, and gang vocals compressed hard and pushed in the “whoa-oh” sections. Live, use a rugged dynamic with strong rejection. Notch bleed (around 250–500 Hz and 2–3 kHz) on band members’ backing mics and mute them between parts."
    }
  ],
  "loudness": [
    {
      "label": "Live:",
      "text": "Small clubs and DIY rooms often run 100–106 dBA at FOH simply because stage volume is already high—sometimes the PA carries little more than vocals and kick. Theaters and festivals sit at 98–103 dBA LAeq-15 and 112–122 dBC; a C-minus-A gap above about 20 dB means too much sub for this style, which needs punch more than deep bass. Peaks run 110–115 dBA. A widely used safe-listening standard for venues sets 100 dBA LAeq-15 as the average limit, along with earplug availability and quiet zones, and many festivals enforce similar caps. Audiences skew young; offer earplugs, and plan for stage divers."
    },
    {
      "label": "Studio / streaming:",
      "text": "Pop-punk and modern punk masters commonly land at −9 to −6 LUFS-I with true peak at −1 dBTP (−2 dBTP when mastering louder than −14 to avoid codec distortion). Most streaming services normalize to −14 LUFS (−11 on some loud settings), so extreme loudness gains nothing and costs punch. Aim for a PLR of roughly 8–10 dB and a loudness range of 3–6 LU; fast drums need transient headroom to stay distinct."
    }
  ],
  "liveStudio": {
    "rows": [
      {
        "area": "Guitars",
        "live": "Stage amps often louder than PA in clubs; mix little guitar, fix tone with mic choice and amp placement",
        "studio": "Double- or quad-tracked, panned hard, interlocking parts, layered amp tones"
      },
      {
        "area": "Vocals",
        "live": "Gain-before-feedback limits; dynamic mics, hard compression, minimal effects",
        "studio": "Comped takes, tuned doubles, stacked harmonies, gang vocal sessions"
      },
      {
        "area": "Drums",
        "live": "Gate toms, notch cymbal bleed, parallel compression on groups",
        "studio": "Sample reinforcement on kick/snare, tape-edited or aligned takes, room mics"
      },
      {
        "area": "Low end",
        "live": "HPF aggressively; keep sub moderate; tight kick over boom",
        "studio": "Sidechain or multiband ducking of bass under kick"
      },
      {
        "area": "Effects",
        "live": "One plate, one slap, tap-tempo delay",
        "studio": "Several reverbs and throws automated per section"
      },
      {
        "area": "Crowd",
        "live": "Plan for stage divers, mics knocked, quick changeovers",
        "studio": "No crowd; can add gang vocals and claps for “live” energy"
      },
      {
        "area": "Loudness",
        "live": "98–104 dBA Leq, venue or festival limits",
        "studio": "−9 to −6 LUFS-I, −1 dBTP"
      }
    ],
    "notes": []
  },
  "notes": [
    {
      "text": "In clubs, ask the guitarists to angle amps across the stage or lift them off the floor rather than just “turn down”; get the vocal working first, then add only what the room needs.",
      "bullet": true
    },
    {
      "text": "Keep guitar gain moderate: too much distortion sounds fizzy and small, while a strong midrange sounds big.",
      "bullet": true
    },
    {
      "text": "At fast tempos, make the kick short and clicky enough to articulate doubles; long, low kicks blur.",
      "bullet": true
    },
    {
      "text": "Don’t bury the vocal or the hooks—pop-punk audiences sing every word and notice when they can’t hear it.",
      "bullet": true
    },
    {
      "text": "Don’t over-polish classic punk; modern pop-punk, by contrast, expects tight drums and tuned vocals.",
      "bullet": true
    },
    {
      "text": "Warped-style festivals mean short changeovers: build a solid default scene and line-check fast.",
      "bullet": true
    }
  ],
  "references": [
    "Ramones, “Blitzkrieg Bop”, 1976",
    "The Clash, “London Calling”, 1979",
    "Minor Threat, “Minor Threat”, 1981",
    "Green Day, “Basket Case”, 1994",
    "Blink-182, “All the Small Things”, 1999",
    "Fall Out Boy, “Sugar, We’re Goin Down”, 2005",
    "Paramore, “Misery Business”, 2007",
    "Machine Gun Kelly, “Bloody Valentine”, 2020"
  ],
  "empty": []
};
