/**
 * Mixing guide 28 — Reggae. GENERATED by scripts/mixing-guides/convert.py
 * from the owner's guide (assets/Mixing-Guides-50-Styles, read only). Edit the
 * conversion (scripts/mixing-guides/edits.py), not this file.
 */
import type { MixingGuide } from '../types';

export const GUIDE: MixingGuide = {
  "id": "reggae",
  "num": 28,
  "title": "Reggae",
  "expects": "Audiences expect bass felt in the chest but never boomy, a relaxed groove behind the beat, and words they can follow.",
  "glance": {
    "origin": "Kingston, Jamaica, late 1960s (out of ska and rocksteady); roots and dub through the 1970s; lovers rock and UK sound-system culture in London from the mid-1970s",
    "tempo": "60–85 BPM half-time feel (120–170 counted in double time); lovers rock 65–80",
    "ensemble": "6–10 piece band: drums, bass, rhythm (skank) guitar, lead guitar, organ, piano/keys, percussion, 2–3 horns, lead vocal plus 2–3 harmony singers",
    "priority": "Drum and bass: a deep, round, melodic bass line locked to a dry one-drop kick, with the lead vocal clear on top",
    "liveSpl": "97–103 dBA LAeq-15 min; 118–128 dBC (sub-heavy, C-minus-A gap often 20–25 dB); sound-system dances run louder in the low end",
    "studioLoudness": "Roots/lovers masters commonly −12 to −9 LUFS-I (modern roots-revival pop crossover −9 to −7); streaming normalizes to about −14"
  },
  "purpose": [
    {
      "text": "Reggae is music for slow dancing, meditation and message. Roots reggae carries Rastafari faith and anti-oppression themes; lovers rock, born in 1970s London, is romance; dub makes the engineer the composer, stripping songs to drum and bass and rebuilding them with echo. Underneath all three is sound-system culture: selectors, operators and MCs playing to crowds who come to feel the bass. Hedley Jones’s 1940s Kingston systems already split the signal into low, mid and high bands for live tone shaping, and that “play the controls” attitude runs through the genre. Audiences expect bass felt in the chest but never boomy, a relaxed groove behind the beat, and words they can follow. They will say “that sounded wrong” if the bass is thin or flabby, the skank buried, the snare fat and rock-tuned, the drums pumping, or the mix harsh. At dances, crowd “forwards” (surges toward the booth, calls for a rewind) tell you a tune landed."
    }
  ],
  "instruments": [
    {
      "label": "Drums:",
      "text": "small kit, snare tuned very high (near timbale pitch), often played as cross-stick rim clicks; kick tight and short; hi-hat carries the variation; timbale and syn-drum fills.",
      "bullet": true
    },
    {
      "label": "Bass:",
      "text": "a passive four-string with flatwounds, plucked near the neck, tone rolled off. Aston “Family Man” Barrett used 18-inch and 4x15 cabinets for depth; synth bass appears in later UK styles.",
      "bullet": true
    },
    {
      "label": "Skank guitar:",
      "text": "clean, bright, short muted offbeat chops. Lead guitar: melodic, often doubling the bass line up an octave.",
      "bullet": true
    },
    {
      "label": "Organ (bubble) and piano:",
      "text": "Organ-style 16th-note shuffle around the offbeat; piano doubles the skank.",
      "bullet": true
    },
    {
      "label": "Horns:",
      "text": "trumpet, trombone, tenor sax in unison lines. Percussion: nyabinghi hand drums (funde, repeater), shakers.",
      "bullet": true
    },
    {
      "label": "Electronics:",
      "text": "in dub, the console, tape echo, spring reverb and filters are instruments; sound systems add sirens. Backing tracks are rare.",
      "bullet": true
    }
  ],
  "arrangement": [
    {
      "text": "Drums sit upstage center with bass beside the drummer (the riddim section), guitars and keys flanking, horns on a riser to one side and harmony singers stage left or right. The grid interlocks: kick and rim click drop on beat three (one drop), rockers puts the kick on one and three, steppers runs four on the floor. Skank guitar and piano hit the offbeats, organ bubbles around them, and the bass sings a melodic, gap-filled line that is the song’s hook. Horns take intros and answers. Arrangements are cyclical; changes come from dropping instruments out and in, a horn break, or a dub section stripped to drum and bass. Roots singles often carried a “version” (dub) on the B-side."
    }
  ],
  "dynamics": [
    {
      "text": "Macro-dynamics are modest: the groove is steady, and drama comes from mutes and effects throws, not loud choruses. Micro-dynamics matter greatly: the space between notes is the music, so preserve the rim click’s attack, the bass note’s decay and the silence after each skank. Keep the bass even, keep drum transients alive, and avoid bus compression that fills the gaps. Dub throws can jump 6–10 dB above the band, so leave headroom and limit the delay return."
    }
  ],
  "balance": [
    {
      "text": "Loudest to quietest: bass and lead vocal at roughly equal perceived weight, kick and rim click, skank and organ bubble, horns (up for their lines), lead guitar, piano, percussion, harmonies, effects returns. The bass owns 40–120 Hz with a round fundamental and little top; the kick is a tight 50–80 Hz thump with short decay and a touch of click, so it reads as a “drop,” not a second bass note. Don’t boost both at the same frequency; a 1–2 dB sidechain duck of bass from kick helps live. Vocal, kick, snare and bass center; skank and piano 20–40% opposite each other, organ off center, horns and harmonies spread. Classic Jamaican mixes were near-mono; don’t over-widen."
    }
  ],
  "eq": {
    "rows": [
      {
        "source": "Kick",
        "cut": "HPF 35–40 Hz; −4 to −6 dB at 250–400 Hz",
        "boost": "+2–3 dB at 60–70 Hz; +1–2 dB at 2.5–4 kHz",
        "notes": "Short and dry; gate or tight decay so it doesn’t blur into the bass"
      },
      {
        "source": "Snare / rim click",
        "cut": "HPF 120–180 Hz; −2–3 dB at 400–600 Hz",
        "boost": "+2–3 dB at 1.5–2.5 kHz (click); +1–2 dB shelf at 8 kHz",
        "notes": "High-tuned, little body"
      },
      {
        "source": "Hi-hat",
        "cut": "HPF 250–400 Hz; −2–3 dB at 8–10 kHz",
        "boost": "+1–2 dB at 5–6 kHz",
        "notes": "Carries the groove"
      },
      {
        "source": "Bass (DI + amp)",
        "cut": "HPF 30–35 Hz; LPF 2.5–4 kHz; −2–3 dB at 250 Hz if woolly",
        "boost": "+2–4 dB at 60–100 Hz; small lift at 600–800 Hz",
        "notes": "Round and dark; the upper-mid lift helps small speakers"
      },
      {
        "source": "Skank guitar",
        "cut": "HPF 150–250 Hz; −2 dB at 300–500 Hz",
        "boost": "+2–3 dB at 2–3 kHz; shelf +1–2 dB at 6–8 kHz",
        "notes": "Should “chick” through without level"
      },
      {
        "source": "Organ bubble",
        "cut": "HPF 120–150 Hz; −2–3 dB at 2–4 kHz if it masks the vocal",
        "boost": "+1–2 dB at 400 Hz–1 kHz",
        "notes": "Lives in the mids, felt more than heard"
      },
      {
        "source": "Piano",
        "cut": "HPF 100–150 Hz; −2 dB at 250–300 Hz",
        "boost": "+2 dB at 2–4 kHz",
        "notes": "Doubles the skank—give it a different tonal spot"
      },
      {
        "source": "Horns",
        "cut": "HPF 120–150 Hz; −2–3 dB at around 3 kHz if piercing",
        "boost": "+1–2 dB at 800 Hz–1.2 kHz (body)",
        "notes": "Bus the section and EQ it as one"
      },
      {
        "source": "Lead vocal",
        "cut": "HPF 80–100 Hz; −2 dB at 200–350 Hz",
        "boost": "+2–3 dB at 2–4 kHz; +1–2 dB shelf at 10–12 kHz",
        "notes": "Warm and forward; patois needs consonant clarity"
      },
      {
        "source": "Nyabinghi drums",
        "cut": "HPF 60–80 Hz; −2 dB at 300–500 Hz",
        "boost": "+2 dB at 100–200 Hz; +2 dB at 3–5 kHz",
        "notes": "Below the kit"
      }
    ],
    "notes": []
  },
  "compression": {
    "rows": [
      {
        "source": "Bass",
        "use": "Yes",
        "ratio": "4:1",
        "attackRelease": "20–30 ms / 150–300 ms",
        "gainReduction": "3–6 dB",
        "notes": "Even notes are vital; tape saturation or an opto helps roundness"
      },
      {
        "source": "Lead vocal",
        "use": "Yes",
        "ratio": "3:1",
        "attackRelease": "10–20 ms / auto",
        "gainReduction": "3–5 dB",
        "notes": "Slowish attack keeps phrasing natural"
      },
      {
        "source": "Kick",
        "use": "Light",
        "ratio": "3:1–4:1",
        "attackRelease": "20–30 ms / 50 ms",
        "gainReduction": "2–3 dB",
        "notes": "Mainly for consistency; gate for shortness"
      },
      {
        "source": "Snare / rim",
        "use": "Light",
        "ratio": "3:1",
        "attackRelease": "5–10 ms / 80 ms",
        "gainReduction": "2–3 dB",
        "notes": "Don’t squash the click"
      },
      {
        "source": "Skank guitar",
        "use": "Yes",
        "ratio": "4:1",
        "attackRelease": "5–10 ms / 50–80 ms",
        "gainReduction": "3–4 dB",
        "notes": "Keeps every chop equal"
      },
      {
        "source": "Horn bus",
        "use": "Light",
        "ratio": "2:1–3:1",
        "attackRelease": "15–30 ms / auto",
        "gainReduction": "2–3 dB",
        "notes": "Glue the section"
      },
      {
        "source": "Mix bus",
        "use": "Optional",
        "ratio": "1.5:1–2:1",
        "attackRelease": "30 ms / auto",
        "gainReduction": "1–2 dB",
        "notes": "Never pumping; reggae needs its gaps"
      }
    ],
    "notes": [
      {
        "text": "Gate kick and toms live (50–80 ms hold). De-ess at 5–8 kHz for 2–3 dB. Classic Jamaican and Black Ark records used tape as the compressor; a tape emulation on bass and drum bus is a good stand-in. Limit the master by 3 dB at most."
      }
    ]
  },
  "fx": {
    "rows": [
      {
        "effect": "Tape echo (classic tape-loop style)",
        "appliedTo": "Skank guitar, rim click, vocal throws",
        "setting": "Dotted-eighth or quarter note (about 350–700 ms at 75 BPM half-time), 25–45% feedback, HPF 200 Hz / LPF 4–5 kHz on return",
        "amount": "Moderate in songs; heavy in dub"
      },
      {
        "effect": "Feedback loop / runaway echo",
        "appliedTo": "Dub drops",
        "setting": "~0.7 s, feedback raised until 4–5 repeats; return fed back to itself; limiter on return",
        "amount": "Heavy, momentary"
      },
      {
        "effect": "Spring reverb",
        "appliedTo": "Snare, rim, horns, vocal",
        "setting": "1.5–2.5 s; “splash” sends for single hits",
        "amount": "Subtle in mix; dramatic as throws"
      },
      {
        "effect": "Plate / hall",
        "appliedTo": "Lead vocal, harmonies (lovers rock)",
        "setting": "1.4–2.2 s decay, 30–60 ms pre-delay",
        "amount": "Moderate"
      },
      {
        "effect": "Sweeping HPF / filter",
        "appliedTo": "Riddim, horns, skank",
        "setting": "80 Hz to 1–2 kHz and back over 1–4 bars",
        "amount": "Dub signature (Tubby, Scientist)"
      },
      {
        "effect": "Phaser / flanger",
        "appliedTo": "Hi-hat, guitar chops, delay return",
        "setting": "0.1–0.5 Hz rate",
        "amount": "Subtle–moderate"
      }
    ],
    "notes": [
      {
        "text": "Dub is timing: open a send for one hit, then close it; hit mutes just before the beat."
      }
    ]
  },
  "vocals": [
    {
      "text": "The lead vocal matches the bass in weight and sits slightly in front of the band, warm and intimate rather than bright. Patois deliveries need consonants clear at 2–4 kHz, so cut mud rather than adding top. Lovers rock wants a sweeter, soul-styled vocal with plate and lush harmonies; roots favors a drier sound with echo on line ends. Pitch correction, if any, should be invisible. Harmony singers (I-Threes style) are compressed together, panned wide and tucked 4–8 dB under the lead. Live, dynamic mics are standard; guest DJs/toasters often work closer and louder, so ride them and skip reverb wash on fast passages."
    }
  ],
  "loudness": [
    {
      "label": "Live:",
      "text": "Theater and festival reggae typically runs 97–103 dBA LAeq-15 at FOH with 118–128 dBC; a C-minus-A gap of 20–25 dB is normal here, and more usually means boom. Peaks 108–112 dBA. Sound-system dances push the sub harder, so cardioid or end-fire sub arrays (10–15 dB less rear energy) and trimming 40–63 Hz rather than the master help meet boundary limits of about 55–65 dBA. Reggae needs more sub than rock but less top; outdoors, a high-shelf trim after dark may help. By common hearing-safety guidance, 100 dBA is safe for only about 15 minutes, so offer earplugs."
    },
    {
      "label": "Studio / streaming:",
      "text": "Roots and lovers rock masters land around −12 to −9 LUFS-I, true peak −1 dBTP (−2 if louder than −14). Streaming normalizes to −14 LUFS, so loud masters gain nothing. Keep limiting light (PLR 10–13 dB) and distortion low so the bass stays round. Check on a sub, in a car and on a phone, where only the bass’s 600–800 Hz overtones carry the line."
    }
  ],
  "liveStudio": {
    "rows": [
      {
        "area": "Low end",
        "live": "Big stage bass rigs; manage room buildup, sub arrays, dB(C) limits",
        "studio": "Shape bass tone and kick decay precisely on full-range monitors"
      },
      {
        "area": "Drums",
        "live": "Gate kick and toms, HPF overheads hard",
        "studio": "Close mics plus spring; tape saturation for vintage tone"
      },
      {
        "area": "Skank & bubble",
        "live": "Easy to bury under stage wash—push presence, not level",
        "studio": "Pan opposite piano/organ; echo on skank for movement"
      },
      {
        "area": "Effects",
        "live": "Tap-tempo delay, live dub throws, limiter on return",
        "studio": "Printed dub passes, automated sends and mutes"
      },
      {
        "area": "Vocals",
        "live": "Feedback limits brightness; ride guest MCs",
        "studio": "Comping, stacked harmonies, line-end echoes"
      },
      {
        "area": "Dynamics",
        "live": "Mix by hand; keep the groove steady through the set",
        "studio": "Fader rides plus light bus glue"
      },
      {
        "area": "Loudness",
        "live": "97–103 dBA, 118–128 dBC",
        "studio": "−12 to −9 LUFS-I, −1 dBTP"
      }
    ],
    "notes": []
  },
  "notes": [
    {
      "text": "Build from drum and bass first; if those feel right alone, the song will.",
      "bullet": true
    },
    {
      "text": "Don’t mix reggae like rock: a fat, compressed snare and scooped mids destroy the style.",
      "bullet": true
    },
    {
      "text": "Leave silence: over-compression and long reverbs fill the gaps the groove depends on.",
      "bullet": true
    },
    {
      "text": "Make the skank cut with brightness and shortness, not fader level.",
      "bullet": true
    },
    {
      "text": "Learn the riddim’s form before dubbing it; throw and close effects in time.",
      "bullet": true
    },
    {
      "text": "Live, make the beat-three drop one tight event: align kick and bass, time-align subs.",
      "bullet": true
    },
    {
      "text": "If a sound-system crew runs the rig, ask how they set the tone controls.",
      "bullet": true
    }
  ],
  "references": [
    "Bob Marley & The Wailers, “Exodus”, 1977",
    "Burning Spear, “Marcus Garvey”, 1975",
    "The Congos, “Fisherman”, 1977 (Black Ark, Lee “Scratch” Perry)",
    "Augustus Pablo / King Tubby, “King Tubbys Meets Rockers Uptown”, 1976",
    "Scientist, “Scientist Rids the World of the Evil Curse of the Vampires”, 1981",
    "Janet Kay, “Silly Games”, 1979 (Dennis Bovell production)",
    "Steel Pulse, “Handsworth Revolution”, 1978",
    "Israel Vibration, “The Same Song”, 1978"
  ],
  "empty": []
};
