/**
 * Mixing guide 29 — Sertanejo. GENERATED by scripts/mixing-guides/convert.py
 * from the owner's guide (assets/Mixing-Guides-50-Styles, read only). Edit the
 * conversion (scripts/mixing-guides/edits.py), not this file.
 */
import type { MixingGuide } from '../types';

export const GUIDE: MixingGuide = {
  "id": "sertanejo",
  "num": 29,
  "title": "Sertanejo",
  "expects": "The audience does not just listen; it sings the entire song, often louder than the PA in quiet passages, and raises phones during the big ballad.",
  "glance": {
    "origin": "Brazilian interior (São Paulo, Minas Gerais, Goiás, Paraná, Mato Grosso do Sul), from 1920s música caipira; electrified in the late 1960s, romantic-pop in the 1980s–90s, “sertanejo universitário” from the mid-2000s",
    "tempo": "Ballads and arrocha 64–85 BPM; mid-tempo pop sertanejo 90–115; vanerão/vaneira and “bailão” feels 120–150",
    "ensemble": "Singing duo (or solo singer) plus 6–9 piece band: drums, percussion, bass, 1–2 acoustic guitars, electric guitar, accordion, keys, viola caipira or fiddle as guests, plus playback",
    "priority": "The two lead voices in tight, intelligible harmony on top of a crowd that sings every word",
    "liveSpl": "Arenas and rodeo festivals 100–105 dBA LAeq-15; roughly 118–126 dBC; clubs (“baladas sertanejas”) 98–102 dBA",
    "studioLoudness": "Masters commonly −9 to −7 LUFS-I (ballads −10 to −8); streaming normalizes to about −14"
  },
  "purpose": [
    {
      "text": "Sertanejo is Brazil’s mass-market heart music: songs about love, betrayal, drinking away heartbreak (“sofrência”), the countryside, pickup trucks and nightlife. It is the most-streamed genre in the country, and its artists headline agricultural fairs and rodeos such as the Festa do Peão de Barretos, where an 80,000-capacity arena fills night after night. The audience does not just listen; it sings the entire song, often louder than the PA in quiet passages, and raises phones during the big ballad. Brazilians also consume live recordings (“ao vivo”) at a far higher rate than any other market, so the “show” sound is the genre’s reference sound. Listeners will say “that sounded wrong” if they cannot understand the lyrics, if the duo’s harmony sounds like two separate singers instead of one voice, if the accordion is missing on the hook, or if the crowd feels absent from a live record."
    }
  ],
  "instruments": [
    {
      "label": "Lead vocals:",
      "text": "usually a duo singing in parallel thirds (sometimes sixths), with heavy vibrato and a bright, nasal “caipira” placement; solo stars (Gusttavo Lima, Ana Castela, Marília Mendonça) carry the same style.",
      "bullet": true
    },
    {
      "label": "Acoustic guitar (violão):",
      "text": "steel-string, mostly piezo/DI, strummed; often the main harmonic engine in ballads.",
      "bullet": true
    },
    {
      "label": "Viola caipira:",
      "text": "ten strings in five paired courses (octave and unison pairs), often in open tunings such as cebolão; bright, chimey and jangly, finger-picked. The genre’s identity instrument for “modão” and roots moments.",
      "bullet": true
    },
    {
      "label": "Accordion (sanfona/acordeon):",
      "text": "melodic fills, intros and hooks; increasingly central again thanks to the forró/piseiro crossover.",
      "bullet": true
    },
    {
      "label": "Electric guitar:",
      "text": "clean or lightly driven arpeggios, country-style bends, and rock-tinged solos in up-tempo songs.",
      "bullet": true
    },
    {
      "label": "Drums and percussion:",
      "text": "pop kit; percussionist with shaker, cajón, pandeiro, timbales, plus electronic pads for arrocha and funknejo patterns.",
      "bullet": true
    },
    {
      "label": "Bass:",
      "text": "electric (five-string common), carrying vanerão gallops, arrocha syncopation and reggaeton-like grooves.",
      "bullet": true
    },
    {
      "label": "Keys and playback:",
      "text": "pads, strings, synth bass and click/timecode playback are standard on tours.",
      "bullet": true
    }
  ],
  "arrangement": [
    {
      "text": "The duo stands front center, typically the “primeira voz” (melody) and “segunda voz” (harmony, usually a third above or below). Drums and percussion sit upstage on risers; bass and guitars to the sides; accordion and keys on their own risers, often downstage so the accordionist can come forward for solos. Arrangements follow pop form: a short accordion or viola intro, a sparse first verse (one voice, acoustic and pads), a pre-chorus that brings the second voice in, and a chorus where both voices, full drums and accordion hook arrive together. A key change or a “breakdown” where the band drops out and the crowd sings the chorus a cappella is a near-universal live moment."
    }
  ],
  "dynamics": [
    {
      "text": "Studio sertanejo is polished and fairly compressed, but the live show has wide macro-dynamics: intimate verses at 92–95 dBA, choruses at 102–105, and crowd sing-along sections where the band drops 10–15 dB. Preserve those drops—they are the emotional climax—while keeping the vocals dense and stable. Ride the duo by phrase rather than squashing them."
    }
  ],
  "balance": [
    {
      "text": "Hierarchy, loudest to quietest: lead duo (as one block), kick and bass, snare, accordion (hooks pushed up), acoustic guitar, electric guitar, keys/pads, percussion, viola (pushed in its features), reverb returns, audience mics. Kick and bass share the bottom: in ballads the bass sustains (60–200 Hz) and the kick is softer and shorter; in arrocha and funknejo the kick or 808 dominates 45–70 Hz, so high-pass the bass slightly higher and let it sit around 80–120 Hz. Pan the duo near center (about 5–15% left/right, matching their stage positions); acoustic guitar and accordion opposite each other at 30–50%; electric guitar and keys wider. A double-tracked violão can go hard left and right in the studio."
    }
  ],
  "eq": {
    "rows": [
      {
        "source": "Lead vocal (primeira voz)",
        "cut": "HPF 90–120 Hz; −2–3 dB at 250–350 Hz; narrow notch at 2.5–4 kHz if nasal/harsh",
        "boost": "+2 dB at 1.5–3 kHz (diction); +1–2 dB shelf at 10 kHz",
        "notes": "Keep the bright, forward tone; do not thin the chest too much"
      },
      {
        "source": "Harmony vocal (segunda voz)",
        "cut": "HPF 120–150 Hz; −2–4 dB at 2–4 kHz (dip where the lead boosts)",
        "boost": "+1 dB at 5–6 kHz only if buried",
        "notes": "Complementary EQ makes two voices fuse"
      },
      {
        "source": "Kick",
        "cut": "HPF 30–35 Hz; −4–6 dB at 300–450 Hz",
        "boost": "+3 dB at 55–70 Hz; +2–3 dB at 3–4 kHz",
        "notes": "Tighter and clickier for vanerão, rounder for ballads"
      },
      {
        "source": "Snare / pads",
        "cut": "HPF 90 Hz; −2–3 dB ring at 600 Hz–1 kHz",
        "boost": "+2 dB at 180–220 Hz; +2 dB at 5–6 kHz",
        "notes": "Electronic claps often layered—EQ as one"
      },
      {
        "source": "Bass",
        "cut": "HPF 35–45 Hz (60 Hz when an 808 runs); −2 dB at 250 Hz",
        "boost": "+2 dB at 80–100 Hz; +2 dB at 800 Hz–1.2 kHz",
        "notes": "Gallop patterns need note definition"
      },
      {
        "source": "Acoustic guitar (piezo/DI)",
        "cut": "HPF 90–120 Hz; −3 dB at 200–400 Hz; −2 dB at 1–2 kHz (piezo quack)",
        "boost": "+2 dB at 10–12 kHz",
        "notes": "Gentle 4–6 kHz dip if brittle"
      },
      {
        "source": "Viola caipira",
        "cut": "HPF 120–150 Hz; −2 dB at 300–500 Hz",
        "boost": "+2 dB at 3–5 kHz (pick shimmer); air shelf 10 kHz",
        "notes": "Its octave courses already sparkle; avoid harshness"
      },
      {
        "source": "Accordion",
        "cut": "HPF 100–150 Hz (treble side); −2–4 dB at 1–2.5 kHz if reedy/honky",
        "boost": "+2 dB at 3–4 kHz on hooks; bass-side mic +2 dB at 120–200 Hz",
        "notes": "Two mics or internal pickups; check bellows noise"
      },
      {
        "source": "Electric guitar",
        "cut": "HPF 100 Hz; LPF 10–12 kHz",
        "boost": "+2 dB at 1.5–2.5 kHz",
        "notes": "Clean tones easily mask vocals—carve 2–3 kHz"
      },
      {
        "source": "Keys / pads",
        "cut": "HPF 150–200 Hz; −2–3 dB at 2–4 kHz",
        "boost": "Minimal",
        "notes": "Pads fill space; keep them out of the voices"
      }
    ],
    "notes": []
  },
  "compression": {
    "rows": [
      {
        "source": "Lead vocals (each)",
        "use": "Yes",
        "ratio": "3:1–4:1",
        "attackRelease": "5–10 ms / 60–120 ms",
        "gainReduction": "4–6 dB",
        "notes": "Matching settings on both voices keeps the blend stable"
      },
      {
        "source": "Duo vocal bus",
        "use": "Yes",
        "ratio": "2:1",
        "attackRelease": "10–20 ms / auto",
        "gainReduction": "2–3 dB",
        "notes": "Glues the thirds into one voice"
      },
      {
        "source": "Accordion",
        "use": "Yes",
        "ratio": "3:1",
        "attackRelease": "15–25 ms / 100 ms",
        "gainReduction": "3–5 dB",
        "notes": "Bellows swells vary a lot; a multiband on 1–3 kHz helps"
      },
      {
        "source": "Acoustic guitar",
        "use": "Yes",
        "ratio": "3:1–4:1",
        "attackRelease": "15–30 ms / 80 ms",
        "gainReduction": "3–5 dB",
        "notes": "Even strumming; stronger for piezo peaks"
      },
      {
        "source": "Kick / bass",
        "use": "Yes",
        "ratio": "4:1",
        "attackRelease": "20–30 ms / 60–100 ms",
        "gainReduction": "3–6 dB",
        "notes": "Optional sidechain bass to kick (2–3 dB) on party tracks"
      },
      {
        "source": "Drum bus",
        "use": "Yes",
        "ratio": "2:1–4:1",
        "attackRelease": "10–30 ms / auto",
        "gainReduction": "2–4 dB",
        "notes": "Parallel blend 20–30% for punch"
      },
      {
        "source": "Mix bus",
        "use": "Light",
        "ratio": "2:1",
        "attackRelease": "10–30 ms / auto",
        "gainReduction": "1–3 dB",
        "notes": "Polished pop glue is expected"
      }
    ],
    "notes": [
      {
        "text": "De-ess both voices at 6–8 kHz for 3–5 dB; the vibrato and bright Portuguese sibilants (“s”, “ch”) get harsh at arena levels. Gate toms and percussion lightly live; do not gate vocals—use an expander (−8 to −10 dB range) instead, because the duo often steps off-mic to let the crowd sing. Live, a limiter on the vocal bus (−1 dB ceiling, 3–4 dB max reduction) catches screams on the big notes."
      }
    ]
  },
  "fx": {
    "rows": [
      {
        "effect": "Plate reverb",
        "appliedTo": "Duo vocals",
        "setting": "1.4–2.0 s decay, 30–60 ms pre-delay, HPF 250 Hz",
        "amount": "Moderate; more on ballads"
      },
      {
        "effect": "Hall reverb",
        "appliedTo": "Ballad choruses, strings, accordion solos",
        "setting": "2.2–3.0 s, 40–80 ms pre-delay",
        "amount": "Moderate"
      },
      {
        "effect": "Tempo delay",
        "appliedTo": "Vocal phrase ends",
        "setting": "1/4 or dotted 1/8, 15–25% feedback, filtered 300 Hz–5 kHz",
        "amount": "Subtle, thrown on line ends"
      },
      {
        "effect": "Separate reverb per voice",
        "appliedTo": "Primeira vs segunda voz",
        "setting": "Two plates differing by 0.2–0.4 s or pre-delay",
        "amount": "Subtle—separates without splitting"
      },
      {
        "effect": "Room / short reverb",
        "appliedTo": "Drums, percussion, violão",
        "setting": "0.6–1.0 s",
        "amount": "Subtle–moderate"
      },
      {
        "effect": "Chorus / doubler",
        "appliedTo": "Acoustic guitar, viola caipira",
        "setting": "0.5–1 Hz rate, low depth; or 10–15 ms Haas",
        "amount": "Subtle"
      },
      {
        "effect": "Audience mics",
        "appliedTo": "Live recordings",
        "setting": "Shotguns and spaced pairs aimed at crowd, delayed to align",
        "amount": "Heavy in sing-alongs, tucked elsewhere"
      }
    ],
    "notes": []
  },
  "vocals": [
    {
      "text": "Vocals are the whole show: roughly 3–5 dB above the band by perceived level, louder than in rock and close to pop. Treat the duo as one instrument: the primeira voz slightly ahead (1–2 dB), the segunda voz tucked just under so the third sounds like color, not competition. Match mic models, gain structure and compressor settings so the blend survives level changes, then use complementary EQ dips. Pitch correction is routine and fairly firm in the studio (graphical or real-time, at moderate speed), and live engineers commonly run real-time tuning gently, but avoid audible robotic effects except on deliberate funknejo tracks. The heavy vibrato is stylistic; do not tune it flat. Lyrics are in Brazilian Portuguese and are sung back by the crowd, so diction (1.5–4 kHz) matters more than air. Live mics are mostly handheld wireless dynamics or vocal condensers, with in-ear monitors and crowd-ambient mics fed back so singers hear the audience."
    }
  ],
  "loudness": [
    {
      "label": "Live:",
      "text": "Rodeo arenas and agricultural-fair stages are huge outdoor spaces with delay towers; at Barretos the 140 × 140 m arena uses main line arrays, down-fills, front-fills and long-throw delays, with sub coverage still solid 70 m from the stage. Typical FOH levels run 100–105 dBA LAeq-15 (a constant 110 dBA across a big New Year’s show is the high extreme), with C-weighted levels 118–126 dBC; keep the C–A gap under about 20 dB unless the set leans heavily on 808-based party tracks. Peaks can exceed 115 dBA when the crowd screams. By common hearing-safety guidance, 100 dBA is safe for only about 15 minutes; long nights with several acts warrant earplugs for crew."
    },
    {
      "label": "Studio / streaming:",
      "text": "Pop sertanejo masters land around −9 to −7 LUFS-I with true peak at −1 dBTP (−2 dBTP for very loud masters to avoid codec overs). Most streaming services normalize to −14 LUFS, so excess loudness buys nothing. Ballads benefit from a PLR of 9–11 dB (about −10 to −12 LUFS-I at −1 dBTP); “ao vivo” releases keep more loudness range (6–9 LU) so the crowd moments land."
    }
  ],
  "liveStudio": {
    "rows": [
      {
        "area": "Vocals",
        "live": "Two open handhelds, expanders, wide crowd pickup; riding phrase by phrase",
        "studio": "Comped, tuned, aligned duo with doubles and detailed rides"
      },
      {
        "area": "Crowd",
        "live": "Part of the show—drop the band for sing-alongs",
        "studio": "On “ao vivo” records, crowd mics are a main element and are edited, aligned and sometimes layered"
      },
      {
        "area": "Instruments",
        "live": "Mostly DI/piezo for violão, viola and accordion to fight bleed",
        "studio": "Real mics on acoustic instruments; many “live” albums overdub instruments in the studio after recording drums, bass and vocals at the show"
      },
      {
        "area": "Low end",
        "live": "Large sub arrays, delay towers time-aligned; HPF the stage wash",
        "studio": "Tight kick/bass carving, 808 layers for party tracks"
      },
      {
        "area": "Playback",
        "live": "Click, timecode, pads and backing vocals from a playback DAW with redundant rigs",
        "studio": "Arranged parts printed and balanced"
      },
      {
        "area": "Effects",
        "live": "One plate, one hall, tapped delay",
        "studio": "Per-section automation, distinct verbs per voice"
      },
      {
        "area": "Loudness",
        "live": "100–105 dBA Leq, local boundary limits",
        "studio": "−9 to −7 LUFS-I, −1 dBTP"
      }
    ],
    "notes": []
  },
  "notes": [
    {
      "text": "Build the mix around the duo: get the two voices blending in solo, then bring the band in around them.",
      "bullet": true
    },
    {
      "text": "Learn the setlist’s crowd moments; when the singer points the mic at the audience, pull the band down and open the audience mics, not the vocal fader.",
      "bullet": true
    },
    {
      "text": "Do not lose the accordion hook under keys and electric guitar; it is the identity of many choruses.",
      "bullet": true
    },
    {
      "text": "Piezo violão and viola get quacky and harsh at volume—tame 1–2 kHz and 4–6 kHz rather than adding top.",
      "bullet": true
    },
    {
      "text": "Mixing an “ao vivo” record: use timecode-locked multitrack, align audience mics to the PA arrival, and keep the crowd audible but never louder than the hook.",
      "bullet": true
    },
    {
      "text": "On mixed bills (sertanejo, forró, piseiro, funk), recheck sub level per act; agronejo and funknejo tracks need far more 40–60 Hz than ballad sets.",
      "bullet": true
    }
  ],
  "references": [
    "Chitãozinho & Xororó, “Evidências”, 1990",
    "Zezé Di Camargo & Luciano, “É o Amor”, 1991",
    "Jorge & Mateus, “Amo Noite e Dia”, 2010",
    "Michel Teló, “Ai Se Eu Te Pego”, 2011",
    "Gusttavo Lima, “Balada”, 2011",
    "Marília Mendonça, “Infiel”, 2016",
    "Henrique & Juliano, “Cuida Bem Dela”, 2017",
    "Ana Castela, “Pipoco” (with Melody and DJ Chris no Beat), 2022"
  ],
  "empty": []
};
