/**
 * Mixing guide 30 — Punjabi Pop / Bhangra. GENERATED by scripts/mixing-guides/convert.py
 * from the owner's guide (assets/Mixing-Guides-50-Styles, read only). Edit the
 * conversion (scripts/mixing-guides/edits.py), not this file.
 */
import type { MixingGuide } from '../types';

export const GUIDE: MixingGuide = {
  "id": "punjabi-pop-bhangra",
  "num": 30,
  "title": "Punjabi Pop / Bhangra",
  "expects": "Listeners expect a chest-thumping dhol, a ringing tumbi hook, and a singer whose Punjabi words and “hoi/balle balle” calls are clear and proud.",
  "glance": {
    "origin": "Punjab (India/Pakistan) harvest and wedding folk; staged bhangra from the 1960s–70s; electrified by UK diaspora bands (Birmingham, Coventry, Bradford, Southall) in the 1980s; reshaped by Canadian (Brampton, Surrey) and Indian Punjabi pop/hip-hop since the 2010s",
    "tempo": "90–110 BPM for most modern Punjabi pop and trap-leaning tracks; classic bhangra/chaal grooves 150–180 BPM (often felt in half time); ballads 70–85",
    "ensemble": "Wedding/club: singer + dhol player + DJ or tracks. Touring pop: lead singer, 1–2 dhol, tumbi/guitar/keys, drummer, bass, 2–3 backing vocals plus timecoded playback (40–60 inputs)",
    "priority": "Dhol-driven groove locked to the low end (808 or bass), with the Punjabi lead vocal riding clearly on top",
    "liveSpl": "98–104 dBA Leq (LAeq-15 min) at arena/stadium shows, peaks regularly past 108 dBA; 115–125 dBC; weddings and banquet halls 92–100 dBA",
    "studioLoudness": "Masters commonly −9 to −6 LUFS-I (older bhangra catalog around −11 to −9); streaming normalizes to about −14"
  },
  "purpose": [
    {
      "text": "Bhangra began as harvest-season dance music in rural Punjab, tied to Vaisakhi, weddings and village fairs, and that purpose has never left it: it exists to make people dance, shout and celebrate together. In the diaspora it became a badge of identity, from 1980s UK “daytimer” parties to today’s sold-out O2 and Canadian arena shows, and every wedding sangeet and baraat still runs on it. Listeners expect a chest-thumping dhol, a ringing tumbi hook, and a singer whose Punjabi words and “hoi/balle balle” calls are clear and proud. They will say “that sounded wrong” if the dhol is thin or buried under an 808, the tumbi is shrill and painful, the vocal is lost in reverb, or the drop lands without impact. Expect the crowd to sing every word, so leave space for them."
    }
  ],
  "instruments": [
    {
      "label": "Dhol:",
      "text": "wooden barrel drum, two heads. The thick bass head (struck with the bent dagga stick) gives a booming, pitched low note; the thin treble head (thapi, played with the flexible teeli) gives a crackling slap. It is the genre’s identity and is loud enough to be heard across a field unamplified.",
      "bullet": true
    },
    {
      "label": "Tumbi:",
      "text": "single steel string over a gourd resonator, flicked with the index finger. Bright, nasal, fundamental around 300 Hz–1 kHz with strong harmonics to 8 kHz. Often sampled or played on keys in modern pop.",
      "bullet": true
    },
    {
      "label": "Algoza:",
      "text": "paired wooden flutes, one melody, one drone; breathy and penetrating.",
      "bullet": true
    },
    {
      "label": "Chimta:",
      "text": "iron tongs with jingles, accenting downbeats; dholki (smaller hand drum used by women at weddings); sarangi and harmonium in folk settings.",
      "bullet": true
    },
    {
      "label": "Modern layer:",
      "text": "808s, trap hats, programmed kicks and claps, synth bass, guitar, piano, strings, and sampled dhol loops. Since the 2010s much Punjabi pop is produced like R&B/hip-hop with folk elements layered on top. Live shows run substantial timecoded playback.",
      "bullet": true
    }
  ],
  "arrangement": [
    {
      "text": "At weddings the dholi stands by the DJ or roams the crowd; on tour, one or two dhol players sit downstage, with band and singers upstage. The dhol plays the core chaal and kaharva-type eight-beat grooves, often doubled by a kick/clap pattern; the 808 or bass carries the root; tumbi or algoza answers the vocal with short hooks between lines. Typical form: tumbi or vocal intro (often free-time alaap or a shouted boli), verse with sparse beat, a pre-hook build of dhol rolls, then the hook with the full dhol, claps and crowd shout. Breakdowns strip everything back to dhol and voice before the last hook; this “dhol-only” moment is a highlight and must hit hard."
    }
  ],
  "dynamics": [
    {
      "text": "The music is mostly high-energy with moderate macro-dynamics: about 6–9 dB between a sparse verse and a full hook, and big contrast at intros, breakdowns and acapella boliyan. Micro-dynamics are extreme on the dhol: the dagga stroke can peak 15–20 dB above its average. Preserve the attack (the slap is the excitement) but control the bass head’s boom so it doesn’t swamp the PA. Ride the vocal through the free-time intros, which are often sung softer and higher. Live, leave about 6 dB of headroom for the final hook and the drop."
    }
  ],
  "balance": [
    {
      "text": "Loudest to quietest: lead vocal and dhol (roughly equal, dhol slap just under the vocal), kick/808 or bass, claps/snare, tumbi or algoza hook (pushed up in its spots), backing vocals and crowd-response shouts, keys and pads, overheads and FX returns. Low end: decide who owns the bottom. In trap-leaning tracks the 808 owns 40–70 Hz and the dhol bass head sits at 80–150 Hz; in classic bhangra the dhol bass head can own 70–120 Hz with the bass guitar tucked above or below. Sidechain or dynamic EQ helps keep them apart. Vocal, dhol, kick, 808 and snare sit center. Pan a second dhol 30–50% if there are two players; tumbi slightly off-center (15–30%) opposite keys or guitar; backing vocals and response shouts wide."
    }
  ],
  "eq": {
    "rows": [
      {
        "source": "Dhol bass head",
        "cut": "HPF 40–50 Hz; −3 to −5 dB at 250–400 Hz (boxiness)",
        "boost": "+2–4 dB at 80–120 Hz (find the pitched boom); +2 dB at 2–3 kHz for stick definition",
        "notes": "Mic 10–20 cm off the head; tuning changes the fundamental, so sweep per player"
      },
      {
        "source": "Dhol treble head",
        "cut": "HPF 150–200 Hz; −2–3 dB at 600–900 Hz (ring)",
        "boost": "+2–4 dB at 3–5 kHz (slap); shelf +2 dB at 10 kHz",
        "notes": "Thin head is very bright; tame 4–6 kHz if harsh on big PAs"
      },
      {
        "source": "808 / sub bass",
        "cut": "HPF 25–30 Hz; dip 2–3 dB at kick fundamental (often 55–65 Hz)",
        "boost": "Saturation for 100–200 Hz harmonics; +1–2 dB at 50–60 Hz",
        "notes": "Keep mono below 120 Hz so it translates to phones"
      },
      {
        "source": "Kick (programmed or acoustic)",
        "cut": "HPF 30 Hz; −3 dB at 300–500 Hz",
        "boost": "+2–3 dB at 60–80 Hz; +2–3 dB at 3–5 kHz click",
        "notes": "Shorten decay so it doesn’t fight the 808 tail"
      },
      {
        "source": "Claps / snare",
        "cut": "HPF 150–200 Hz",
        "boost": "+2 dB at 200 Hz (body); +2–3 dB at 5–8 kHz",
        "notes": "Clap on 2 and 4 often layered with dhol slap"
      },
      {
        "source": "Tumbi",
        "cut": "HPF 200–250 Hz; −2–4 dB narrow at 2.5–4 kHz if piercing",
        "boost": "+1–2 dB at 800 Hz–1.2 kHz (body); gentle shelf at 8 kHz",
        "notes": "The hook must cut, not sting; dynamic EQ on 3 kHz works well"
      },
      {
        "source": "Algoza / flute",
        "cut": "HPF 250 Hz; −2 dB at 1–2 kHz if honky",
        "boost": "+1–2 dB at 5–6 kHz (breath)",
        "notes": "Drone pipe can mask the vocal; tuck it"
      },
      {
        "source": "Chimta",
        "cut": "HPF 400–500 Hz",
        "boost": "+1–2 dB at 6–8 kHz",
        "notes": "Small level; it’s an accent"
      },
      {
        "source": "Lead vocal",
        "cut": "HPF 90–120 Hz (male), 120–150 Hz (female); −2–3 dB at 250–400 Hz",
        "boost": "+2–3 dB at 2–4 kHz (presence); +1–2 dB shelf at 10–12 kHz",
        "notes": "High-pitched folk delivery can get edgy near 3–5 kHz; notch carefully"
      },
      {
        "source": "Backing vocals / shouts",
        "cut": "HPF 150–200 Hz; −2–3 dB at 3 kHz",
        "boost": "+1 dB at 8–10 kHz",
        "notes": "Keep “hoi” responses bright but behind the lead"
      }
    ],
    "notes": []
  },
  "compression": {
    "rows": [
      {
        "source": "Lead vocal (stage 1, FET)",
        "use": "Yes",
        "ratio": "4:1",
        "attackRelease": "1–5 ms / 50–80 ms",
        "gainReduction": "3–6 dB",
        "notes": "Catches the shouted peaks of boliyan"
      },
      {
        "source": "Lead vocal (stage 2, opto)",
        "use": "Yes",
        "ratio": "2:1–3:1",
        "attackRelease": "Program",
        "gainReduction": "2–4 dB",
        "notes": "Smooths long sustained notes"
      },
      {
        "source": "Dhol bass head",
        "use": "Yes",
        "ratio": "4:1",
        "attackRelease": "20–30 ms / 80–120 ms",
        "gainReduction": "3–6 dB",
        "notes": "Slow attack keeps the dagga thump"
      },
      {
        "source": "Dhol treble head",
        "use": "Light",
        "ratio": "3:1",
        "attackRelease": "5–10 ms / 50 ms",
        "gainReduction": "2–4 dB",
        "notes": "Clipper or transient shaper often better"
      },
      {
        "source": "808 / bass",
        "use": "Yes",
        "ratio": "4:1 + sidechain from kick",
        "attackRelease": "10 ms / 60–100 ms",
        "gainReduction": "3–5 dB; ducking 2–4 dB",
        "notes": "Low threshold, fast release on the duck"
      },
      {
        "source": "Tumbi",
        "use": "Yes",
        "ratio": "3:1",
        "attackRelease": "5–10 ms / 80 ms",
        "gainReduction": "3–5 dB",
        "notes": "Evens finger flicks so the hook stays consistent"
      },
      {
        "source": "Drum/percussion bus",
        "use": "Yes",
        "ratio": "2:1–4:1",
        "attackRelease": "10–30 ms / auto",
        "gainReduction": "2–3 dB",
        "notes": "Glue dhol, claps and kick together"
      },
      {
        "source": "Mix bus",
        "use": "Optional",
        "ratio": "2:1",
        "attackRelease": "10–30 ms / auto",
        "gainReduction": "1–2 dB",
        "notes": "Leave loudness to mastering"
      }
    ],
    "notes": [
      {
        "text": "Parallel compression on the dhol (8:1, 8–12 dB reduction, blended 20–30%) adds weight without killing the slap. Gate the dhol mics lightly live only if spill is severe; usually a downward expander (2:1, −10 dB range) is safer because rolls and ghost strokes matter. De-ess the lead at 5–8 kHz for 2–4 dB. A soft clipper on the percussion bus (1–2 dB) helps modern masters get loud without pumping."
      }
    ]
  },
  "fx": {
    "rows": [
      {
        "effect": "Plate reverb",
        "appliedTo": "Lead vocal",
        "setting": "1.2–1.8 s decay, 30–60 ms pre-delay, HPF 300 Hz",
        "amount": "Moderate in hooks, lighter in verses"
      },
      {
        "effect": "Tempo delay",
        "appliedTo": "Vocal phrase ends, “hoi” shouts",
        "setting": "1/4 or dotted 1/8, 20–30% feedback, LPF 5 kHz",
        "amount": "Moderate, automated; throws on hook tails"
      },
      {
        "effect": "Long hall",
        "appliedTo": "Free-time alaap / intros",
        "setting": "2.5–3.5 s decay, 40–80 ms pre-delay",
        "amount": "Heavy on intros, then pull back for the beat"
      },
      {
        "effect": "Short room",
        "appliedTo": "Dhol, claps",
        "setting": "0.5–0.9 s decay",
        "amount": "Subtle; gives the dhol a “space” without blurring"
      },
      {
        "effect": "Slap / short delay",
        "appliedTo": "Tumbi, algoza",
        "setting": "60–110 ms, low feedback",
        "amount": "Subtle; widens the hook"
      },
      {
        "effect": "Pitch correction",
        "appliedTo": "Lead (modern pop)",
        "setting": "Fast retune for stylized tracks; slow for folk",
        "amount": "Light to obvious, per artist"
      },
      {
        "effect": "Saturation",
        "appliedTo": "808, dhol bus",
        "setting": "Tube/tape style, 20–30% wet",
        "amount": "Moderate; adds harmonics for small speakers"
      }
    ],
    "notes": []
  },
  "vocals": [
    {
      "text": "The Punjabi lead is the star and sits clearly in front, about 2–4 dB above the dhol by perceived level, more forward than in rock. Traditional singers (in the line of Kuldeep Manak’s high, powerful kali style) project hard in the upper midrange, so the engineer’s job is to keep that power from turning harsh: dynamic EQ around 3–4 kHz, gentle de-essing, and serial compression. Keep consonants clear; the audience follows every line. Modern Canadian-style Punjabi pop and hip-hop (AP Dhillon, Karan Aujla, Shubh) uses tighter, R&B-like processing with doubles, stylized tuning and darker reverbs; folk-leaning singers want lighter correction that preserves ornaments (murki) and slides. Backing vocals and crowd shouts are tucked 6–10 dB under and panned wide. Live, a rugged dynamic or supercardioid capsule handles high SPL from dhol spill; give the singer a strong in-ear mix with plenty of dhol so they stay in time."
    }
  ],
  "loudness": [
    {
      "label": "Live:",
      "text": "Arena and stadium Punjabi pop shows run hot. Big Punjabi stadium tours run SPL regularly above 108 dB, and stadium shows in India now deploy large flown-plus-ground sub arrays for 75,000-plus crowds. As a sensible target, run 98–104 dBA LAeq-15 at FOH with C-weighted levels of 115–125 dBC; a C-minus-A gap of over 20 dB means too much sub. Weddings, banquet halls and gurdwara-adjacent venues are smaller, reflective rooms: 92–100 dBA is plenty, and the dhol alone can exceed 105 dBA at a metre, so you may barely need to amplify it. UK workplace rules set action values of 80 and 85 dBA daily exposure for staff; earplugs for crew, dholis and family members dancing next to the subs are strongly advised."
    },
    {
      "label": "Studio / streaming:",
      "text": "Modern Punjabi pop masters commonly land at −9 to −6 LUFS-I with true peak at −1 dBTP (or −2 dBTP when louder than −14, a common streaming recommendation). Most streaming services normalize to −14 LUFS (−11 on some loud settings), so extreme loudness costs dhol transients for no gain. Aim for a PLR of about 8–10 dB."
    }
  ],
  "liveStudio": {
    "rows": [
      {
        "area": "Dhol",
        "live": "Loud acoustically; mic both heads, control spill into vocals, watch 100–250 Hz room buildup",
        "studio": "Layer live dhol with samples; parallel compression and saturation for size"
      },
      {
        "area": "Low end",
        "live": "Choose between dhol boom and 808 per song with snapshots; keep subs clean across stadium zones",
        "studio": "Sidechain and dynamic EQ carve kick, dhol and 808 precisely"
      },
      {
        "area": "Vocals",
        "live": "Gain-before-feedback limits; dynamic mics, short FX chain, tap delays",
        "studio": "Comping, tuning, doubles, detailed rides on every line"
      },
      {
        "area": "Playback",
        "live": "Timecoded tracks; balance live dhol vs track dhol so they don’t flam",
        "studio": "Everything is one session; samples timed exactly"
      },
      {
        "area": "Effects",
        "live": "One or two reverbs, tapped delay, snapshot recalls per song",
        "studio": "Multiple automated reverbs/delays per section"
      },
      {
        "area": "Crowd",
        "live": "Leave gaps for singalong; add audience mics for broadcast/social feeds",
        "studio": "Recorded crowd shouts or gang vocals layered in"
      },
      {
        "area": "Loudness",
        "live": "98–104 dBA LAeq-15, peaks above 108 dBA",
        "studio": "−9 to −6 LUFS-I, −1 dBTP"
      }
    ],
    "notes": []
  },
  "notes": [
    {
      "text": "Talk to the dholi before the show: ask which songs get solos and rolls, and where they will stand. Mic the bass head 10–20 cm off-axis with a dynamic kick or tom mic and the treble head with a classic dynamic or small condenser; a wireless clip-on is useful for players who move through the crowd.",
      "bullet": true
    },
    {
      "text": "Check polarity between the two dhol mics; they face opposite directions and often cancel in the low mids.",
      "bullet": true
    },
    {
      "text": "Don’t let the 808 and dhol bass head pile up at 60–120 Hz; pick one owner per song.",
      "bullet": true
    },
    {
      "text": "Tame the tumbi with dynamic EQ, not a blanket cut; it must still pop.",
      "bullet": true
    },
    {
      "text": "Leave room for crowd chants and the artist’s call-outs; mute vocal FX during talk.",
      "bullet": true
    },
    {
      "text": "Classic UK bhangra sounds rawer and more mid-forward than Canadian trap-Punjabi; mix to the era of the song.",
      "bullet": true
    }
  ],
  "references": [
    "Kuldeep Manak, “Tere Tille Ton”, 1976",
    "Malkit Singh, “Gur Nalon Ishq Mitha”, 1987",
    "Daler Mehndi, “Tunak Tunak Tun”, 1998",
    "Panjabi MC feat. Labh Janjua, “Mundian To Bach Ke”, 1998 (re-release 2002)",
    "The Dhol Foundation, “Big Drum Small World” (album), 2001",
    "Imran Khan, “Amplifier”, 2009",
    "AP Dhillon, Gurinder Gill & Shinda Kahlon, “Brown Munde”, 2020",
    "Diljit Dosanjh, “Born to Shine”, 2020"
  ],
  "empty": []
};
