/**
 * Mixing guide 37 — Amapiano. GENERATED by scripts/mixing-guides/convert.py
 * from the owner's guide (assets/Mixing-Guides-50-Styles, read only). Edit the
 * conversion (scripts/mixing-guides/edits.py), not this file.
 */
import type { MixingGuide } from '../types';

export const GUIDE: MixingGuide = {
  "id": "amapiano",
  "num": 37,
  "title": "Amapiano",
  "expects": "The crowd expects to feel the log drum physically, hear jazzy keys float over it, and shout back the hooks.",
  "glance": {
    "origin": "Gauteng townships, South Africa (Mamelodi, Atteridgeville, Soweto, Alexandra, Katlehong), roughly 2012–2016; rooted in kwaito, deep house, Bacardi and jazz; national breakout 2019",
    "tempo": "108–115 BPM (112 is a common default); “private school” piano sits at the slower end",
    "ensemble": "DJ/producer plus 1–4 vocalists and hype MCs; often a featured sax, keys or guitar player; dancers on stage; bigger shows add a band or orchestra",
    "priority": "The log drum: weighty in the sub, woody and pitched in the mids, landing between the kicks without masking them",
    "liveSpl": "98–103 dBA Leq (LAeq-15 min), roughly 118–128 dBC; sub-heavy, so watch the C-minus-A gap",
    "studioLoudness": "Masters commonly −9 to −6 LUFS-I (soulful/private school around −10 to −8); streaming normalizes to about −14"
  },
  "purpose": [
    {
      "text": "Amapiano (“the pianos” in isiZulu) is dance music born in tavern and township party culture (Mamelodi’s Jack Budha tavern, street parties, taxis), with tracks spreading on messaging apps before radio. It is for long, unhurried dancing — routines such as Dakiwe and uMlando, plus social-video challenges — and for collective joy and township pride. The crowd expects to feel the log drum physically, hear jazzy keys float over it, and shout back the hooks. A mellow listening side also exists (“private school” piano, associated with Kelvin Momo). Listeners will say “that sounded wrong” if the log drum is thin, distorted to mush or buried under the kick; if the shakers are missing or harsh; if the tempo feels rushed; or if the mix sounds like over-bright, over-pumped EDM."
    }
  ],
  "instruments": [
    {
      "label": "Log drum:",
      "text": "the signature sound, popularized by MDU aka TRP: a pitched, woody bass-percussion hybrid, originally a stock software-synth preset, now often layered from soft kick, sine sub and a mallet layer, playing syncopated basslines that follow the chords.",
      "bullet": true
    },
    {
      "label": "Kick:",
      "text": "soft and round, four-on-the-floor or syncopated; the timekeeper, not the hero.",
      "bullet": true
    },
    {
      "label": "Shakers and percussion:",
      "text": "constant 16th-note shakers (often two, slightly offset), rimshots, congas, sparse claps, offbeat open hats.",
      "bullet": true
    },
    {
      "label": "Piano/keys:",
      "text": "Electric piano and acoustic piano looping 7th and 9th chords; warm pads.",
      "bullet": true
    },
    {
      "label": "Live soloists:",
      "text": "sax (Jay Sax), keys (Moscow on Keyz), guitar (Xolani Guitars), occasionally violin or trumpet.",
      "bullet": true
    },
    {
      "label": "Vocals:",
      "text": "hooks, chants, spoken and rapped parts in isiZulu, Sesotho, Setswana and slang, plus vocal chops.",
      "bullet": true
    },
    {
      "label": "Playback:",
      "text": "almost always a DJ mix or stems, with live elements on top.",
      "bullet": true
    }
  ],
  "arrangement": [
    {
      "text": "Most shows are DJ-led: the DJ upstage center at decks, vocalists and hype men front, dancers across the stage, sometimes a sax or keys player beside the booth. Larger concerts (stadium shows, and in 2024 a show with a 33-piece orchestra) add a full band. In the track, kick and shakers set the floor, the log drum carries bass and groove, keys and pads supply harmony, and vocals sit inside the groove. Arrangements are long and DJ-friendly: 8–16 bar intro, 16-bar foundation, a 16–32 bar “log drum section”, a breakdown (log drum out, keys and vocals exposed) and a return. Tracks of 6–8 minutes are normal; the biggest moment is usually the log drum coming back after a drop-out."
    }
  ],
  "dynamics": [
    {
      "text": "Macro-dynamics come from arrangement — elements dropping out and returning — not performance swells; breakdown to full log-drum section is typically 4–8 dB. Micro-dynamics are tightly controlled: the log drum needs even level across its pitched notes, and shakers stay steady for hours. But the groove lives in transient shape and timing (swing, ghost notes, hits a few ms off grid), so do not compress the log drum or mix bus flat. Live, ride the log drum and vocals through drop-outs; the log drum return is a key moment of the night."
    }
  ],
  "balance": [
    {
      "text": "Hierarchy, loudest to quietest: log drum, kick (behind in the sub, clear in its click), lead vocal/hooks, shakers, keys and pads, soloist, percussion, FX returns. Low end is everything: the log drum owns 40–80 Hz plus body at 100–250 Hz; the kick owns the transient and a narrow band (often 50–70 Hz). The log drum should land between kicks, with a light 1–2 dB duck where they collide; any separate sub stays simple. Keep everything below 100–120 Hz mono. Kick, log drum, vocal and main shaker sit center; second shaker and percussion 20–40% out; keys and pads wide; soloist slightly off center."
    }
  ],
  "eq": {
    "rows": [
      {
        "source": "Log drum",
        "cut": "HPF 25–30 Hz; −2–4 dB at 300–500 Hz if boxy",
        "boost": "+2–3 dB at 45–60 Hz (weight); +2–3 dB at 800 Hz–1.5 kHz (woody “knock”)",
        "notes": "Saturation adds 200 Hz–2 kHz harmonics for phone translation"
      },
      {
        "source": "Kick",
        "cut": "HPF 30 Hz; −3 dB at 200–400 Hz",
        "boost": "+2 dB at the fundamental (50–70 Hz); +2 dB at 3–5 kHz",
        "notes": "Softer and shorter than in house"
      },
      {
        "source": "Sub bass (if any)",
        "cut": "LPF 120–150 Hz",
        "boost": "Gentle +1–2 dB at 40–50 Hz",
        "notes": "Match the log drum’s envelope and check phase alignment"
      },
      {
        "source": "Shakers",
        "cut": "HPF 300–500 Hz; dip 6–8 kHz if spitty",
        "boost": "+1–2 dB at 10–12 kHz shelf",
        "notes": "Constant element: harshness wears ears out over a long set"
      },
      {
        "source": "Percussion (congas, rims)",
        "cut": "HPF 150–200 Hz; −2 dB at 400 Hz",
        "boost": "+2 dB at 2–4 kHz (slap)",
        "notes": "Fills gaps around the log drum; keep thin"
      },
      {
        "source": "electric piano / piano",
        "cut": "HPF 100–150 Hz; −2–3 dB at 250–400 Hz",
        "boost": "+1–2 dB at 2–3 kHz for definition",
        "notes": "Tape-style warmth over bright EQ; leave the log drum’s low mids alone"
      },
      {
        "source": "Pads",
        "cut": "HPF 150–250 Hz; LPF 8–10 kHz",
        "boost": "Little or none",
        "notes": "Background bed; often sidechained gently"
      },
      {
        "source": "Saxophone / trumpet",
        "cut": "HPF 120–150 Hz; −2 dB at 1–2 kHz if honky",
        "boost": "+1–2 dB at 3–5 kHz",
        "notes": "Live: notch feedback resonances and keep a clean path"
      },
      {
        "source": "Lead vocal",
        "cut": "HPF 90–120 Hz; −2–3 dB at 250–400 Hz; notch 2.5–4 kHz if harsh",
        "boost": "+2 dB at 3–5 kHz; +1–2 dB shelf at 10–12 kHz",
        "notes": "Warm, smooth top; chants can be thinner and brighter"
      }
    ],
    "notes": []
  },
  "compression": {
    "rows": [
      {
        "source": "Log drum",
        "use": "Yes",
        "ratio": "3:1–4:1",
        "attackRelease": "20–40 ms / 50–100 ms",
        "gainReduction": "2–4 dB",
        "notes": "Slow attack keeps the knock; evens out pitched notes; soft clip after for crunch"
      },
      {
        "source": "Log drum ducked by kick",
        "use": "Yes (sidechain)",
        "ratio": "4:1",
        "attackRelease": "0.5–1 ms / 40–80 ms",
        "gainReduction": "1–2 dB",
        "notes": "Fast and shallow — the kick should poke through, not pump"
      },
      {
        "source": "Kick",
        "use": "Light",
        "ratio": "3:1",
        "attackRelease": "15–30 ms / 50 ms",
        "gainReduction": "1–3 dB",
        "notes": "Often already shaped in the sample"
      },
      {
        "source": "Lead vocal",
        "use": "Yes",
        "ratio": "3:1–4:1",
        "attackRelease": "5–10 ms / 60–100 ms",
        "gainReduction": "3–6 dB",
        "notes": "Two stages in studio; chant and MC mics harder (6–8 dB)"
      },
      {
        "source": "Backing vocals / chants",
        "use": "Yes",
        "ratio": "4:1",
        "attackRelease": "5 ms / auto",
        "gainReduction": "4–6 dB",
        "notes": "Tuck as a group"
      },
      {
        "source": "Sax / live keys",
        "use": "Light",
        "ratio": "2:1–3:1",
        "attackRelease": "15–25 ms / auto",
        "gainReduction": "2–3 dB",
        "notes": "Preserve the soloist’s expression"
      },
      {
        "source": "Drum/percussion bus",
        "use": "Yes",
        "ratio": "2:1",
        "attackRelease": "20–30 ms / auto",
        "gainReduction": "1–3 dB",
        "notes": "Glue shakers and percussion without dulling swing"
      },
      {
        "source": "Mix bus",
        "use": "Optional",
        "ratio": "1.5:1–2:1",
        "attackRelease": "30 ms / auto",
        "gainReduction": "1–2 dB",
        "notes": "Glue only; push loudness in mastering"
      }
    ],
    "notes": [
      {
        "text": "A gentle kick sidechain on pads and keys (1–3 dB) adds the “breathing” feel; heavy EDM pumping is wrong. De-ess vocals at 5–8 kHz for 2–4 dB. In mastering, combine soft clipping with 2–4 dB of limiting rather than one limiter doing 6+ dB."
      }
    ]
  },
  "fx": {
    "rows": [
      {
        "effect": "Saturation / soft clip",
        "appliedTo": "Log drum",
        "setting": "Tape or waveshaper, 1–3 dB drive; mix 30–60%",
        "amount": "Moderate (part of the tone)"
      },
      {
        "effect": "Plate or room reverb",
        "appliedTo": "Lead vocal",
        "setting": "1.2–1.8 s decay, 20–40 ms pre-delay, HPF 250 Hz",
        "amount": "Subtle–moderate"
      },
      {
        "effect": "Tempo delay",
        "appliedTo": "Vocal phrase ends, chants, sax",
        "setting": "1/8 dotted or 1/4 at 108–115 BPM (about 520–555 ms for 1/4, 390–415 ms for dotted 1/8), 20–30% feedback",
        "amount": "Moderate, thrown on hooks"
      },
      {
        "effect": "Hall / long reverb",
        "appliedTo": "Keys, pads, breakdowns",
        "setting": "2.0–3.0 s decay, 40–60 ms pre-delay",
        "amount": "Moderate, automated up in breakdowns"
      },
      {
        "effect": "Short room",
        "appliedTo": "Shakers, percussion",
        "setting": "0.4–0.8 s decay",
        "amount": "Subtle; adds space without washing the 16ths"
      },
      {
        "effect": "Filter sweep / tape stop",
        "appliedTo": "Full mix, transitions",
        "setting": "LPF/HPF automation over 4–8 bars",
        "amount": "DJ-style, at drop-outs and returns"
      },
      {
        "effect": "Chorus / tape wobble",
        "appliedTo": "electric piano",
        "setting": "0.3–0.8 Hz rate, light depth",
        "amount": "Subtle"
      }
    ],
    "notes": [
      {
        "text": "HPF reverb returns at 200–300 Hz; reverb on the log drum blurs the bass line."
      }
    ]
  },
  "vocals": [
    {
      "text": "Amapiano vocals sit inside the groove, roughly level with the log drum’s midrange rather than floating 3–4 dB above everything as in pop. Hooks are often chants and call-and-response, so the phrase must read clearly even if not every word is front and center. Lyrics in isiZulu, Sesotho, Setswana and township slang carry wordplay; check intelligibility at 2–5 kHz and ask the artist which lines matter most. Lead tone is warm and soulful, with strong R&B and gospel influence (e.g. the stacked harmonies on Tyla’s “Water”). Pitch correction is common but usually transparent. Backing stacks pan wide and compress as a group. Live, expect several vocalists and MCs over playback: give each a dynamic mic, set hype-mic HPFs around 150 Hz, and mute playback vocals when the live singer takes the line to avoid phasing."
    }
  ],
  "loudness": [
    {
      "label": "Live:",
      "text": "Club, tavern and festival amapiano typically runs 98–103 dBA LAeq-15 at FOH, peaking at 108–112 dBA on log drum returns. Being sub-led, 118–128 dBC is common; a C-minus-A gap above 20 dB at already-high A levels means the sub is too hot. Cardioid sub arrays keep the log drum tight and off the stage and neighbors. By common hearing-safety guidance, 100 dBA is safe for only about 15 minutes, and amapiano nights run for hours — offer earplugs and check venue or municipal limits."
    },
    {
      "label": "Studio / streaming:",
      "text": "Club-oriented masters typically land at −9 to −6 LUFS-I, soulful releases nearer −10 to −8. True peak −1 dBTP, or −2 dBTP if louder than −14 LUFS (common streaming guidance). Services normalize to about −14 LUFS, so extra loudness buys nothing and can flatten the log drum’s bounce. Aim for a PLR of about 8–10 dB and check phones and small wireless speakers, where the log drum must still read through its harmonics."
    }
  ],
  "liveStudio": {
    "rows": [
      {
        "area": "Low end",
        "live": "Tune subs for 40–80 Hz punch, not boom; watch dBC",
        "studio": "Fine-tune log drum vs kick timing and phase; mono below 100–120 Hz"
      },
      {
        "area": "Source",
        "live": "Mostly DJ playback; you mix vocals, soloists and system",
        "studio": "Every log drum and shaker layer balanced"
      },
      {
        "area": "Vocals",
        "live": "Several MCs over playback vocals — manage mutes and phasing",
        "studio": "Comped leads, stacks, light tuning, rides"
      },
      {
        "area": "Live instruments",
        "live": "Sax/keys/guitar over a dense track; carve 2–5 kHz",
        "studio": "Session players placed inside the mix"
      },
      {
        "area": "Effects",
        "live": "Tap-tempo delay on hooks, one vocal reverb",
        "studio": "Automated reverbs and delays by section, transition FX"
      },
      {
        "area": "Dynamics",
        "live": "Ride the log drum returns and vocals by hand",
        "studio": "Arrangement drop-outs and automation"
      },
      {
        "area": "Loudness",
        "live": "98–103 dBA Leq, 118–128 dBC",
        "studio": "−9 to −6 LUFS-I, −1 dBTP"
      }
    ],
    "notes": []
  },
  "notes": [
    {
      "text": "Get the log drum right first: solo it with the kick, check it is deep in the subs and woody in the mids, then build around it.",
      "bullet": true
    },
    {
      "text": "Check phase and envelope alignment whenever the log drum is layered with a sub.",
      "bullet": true
    },
    {
      "text": "Do not push tempo or brightness to manufacture energy; the groove depends on a relaxed swing.",
      "bullet": true
    },
    {
      "text": "Do not sidechain-pump like EDM; a 1–2 dB duck is plenty.",
      "bullet": true
    },
    {
      "text": "Shakers play nonstop for hours; tame 6–8 kHz to avoid fatigue.",
      "bullet": true
    },
    {
      "text": "Live, ask the DJ for a clean, unclipped feed (stems if possible) and headroom on the DJ mixer.",
      "bullet": true
    },
    {
      "text": "Over-clipping the master turns the log drum to mush; soft-clip in stages.",
      "bullet": true
    },
    {
      "text": "If you do not speak the languages, ask which hooks the crowd sings back.",
      "bullet": true
    }
  ],
  "references": [
    "Samthing Soweto, Sha Sha, DJ Maphorisa & Kabza De Small, “Akulaleki”, 2019",
    "Busta 929 & Mpura feat. Zuma, Mr JazziQ, Lady Du & Reece Madlisa, “Umsebenzi Wethu”, 2019",
    "Focalistic & Vigro Deep, “Ke Star”, 2020",
    "Young Stunna feat. Kabza De Small & DJ Maphorisa, “Adiwele”, 2021",
    "Kelvin Momo, Amukelani (album), 2021",
    "Uncle Waffles, Tman Xpress, Sino Msolo & Boibizza, “Tanzania”, 2022",
    "Tyla, “Water”, 2023"
  ],
  "empty": []
};
