/**
 * Mixing guide 40 — Cumbia. GENERATED by scripts/mixing-guides/convert.py
 * from the owner's guide (assets/Mixing-Guides-50-Styles, read only). Edit the
 * conversion (scripts/mixing-guides/edits.py), not this file.
 */
import type { MixingGuide } from '../types';

export const GUIDE: MixingGuide = {
  "id": "cumbia",
  "num": 40,
  "title": "Cumbia",
  "expects": "Audiences expect a relaxed but unstoppable sway, a melody they can sing back, and the lead line (accordion, keyboard or guitar) bright and present.",
  "glance": {
    "origin": "Caribbean coast of Colombia (Magdalena River basin, Depresión Momposina), documented by the early 1800s; urbanized by Discos Fuentes-era orchestras in the 1940s–60s, then spread into Mexican sonidera and tecnocumbia, Peruvian chicha (late 1960s) and Argentine villera (1999)",
    "tempo": "80–110 BPM, felt in 2 (rebajada/sonidera can drop to 70–85; villera and tecnocumbia often 95–110)",
    "ensemble": "6–14 piece: accordion or keys/keytar, bass, güiro/guacharaca, congas, timbales, optional kit, guitar, 1–3 vocalists, sometimes horns; or a sonidero with turntables/laptop plus MC mic",
    "priority": "The bass-and-güiro groove: the bass on 1 and the “and” of 2, with the scraper’s steady chop always audible",
    "liveSpl": "94–100 dBA Leq (LAeq-15 min); about 110–120 dBC; sonidero street parties often run hotter in the subs",
    "studioLoudness": "Modern masters commonly −10 to −8 LUFS-I (vintage reissues −14 to −11); streaming normalizes to about −14"
  },
  "purpose": [
    {
      "text": "Cumbia is dance music first: couples turning in circles at weddings, quinceañeras, block parties, bailes in rented halls and sonidero street dances in Iztapalapa, Tepito, Monterrey, Lima or the conurbano of Buenos Aires. It carries regional and class identity: Colombian coastal heritage (national intangible heritage, 2022), Mexico City’s working-class sonideros (city heritage, 2023), chicha’s migrant stories and villera’s street swagger. Audiences expect a relaxed but unstoppable sway, a melody they can sing back, and the lead line (accordion, keyboard or guitar) bright and present. They will say “that sounded wrong” if the güiro disappears, the bass is boomy and loses its bounce, the accordion turns shrill, or the vocals are unintelligible. At sonidero events the saludos (dedications read over the music, drenched in echo) matter as much as the record itself."
    }
  ],
  "instruments": [
    {
      "label": "Traditional Colombian:",
      "text": "gaita hembra and macho (Indigenous duct flutes), caña de millo (cane clarinet), tambor alegre (lead drum), tambor llamador (offbeat time-keeper), tambora (two-headed bass drum), maracas and guacharaca.",
      "bullet": true
    },
    {
      "label": "Accordion:",
      "text": "diatonic button accordion, played treble side for melody and bass buttons for punctuation; central to Colombian vallenato-tinged cumbia and to Monterrey’s colombiana scene.",
      "bullet": true
    },
    {
      "label": "Scraper:",
      "text": "güiro (gourd) or guacharaca (cane), the most important small instrument in the mix.",
      "bullet": true
    },
    {
      "label": "Latin percussion:",
      "text": "congas, timbales with cowbell, bongó, sometimes kit or electronic drums.",
      "bullet": true
    },
    {
      "label": "Bass:",
      "text": "electric (or synth in tecnocumbia/villera), carrying root–fifth figures.",
      "bullet": true
    },
    {
      "label": "Keyboards:",
      "text": "organ in chicha; synth leads and keytar “accordion” patches in villera and sonidera.",
      "bullet": true
    },
    {
      "label": "Electric guitar:",
      "text": "chicha’s lead voice, with fuzz, wah, spring reverb and tape-style delay.",
      "bullet": true
    },
    {
      "label": "Horns:",
      "text": "trumpets, saxes, clarinets in big-band “música tropical”.",
      "bullet": true
    },
    {
      "label": "Playback:",
      "text": "synth layers in tecnocumbia; sonideros play records or files.",
      "bullet": true
    }
  ],
  "arrangement": [
    {
      "text": "A typical stage has percussion upstage center (congas one side, timbales the other, güiro player often standing beside the singer), bass near the percussion, accordion or keys downstage, singers front. Bass and güiro lock the groove; the bass usually plays root on 1, third on 2, fifth on the “and” of 2, while the güiro plays a down-stroke on the beat followed by a fast down-up figure. Congas alternate bass and open tones, and timbales add cáscara, fills and rolls into sections. Accordion or keyboard states the melody in the intro, answers vocal lines and takes instrumental breaks between verses. Arrangements are cyclical: intro riff, verse, coro, instrumental (accordion or guitar solo, timbal break), repeat, with a stripped breakdown where the singer calls out band members or towns. Sections are marked by fills and hits, not big density shifts."
    }
  ],
  "dynamics": [
    {
      "text": "Cumbia is steady by nature: dancers want continuous energy through 5–7 minute medleys, and macro dynamics are small (about 3–6 dB). Drama comes from the lead instrument entering, timbal fills and breakdowns to bass and güiro. Preserve those breakdowns and the timbal accents; control the micro-dynamics of accordion (bellows swells can jump 6–10 dB) and of shouting backing vocalists. Over-limiting kills the bounce of the bass and flattens the güiro into hiss."
    }
  ],
  "balance": [
    {
      "text": "Typical hierarchy, loudest to quietest: lead vocal (or MC), lead instrument (accordion/keys/guitar) during its spots, bass, güiro, congas, timbales, kick (if present), horns, backing vocals, pads, effects. Low end: the bass owns 60–200 Hz; the kick, when used, should be short and tucked (cumbia is not a four-on-the-floor kick genre) and the tambora or conga bass tone sits around 80–120 Hz. Keep the bass articulate at 700 Hz–1 kHz so the bounce reads on small speakers. Pan the güiro 10–25% off center, always felt. Congas and timbales on opposite sides to match the stage; accordion or keys near center; horns spread moderately. Lead vocal and bass dead center."
    }
  ],
  "eq": {
    "rows": [
      {
        "source": "Bass (electric or synth)",
        "cut": "HPF 35–40 Hz; −2–3 dB at 200–300 Hz if boomy",
        "boost": "+2 dB at 70–90 Hz; +2–3 dB at 800 Hz–1 kHz",
        "notes": "Bounce and note definition matter more than sub weight"
      },
      {
        "source": "Kick / tambora",
        "cut": "HPF 35–40 Hz; −3–5 dB at 300–500 Hz",
        "boost": "+2–3 dB at 60–90 Hz; +2 dB at 2–3 kHz",
        "notes": "Keep short; don’t let it cover the bass on beat 1"
      },
      {
        "source": "Güiro / guacharaca",
        "cut": "HPF 300–500 Hz; dip 6–8 kHz if spitty",
        "boost": "+1–2 dB at 3–5 kHz",
        "notes": "Steady presence, not piercing; check it at low volume"
      },
      {
        "source": "Congas",
        "cut": "HPF 70–90 Hz; −2 dB at 200 Hz",
        "boost": "+1–2 dB at 300–400 Hz (tone); +2 dB at 4–5 kHz (slap)",
        "notes": "Light touch; slaps should crack, not click"
      },
      {
        "source": "Timbales / cowbell",
        "cut": "HPF 100–150 Hz; dip cowbell at 800 Hz–1.2 kHz if clangy",
        "boost": "+2 dB at 5–8 kHz for shell and rim",
        "notes": "Rolls should cut through without needing extra level"
      },
      {
        "source": "Accordion",
        "cut": "HPF 80–120 Hz (treble mic), 60 Hz (bass mic); −2–4 dB at 2.5–4 kHz (reed harshness); −2 dB at 250–400 Hz",
        "boost": "+1–2 dB at 1–2 kHz for bite; gentle 8–10 kHz shelf",
        "notes": "Musette tuning beats; avoid boosting where it gets shrill"
      },
      {
        "source": "Keyboards / keytar",
        "cut": "HPF 100–150 Hz; −2 dB at 300 Hz",
        "boost": "+1–2 dB at 2–3 kHz for leads",
        "notes": "Synth “accordion” patches often need 3 kHz tamed"
      },
      {
        "source": "Chicha guitar",
        "cut": "HPF 100 Hz; LPF 10–12 kHz; dip fuzz at 3–4 kHz",
        "boost": "+2 dB at 1–1.5 kHz",
        "notes": "Keep the surf twang; tape-ish top roll-off sounds right"
      },
      {
        "source": "Lead vocal",
        "cut": "HPF 90–120 Hz; −2–3 dB at 250–400 Hz",
        "boost": "+2–3 dB at 3–4 kHz; +1–2 dB at 10 kHz",
        "notes": "Spanish consonants need presence; avoid sibilant top"
      },
      {
        "source": "Horns",
        "cut": "HPF 120–150 Hz; −2 dB at 2.5–3.5 kHz if blaring",
        "boost": "+1–2 dB at 800 Hz–1 kHz",
        "notes": "Sit behind the vocal and lead instrument"
      }
    ],
    "notes": []
  },
  "compression": {
    "rows": [
      {
        "source": "Lead vocal",
        "use": "Yes",
        "ratio": "3:1–4:1",
        "attackRelease": "5–10 ms / 60–100 ms",
        "gainReduction": "3–6 dB",
        "notes": "Singers shout band names and coros; catch peaks"
      },
      {
        "source": "Sonidero MC mic",
        "use": "Yes",
        "ratio": "4:1–6:1",
        "attackRelease": "2–5 ms / 100 ms",
        "gainReduction": "6–8 dB",
        "notes": "Keeps saludos even over the track; gate or expander when idle"
      },
      {
        "source": "Accordion",
        "use": "Yes",
        "ratio": "3:1",
        "attackRelease": "10–20 ms / 100–150 ms",
        "gainReduction": "3–5 dB",
        "notes": "Tames bellows swells; optional multiband dip at 3 kHz"
      },
      {
        "source": "Bass",
        "use": "Yes",
        "ratio": "4:1",
        "attackRelease": "15–25 ms / 80–120 ms",
        "gainReduction": "3–6 dB",
        "notes": "Slow attack keeps the pluck that drives the bounce"
      },
      {
        "source": "Congas",
        "use": "Light",
        "ratio": "2:1–3:1",
        "attackRelease": "10–20 ms / fast",
        "gainReduction": "2–3 dB",
        "notes": "Fast attack kills the slap"
      },
      {
        "source": "Güiro",
        "use": "Optional",
        "ratio": "2:1",
        "attackRelease": "5 ms / fast",
        "gainReduction": "1–2 dB",
        "notes": "Mostly for consistency between scraper players"
      },
      {
        "source": "Horn section bus",
        "use": "Yes",
        "ratio": "3:1",
        "attackRelease": "10–20 ms / auto",
        "gainReduction": "2–4 dB",
        "notes": "Glues section hits"
      },
      {
        "source": "Mix bus",
        "use": "Optional",
        "ratio": "2:1",
        "attackRelease": "30 ms / auto",
        "gainReduction": "1–2 dB",
        "notes": "Gentle glue; keep groove breathing"
      }
    ],
    "notes": [
      {
        "text": "Prefer an expander (10–15 dB range) over hard gates on timbales; gates chop rolls. De-ess vocals at 5–8 kHz for 2–3 dB. Parallel percussion-bus compression blended 15–25% adds density."
      }
    ]
  },
  "fx": {
    "rows": [
      {
        "effect": "Sonidero echo",
        "appliedTo": "MC / saludos mic",
        "setting": "Tempo delay 1/4 or dotted 1/8, 40–60% feedback, HPF 300 Hz / LPF 4 kHz, plus 2–3 s hall",
        "amount": "Heavy (a stylistic signature)"
      },
      {
        "effect": "Plate reverb",
        "appliedTo": "Lead vocal",
        "setting": "1.0–1.6 s decay, 30–50 ms pre-delay",
        "amount": "Subtle–moderate"
      },
      {
        "effect": "Slap / tape delay",
        "appliedTo": "Chicha guitar, vocals in vintage styles",
        "setting": "90–140 ms, 10–25% feedback, dark return",
        "amount": "Moderate"
      },
      {
        "effect": "Spring reverb",
        "appliedTo": "Chicha guitar, organ",
        "setting": "1.5–2.5 s, amp spring",
        "amount": "Moderate–heavy, surf style"
      },
      {
        "effect": "Short room",
        "appliedTo": "Percussion bus",
        "setting": "0.5–0.8 s decay",
        "amount": "Subtle; percussion stays mostly dry"
      },
      {
        "effect": "Chorus / phaser",
        "appliedTo": "Keytar leads, villera synths",
        "setting": "0.5–1 Hz rate, 20–40% mix",
        "amount": "Part of the patch"
      },
      {
        "effect": "Plate on timbal solos",
        "appliedTo": "Timbales",
        "setting": "≤0.8 s decay",
        "amount": "Only in breaks"
      }
    ],
    "notes": [
      {
        "text": "Keep percussion dry; reverb blurs the güiro. The sonidero echo is meant to be obvious, but ride its return so it doesn’t smear the lead line."
      }
    ]
  },
  "vocals": [
    {
      "text": "The lead vocal sits about 2–4 dB above the accordion/keys by perceived level, every word clear; this audience sings along. Tone is warm and mid-forward; a nasal edge is normal in Colombian and chicha styles. Pitch correction is light in modern pop-cumbia (Grupo 5, Los Ángeles Azules); villera vocals are raw, often spoken-shouted. Coros are compressed harder, panned moderately wide, 4–6 dB under the lead. Use dynamic mics live; give the MC a dedicated channel with its own delay send. Notch cowbell bleed (800 Hz–1.2 kHz) on nearby vocal mics."
    }
  ],
  "loudness": [
    {
      "label": "Live:",
      "text": "Halls, ballrooms and festival stages typically run 94–100 dBA LAeq-15 at FOH with peaks to 108–110 dBA; C-weighted levels around 110–120 dBC. Crowds span children to grandparents; 96–98 dBA is usually plenty. Sonidero street systems lean on subs; a C-minus-A gap above 20 dB signals that low frequencies may be excessive. By common hearing-safety guidance, 100 dBA is safe for about 15 minutes, and every 3 dB more halves that; parties often run 4–6 hours, so offer earplugs and watch your own exposure."
    },
    {
      "label": "Studio / streaming:",
      "text": "Modern cumbia and tecnocumbia masters land around −10 to −8 LUFS-I, with true peak at −1 dBTP (−2 dBTP for masters louder than −14). Most streaming services normalize to −14 LUFS, so very loud masters gain nothing. A PLR of 9–11 dB keeps the bass bounce and güiro transients alive (at −2 dBTP that means a master at about −11 LUFS-I or quieter). Vintage-style productions (Ondatrópica, chicha revival) sit happily at −12 to −11."
    }
  ],
  "liveStudio": {
    "rows": [
      {
        "area": "Low end",
        "live": "Fight hall boom at 100–200 Hz; HPF percussion mics firmly",
        "studio": "Shape the bass bounce precisely, carve kick/bass with EQ or sidechain"
      },
      {
        "area": "Accordion",
        "live": "Clip-on mics (e.g., stereo clip kit) or a dynamic at 30–45 cm; watch feedback around 2–4 kHz",
        "studio": "Two condensers, one each side, 30–60 cm; blend treble and bass sides"
      },
      {
        "area": "Percussion",
        "live": "Bleed everywhere; a few close mics plus an overhead",
        "studio": "Separate tracks, room mics for natural conga ambience"
      },
      {
        "area": "Vocals / MC",
        "live": "Separate MC channel with tap-tempo echo for saludos",
        "studio": "Lead comping, doubled coros, automation of ad-libs"
      },
      {
        "area": "Effects",
        "live": "One plate, one tap delay, MC echo",
        "studio": "Spring, tape and plate per element; vintage character"
      },
      {
        "area": "Dynamics",
        "live": "Long sets; ride the lead instrument in solos",
        "studio": "Automation of solos, breaks and fills"
      },
      {
        "area": "Loudness",
        "live": "94–100 dBA Leq",
        "studio": "−10 to −8 LUFS-I, −1 dBTP"
      }
    ],
    "notes": []
  },
  "notes": [
    {
      "text": "Build the mix from bass and güiro first; if dancers stop swaying, check those two before anything else.",
      "bullet": true
    },
    {
      "text": "Don’t treat cumbia like reggaetón or EDM: a big sustained kick and sub boom smother the root–fifth bass pattern.",
      "bullet": true
    },
    {
      "text": "Mic the accordion from enough distance to hear both reed sides, or use dedicated clip-on systems; a single close mic on the grille sounds thin and harsh.",
      "bullet": true
    },
    {
      "text": "Tame the accordion and keyboard in the 2.5–4 kHz zone, where they compete with the vocal and turn shrill at volume.",
      "bullet": true
    },
    {
      "text": "Keep a dedicated MC mic and echo ready; dedications come unannounced.",
      "bullet": true
    },
    {
      "text": "Don’t over-gate timbales or congas; fills and ghost strokes are the groove.",
      "bullet": true
    },
    {
      "text": "Respect regional flavors: Colombian (accordion, horns), sonidera (keys, echo, slower), chicha (fuzz, wah, spring), villera (keytar, electronic drums, lo-fi grit).",
      "bullet": true
    }
  ],
  "references": [
    "Lucho Bermúdez y su Orquesta, “Prende la vela”, 1950s (Colombian big-band cumbia)",
    "Andrés Landero, “La Pava Congona”, 1960s",
    "Los Destellos, “Elsa”, 1968",
    "Los Mirlos, “Sonido Amazónico”, 1973",
    "La Sonora Dinamita, “Que Bello”, 1982",
    "Los Ángeles Azules, “El Listón de tu Pelo”, 1996",
    "Celso Piña y su Ronda Bogotá, “Cumbia sobre el río”, 2001",
    "Damas Gratis, “Se te ve la tanga”, 2000",
    "Ondatrópica, “Ondatrópica” (album), 2012"
  ],
  "empty": []
};
