/**
 * Mixing guide 43 — Dangdut. GENERATED by scripts/mixing-guides/convert.py
 * from the owner's guide (assets/Mixing-Guides-50-Styles, read only). Edit the
 * conversion (scripts/mixing-guides/edits.py), not this file.
 */
import type { MixingGuide } from '../types';

export const GUIDE: MixingGuide = {
  "id": "dangdut",
  "num": 43,
  "title": "Dangdut",
  "expects": "Audiences want to feel the kendang in the body, follow every word (they sing along and know the cengkok, the vocal ornaments), and hear suling and keyboard hooks answer the singer.",
  "glance": {
    "origin": "Indonesia: grew from Orkes Melayu in Jakarta and Surabaya (1950s–60s) into dangdut in the late 1960s–70s; dangdut koplo developed in East Java (Surabaya/Sidoarjo area) in the late 1990s–2000s",
    "tempo": "Classic dangdut 120–140 BPM; koplo feels faster (130–160 BPM) because the kendang packs in more strokes per bar; slow ballads 70–90 BPM",
    "ensemble": "Orkes (OM): 7–12 players — kendang, suling, 1–2 keyboards, 2 electric guitars, bass, mandolin, drum kit or tambourine, plus 2–6 rotating singers; solo “organ tunggal” keyboardist + kendang + singer",
    "priority": "The kendang: the low “dhut” and the crisp “tak” must punch through with the lead vocal riding on top",
    "liveSpl": "96–102 dBA LAeq-15 for village stages and festivals; 115–125 dBC; East Java caps static systems at 120 dB (2025 rule)",
    "studioLoudness": "Masters commonly −10 to −7 LUFS-I (video uploads often louder); streaming services normalize to about −14"
  },
  "purpose": [
    {
      "text": "Dangdut is dance music for crowds. Joget (free dancing) in front of the stage is the point, and koplo shows add saweran: fans hand money to the singer mid-song. Born among the urban working class and turned into a national sound by Rhoma Irama, it now plays at weddings, circumcision feasts, Independence Day stages, election rallies, TV shows and stadiums. Audiences want to feel the kendang in the body, follow every word (they sing along and know the cengkok, the vocal ornaments), and hear suling and keyboard hooks answer the singer. It “sounds wrong” when the kendang is buried under the kit, the sub turns the dhut to mush, the vocal is harsh or unclear, or the band sounds polite. Koplo “jos” breaks and fills are cue points where the dancing jumps."
    }
  ],
  "instruments": [
    {
      "label": "Kendang / gendang (ketipung):",
      "text": "paired hand drums, wood or PVC. The larger head (~20 cm) gives the low, pitch-bent “dhut” (like a tabla bayan); the small head (~15 cm) the sharp “tak.” East Java koplo may add bem and sabet drums. This is the lead rhythm voice.",
      "bullet": true
    },
    {
      "label": "Suling:",
      "text": "bamboo flute for intros, fills and vocal answers; breathy, ornamented, high.",
      "bullet": true
    },
    {
      "label": "Keyboards:",
      "text": "arranger workstations (home arranger keyboards are iconic) for strings, brass, organ, melodic leads and sometimes drum/bass patterns; in organ tunggal one keyboardist covers everything.",
      "bullet": true
    },
    {
      "label": "Electric guitars:",
      "text": "lead guitar with rock overdrive and Rhoma Irama–style fast runs; rhythm guitar playing clean offbeat chops.",
      "bullet": true
    },
    {
      "label": "Mandolin:",
      "text": "tremolo lines carried over from Orkes Melayu, still heard in classic dangdut.",
      "bullet": true
    },
    {
      "label": "Bass:",
      "text": "electric bass, usually simple, locked to the dhut.",
      "bullet": true
    },
    {
      "label": "Drum kit / tambourine:",
      "text": "a light kit (kick, hats, snare) or electronic pad. In koplo it supports the kendang rather than leading.",
      "bullet": true
    },
    {
      "label": "Playback:",
      "text": "backing tracks for TV and small shows; remix versions use drum machines.",
      "bullet": true
    }
  ],
  "arrangement": [
    {
      "text": "On a typical OM stage the kendang sits center on a riser near the front, keyboards to one side, guitars and bass on the other, suling near the singers, who take turns at center front. The kendang player is the real band leader: his fills cue starts, breaks, tempo shifts and endings. Classic dangdut runs intro (suling or guitar), a slower sung opening, then the full groove, with “dang” on beat 4 and “dhut” on beat 1. Koplo reverses this, fills each bar with five or more strokes, and adds a “reff” where the drums double up and the crowd sings. Guitar or suling solos between verses. Harmony: keyboards and rhythm guitar; melody: vocal, suling, keyboard lead, lead guitar; rhythm: kendang, bass, kit."
    }
  ],
  "dynamics": [
    {
      "text": "The slow intro can sit 8–12 dB below the full groove, with the koplo double-time reff as the peak. Kendang slaps and fills can jump 10–15 dB above the pattern. Indonesian studio practice favors fader automation over heavy compression. Preserve the intro-to-groove jump and reff lift; control kendang peaks and the level swings between rotating singers; ride the suling up for fills."
    }
  ],
  "balance": [
    {
      "text": "Hierarchy, loudest to quietest: lead vocal and kendang (roughly equal; the dhut is often the loudest low element), bass, suling and keyboard lead in their fills, lead guitar in solos, kick and hats, rhythm guitar and pads, mandolin, backing vocals, effects returns. Low end: the dhut lives around 80–150 Hz with a pitch bend, so the bass sits under it (40–90 Hz); keep the kit kick short and never let sub mask the kendang. Panning: vocal, kendang, suling, bass, kick and lead guitar center; keyboards and rhythm guitar left/right; mandolin, tambourine and backing vocals wide, with keyboard lows kept mono."
    }
  ],
  "eq": {
    "rows": [
      {
        "source": "Kendang – dhut (large head)",
        "cut": "HPF 45–55 Hz; −2–4 dB at 250–400 Hz (boxy)",
        "boost": "+2–4 dB at 90–130 Hz (body/bend); +2 dB at 2–3 kHz (finger slap)",
        "notes": "Find the pitch of the bend and keep the bass off it"
      },
      {
        "source": "Kendang – tak (small head)",
        "cut": "HPF 150–200 Hz; notch ring 800 Hz–1.5 kHz if it honks",
        "boost": "+2–3 dB at 3–5 kHz (crack); shelf +1–2 dB at 8–10 kHz",
        "notes": "Don’t let 4 kHz turn painful on big PA; dynamic EQ helps"
      },
      {
        "source": "Suling",
        "cut": "HPF 250–350 Hz; −2–3 dB at 5–6 kHz if breath is excessive",
        "boost": "+1–2 dB at 700 Hz–1 kHz (warmth); +1–2 dB at 2.5–3 kHz (presence)",
        "notes": "Keep some breath; it’s part of the sound"
      },
      {
        "source": "Keyboard (strings/brass/organ)",
        "cut": "HPF 100–150 Hz; −2 dB at 300–500 Hz",
        "boost": "+1–2 dB at 6–8 kHz shelf for strings",
        "notes": "Arranger patches are already bright and stereo; cut more than boost"
      },
      {
        "source": "Lead guitar",
        "cut": "HPF 100–120 Hz; dip 3–4 kHz if fizzy",
        "boost": "+2 dB at 1–1.5 kHz to push forward",
        "notes": "Fast runs need mid clarity, not top"
      },
      {
        "source": "Rhythm guitar",
        "cut": "HPF 150–200 Hz; LPF 10–12 kHz",
        "boost": "+1–2 dB at 2–3 kHz",
        "notes": "Thin it so it chops between kendang strokes"
      },
      {
        "source": "Bass",
        "cut": "HPF 35–40 Hz; −2–3 dB at 100–130 Hz if it masks the dhut",
        "boost": "+2 dB at 50–70 Hz; +2 dB at 700 Hz–1 kHz (definition)",
        "notes": "Sidechain or dynamic EQ to the dhut is useful in the studio"
      },
      {
        "source": "Kick (kit)",
        "cut": "HPF 40 Hz; −3–5 dB at 300–500 Hz",
        "boost": "+2 dB at 60–80 Hz; +2–3 dB at 2–4 kHz",
        "notes": "Short and tight; supports rather than leads"
      },
      {
        "source": "Mandolin",
        "cut": "HPF 200–250 Hz; −2 dB at 2.5 kHz if it’s spiky",
        "boost": "+1–2 dB at 5–7 kHz",
        "notes": "Tuck behind suling"
      },
      {
        "source": "Lead vocal",
        "cut": "HPF 90–120 Hz (female) / 70–90 Hz (male); −2–3 dB at 250–400 Hz",
        "boost": "+2–3 dB at 2.5–4 kHz (words); +1–2 dB at 10–12 kHz (air)",
        "notes": "Many singers are nasal and bright; watch 1–2 kHz and 3–4 kHz"
      }
    ],
    "notes": []
  },
  "compression": {
    "rows": [
      {
        "source": "Kendang (each mic)",
        "use": "Yes",
        "ratio": "3:1–4:1",
        "attackRelease": "10–20 ms / 60–100 ms",
        "gainReduction": "3–6 dB",
        "notes": "Slower attack keeps the slap; catches loud fills"
      },
      {
        "source": "Kendang bus (parallel)",
        "use": "Optional",
        "ratio": "6:1–8:1",
        "attackRelease": "3–10 ms / 80 ms",
        "gainReduction": "8–10 dB, blended 20–30%",
        "notes": "Thickens the dhut on large PA"
      },
      {
        "source": "Lead vocal",
        "use": "Yes",
        "ratio": "3:1–4:1",
        "attackRelease": "3–10 ms / 60–120 ms or auto",
        "gainReduction": "3–6 dB",
        "notes": "Singers rotate; save a scene or preset per singer"
      },
      {
        "source": "Suling",
        "use": "Light",
        "ratio": "2:1–3:1",
        "attackRelease": "10–20 ms / auto",
        "gainReduction": "2–3 dB",
        "notes": "Keeps fills steady without killing expression"
      },
      {
        "source": "Bass",
        "use": "Yes",
        "ratio": "4:1",
        "attackRelease": "10–20 ms / 100 ms",
        "gainReduction": "3–6 dB",
        "notes": "Even notes under the moving kendang"
      },
      {
        "source": "Keyboard bus",
        "use": "Light",
        "ratio": "2:1",
        "attackRelease": "20–30 ms / auto",
        "gainReduction": "1–3 dB",
        "notes": "Arranger sounds are pre-compressed"
      },
      {
        "source": "Mix bus",
        "use": "Optional",
        "ratio": "2:1",
        "attackRelease": "30 ms / auto",
        "gainReduction": "1–2 dB",
        "notes": "Glue only; kendang transients must survive"
      }
    ],
    "notes": [
      {
        "text": "Kendang rarely needs a gate; a gentle expander (−6 to −10 dB range, 100–150 ms release) cleans bleed on loud stages. De-ess bright voices at 6–9 kHz for 2–4 dB. Keep master limiting to 2–4 dB, or the dhut flattens and the tak turns brittle."
      }
    ]
  },
  "fx": {
    "rows": [
      {
        "effect": "Plate / hall reverb",
        "appliedTo": "Lead vocal",
        "setting": "1.4–2.2 s decay, 40–80 ms pre-delay, HPF 250 Hz",
        "amount": "Moderate (dangdut vocals are traditionally wetter than rock)"
      },
      {
        "effect": "Tempo delay",
        "appliedTo": "Vocal phrase ends, cengkok tails",
        "setting": "1/4 or dotted 1/8, 20–30% feedback, LPF 5 kHz",
        "amount": "Subtle–moderate, more in slow intros"
      },
      {
        "effect": "Room / short plate",
        "appliedTo": "Kendang",
        "setting": "0.6–1.0 s decay, 10–20 ms pre-delay",
        "amount": "Subtle; adds “resonance” without smearing strokes"
      },
      {
        "effect": "Hall reverb",
        "appliedTo": "Suling",
        "setting": "1.8–2.5 s decay, 30–60 ms pre-delay",
        "amount": "Moderate"
      },
      {
        "effect": "Slap delay",
        "appliedTo": "Lead guitar",
        "setting": "90–130 ms, 10% feedback",
        "amount": "Subtle"
      },
      {
        "effect": "Harmonic exciter",
        "appliedTo": "Mandolin, bass (studio)",
        "setting": "Light upper-harmonic or sub enhancer",
        "amount": "Subtle; used in Indonesian studio practice"
      }
    ],
    "notes": [
      {
        "text": "On big stages, pull vocal reverb back about a third in the koplo reff."
      }
    ]
  },
  "vocals": [
    {
      "text": "The singer is the star: about 3–5 dB above the band by feel, every word clear. Audiences judge the cengkok — slides, slow vibrato, rapid turns and, in modern koplo, Arabic-style throat ornaments — so compress gently enough that ornaments survive. Pitch correction is light and slow; hard tuning destroys cengkok (except in deliberate remix styles). Tone is bright and forward, often slightly nasal, with a generous reverb tail. Backing and crowd-answer vocals sit wide, 6–10 dB under. Male/female duets are common; match levels and EQ beforehand. Live, use a rugged dynamic, wired or wireless. Singers roam into the crowd during saweran, so pick a high-rejection capsule, ring out monitors and watch the front fills. Lyrics are mostly Indonesian or Javanese; clear consonants (2–4 kHz) matter more than air."
    }
  ],
  "loudness": [
    {
      "label": "Live:",
      "text": "Village stages, kampung festivals and touring OM shows usually run 96–102 dBA LAeq-15 at FOH, peaks 110–115 dBA, around 115–125 dBC. East Java’s “sound horeg” speaker-truck events, often playing koplo remixes, have measured 120–130 dB; in August 2025 the province capped stationary systems at 120 dB and moving units at 85 dB. A C-minus-A gap of 20 dB or more at 100 dBA signals excessive sub; dangdut needs controlled low-mids for the dhut, not EDM sub. Common hearing-safety guidance rates 100 dBA safe for about 15 minutes, and outdoor shows run 3–5 hours, so offer earplugs and protect your own hearing."
    },
    {
      "label": "Studio / streaming:",
      "text": "Masters typically land at −10 to −7 LUFS-I, true peak −1 dBTP (−2 dBTP when hotter than −14). Most listening is video streaming on phones, normalized to about −14 LUFS, so very loud masters just lose kendang punch. A PLR of 8–11 dB and LRA of 5–8 LU keep the intro-to-groove jump. On phone speakers the dhut must still read through its 2–3 kHz slap."
    }
  ],
  "liveStudio": {
    "rows": [
      {
        "area": "Kendang",
        "live": "Two close dynamics on tak and dhut heads, 3–8 cm; protect from keyboard and vocal bleed",
        "studio": "Add a condenser 30–60 cm above for natural tone; parallel bus for weight"
      },
      {
        "area": "Low end",
        "live": "Fight outdoor wind and tent boom; keep bass and kick off 90–130 Hz",
        "studio": "Sidechain or dynamic EQ bass to the dhut"
      },
      {
        "area": "Vocals",
        "live": "Many singers per night; preset per singer, heavy feedback control as they roam",
        "studio": "Comping, detailed rides, careful light tuning"
      },
      {
        "area": "Keyboards",
        "live": "Stereo DI from arranger; level swings between patches — ride constantly",
        "studio": "Patches printed, cleaned and layered"
      },
      {
        "area": "Effects",
        "live": "Tap-tempo delay and one vocal reverb; less wet in loud reff sections",
        "studio": "Multiple reverbs (plate, hall, room) automated by section"
      },
      {
        "area": "Dynamics",
        "live": "Mixed by hand; the kendang player’s cues drive changes",
        "studio": "Fader automation preferred over compression"
      },
      {
        "area": "Loudness",
        "live": "96–102 dBA LAeq-15, local caps (e.g., 120 dB East Java static systems)",
        "studio": "−10 to −7 LUFS-I, −1 dBTP"
      }
    ],
    "notes": []
  },
  "notes": [
    {
      "text": "Build the mix from kendang and vocal, then bass, then the rest.",
      "bullet": true
    },
    {
      "text": "Learn the kendang player’s cues (rolls, “jos” fills) that signal breaks, double-time and endings.",
      "bullet": true
    },
    {
      "text": "Don’t let the kit kick or sub replace the dhut; the kendang is the genre’s identity.",
      "bullet": true
    },
    {
      "text": "Tame 3–5 kHz on the tak through big PA; long outdoor shows tire ears fast.",
      "bullet": true
    },
    {
      "text": "Save a vocal preset per singer; singer-to-singer level swings are the most common live problem.",
      "bullet": true
    },
    {
      "text": "Ride the keyboard: arranger patches jump in level between strings, brass and organ.",
      "bullet": true
    },
    {
      "text": "Avoid hard tuning and over-limiting; both erase cengkok and kendang dynamics.",
      "bullet": true
    },
    {
      "text": "Leave headroom: koplo sets build for hours as the crowd joins in.",
      "bullet": true
    }
  ],
  "references": [
    "Ellya Khadam, “Boneka dari India”, mid-1950s (Orkes Melayu roots)",
    "Rhoma Irama & Soneta Group, “Begadang”, 1973",
    "Didi Kempot, “Pamer Bojo”, 2016",
    "Via Vallen, “Sayang”, 2017",
    "Nella Kharisma, “Jaran Goyang”, 2017",
    "Via Vallen, “Meraih Bintang”, 2018",
    "Siti Badriah, “Lagi Syantik”, 2018",
    "Denny Caknan, “Kartonyono Medot Janji”, 2019"
  ],
  "empty": []
};
