/**
 * Mixing guide 44 — MPB / Bossa Nova. GENERATED by scripts/mixing-guides/convert.py
 * from the owner's guide (assets/Mixing-Guides-50-Styles, read only). Edit the
 * conversion (scripts/mixing-guides/edits.py), not this file.
 */
import type { MixingGuide } from '../types';

export const GUIDE: MixingGuide = {
  "id": "mpb-bossa-nova",
  "num": 44,
  "title": "MPB / Bossa Nova",
  "expects": "Audiences listen to the words, and Brazilian crowds sing along—in a pagode roda that is the point.",
  "glance": {
    "origin": "Rio de Janeiro’s Zona Sul (Copacabana, Ipanema), late 1950s for bossa nova; MPB grows out of it from the mid-1960s across Brazil; samba and pagode roots in Rio’s subúrbios (Cacique de Ramos, late 1970s)",
    "tempo": "Bossa nova 120–145 BPM (felt “in two” at 60–72); MPB ballads and samba-canção 60–90; samba/pagode roughly 90–110 in 2/4",
    "ensemble": "Voice and violão alone; trio/quartet (guitar, piano, upright or electric bass, brushes/percussion); MPB tours 6–10 piece; pagode 5–8 players who all sing",
    "priority": "The voice and the nylon-string guitar as an equal, intimate pair, with every word of Portuguese clear",
    "liveSpl": "Bossa/voice-and-guitar 82–90 dBA LAeq-15; MPB theater 88–95 dBA; pagode/samba shows 95–100 dBA, about 110–118 dBC",
    "studioLoudness": "Bossa/MPB masters commonly −16 to −12 LUFS-I; modern pagode −10 to −8; streaming normalizes to about −14"
  },
  "purpose": [
    {
      "text": "Bossa nova was born as apartment and small-club music: a seated singer with a guitar (the “banquinho e violão” image). João Gilberto’s idea was to put a whole samba percussion section into the right hand of a guitar and to sing softly, almost speaking, instead of the operatic radio style that preceded him. MPB, which followed in the mid-1960s with Elis Regina, Chico Buarque, Caetano Veloso, Gilberto Gil, Milton Nascimento and Gal Costa, is song-first music: sophisticated harmony and poetry, often carrying political meaning written in metaphor to slip past military-era censors. Audiences listen to the words, and Brazilian crowds sing along—in a pagode roda that is the point."
    },
    {
      "text": "What sounds wrong to this audience: a voice that is loud and hyped rather than close and warm; a guitar that is boomy, quacky or buried; sibilant, brittle Portuguese; percussion that turns a gentle swing into a pounding backbeat; and too much reverb smearing harmony and syncopation. A mix that is loud in a seated theater is a failure."
    }
  ],
  "instruments": [
    {
      "label": "Violão (nylon-string guitar):",
      "text": "the heart of the style. The thumb plays the surdo-like bass on beats while the fingers pluck syncopated chords (the batida). Warm tone, fast decay; often an acoustic-electric with piezo in live MPB.",
      "bullet": true
    },
    {
      "label": "Voice:",
      "text": "close, conversational, low in effort.",
      "bullet": true
    },
    {
      "label": "Piano / electric piano:",
      "text": "Jobim-style sparse voicings; electric piano is common in 1970s MPB.",
      "bullet": true
    },
    {
      "label": "Bass:",
      "text": "upright in bossa trios; fretless or fingered electric in MPB.",
      "bullet": true
    },
    {
      "label": "Drums:",
      "text": "brushes, cross-stick rimclick, light hi-hat; bossa patterns rather than rock backbeats.",
      "bullet": true
    },
    {
      "label": "Samba percussion:",
      "text": "surdo (low drum marking beat 2), pandeiro (frame drum with jingles, often a nylon head in pagode), tamborim (small high drum played with a stick), ganzá/chocalho and caxixi (shakers), agogô (two-tone bell), cuíca (friction drum that “talks”), repique.",
      "bullet": true
    },
    {
      "label": "Pagode additions:",
      "text": "cavaquinho (small four-string, bright and percussive), banjo tuned like a cavaquinho, tantã (a low hand-played drum that replaces the surdo), repique de mão, 7-string violão carrying bass counterlines.",
      "bullet": true
    },
    {
      "label": "Winds and strings:",
      "text": "flute, tenor sax, strings. Playback is rare outside pop-MPB.",
      "bullet": true
    }
  ],
  "arrangement": [
    {
      "text": "The core is singer and guitar, sometimes the same person. A bossa trio adds piano or second guitar, bass and a drummer on brushes; the bass locks with the guitarist’s thumb and the drummer’s rimclick mimics a tamborim. MPB bands add a percussionist with a table of small instruments to one side and winds or strings opposite. In pagode the band sits in a circle (the roda) around a table; nearly everyone sings in unison choruses, and the cavaquinho leads harmony and intros."
    },
    {
      "text": "Arrangements breathe: voice and guitar first, the band entering on the second pass, a flute or sax solo, then near-solo voice for the last verse. In pagode the full percussion kicks in on the chorus while the audience sings."
    }
  ],
  "dynamics": [
    {
      "text": "Bossa nova is soft and narrow in level but rich in micro-dynamics: the difference between a ghosted thumb note and an accented chord is the groove. Over-compressing the guitar flattens the batida and kills the swing. MPB macro-dynamics can be wide—Elis Regina could go from whisper to belt within a phrase—so ride the vocal by hand rather than clamp it. Samba and pagode are steadier and louder, building through the set as the crowd joins in; leave headroom for the last 30 minutes."
    }
  ],
  "balance": [
    {
      "text": "Hierarchy for bossa and MPB, loudest to quietest: lead voice, violão (within 1–3 dB of the voice; Gilberto’s 1958 Odeon sessions used separate mics so voice and guitar were picked up equally), piano/keys, bass, solo instrument in its spot, brushes/rimclick, small percussion, reverb returns. Low end: the guitarist’s thumb and the bass share the bottom—keep the guitar’s lows filtered so the bass owns 40–120 Hz, and favor upright bass note definition over boom. Kick is light or absent. Pan voice, guitar and bass center (or guitar slightly off center if a second guitar is present). Piano in stereo but narrow, percussion panned 20–60% to place the shaker and tamborim opposite each other, strings wide."
    },
    {
      "text": "For pagode the hierarchy changes: lead singer, group chorus, cavaquinho and banjo, pandeiro, tantã/surdo, repique, then 7-string and bass. The surdo/tantã on beat 2 is the pulse; the bass should sit just above it."
    }
  ],
  "eq": {
    "rows": [
      {
        "source": "Violão (mic)",
        "cut": "HPF 70–90 Hz; −3 to −6 dB at 150–250 Hz (boom near the soundhole); −2 dB narrow at 800 Hz–1.2 kHz if boxy",
        "boost": "+1–2 dB at 3–5 kHz (finger attack); +1–2 dB shelf at 10–12 kHz",
        "notes": "Mic 15–30 cm from the 12th–14th fret; small-diaphragm condenser"
      },
      {
        "source": "Violão (piezo/DI)",
        "cut": "HPF 80–100 Hz; −4–6 dB at 1–2 kHz (“quack”); LPF 10–12 kHz",
        "boost": "+1–2 dB at 200 Hz if thin",
        "notes": "Blend with a mic or use an IR/acoustic simulator"
      },
      {
        "source": "Lead vocal",
        "cut": "HPF 80–120 Hz (higher on close condensers); −2–3 dB at 200–300 Hz (proximity)",
        "boost": "+1–2 dB at 2.5–4 kHz; +1 dB air at 10–12 kHz",
        "notes": "Gentle—soft voices get harsh fast if pushed"
      },
      {
        "source": "Upright bass",
        "cut": "HPF 35–40 Hz; −2–3 dB at 200–300 Hz",
        "boost": "+2 dB at 70–90 Hz; +1–2 dB at 700 Hz–1 kHz (note)",
        "notes": "Blend pickup and mic; watch feedback near 100–200 Hz"
      },
      {
        "source": "Piano / electric piano",
        "cut": "HPF 60–80 Hz; −2 dB at 250–400 Hz",
        "boost": "+1–2 dB at 2–4 kHz for definition",
        "notes": "Keep out of the voice’s 2–4 kHz zone when comping"
      },
      {
        "source": "Surdo / tantã",
        "cut": "HPF 35–40 Hz; −3–5 dB at 250–400 Hz (mud)",
        "boost": "+2–3 dB at 60–90 Hz; +2 dB at 2–3 kHz (stick/hand)",
        "notes": "LDC 30–90 cm away sounds more natural than a kick mic up close"
      },
      {
        "source": "Pandeiro",
        "cut": "HPF 120–150 Hz (keep slap); −2 dB at 400 Hz",
        "boost": "+2 dB at 200 Hz (head); +1–2 dB at 8–10 kHz (platinelas)",
        "notes": "Tame jingle spikes with a dynamic EQ at 4–6 kHz"
      },
      {
        "source": "Cavaquinho / banjo",
        "cut": "HPF 150–200 Hz; −2–4 dB at 2.5–4 kHz if piercing",
        "boost": "+1–2 dB at 600–900 Hz for body",
        "notes": "Competes with the vocal—carve rather than boost"
      },
      {
        "source": "Shaker / tamborim / agogô",
        "cut": "HPF 300–500 Hz; dip 3–5 kHz if harsh",
        "boost": "Slight shelf at 10 kHz",
        "notes": "Mostly a placement problem, not an EQ one"
      },
      {
        "source": "Brushes / overheads",
        "cut": "HPF 150–200 Hz",
        "boost": "+1 dB shelf at 8–10 kHz",
        "notes": "Rimclick should be audible but not snappy"
      }
    ],
    "notes": []
  },
  "compression": {
    "rows": [
      {
        "source": "Lead vocal",
        "use": "Yes (light)",
        "ratio": "2:1–3:1 (opto)",
        "attackRelease": "10–20 ms / program or 100–200 ms",
        "gainReduction": "2–4 dB",
        "notes": "Ride the fader first; add a 4:1 fast stage only for belters"
      },
      {
        "source": "Violão",
        "use": "Light",
        "ratio": "1.5:1–2:1",
        "attackRelease": "20–30 ms / 100–150 ms",
        "gainReduction": "1–3 dB",
        "notes": "Preserve thumb/finger contrast; automation over compression"
      },
      {
        "source": "Upright / electric bass",
        "use": "Yes",
        "ratio": "3:1",
        "attackRelease": "20–30 ms / 100 ms",
        "gainReduction": "2–4 dB",
        "notes": "Evens note level without losing the walk"
      },
      {
        "source": "Piano",
        "use": "Light",
        "ratio": "2:1",
        "attackRelease": "20–30 ms / auto",
        "gainReduction": "1–2 dB",
        "notes": "Mostly for live consistency"
      },
      {
        "source": "Percussion subgroup",
        "use": "Yes",
        "ratio": "2:1–3:1",
        "attackRelease": "10–20 ms / 80–100 ms",
        "gainReduction": "2–3 dB",
        "notes": "Light group compression, as on intimate bossa tours"
      },
      {
        "source": "Pandeiro / cavaquinho (pagode)",
        "use": "Yes",
        "ratio": "3:1–4:1",
        "attackRelease": "5–10 ms / 60–80 ms",
        "gainReduction": "3–5 dB",
        "notes": "Controls jingle and strum spikes"
      },
      {
        "source": "Chorus vocals (pagode)",
        "use": "Yes",
        "ratio": "4:1",
        "attackRelease": "5–10 ms / 80 ms",
        "gainReduction": "4–6 dB",
        "notes": "Keeps the group block steady"
      },
      {
        "source": "Mix bus",
        "use": "Optional",
        "ratio": "1.5:1–2:1",
        "attackRelease": "30 ms / auto",
        "gainReduction": "0.5–1.5 dB",
        "notes": "Glue only"
      }
    ],
    "notes": [
      {
        "text": "Avoid gates on percussion and guitar. Use a de-esser on the voice at 6–8 kHz for 2–3 dB; Portuguese “s,” “ch” and “x” sounds are frequent. Parallel compression is useful in pagode (drums, bass, voices) but rarely in bossa nova. Master limiting for bossa should stay at 1–2 dB."
      }
    ]
  },
  "fx": {
    "rows": [
      {
        "effect": "Small room / chamber",
        "appliedTo": "Whole band, guitar",
        "setting": "0.6–1.0 s decay, 10–20 ms pre-delay",
        "amount": "Subtle—the room is part of the intimacy"
      },
      {
        "effect": "Plate reverb",
        "appliedTo": "Lead vocal",
        "setting": "1.2–1.8 s decay, 30–60 ms pre-delay, HPF 200 Hz / LPF 6 kHz",
        "amount": "Subtle"
      },
      {
        "effect": "Hall",
        "appliedTo": "Strings, flute, sax, ballads",
        "setting": "1.8–2.5 s decay, 40–80 ms pre-delay",
        "amount": "Moderate"
      },
      {
        "effect": "Slap / short delay",
        "appliedTo": "Vocal (MPB, pagode)",
        "setting": "80–120 ms, 0–10% feedback, filtered",
        "amount": "Subtle"
      },
      {
        "effect": "Tempo delay",
        "appliedTo": "Phrase ends, solos",
        "setting": "1/4 or dotted 1/8, 15–20% feedback",
        "amount": "Subtle, automated"
      },
      {
        "effect": "Tremolo / chorus",
        "appliedTo": "electric piano, clean electric guitar",
        "setting": "Slow rate (0.5–2 Hz)",
        "amount": "Part of the tone"
      }
    ],
    "notes": [
      {
        "text": "Two reverbs and a delay cover almost every show. Keep the voice and guitar drier than you would in pop: the listener should feel close to the singer."
      }
    ]
  },
  "vocals": [
    {
      "text": "The voice sits on top but close, not floating above the band like pop. In bossa nova, voice and guitar sit nearly level; in MPB the voice leads by roughly 2–4 dB of perceived level. Tone should be warm and present with little air hype; soft singers like Gilberto, Nara Leão or Bebel Gilberto rely on proximity, so manage the 150–300 Hz buildup instead of pushing highs. Pitch correction is used sparingly and should never be audible—the slightly behind-the-beat, speech-like phrasing is the style, so don’t quantize or tighten timing. Doubles are rare; pagode choruses are a unison block tucked 3–6 dB under the lead."
    },
    {
      "text": "Live, a handheld condenser with a light chain helps soft voices. A dynamic mic works for louder pagode singers. Intelligibility in Portuguese depends on 1–4 kHz and on nasal vowels; don’t cut too deep around 1 kHz."
    }
  ],
  "loudness": [
    {
      "label": "Live:",
      "text": "Voice-and-guitar bossa in clubs and theaters works at 82–90 dBA LAeq-15 at FOH, peaks under 100 dBA; the audience is often seated and silent. Full-band MPB in theaters runs 88–95 dBA, festival stages 95–100 dBA (big MPB festival rigs use L/C/R arrays mainly for vocal clarity, not level). Pagode and samba shows run 95–100 dBA, about 110–118 dBC, with moderate sub for surdo and bass; a C-minus-A gap above 20 dB means too much sub. Gain-before-feedback on nylon guitar and soft vocals is the real limit; keep stage levels low. Common hearing-safety guidance allows only about 30 minutes at 97 dBA, so offer earplugs at pagode shows."
    },
    {
      "label": "Studio / streaming:",
      "text": "Bossa and MPB masters typically land at −16 to −12 LUFS-I with a peak-to-loudness ratio of 12–16 dB and true peak at −1 dBTP; classic reissues are often quieter. Modern pagode and samba-pop masters run −10 to −8 LUFS-I, true peak −1 to −2 dBTP. Most streaming services normalize to about −14, so a loud bossa master gains nothing and loses the batida’s detail. A loudness range of 6–10 LU is normal for MPB."
    }
  ],
  "liveStudio": {
    "rows": [
      {
        "area": "Violão",
        "live": "Piezo + clip-on mic blended; notch feedback around 150–250 Hz",
        "studio": "Pair of small-diaphragm condensers or a vintage-style tube condenser, 20–40 cm away"
      },
      {
        "area": "Vocals",
        "live": "Handheld condenser, minimal FX, careful feedback control",
        "studio": "Close large-diaphragm condenser; figure-8 nulls when singer plays guitar"
      },
      {
        "area": "Percussion",
        "live": "Few mics, subgroup compression, low monitor bleed",
        "studio": "LDC at 60–120 cm per instrument; room mics give air"
      },
      {
        "area": "Low end",
        "live": "Fight room boom; HPF guitar firmly, modest subs",
        "studio": "Fine-tune bass vs thumb notes; upright resonance kept natural"
      },
      {
        "area": "Dynamics",
        "live": "Ride the vocal and guitar live; seated rooms need low level",
        "studio": "Automation rides instead of heavy compression"
      },
      {
        "area": "Effects",
        "live": "Two reverbs and one delay",
        "studio": "Real rooms, plates, halls for strings; automated sends"
      },
      {
        "area": "Loudness",
        "live": "82–100 dBA depending on genre and room",
        "studio": "−16 to −12 LUFS-I (bossa/MPB), −10 to −8 (pagode)"
      }
    ],
    "notes": []
  },
  "notes": [
    {
      "text": "Start with the source: guitar position, singer’s distance from the mic, and room choice matter more than plug-ins.",
      "bullet": true
    },
    {
      "text": "When a singer plays the guitar, use figure-8 mics with nulls aimed at the other source, or spread mics apart; this can cut spill by 3–6 dB.",
      "bullet": true
    },
    {
      "text": "Keep piezo “quack” out of the PA; blend a mic or cut 1–2 kHz.",
      "bullet": true
    },
    {
      "text": "Bossa nova is not a rock band: no punchy kick or snapping snare.",
      "bullet": true
    },
    {
      "text": "Don’t over-tune or tighten timing—Portuguese phrasing that floats around the beat is the style.",
      "bullet": true
    },
    {
      "text": "Tune surdo and tantã so they don’t fight the bass.",
      "bullet": true
    },
    {
      "text": "In pagode, leave room for the crowd singing; it is part of the show.",
      "bullet": true
    }
  ],
  "references": [
    "João Gilberto, “Chega de Saudade”, 1959",
    "Stan Getz & João Gilberto, “Getz/Gilberto”, 1964",
    "Elis Regina & Antônio Carlos Jobim, “Elis & Tom”, 1974",
    "Caetano Veloso, “Caetano Veloso” (“Irene” / “Não Identificado” album), 1969",
    "Chico Buarque, “Construção”, 1971",
    "Milton Nascimento & Lô Borges, “Clube da Esquina”, 1972",
    "Fundo de Quintal, “Samba é no Fundo de Quintal”, 1980",
    "Bebel Gilberto, “Tanto Tempo”, 2000",
    "Marisa Monte, “Portas”, 2021"
  ],
  "empty": []
};
