/**
 * Mixing guide 46 — Lo-fi / Chillhop. GENERATED by scripts/mixing-guides/convert.py
 * from the owner's guide (assets/Mixing-Guides-50-Styles, read only). Edit the
 * conversion (scripts/mixing-guides/edits.py), not this file.
 */
import type { MixingGuide } from '../types';

export const GUIDE: MixingGuide = {
  "id": "lo-fi-chillhop",
  "num": 46,
  "title": "Lo-fi / Chillhop",
  "expects": "Listeners want a steady, warm, nostalgic mood that never demands attention: dusty jazz or soul chords, vinyl crackle, rain, a lazy behind-the-beat groove.",
  "glance": {
    "origin": "Instrumental hip-hop beat scenes of the late 1990s–2000s (J Dilla and Madlib in the US, Nujabes in Tokyo); grew into a streaming genre from about 2013–2017 (24/7 streams from France, a key label in Rotterdam)",
    "tempo": "70–95 BPM (some chillhop up to 100), heavily swung 16ths",
    "ensemble": "Solo producer with sampler/laptop; live sets 1–2 people (sampler + keys), occasionally a 3–5 piece band (keys, guitar, bass, drums, horn)",
    "priority": "The warm, swung drum-and-keys pocket: a soft, round kick and dusty snare under a mellow, filtered chord loop, with nothing harsh",
    "liveSpl": "85–95 dBA Leq (LAeq-15 min); roughly 100–110 dBC; café/lounge sets 75–85 dBA",
    "studioLoudness": "Masters commonly −14 to −10 LUFS-I, true peak −1 dBTP; streaming normalizes to about −14"
  },
  "purpose": [
    {
      "text": "Lo-fi is functional background music for studying, working, gaming and winding down. Its huge audience mostly hears it through 24/7 livestreams and playlists (the best-known 24/7 stream started in 2017 and became a cultural symbol) or seasonal label compilations. Listeners want a steady, warm, nostalgic mood that never demands attention: dusty jazz or soul chords, vinyl crackle, rain, a lazy behind-the-beat groove. Imperfection is the point, borrowed from J Dilla’s unquantized sampler drums and Nujabes’ rolled-off jazz samples. What sounds “wrong” here: brittle hi-hats, a clicky modern kick, loud sudden transients, wide jumps in level between tracks on a playlist, sub bass that rattles laptop speakers, a vocal sample that jumps out, or noise so heavy the music feels broken rather than worn."
    }
  ],
  "instruments": [
    {
      "label": "Drums:",
      "text": "sampled breaks or soft one-shots (often from old records, vintage-sampler style), kick and snare rounded, hats and shakers low-passed; brushes and rimshots common.",
      "bullet": true
    },
    {
      "label": "Keys:",
      "text": "electric pianos (tine and reed), felt or upright piano, jazz-voiced 7th/9th chords; often the main melodic element.",
      "bullet": true
    },
    {
      "label": "Guitar:",
      "text": "clean jazz or nylon-string guitar, chorus-y electric licks.",
      "bullet": true
    },
    {
      "label": "Bass:",
      "text": "upright or electric bass samples, filtered sample-basslines, or a soft sine/808 sub.",
      "bullet": true
    },
    {
      "label": "Textures:",
      "text": "vinyl crackle, tape hiss, rain, café ambience, anime or old-film dialogue snippets, field recordings.",
      "bullet": true
    },
    {
      "label": "Hardware/plugins as instruments:",
      "text": "compact performance samplers (lo-fi, vinyl and cassette sims, a built-in compressor), pad samplers and vintage 12-bit-style samplers; vinyl, lo-fi and tape emulation plug-ins.",
      "bullet": true
    },
    {
      "label": "Occasional live adds:",
      "text": "saxophone, flute, trumpet, vocal chops.",
      "bullet": true
    }
  ],
  "arrangement": [
    {
      "text": "Most tracks are short (1:30–3:00) loops: an intro with filtered chords or crackle alone, drums enter, a B section with a counter-melody or chord change, a breakdown where drums drop or the low-pass closes, then a fade or tape-stop ending. Keys carry harmony and melody, drums and bass carry the pocket, textures fill the gaps. Live, the typical setup is a table with a compact sampler and a controller, sometimes a keyboard player; the producer mutes and filters stems, resamples, and uses delay throws to bridge between beats (no crossfader on most samplers). Band versions place drums center, bass beside it, keys and guitar either side, horn or flute front."
    }
  ],
  "dynamics": [
    {
      "text": "Lo-fi has small macro-dynamics: sections differ by 2–5 dB, mostly through filtering and arrangement drops rather than level jumps. Micro-dynamics are deliberately softened: transients are rounded by saturation, tape and gentle compression so the track can sit under conversation or concentration. Preserve the gentle swell of a breakdown into the full groove, but control spikes (snare hits, sample pops, a loud vocal chop). Consistency across a playlist matters more than in almost any other genre; a track that jumps 3 dB louder than its neighbors breaks the spell."
    }
  ],
  "balance": [
    {
      "text": "Hierarchy, loudest to quietest: kick and snare (soft but clear), keys/main loop, bass, melody or lead sample, hats and percussion, textures, ambience and FX returns. The kick is a short round thump around 60–90 Hz; the bass owns the sustained low end, usually ducked by the kick with sidechain. Keep total low end modest, since much listening is on earbuds and laptops. Kick, snare, bass and main loop sit center; hats and shakers slightly off-center; guitar or counter-melody panned 20–40% opposite the keys; crackle and rain wide. Lo-fi often uses a somewhat narrowed stereo field, which suits the “old record” feel."
    }
  ],
  "eq": {
    "rows": [
      {
        "source": "Kick",
        "cut": "HPF 30–40 Hz; −3 dB at 300–500 Hz; LPF 5–8 kHz",
        "boost": "+2–3 dB at 60–90 Hz",
        "notes": "Remove beater click; it should “thud,” not tick"
      },
      {
        "source": "Snare / rim",
        "cut": "HPF 100–150 Hz; −2–4 dB at 3–5 kHz",
        "boost": "+2 dB at 180–250 Hz (body)",
        "notes": "LPF around 6–8 kHz keeps it dusty"
      },
      {
        "source": "Hats / shakers",
        "cut": "HPF 300–500 Hz; LPF 7–10 kHz",
        "boost": "—",
        "notes": "Keep 1–2 dB under where they first feel right; brightness tires listeners"
      },
      {
        "source": "Drum break bus",
        "cut": "HPF 40 Hz; dip 2–4 kHz if harsh",
        "boost": "+1–2 dB at 100–200 Hz",
        "notes": "Bit-reduce to 12-bit / ~22–26 kHz for sampler grit"
      },
      {
        "source": "Keys / chord loop (electric piano, piano)",
        "cut": "HPF 150–200 Hz; LPF 1.5–4 kHz (12 dB/oct), opened for breakdown lift",
        "boost": "+1–2 dB at 400–800 Hz (warmth)",
        "notes": "The classic “muffled” loop; automate cutoff for movement"
      },
      {
        "source": "Bass (upright/electric)",
        "cut": "HPF 35 Hz; −2 dB at 250 Hz",
        "boost": "+2 dB at 80–100 Hz; small lift at 700 Hz–1 kHz for laptop audibility",
        "notes": "Sine subs need harmonics (saturation) to read on small speakers"
      },
      {
        "source": "Guitar",
        "cut": "HPF 150–200 Hz; LPF 6–8 kHz",
        "boost": "+1–2 dB at 1–2 kHz",
        "notes": "Keep it out of the keys’ 300–600 Hz zone"
      },
      {
        "source": "Vocal chop / dialogue sample",
        "cut": "HPF 200–300 Hz; LPF 4–6 kHz",
        "boost": "+1–2 dB at 1–2 kHz",
        "notes": "Band-limited “telephone/film” tone; sits behind the loop"
      },
      {
        "source": "Crackle / rain textures",
        "cut": "HPF 200–500 Hz",
        "boost": "—",
        "notes": "Keep 15–25 dB below the main loop"
      },
      {
        "source": "Master",
        "cut": "HPF 25–30 Hz",
        "boost": "Optional gentle shelf −1 to −3 dB above 10–12 kHz",
        "notes": "Master-bus top roll-off is a common genre choice"
      }
    ],
    "notes": []
  },
  "compression": {
    "rows": [
      {
        "source": "Drum bus",
        "use": "Yes",
        "ratio": "4:1",
        "attackRelease": "10–30 ms / 80–150 ms (or auto)",
        "gainReduction": "3–5 dB",
        "notes": "Glue and soften; vintage FET or VCA style"
      },
      {
        "source": "Kick",
        "use": "Light",
        "ratio": "3:1",
        "attackRelease": "20–30 ms / 60 ms",
        "gainReduction": "2–3 dB",
        "notes": "Saturation often does more than compression"
      },
      {
        "source": "Bass (sidechained to kick)",
        "use": "Yes",
        "ratio": "4:1–6:1",
        "attackRelease": "1–5 ms / 80–150 ms (tempo-timed)",
        "gainReduction": "3–6 dB on kick hits",
        "notes": "Creates the gentle breathing pump"
      },
      {
        "source": "Keys / loop (sidechain)",
        "use": "Optional",
        "ratio": "2:1–4:1",
        "attackRelease": "5–10 ms / 150–250 ms",
        "gainReduction": "1–3 dB",
        "notes": "Subtle duck on kick for space and sway"
      },
      {
        "source": "Keys / loop (level)",
        "use": "Yes",
        "ratio": "2:1–3:1",
        "attackRelease": "20–30 ms / auto",
        "gainReduction": "2–4 dB",
        "notes": "Opto style for smooth, even chords"
      },
      {
        "source": "Vocal (if sung or rapped)",
        "use": "Yes",
        "ratio": "3:1–4:1",
        "attackRelease": "5–10 ms / 60–100 ms",
        "gainReduction": "3–6 dB",
        "notes": "De-ess 5–8 kHz, 2–4 dB"
      },
      {
        "source": "Mix bus",
        "use": "Yes",
        "ratio": "2:1",
        "attackRelease": "30 ms / auto",
        "gainReduction": "1–3 dB",
        "notes": "Cohesive “one record” glue"
      }
    ],
    "notes": [
      {
        "text": "Many producers deliberately over-compress the 2-bus or use a compact sampler’s built-in compressor on the whole beat; aim for warmth and density, not pumping you notice. Parallel drum compression (8:1, 8–10 dB, blended 20–30%) adds weight to quiet breaks. Gates are rarely used; noise and bleed are part of the sound. Master limiting should take 1–3 dB at most."
      }
    ]
  },
  "fx": {
    "rows": [
      {
        "effect": "Tape saturation / wow & flutter",
        "appliedTo": "Keys, guitar, whole mix",
        "setting": "Drive to 1–3% THD feel; wow 0.3–1 Hz, depth a few cents; flutter faint",
        "amount": "Moderate on keys; subtle on mix bus"
      },
      {
        "effect": "Vinyl sim / crackle layer",
        "appliedTo": "Mix bus or separate texture track",
        "setting": "Crackle −25 to −35 dBFS; hum off or very low; slight LPF",
        "amount": "Subtle to moderate"
      },
      {
        "effect": "Bitcrush / sample-rate reduction",
        "appliedTo": "Drums, sample chops",
        "setting": "12-bit, 22–26 kHz (vintage 12-bit sampler feel); blend 30–60%",
        "amount": "Moderate"
      },
      {
        "effect": "Room / plate reverb",
        "appliedTo": "Snare, keys",
        "setting": "0.8–1.5 s decay, 10–30 ms pre-delay, LPF returns at 4–6 kHz",
        "amount": "Subtle to moderate"
      },
      {
        "effect": "Long dark hall",
        "appliedTo": "Melody, guitar, breakdowns",
        "setting": "2.5–4 s decay, heavily damped",
        "amount": "Moderate, ducked by drums"
      },
      {
        "effect": "Tempo delay",
        "appliedTo": "Melody, chops, live transitions",
        "setting": "1/4 or dotted 1/8, 25–45% feedback, filtered 300 Hz–3 kHz",
        "amount": "Subtle; heavier as a throw"
      },
      {
        "effect": "Chorus / phaser / rotary",
        "appliedTo": "electric piano, guitar",
        "setting": "0.3–0.8 Hz rate, low depth",
        "amount": "Part of the tone"
      }
    ],
    "notes": [
      {
        "text": "Run noise and crackle as their own tracks so they can be balanced, faded at the ends, and kept consistent across a release."
      }
    ]
  },
  "vocals": [
    {
      "text": "Most lo-fi is instrumental; voices arrive as film or anime dialogue snippets, chopped soul vocals, or soft hums. Treat them as instruments: band-limited, 3–6 dB behind the loop, often with delay tails. Chillhop and lo-fi songs with singers (bedroom-pop crossover) want an intimate, close, breathy vocal: condenser at 15–20 cm, light pitch correction that stays inaudible, gentle saturation, a short plate, and a double or harmony tucked 8–12 dB under. Rapped verses over lo-fi beats (in the Madlib/Nujabes tradition) sit forward and dry with a slap of 80–120 ms. Live, use a warm dynamic or handheld condenser and avoid bright presence boosts; intelligibility comes from a clean 1–3 kHz, not from 8 kHz sizzle. Clear sample rights for spoken-word and vocal snippets before release."
    }
  ],
  "loudness": [
    {
      "label": "Live:",
      "text": "Lo-fi shows run from café and record-store sets (75–85 dBA) to club and festival beat sets (90–98 dBA LAeq-15), with C-weighted levels around 100–110 dBC. The crowd often sits or sways; the goal is an immersive, warm level where people can still talk at the bar. Keep C-minus-A under about 15 dB: a sine sub that sounds polite on earbuds can boom in a room, so HPF the PA around 35–40 Hz and watch 50–80 Hz. Samplers often output consumer-level signals (−10 dBV) with noisy floors; take them through good DIs and set gain so the crackle does not become hiss. Peaks rarely need to exceed 105 dBA."
    },
    {
      "label": "Studio / streaming:",
      "text": "Most releases land at −14 to −10 LUFS-I, with true peak at −1 dBTP; a few catalog tracks run quieter (−16). Since streaming services normalize to about −14, mastering hotter buys nothing and costs softness. Because playlists matter so much, match loudness across an album or compilation within about 1 LU. PLR of 9–13 dB and LRA of 3–6 LU are typical; the genre tolerates little dynamic range but hates squashed, clipped transients."
    }
  ],
  "liveStudio": {
    "rows": [
      {
        "area": "Sources",
        "live": "Stereo pair from sampler/laptop, maybe split stems; occasional keys/sax mics",
        "studio": "Every sample, texture and FX layer controllable"
      },
      {
        "area": "Low end",
        "live": "Room boom from sine subs; HPF 35–40 Hz, tame 60–80 Hz, compensate for crowd absorption",
        "studio": "Keep sub restrained for earbuds and laptops"
      },
      {
        "area": "Top end",
        "live": "Pre-filtered sources can sound dull on a big PA; a broad +1–2 dB at 3–5 kHz on the input may help",
        "studio": "Low-pass freely; dull is the aesthetic"
      },
      {
        "area": "Noise",
        "live": "Crackle and hiss get amplified with gain; manage with input gain, not gates",
        "studio": "Textures as separate, balanced tracks"
      },
      {
        "area": "Transitions",
        "live": "Producer bridges beats with delay throws, FX pads, resampling; ride level so jumps stay under 2 dB",
        "studio": "Fades, tape stops and crossfades on the master"
      },
      {
        "area": "Loudness",
        "live": "85–95 dBA Leq; seated/lounge sets lower",
        "studio": "−14 to −10 LUFS-I, matched across release"
      },
      {
        "area": "Monitoring",
        "live": "Small wedge or IEMs; artist mainly needs to hear the sampler",
        "studio": "Check on earbuds, laptop and phone speakers"
      }
    ],
    "notes": []
  },
  "notes": [
    {
      "text": "Filter, saturate and soften rather than boost; let the chord loop’s tone set the mood.",
      "bullet": true
    },
    {
      "text": "Don’t over-quantize drums; nudge hats and snares 5–20 ms late for that lazy Dilla feel, keep the kick close to the grid.",
      "bullet": true
    },
    {
      "text": "Too much crackle and wow turns warm into seasick; automate textures and test at low listening level.",
      "bullet": true
    },
    {
      "text": "Check mono: chorus, wide crackle and stereo widening often collapse badly.",
      "bullet": true
    },
    {
      "text": "Make sure bass is audible on phone speakers through 700 Hz–1 kHz harmonics, not more sub.",
      "bullet": true
    },
    {
      "text": "Live, ask for stems or a separate drums/music split if possible; it makes room tuning far easier.",
      "bullet": true
    },
    {
      "text": "Watch levels between beats in a live set; uneven sampler patches are the biggest problem.",
      "bullet": true
    }
  ],
  "references": [
    "Nujabes, “Aruarian Dance”, 2004",
    "Nujabes feat. Cise Starr & Akin, “Feather”, 2005",
    "J Dilla, Donuts, 2006",
    "Madvillain, Madvillainy, 2004",
    "Knxwledge, Hud Dreems, 2015",
    "Tomppabeats, Harbor LP, 2016",
    "Various Artists (Chillhop Music), Chillhop Essentials Summer 2016, 2016",
    "potsu feat. shiloh, “I’m Closing My Eyes”, 2017"
  ],
  "empty": []
};
