/**
 * Mixing guide 48 — Musical Theatre. GENERATED by scripts/mixing-guides/convert.py
 * from the owner's guide (assets/Mixing-Guides-50-Styles, read only). Edit the
 * conversion (scripts/mixing-guides/edits.py), not this file.
 */
import type { MixingGuide } from '../types';

export const GUIDE: MixingGuide = {
  "id": "musical-theatre",
  "num": 48,
  "title": "Musical Theatre",
  "expects": "Theatre audiences are seated, attentive and paying high ticket prices; they expect the sound to be clear, warm and “invisible,” with the voice appearing to come from the performer’s mouth rather than from a speaker cluster.",
  "glance": {
    "origin": "Broadway (New York) and London’s West End, from operetta and vaudeville roots in the early 1900s; radio-mic’d “megamusical” sound from the 1980s; now worldwide touring and resident productions",
    "tempo": "Wide: 60–90 BPM ballads, 100–140 BPM up-tempo and dance numbers, frequent rubato, tempo changes and spoken-over underscore within a single song",
    "ensemble": "15–40 cast on body mics (principals often double-mic’d) plus a 6–25 piece pit orchestra or band; 100–140+ inputs on a large show",
    "priority": "Every word intelligible — lyrics and dialogue carry the story — with voices that seem to come from the actor, not the speakers",
    "liveSpl": "Book/legit shows roughly 80–88 dBA LAeq over an act, big numbers peaking 95–100 dBA; rock/pop-score musicals 90–96 dBA LAeq with peaks near 105 dBA (approximate industry ranges, not published limits)",
    "studioLoudness": "Cast albums commonly −14 to −10 LUFS-I (traditional orchestral scores toward −16 to −13; pop/hip-hop scores −11 to −9); streaming normalizes to about −14"
  },
  "purpose": [
    {
      "text": "A musical is storytelling first: songs exist to move plot and reveal character, so the audience must catch every lyric, every joke and every whispered line. Theatre audiences are seated, attentive and paying high ticket prices; they expect the sound to be clear, warm and “invisible,” with the voice appearing to come from the performer’s mouth rather than from a speaker cluster. The target is to hear every word as easily as on TV while the show still feels exciting and unamplified. What makes this audience say “that sounded wrong”: a missed first word from a late fader, a phasey voice from two open mics, an orchestra burying a lyric, a boomy body mic, costume rustle, or a show so loud it becomes tiring."
    }
  ],
  "instruments": [
    {
      "label": "Voices on body mics:",
      "text": "miniature omni lavaliers worn at the hairline, over the ear or under wigs; visible headset booms for loud rock/pop scores where hidden mics cannot get enough gain.",
      "bullet": true
    },
    {
      "label": "Pit orchestra:",
      "text": "strings, woodwind doublers (one player on flute, clarinet and sax), brass, harp, piano and synths (string/brass patches thicken a small band), bass, drums, percussion, guitars.",
      "bullet": true
    },
    {
      "label": "Rock and pop scores:",
      "text": "onstage or isolated bands with drum shields and in-ears (Rock of Ages, Hamilton, Six).",
      "bullet": true
    },
    {
      "label": "Playback:",
      "text": "Show-control or DAW cues for effects, atmospheres and stems; click to the drummer; character voice processing.",
      "bullet": true
    },
    {
      "label": "Floats:",
      "text": "occasional front-of-stage pickups for dance taps.",
      "bullet": true
    }
  ],
  "arrangement": [
    {
      "text": "The cast moves freely across a proscenium stage; the orchestra sits in a pit, a back-stage band room or on set, often watching the conductor on video monitors. Principals carry melody and dialogue; the ensemble adds harmony and weight; the orchestra plays underscore under dialogue, then swells for songs. A number typically moves from scene with underscore into verse, build and “button” (the final chord that cues applause). The mixer works from a marked script showing every mic pickup, and console scenes reassign DCA/VCA faders scene by scene so the same physical fader might control a different actor every few minutes."
    }
  ],
  "dynamics": [
    {
      "text": "Musical theatre has the widest dynamic range of almost any amplified genre. A show can carry 30–40 dB of program dynamic range compared with 5–10 dB at a concert: underscore might sit around −25 dB on the band VCA while a finale peaks at +10 dB. Preserve that range — the hush before a big ballad note is what makes the note land. Control comes from hands on faders, not heavy compression. Leave headroom so the Act 2 finale can be the biggest moment."
    }
  ],
  "balance": [
    {
      "text": "Hierarchy, loudest to quietest: the speaking or singing principal, other principals in a duet, ensemble vocals, melodic orchestra lines that answer the voice, rhythm section, sustained strings and pads, effects and atmospheres. Low end is gentle by rock standards: the bass and kick support the groove without dominating, and the subs are used for weight in big moments, not constantly. Voices sit center and, ideally, image to the actor through delay; on high-end systems (delay-matrix and object-based systems) each mic is time-aligned so the natural voice reaches listeners about 10–20 ms before the reinforcement, letting the precedence effect pull the image to the performer. The orchestra keeps a natural pit spread across left-center-right arrays. Cast albums often sit near a 55:45 vocal-to-band balance, versus pop’s typical 70:30."
    }
  ],
  "eq": {
    "rows": [
      {
        "source": "Hairline/forehead lav (omni)",
        "cut": "HPF 100–150 Hz (men), 150–200 Hz (women); −2 to −5 dB broad dip 300 Hz–1 kHz",
        "boost": "+1–3 dB at 5–6 kHz presence; +1–2 dB shelf at 10–12 kHz",
        "notes": "Forehead is the most neutral position; small EQ moves per actor, saved in their channel"
      },
      {
        "source": "Ear/cheek-placed lav",
        "cut": "HPF 150–200 Hz; −4 to −6 dB at 200–400 Hz (cheek can add 5–8 dB at low frequencies)",
        "boost": "+3–5 dB at 4–8 kHz or use HF-boost grille",
        "notes": "Cheek and jaw positions sound dull and boomy; fix placement first"
      },
      {
        "source": "Headset boom",
        "cut": "HPF 120–180 Hz; dip 2–4 kHz if edgy; notch plosive thumps",
        "boost": "+1–2 dB at 8–10 kHz",
        "notes": "More gain before feedback; watch breath noise"
      },
      {
        "source": "Ensemble/chorus mics",
        "cut": "HPF 150–200 Hz; −2–3 dB at 250–500 Hz (build-up from many open mics)",
        "boost": "Minimal",
        "notes": "Group onto a chorus bus and EQ the sum"
      },
      {
        "source": "Strings (spot mics)",
        "cut": "HPF 100–150 Hz violins, 50–60 Hz cello; dip 2.5–3.5 kHz if steely",
        "boost": "+1–2 dB shelf at 10 kHz",
        "notes": "A narrow cut near 3.5 kHz on the string bus is a common fix"
      },
      {
        "source": "Woodwinds / brass",
        "cut": "HPF 100–150 Hz; −2 dB at 2–4 kHz on bright trumpets",
        "boost": "+1–2 dB at 1–3 kHz on reeds for definition",
        "notes": "Doublers switch instruments — snapshot EQ per instrument if needed"
      },
      {
        "source": "Piano / keys",
        "cut": "HPF 60–80 Hz; −2–3 dB at 250–400 Hz",
        "boost": "+1–2 dB at 3–5 kHz",
        "notes": "Keep synth pads out of 1–4 kHz vocal zone"
      },
      {
        "source": "Bass",
        "cut": "HPF 35–40 Hz; −2 dB at 200–250 Hz",
        "boost": "+2 dB at 700–800 Hz for line definition",
        "notes": "Should articulate the harmony under dialogue"
      },
      {
        "source": "Drums (pit, shielded)",
        "cut": "HPF kick 40 Hz, overheads 200–300 Hz; −3 dB at 400 Hz kick",
        "boost": "+2 dB at 60–80 Hz kick, 4–5 kHz snare",
        "notes": "Acoustic spill is already loud in front rows; reinforce lightly"
      }
    ],
    "notes": []
  },
  "compression": {
    "rows": [
      {
        "source": "Principal vocal (channel)",
        "use": "Yes, light",
        "ratio": "2:1–3:1",
        "attackRelease": "10–20 ms / 100–150 ms",
        "gainReduction": "2–4 dB on belts",
        "notes": "Threshold set so most lines never touch it; fingers do the real work"
      },
      {
        "source": "Belters / rock-score leads",
        "use": "Yes",
        "ratio": "3:1–4:1",
        "attackRelease": "5–10 ms / 80–120 ms",
        "gainReduction": "3–6 dB",
        "notes": "Plus channel limiter to catch screams"
      },
      {
        "source": "Vocal group bus",
        "use": "Yes",
        "ratio": "2:1–2.5:1 (or 5:1–7:1 as peak catcher)",
        "attackRelease": "15–30 ms / auto",
        "gainReduction": "1–3 dB",
        "notes": "Smooths the combined cast without pumping"
      },
      {
        "source": "Ensemble/chorus bus",
        "use": "Yes",
        "ratio": "3:1",
        "attackRelease": "10–20 ms / 100 ms",
        "gainReduction": "2–4 dB",
        "notes": "Keeps big numbers from swamping the principals"
      },
      {
        "source": "Orchestra/band bus",
        "use": "Light",
        "ratio": "2:1",
        "attackRelease": "20–30 ms / auto",
        "gainReduction": "1–2 dB",
        "notes": "Preserve orchestral swells; ride the band VCA instead"
      },
      {
        "source": "Bass",
        "use": "Yes",
        "ratio": "3:1–4:1",
        "attackRelease": "10–20 ms / 100 ms",
        "gainReduction": "3–5 dB",
        "notes": "Even level under dialogue"
      },
      {
        "source": "Sung-dialogue de-esser",
        "use": "Yes",
        "ratio": "—",
        "attackRelease": "—",
        "gainReduction": "2–4 dB at 5–8 kHz",
        "notes": "Close lavs exaggerate sibilance, especially headsets"
      }
    ],
    "notes": [
      {
        "text": "Gates are rarely used on vocal mics — fader pickups replace them. Dynamic EQ at 200–400 Hz and 2–4 kHz helps actors whose tone changes from speech to belt. Set transmitter gain so peaks sit near −12 dBFS."
      }
    ]
  },
  "fx": {
    "rows": [
      {
        "effect": "Vocal plate or hall",
        "appliedTo": "Sung numbers, principals",
        "setting": "1.2–2.0 s decay, 20–50 ms pre-delay, HPF 200 Hz",
        "amount": "Subtle for dialogue (often none), moderate in ballads"
      },
      {
        "effect": "Orchestral hall",
        "appliedTo": "Strings, winds, harp",
        "setting": "1.8–2.5 s decay",
        "amount": "Subtle–moderate; enlarges a small pit"
      },
      {
        "effect": "Ensemble reverb",
        "appliedTo": "Chorus bus",
        "setting": "1.5–2.0 s, slightly darker than the lead",
        "amount": "Moderate — glues 20 voices"
      },
      {
        "effect": "Slap/short delay",
        "appliedTo": "Rock/pop-score vocals",
        "setting": "80–120 ms, low feedback",
        "amount": "Subtle"
      },
      {
        "effect": "Tempo delay throws",
        "appliedTo": "Phrase endings, big notes",
        "setting": "1/4 or 1/8 note, 15–25% feedback",
        "amount": "Automated per cue"
      },
      {
        "effect": "Character FX",
        "appliedTo": "Ghosts, villains, offstage voices, “Wizard” voices",
        "setting": "Pitch shift, filtering, long verb, modulation",
        "amount": "Heavy, cued by snapshot"
      },
      {
        "effect": "System alignment delay",
        "appliedTo": "Every vocal output",
        "setting": "Voice arrives 10–20 ms after the natural sound",
        "amount": "Always on — not an effect, but essential"
      }
    ],
    "notes": [
      {
        "text": "Reverb sends change by scene: drier for dialogue, wetter as the song lifts."
      }
    ]
  },
  "vocals": [
    {
      "text": "The voice is king. Mix line by line: bring each actor’s fader up quickly just before they speak and pull it down when they finish, so only one or two mics are open at once. That avoids comb filtering between nearby actors and lowers noise and feedback risk. Use faders, not mutes — an actor can whisper one line and shout the next. Learn the script nearly word for word, including each performer’s habits. Placement beats EQ: the forehead/hairline is most natural, ear and cheek positions add boom and lose top. Principals often wear two mics with a backup receiver patched to a spare fader. Pitch correction is not used live in traditional book shows; cast albums use light, transparent tuning. For fast patter (Sondheim, Hamilton’s rap) and dialogue over underscore, dip the band 2–4 dB rather than pushing the vocal."
    }
  ],
  "loudness": [
    {
      "label": "Live:",
      "text": "Traditional book musicals generally aim for natural-sounding reinforcement around 80–88 dBA LAeq through an act, with loud numbers reaching 95–100 dBA; rock and pop-score shows run hotter, and the loudest West End rock shows peak around 110 dBA at FOH. These are practitioner ranges, not regulated limits. Keep dBC within about 12–15 dB of dBA; subs belong to finales and effects. Audiences include children and older patrons, and loudness complaints are common. Check pit exposure — musicians play eight shows a week — and offer molded earplugs."
    },
    {
      "label": "Studio / streaming:",
      "text": "Cast albums are mastered gentler than pop: traditional orchestral scores often land around −16 to −13 LUFS-I, contemporary pop and hip-hop scores −11 to −9, with true peak at −1 dBTP. Streaming services normalize to about −14 LUFS, so over-limiting gains nothing. Keep a loudness range (LRA) of roughly 8–14 LU on orchestral albums — the dynamics are part of the drama."
    }
  ],
  "liveStudio": {
    "rows": [
      {
        "area": "Vocal capture",
        "live": "Body lavs and headsets, line-by-line pickups, one mic open at a time",
        "studio": "Large-diaphragm studio mics close on every singer, ensembles mic’d individually with gobos"
      },
      {
        "area": "Session",
        "live": "Eight shows a week, snapshots and DCAs per scene",
        "studio": "Often a “mammoth” one- to few-day recording with cast and orchestra together; bigger shows track for weeks"
      },
      {
        "area": "Dynamics",
        "live": "Hands on faders, 30–40 dB of range",
        "studio": "Fader rides on subgroups, light serial compression (optical/FET class)"
      },
      {
        "area": "Imaging",
        "live": "Delay-based localisation to the actor’s stage position",
        "studio": "Stereo picture; panning to suggest staging, dialogue mostly cut"
      },
      {
        "area": "Effects",
        "live": "Scene-changed reverb, character FX, drier dialogue",
        "studio": "Several shared reverbs (room, plate, hall) and tempo delays"
      },
      {
        "area": "Orchestra",
        "live": "Reinforce lightly; acoustic pit spill is part of the sound",
        "studio": "Full spot-mic and room capture, string sweetening"
      },
      {
        "area": "Loudness",
        "live": "80–96 dBA LAeq depending on score",
        "studio": "−16 to −9 LUFS-I depending on score"
      }
    ],
    "notes": []
  },
  "notes": [
    {
      "text": "Bring faders up a fraction before the first word; a late pickup loses the consonant that makes the line understandable.",
      "bullet": true
    },
    {
      "text": "Never leave two close mics open in dialogue; cross-fade between actors.",
      "bullet": true
    },
    {
      "text": "Mix to the story: follow the scene’s emotion, tuck the band under lyrics, and let applause buttons breathe.",
      "bullet": true
    },
    {
      "text": "Multitrack performances so new operators can rehearse the mix against the desk scenes.",
      "bullet": true
    },
    {
      "text": "Work with wigs and wardrobe on placement; consistent placement show to show beats any EQ preset.",
      "bullet": true
    },
    {
      "text": "Avoid over-compressing to save fader work, wet dialogue, and an orchestra that forces singers to belt.",
      "bullet": true
    }
  ],
  "references": [
    "Original Broadway Cast, “Hamilton” (Lin-Manuel Miranda), 2015",
    "Original London Cast, “Les Misérables”, 1985",
    "Original London Cast, “The Phantom of the Opera”, 1987",
    "Original Broadway Cast, “Wicked” (Stephen Schwartz), 2003",
    "Original Broadway Cast, “Company” (Stephen Sondheim), 1970",
    "Original Broadway Cast, “Dear Evan Hansen”, 2017",
    "Original Broadway Cast, “Hadestown”, 2019",
    "Original West End Cast, “Six”, 2018"
  ],
  "empty": []
};
