/**
 * Mixing guide 50 — French Variété / Chanson. GENERATED by scripts/mixing-guides/convert.py
 * from the owner's guide (assets/Mixing-Guides-50-Styles, read only). Edit the
 * conversion (scripts/mixing-guides/edits.py), not this file.
 */
import type { MixingGuide } from '../types';

export const GUIDE: MixingGuide = {
  "id": "french-variete-chanson",
  "num": 50,
  "title": "French Variété / Chanson",
  "expects": "The audience treats the text as the point: the French public expects to understand the lyrics, because the songs follow the rhythms of the language and are valued for their writing.",
  "glance": {
    "origin": "France (Paris above all), with Belgium, Switzerland and Québec; roots in 1830s cafés-concerts and Montmartre cabarets, the 1950s Left Bank singer-songwriters (Brassens, Brel, Ferré, Barbara), 1960s yé-yé and TV variété, to today’s French pop (Stromae, Angèle, Clara Luciani)",
    "tempo": "60–130 BPM (ballads 60–80; valse musette in 3/4 at 140–180 BPM; modern variété-pop 95–125)",
    "ensemble": "From solo voice + piano or guitar, to a 3–5 piece chanson band (piano, accordion, double bass, guitar, light drums), to a 7–12 piece variété touring band with backing vocals, strings or brass",
    "priority": "The lead vocal and every word of the French text — clear, natural, and in front",
    "liveSpl": "Theatre/concert-hall chanson 85–92 dBA LAeq-15; variété arena shows 95–100 dBA; French law caps public venues at 102 dBA / 118 dBC LAeq-15",
    "studioLoudness": "Acoustic chanson masters often −14 to −11 LUFS-I; modern variété-pop −10 to −8; streaming normalizes to about −14"
  },
  "purpose": [
    {
      "text": "Chanson is storytelling and poetry set to melody. Its audience treats the text as the point: lines are quoted, singers are judged as authors and actors, and a concert at a hall such as the Olympia, Bobino or a municipal théâtre is a seated, attentive event closer to a recital than a rock gig. Variété broadens that into mass entertainment — big TV-style productions, singalongs, emotional ballads, dance numbers — but even here the French public expects to understand the lyrics, because the songs follow the rhythms of the language and are valued for their writing. French radio’s 40% francophone quota (law of 1994) also keeps these songs in daily circulation, so audiences know the words. A French audience will say “on ne comprend rien” (you can’t understand a thing) at a vocal buried under keyboards, a harsh 3 kHz glare, or reverb that smears syllables."
    }
  ],
  "instruments": [
    {
      "label": "Voice:",
      "text": "the central instrument, from half-spoken (Gainsbourg, Souchon) to full theatrical belting (Piaf, Aznavour, Dion).",
      "bullet": true
    },
    {
      "label": "Piano:",
      "text": "grand piano is the backbone of rive-gauche chanson (Barbara, Brel with Gérard Jouannest); often the only accompaniment.",
      "bullet": true
    },
    {
      "label": "Accordion:",
      "text": "the signature colour of musette and realist chanson, revived by the nouvelle scène (Les Têtes Raides, Zaz). Treble and bass sides behave like two instruments; bellows and key noise are part of the sound.",
      "bullet": true
    },
    {
      "label": "Guitar:",
      "text": "nylon or steel acoustic (Brassens’ fingerstyle), manouche/gypsy-jazz rhythm guitar, clean electric in variété.",
      "bullet": true
    },
    {
      "label": "Double bass or electric bass:",
      "text": "acoustic upright in chanson trios; electric or synth bass in variété.",
      "bullet": true
    },
    {
      "label": "Drums/percussion:",
      "text": "brushes, light kits, cajón; full pop kits and programmed beats in variété.",
      "bullet": true
    },
    {
      "label": "Strings and brass:",
      "text": "orchestral arrangements are a hallmark (Jean-Claude Vannier, Michel Legrand).",
      "bullet": true
    },
    {
      "label": "Playback:",
      "text": "synth pads, stems and click in modern variété; some shows run instrument processing in a DAW.",
      "bullet": true
    }
  ],
  "arrangement": [
    {
      "text": "Classic layout: singer front centre, piano stage left or right (often angled so singer and pianist see each other), accordion and double bass close by, drums small and upstage. In variété tours expect the full pop lineup: drums, bass, two guitars, keys/MD, two or three backing vocalists, sometimes strings and brass (a big variété tour can carry a four-piece string section and three-piece brass). The arrangement frames the words: sparse verses (often voice and one instrument), the band entering progressively, and choruses lifted by strings and harmonies, with instruments filling the breath gaps rather than the lines. Many chansons build to a final emotional climax (Brel’s “Amsterdam” is a long crescendo), so leave headroom."
    }
  ],
  "dynamics": [
    {
      "text": "Chanson has wide macro-dynamics: a whispered verse to a belted final chorus can span 15–20 dB, especially solo with piano. That contrast is the drama and must be kept; the engineer controls the extremes so the quiet words stay audible and the climax does not hurt. Ride the vocal fader rather than relying on heavy compression; singers act the text, with sudden drops to near-speech. Variété-pop is more controlled (6–10 dB section contrast), but ballads still need room to grow."
    }
  ],
  "balance": [
    {
      "text": "Hierarchy, loudest to quietest: lead vocal (clearly on top, often 3–6 dB above the band by feel, more than in rock), the main accompanying instrument (piano, guitar or accordion), bass, strings/pads, drums and percussion, backing vocals, reverb returns. In acoustic settings the double bass carries the low end at 50–200 Hz with the kick light and short; in variété-pop let the bass or synth bass own the sustained low end and keep the kick tight. Vocal, bass and kick centre; piano in stereo but moderately narrow (roughly 60–70% width) so it does not surround the voice; accordion slightly off-centre opposite the guitar; strings spread wide; backing vocals panned left and right behind the lead. Keep the 1–4 kHz zone uncluttered for the voice."
    }
  ],
  "eq": {
    "rows": [
      {
        "source": "Lead vocal",
        "cut": "HPF 80–120 Hz (male) / 120–150 Hz (female); −2–3 dB at 200–350 Hz; notch harsh 2.5–3.5 kHz if needed",
        "boost": "+1–3 dB broad at 2–4 kHz (consonants); +1–2 dB shelf at 10–12 kHz",
        "notes": "2–4 kHz carries most consonants; keep it clear but never shrill"
      },
      {
        "source": "Grand piano",
        "cut": "HPF 40–60 Hz; −2–3 dB at 250–400 Hz; dip 2–3 kHz under the vocal",
        "boost": "+1–2 dB at 80–120 Hz for weight; shelf at 8–10 kHz",
        "notes": "Close mics live under the lid; carve a gentle pocket for the voice"
      },
      {
        "source": "Accordion",
        "cut": "HPF 80–100 Hz (treble side), 50–60 Hz (bass side); −2–3 dB at 1–2 kHz if nasal/honky",
        "boost": "+1–2 dB at 3–5 kHz for reed definition",
        "notes": "Dip bellows/key clatter by placement, not EQ"
      },
      {
        "source": "Double bass",
        "cut": "HPF 35–40 Hz; −2–4 dB at 150–250 Hz (boom/room resonance)",
        "boost": "+2 dB at 700 Hz–1 kHz (definition); +1–2 dB at 2–3 kHz (finger attack)",
        "notes": "Lowest note E1 is 41 Hz; blend pickup with mic"
      },
      {
        "source": "Nylon / acoustic guitar",
        "cut": "HPF 80–100 Hz; −2–3 dB at 200–300 Hz",
        "boost": "+1–2 dB at 3–5 kHz; air at 10 kHz",
        "notes": "Keep body; fingerstyle needs articulation"
      },
      {
        "source": "Kick (light kit)",
        "cut": "HPF 30–40 Hz; −3 dB at 300–500 Hz",
        "boost": "+2 dB at 60–80 Hz; +1–2 dB at 2–3 kHz",
        "notes": "Much less level than in pop/rock"
      },
      {
        "source": "Snare / brushes",
        "cut": "HPF 100 Hz; −2 dB at ring",
        "boost": "+1–2 dB at 5–8 kHz for brush texture",
        "notes": "Brushes are quiet: watch bleed and gain"
      },
      {
        "source": "Strings",
        "cut": "HPF 80–120 Hz (violins 150 Hz); −2 dB at 2–3 kHz under vocal",
        "boost": "Shelf +1–2 dB at 10 kHz",
        "notes": "Make room in the vocal band rather than pushing the voice"
      },
      {
        "source": "Backing vocals",
        "cut": "HPF 150–200 Hz; −2–3 dB at 3 kHz",
        "boost": "Shelf at 10 kHz",
        "notes": "Duller and wider than the lead"
      },
      {
        "source": "Synth bass / pads (variété)",
        "cut": "HPF 30 Hz; cut 1–4 kHz on pads",
        "boost": "—",
        "notes": "Pads are the most common vocal masker"
      }
    ],
    "notes": []
  },
  "compression": {
    "rows": [
      {
        "source": "Lead vocal (chanson)",
        "use": "Yes, gentle",
        "ratio": "2:1–3:1",
        "attackRelease": "10–20 ms / 100–200 ms or auto (opto)",
        "gainReduction": "2–4 dB",
        "notes": "Faders do the main work; keep whispers natural"
      },
      {
        "source": "Lead vocal (variété-pop)",
        "use": "Yes, serial",
        "ratio": "4:1 (FET) then 2–3:1 (opto)",
        "attackRelease": "1–5 ms / 50 ms; program-dependent",
        "gainReduction": "3–6 dB total",
        "notes": "FET into opto is common in the studio"
      },
      {
        "source": "Piano",
        "use": "Light",
        "ratio": "2:1",
        "attackRelease": "20–30 ms / 150 ms",
        "gainReduction": "1–3 dB",
        "notes": "Slow vari-mu style keeps the touch"
      },
      {
        "source": "Accordion",
        "use": "Yes",
        "ratio": "2:1–3:1",
        "attackRelease": "10–20 ms / 100–150 ms",
        "gainReduction": "2–4 dB",
        "notes": "Tames bellows swells"
      },
      {
        "source": "Double bass",
        "use": "Yes",
        "ratio": "3:1–4:1",
        "attackRelease": "15–25 ms / 100 ms",
        "gainReduction": "3–5 dB",
        "notes": "Evens uneven notes"
      },
      {
        "source": "Strings bus",
        "use": "Light",
        "ratio": "1.5:1–2:1",
        "attackRelease": "30 ms / auto",
        "gainReduction": "1–2 dB",
        "notes": "Keep phrasing intact"
      },
      {
        "source": "Mix bus",
        "use": "Optional",
        "ratio": "1.5:1–2:1",
        "attackRelease": "30 ms / auto",
        "gainReduction": "1–2 dB",
        "notes": "Glue only; protect dynamics"
      }
    ],
    "notes": [
      {
        "text": "De-ess the vocal at roughly 5–8 kHz (lower for male voices, sometimes 4–5 kHz) for 2–4 dB on the worst sibilants only; French has many “s”, “ch” and “j” sounds, and over-de-essing makes words lisp. Gates are rarely needed in chanson. Live, leaving the master uncompressed keeps the music airy."
      }
    ]
  },
  "fx": {
    "rows": [
      {
        "effect": "Plate / small hall",
        "appliedTo": "Lead vocal",
        "setting": "1.2–1.8 s decay, 40–80 ms pre-delay, HPF 200 Hz / LPF 8 kHz on return",
        "amount": "Subtle; pre-delay keeps consonants dry"
      },
      {
        "effect": "Concert hall",
        "appliedTo": "Piano, strings, ballads",
        "setting": "1.8–2.5 s decay, 20–40 ms pre-delay",
        "amount": "Moderate in studio; minimal in a reverberant theatre"
      },
      {
        "effect": "Short room",
        "appliedTo": "Whole acoustic ensemble",
        "setting": "0.6–1.0 s",
        "amount": "Subtle — one shared space"
      },
      {
        "effect": "Slap / short delay",
        "appliedTo": "Lead vocal (variété, rock-leaning chanson)",
        "setting": "90–140 ms, low feedback, filtered",
        "amount": "Subtle"
      },
      {
        "effect": "Tempo delay",
        "appliedTo": "Phrase ends, ballad tags",
        "setting": "1/4 or dotted 1/8, 15–25% feedback",
        "amount": "Subtle, automated"
      },
      {
        "effect": "Vocal doubling / chorus",
        "appliedTo": "Variété choruses",
        "setting": "Real double tucked 6–10 dB under",
        "amount": "Occasional"
      }
    ],
    "notes": [
      {
        "text": "Chanson favours dry, close vocals (Gainsbourg, Brassens); reverb belongs on the space, not the words."
      }
    ]
  },
  "vocals": [
    {
      "text": "The voice is the mix. Place it clearly in front, with every syllable understood, including the mute “e” that chanson singers often pronounce as a sung syllable. Tone should be natural and warm with present but not edgy consonants; many classic records sound slightly dark on top rather than airy. French sibilants and nasal vowels (an, on, in) need care: too much cut at 300–800 Hz thins nasal vowels, too much 2–4 kHz makes “s” and “ch” piercing. Pitch correction should be transparent and sparing in chanson — slight imperfection is expressive and accepted — while modern variété-pop often uses fuller tuning. Backing vocals are tucked well below the lead. Live, condenser handhelds or headset/capsule mics suit quieter theatre stages; a simple chain of capsule, preamp, compressor, de-esser and EQ is often enough. In seated theatres keep the vocal near natural size — realism is lost when voices are far louder than life."
    }
  ],
  "loudness": [
    {
      "label": "Live:",
      "text": "Seated chanson in théâtres and concert halls typically runs 85–92 dBA LAeq-15 at FOH, with C-weighted levels around 95–105 dBC and peaks around 100–105 dBA. Variété arena and festival shows sit at 95–100 dBA, 110–116 dBC. French décret 2017-1244 limits any publicly accessible area to 102 dBA and 118 dBC over 15 minutes (94 dBA / 104 dBC for shows aimed at children under six), and venues over 300 capacity must record and display levels at the desk, offer free earplugs and provide rest zones. Sub content is modest in chanson; keep a C-minus-A gap under about 15 dB. Delay and front-fill speakers let you keep FOH lower and still reach the back rows — the right approach for theatres."
    },
    {
      "label": "Studio / streaming:",
      "text": "Acoustic chanson and piano-voice records sound best at −14 to −11 LUFS-I with a PLR of 12–16 dB and LRA of 8–12 LU; modern variété-pop is mastered around −10 to −8 LUFS-I. Keep true peak at −1 dBTP (−2 dBTP for masters louder than −14). Most streaming services normalize to −14 LUFS, so a dynamic chanson master loses nothing and keeps its emotion."
    }
  ],
  "liveStudio": {
    "rows": [
      {
        "area": "Vocal",
        "live": "Gain-before-feedback limits EQ on quiet singers; close condensers, constant fader rides",
        "studio": "Large-diaphragm condensers (classic tube types), serial compression, line-by-line rides"
      },
      {
        "area": "Room",
        "live": "Theatre acoustics already add reverb; use little or none",
        "studio": "Reverb creates the space; shared hall or plate"
      },
      {
        "area": "Piano",
        "live": "Close mics under lid, bleed from monitors; HPF more",
        "studio": "Stereo pair plus room, fuller low end"
      },
      {
        "area": "Accordion",
        "live": "Clip-on or close cardioid, watch bellows movement",
        "studio": "Pair of cardioids 1–2 ft forward, not hard-panned"
      },
      {
        "area": "Dynamics",
        "live": "Ride the singer by ear; protect quiet verses from the HVAC and audience noise",
        "studio": "Automation sculpts each phrase"
      },
      {
        "area": "Playback",
        "live": "Variété shows use click and stems; keep stems under the live vocal",
        "studio": "Full arrangement, orchestral overdubs"
      },
      {
        "area": "Loudness",
        "live": "85–100 dBA, legal 102 dBA / 118 dBC",
        "studio": "−14 to −8 LUFS-I depending on sub-style"
      }
    ],
    "notes": []
  },
  "notes": [
    {
      "text": "Learn the songs; know when the key line arrives and lift the vocal 1–2 dB there.",
      "bullet": true
    },
    {
      "text": "If you don’t speak French, check intelligibility with someone who does, or with the lyric sheet.",
      "bullet": true
    },
    {
      "text": "Avoid a bright pop vocal top on a chanson singer; warmth and presence beat air.",
      "bullet": true
    },
    {
      "text": "Don’t over-de-ess: lisping “s” sounds are a common fault on French vocals.",
      "bullet": true
    },
    {
      "text": "Pads and strings in the 1–4 kHz range are the usual cause of buried words in variété.",
      "bullet": true
    },
    {
      "text": "Chanson audiences are silent, so fan, wedge and hum noise is very audible.",
      "bullet": true
    }
  ],
  "references": [
    "Édith Piaf, “La vie en rose”, 1947",
    "Georges Brassens, “Les copains d’abord”, 1964",
    "Jacques Brel, “Amsterdam” (Enregistrement public à l’Olympia 1964), 1964",
    "Barbara, “Göttingen”, 1965",
    "Serge Gainsbourg, “Histoire de Melody Nelson”, 1971",
    "Alain Souchon, “Foule sentimentale”, 1993",
    "Zaz, “Je veux”, 2010",
    "Stromae, “Formidable”, 2013",
    "Clara Luciani, “La grenade”, 2018"
  ],
  "empty": []
};
