/**
 * I03a HANDHELD SHAKER — the pages' words (engine/model/copy.ts). The
 * starting-points voice (owner ruling 2026-10-04): no source, brand or model
 * names, no badges; tendencies, never results.
 */
import type { LessonCopy } from '../../engine/model/copy.ts';
import { spWords } from '../shared/smallperc/commonItems.ts';
import { P0 } from '../shared/smallperc/geom.ts';

export const SHK_COPY: LessonCopy = {
  variantKey: 'SHAKEN',
  variantShort: { toward: 'shaken toward the mic', side: 'shaken side to side' },
  sceneSubject: { toward: 'a handheld shaker shaken toward and away from the mic', side: 'a handheld shaker shaken side to side' },
  viewTag: { side: 'SIDE', top: 'FROM ABOVE' },
  axes: {
    x: { plus: 'toward the mic side', minus: 'toward the player', label: 'FRONT–BACK', blurb: 'Toward the audience and the mic, or toward the player (x).' },
    y: { plus: 'lower', minus: 'higher', label: 'HEIGHT', blurb: 'Up or down (y). Distances are read from the middle of the playing area.' },
    z: { plus: 'to player’s right', minus: 'to player’s left', label: 'ACROSS', blurb: 'Toward the player’s left or right (z).' },
    origin: { toward: P0, side: P0 },
  },
  instrument: {
    figureBadge: 'A handheld shaker, held in the right hand',
    figureLabel: 'Side view of a player holding a small clear shaker tube in the right hand, in front of the chest at about waist-to-chest height, the tube pointing toward the audience.',
    partsBadge: 'A handheld shaker · tap a part to name it',
    partsLooking: { side: 'Side view · the player from the right', top: 'From above · the player and the shaker' },
    partsIdle: 'A closed tube with loose fill inside, held and moved by the player — the whole instrument moves while it plays. The next page shows how the fill makes the sound.',
    variantNotes: {
      toward: 'TOWARD THE MIC: the shaker moves toward and away from a mic in front — each forward stroke comes closer, so it reads louder there.',
      side: 'SIDE TO SIDE: the same strokes, across the front — the distance to a mic in front changes less, so the level tends to stay steadier.',
    },
  },
  sound: {
    strikes: [{ id: 'c', label: 'THE STROKE', mm: 0, blurb: 'One stroke of the shaker.' }],
    strikeDefault: 'c',
    striker: 'STROKE',
    strikerPhrase: 'the stroke',
    subject: 'A clear shaker tube drawn large, with the fill inside',
    looking: { toward: 'The shaker drawn large · one stroke', side: 'The shaker drawn large · one stroke' },
    cells: [
      { k: 'SHELL', at: ['MOVING', 'STOPS, TURNS', 'MOVING BACK', 'MOVING BACK'], flex: 1.1 },
      { k: 'FILL', at: ['LAGS', 'KEEPS GOING', 'HITS THE END', 'SETTLING'], flex: 1.1 },
      { k: 'SOUND', at: ['—', '—', 'ATTACK', 'ALL ROUND'], flex: 1 },
    ],
    reveal: 'The fill does not move with the shell: it lags, keeps going when the stroke turns back, and lands on the end — that impact is the accent. In between, it slides and rubs along the wall: the wash.',
    after: 'Then the next stroke starts it all again. The fill, the shell, the grip and the player’s stroke all change the balance between the accent and the wash.',
    shapesNotes: ['The pictures show the order of events and where the sound starts — never its level. Real fill is hundreds of grains; it is drawn as a few beads.'],
    coupledSubject: 'The shaker drawn large',
    coupledNote: 'One instrument, two ingredients: the impacts on the end (the attack) and the sliding along the wall (the wash). The player’s stroke sets the balance — the mic only hears it.',
    silentNote: 'This lab never plays a sound and draws no frequency curve: how a real shaker sounds depends on its shell, its fill, the grip and the player. The pictures show where the sound comes from and where it leaves.',
    pair: {
      title: 'Accent or wash',
      badge: 'A simplified picture: where the fill goes, not how loud · a few beads stand for the fill · motion drawn larger',
      looking: 'The shaker drawn large · one stroke',
      prompt: 'Drag SWING through the stroke, then switch STROKE. Watch where the fill goes.',
      key: 'STROKE',
      rest: 'the middle of the stroke',
      cells: ['STROKE', 'THE FILL', 'YOU HEAR'],
      together: {
        option: 'SHARP (AN ACCENT)',
        blurb: 'A short, sharp turn at the end of each stroke: the fill flies on and slams into the end cap.',
        short: 'SHARP',
        title: 'A SHARP STROKE',
        card: 'The shell stops short and turns back; the loose fill keeps going and slams into the end cap. That impact is the ACCENT — and the harder the turn, the stronger it tends to be.',
        v0: 'SHARP',
        sub0: 'a short turn',
        v1: 'SLAMS THE END',
        air: { plus: 'ACCENT', minus: 'ACCENT', rest: 'IN FLIGHT' },
      },
      opposed: {
        option: 'SMOOTH (A WASH)',
        blurb: 'A rounded turn: the fill rolls and slides along the wall instead of slamming the end.',
        short: 'SMOOTH',
        title: 'A SMOOTH STROKE',
        card: 'The shell turns gently; the fill rolls and slides along the wall rather than slamming the cap. Many small rubs instead of one impact: a softer, more continuous WASH.',
        v0: 'SMOOTH',
        sub0: 'a rounded turn',
        v1: 'SLIDES ALONG',
        air: { plus: 'WASH', minus: 'WASH', rest: 'SLIDING' },
      },
    },
  },
  setting: {
    kitA11y: 'A percussion station from above: the shaker player in the middle, other percussion beside them, a drum kit and an amp upstage, a singer’s microphone downstage.',
    kitLanding: 'Tap anything around the shaker player — or step through ITEM — to see what it means for a shaker mic. There is nothing to answer yet.',
    kitIdle: 'The shaker player often stands at a percussion station, moving between small instruments. Around them: loud neighbours — cymbals, drums, amps and voices.',
    leftHanded: 'Players shake with either hand, or both, and turn between instruments — check the real part, and where the player stands for it.',
    stageA11y: 'The band on a stage, from above: the percussion station, a floor monitor downstage of it facing back, the player’s own monitor behind them, the audience and the PA at the front.',
    studioA11y: 'The band in a studio room, from above: the percussion station, a percussion area mic above it, the room’s walls, no monitors.',
    stageIdle: 'Two floor monitors: one downstage of the station facing back toward it, and the player’s own behind them. The PA faces the audience.',
    studioIdle: 'No monitors. An area mic over the percussion may already carry the shaker — and the room is part of the sound.',
    before: [
      { title: 'WATCH THE WHOLE PART', text: 'Ask for the part at its quietest and loudest, with any big accents, and watch the whole playing arc — not one isolated stroke. Mark a comfortable playing spot.' },
      { title: 'THE INSTRUMENT FIRST', text: 'A softer or a louder shaker can solve a harshness or a projection problem before any mic does. Listen at the audience or monitoring position first.' },
      { title: 'WORK WITH THE PLAYER’S MOTION', text: 'Let the player play comfortably — never ask for a stiff, stationary wrist so a close mic works. The stand and cable stay out of the arc, the face and the other instruments.' },
    ],
    plan: {
      title: 'At the percussion station',
      badge: 'The station from above · a typical layout · grey = the player’s space',
      looking: 'Plan · the station, the audience to the right',
      stageBadge: 'From above · a stage · two monitors where a stage often puts them',
      studioBadge: 'From above · a studio room',
      stageLooking: 'Plan · the station on a stage',
      studioLooking: 'Plan · the station in a studio',
      widePrompt: 'Switch STAGE / STUDIO, and tap what is new around the station.',
    },
  },
  placement: {
    workedZone: { toward: 'shk.front.toward', side: 'shk.front.side' },
    workedLine: 'This starting point is also read against {line}: the readout says how far the mic is from the whole motion.',
    workedAim: 'Face the middle of the playing area — the starting point counts while the mic faces it within {tol}°. Distance, height and angle are separate things to try.',
    workedClear: 'Clear of the whole motion — the shaker’s arc, the hand and arm, the face. Clearance comes first: the distance is a starting point, not a safety clearance, and the player stops before a real mic moves.',
    blocked: {},
    reveal: 'Toward and away, each forward stroke tends to jump out; side to side, the level tends to stay steadier. Higher up, the balance of rattle, hand noise and neighbours changes — and shakers and players vary, so “it depends” is fair too.',
    typeNotes: { smallDynCard: 'A robust dynamic can make sense in a crowded live setup; a small condenser tends to show more fine detail. Neither is a rule — compare by ear.' },
    note: 'Clearance comes first: stop the player before moving a real mic. Watch PEAK meters — a shaker’s brief peaks can overload an input that a slow meter says is fine.',
    availableLead: 'Starting points for this mic and way of shaking',
    learn: {
      intro: 'What you just did, in words. After our research, a mic about 30–60 cm (1–2 ft) from the middle of the playing area, facing where most strokes happen, is where we suggest you begin — a common minimum for percussion is about 30 cm between mic and instrument. Starting points, not rules: move and listen — there is no single right answer.',
      separate: 'Distance, height and angle are separate variables: change one at a time, with the same pattern. Distance is read from the middle of the playing area — not from the nearest point of one stroke.',
      clearance: 'Clearance comes first. Have the player show the whole arc and the biggest accent before anything is placed. Keep-clear areas appear as the mic gets close — in red, with the reason, if a move is stopped — and show roughly where to keep clear — leave more room for a real player.',
      tendencies: 'Farther back if one stroke jumps in level, if single clicks dominate, or if the player cannot move freely; closer if the room or the band swamps it. All tendencies to check by ear.',
    },
  },
  context: {
    variant: 'side',
    zone: 'shk.front.side',
    typeId: 'orchSdc',
    patterns: [
      { id: 'cardioid', label: 'cardioid', typeId: 'orchSdc' },
      { id: 'supercardioid', label: 'supercardioid', typeId: 'orchSdc' },
      { id: 'hypercardioid', label: 'hypercardioid', typeId: 'orchSdc' },
    ],
    micNoun: 'A small condenser',
    shield: ['shk.shell.side'],
    azMax: 45,
    elMax: 45,
    aimBlurb: 'Swing the front up to 45° either way — it still faces the playing area.',
    plan: { u0: -1300, u1: 1650, v0: -900, v1: 900 },
    side: { u0: -1300, u1: 1650, v0: -1800, v1: 60 },
    target: 'downstage',
    frontIds: ['fill'],
    targetWord: 'monitor',
    looking: 'Top view · the mic in front of the shaker',
    prompt: 'The monitor stays where the stage needs it. Turn the MIC (AIM) or change its PATTERN until the downstage wedge sits in the rejection.',
    activityDone: 'done — the downstage wedge sat in a null by your aim or pattern',
    deepNull: 'On this simplified pattern a null looks infinitely deep. Real microphones reject far less there. Use the null to aim, not to promise silence.',
    cardioidReveal: 'What you just saw: a cardioid rejects most directly behind (180°). Supercardioid and hypercardioid patterns have a rear lobe and their deepest rejection off to the sides of the rear — so a wedge is placed by the real pattern, not simply behind.',
    shieldNote: 'Real patterns change with pitch and the stage reflects sound — this is the reasoning, not a prediction. A wider pattern covers a moving player but hears more of the stage.',
    studioId: 'shk.ctx.studio',
    studioPrompt: 'A studio session has no wedge to reject. The decision changes: does the shaker need its own mic at all?',
    studioNote: 'In a quiet overdub, choose the room and the shaker first; one mic for one player is usually enough. Switch back to LIVE for the monitor exercise.',
    learn: {
      intro: 'These are scenario-based comparisons, not rules: a dedicated spot may suit a busy stage; an existing overhead may suit a quiet one.',
      points: [
        { title: 'SPOT OR SHARED', text: 'A shared overhead can work on a quiet stage, but it also hears cymbals, monitors and backline. One dedicated directional mic can serve a station of shakers and tambourine.' },
        { title: 'THE PATTERN’S NULLS', text: 'A cardioid rejects most behind it; supercardioid and hypercardioid patterns have a rear lobe and nulls off to the sides of the rear — place the wedge by the real pattern.' },
        { title: 'NOT ENOUGH LEVEL', text: 'If close placement still cannot give enough level before feedback: lower the stage, move the player, or choose a louder shaker. Never solve feedback by adding gain.' },
        { title: 'SECURE IT', text: 'Boom, cable and connector secured so the playing motion cannot pull the mic down; a clip on another instrument does not follow a separately moving shaker.' },
      ],
      body: 'On an amplified stage the monitors stay where the players need them: turn the mic or choose its pattern so a null faces a loud unwanted source. Mute an unused channel when it is not needed.',
      warn: 'No mic position alone prevents feedback: the monitors and PA, channel gain and EQ, the room and the open mics all matter. Work it out with the system operator, and never create feedback deliberately.',
    },
  },
  twoMic: {
    variant: 'side',
    A: { typeId: 'orchSdc', pattern: 'cardioid', zone: 'shk.front.side' },
    B: { typeId: 'orchSdc', pattern: 'cardioid', zone: 'shk.above.side' },
    learn: [
      'A common situation: the shaker spot, and another mic that hears it too — a percussion overhead or a room mic. Each hears it at a different time. A single mono spot is usually enough; a room mic earns its place only if the room adds something the part needs.',
      'Compare the mics together at the intended levels in MONO. If the shaker turns thin or strange, move, re-aim or rebalance first; try polarity as a diagnostic, not an automatic switch.',
    ],
    warn: 'This simplified graph shows one point source and straight paths — a real shaker moves while it is played, so the delay between two mics changes with every stroke. Read the notch depths as illustrative only.',
  },
  practice: {
    gain: 'shk.prac.gain',
    second: 'shk.prac.3',
    mixed: ['shk.mix.1', 'shk.mix.2', 'shk.mix.3'],
    mixedIntro: 'Three cards from earlier pages, mixed: a reference point, a pattern’s null, and the delay between two mics.',
  },
  where: { inside: 'inside the motion', outside: 'clear of the motion' },
  viewWords: { side: 'Side view,', top: 'Top view' },
  words: spWords({ instrument: 'shaker', reference: 'playing area', axis: 'the line to the playing area', facing: 'facing the playing area' }),
};
