/**
 * C12 CLAVINET — the pages' amp words (engine/model/copy.ts). Starting-points
 * voice (owner ruling 2026-10-04): no sources, brands or badges. The monitor
 * null is aimed TOWARD the loudest monitor (CORRECTIONS_LOG C12-02).
 */
import type { LessonCopy } from '../../engine/model/copy.ts';
import { OPPOSITE_SIDES_POLARITY } from '../../engine/model/sharedItems.ts';
import { GRILLE_X } from './ampSpec.ts';

export const CLAV_COPY: LessonCopy = {
  variantKey: 'AMP',
  variantShort: { combo: 'open-back combo', cab: 'closed 1×12 cabinet' },
  sceneSubject: { combo: 'an open-backed combo amplifier with one 12-inch speaker', cab: 'a closed 1×12 speaker cabinet' },
  viewTag: { side: 'SIDE · CUT OPEN THROUGH THE SPEAKER', top: 'FROM ABOVE' },
  axes: {
    x: { plus: 'out from the amp', minus: 'toward the amp', label: 'IN–OUT', blurb: 'Out from the amp’s front, or back toward it (x).' },
    y: { plus: 'lower', minus: 'higher', label: 'HEIGHT', blurb: 'Up or down across the speaker (y). Distances are read from the surface each starting point names — the grille, or the open back.' },
    z: { plus: 'to the right', minus: 'to the left', label: 'ACROSS', blurb: 'Across the speaker, left or right as you face the amp (z).' },
  },
  instrument: {
    figureBadge: 'The amplifier the clavinet plays through, cut open through its speaker',
    figureLabel: 'Side view of a combo amplifier cut open: the grille cloth at the front, the 12-inch speaker behind it with its cone, dust cap and magnet, the chassis and tubes along the top, the partly open back.',
    partsBadge: 'Tap a part to name it',
    partsLooking: { side: 'Side view · the amp cut open', top: 'From above · the amp' },
    partsIdle: 'The clavinet itself makes almost no sound in the air: its pickups make a signal, and the amplifier’s speaker turns it back into sound. That speaker is what a mic hears — the next page shows the whole chain. Tap anything here first.',
    variantNotes: { cab: 'CLOSED CABINET: a separate amplifier drives it, and the speaker’s sound comes only from the front — there is no rear mic position.' },
  },
  sound: {
    strikes: [{ id: 'c', label: 'CENTRE', mm: 0, blurb: 'Not used by this lesson.' }],
    strikeDefault: 'c',
    striker: 'TANGENT',
    strikerPhrase: 'the tangent',
    subject: 'One key and its string, cut open',
    looking: {},
    cells: [],
    reveal: '',
    after: '',
    shapesNotes: [],
    coupledSubject: '',
    coupledNote: '',
    silentNote: '',
  },
  setting: {
    kitA11y: 'The amp, the clavinet and the keyboardist from above, with the pedals and the cables.',
    kitLanding: 'Tap anything around the amp — or step through ITEM — to see what it means for the capture. There is nothing to answer yet.',
    kitIdle: 'The keyboardist stands at the clavinet with the amp behind them; the cable runs through the pedals to the amp. Everything here is either the player’s space, part of the signal path, or something a mic will hear.',
    leftHanded: '',
    stageA11y: 'The amp and the clavinet on a stage, from above: the keyboardist’s wedge, the band’s monitor, the band and the PA.',
    studioA11y: 'The amp and the clavinet in a studio, from above: a DI box, a close mic and a room mic.',
    stageIdle: 'On a loud stage the direct signal usually goes to the PA; the amp is miked when it is part of the sound the player wants.',
    studioIdle: 'In the studio a clean direct track and a close mic on the amp are often kept side by side, each labelled.',
    before: [
      { title: 'DRAW THE PATH FIRST', text: 'Write down the chain before any mic: clavinet → pedals → amp → speaker → mic → console, and where a direct signal is taken (before or after the pedals). Note the clavinet’s pickup and filter switches, the pedal order and the amp settings — they are part of the sound.' },
      { title: 'ELECTRICAL SAFETY', text: 'The clavinet’s output goes to a DI or a line or instrument input — never a mic input, never phantom power. Keep mains cables, extension leads and the amp’s ventilation clear; never open a powered amp or change the instrument’s wiring. Hum or an intermittent output is for a qualified technician.' },
    ],
  },
  placement: {
    workedZone: { combo: 'cl.line', cab: 'cl.line' },
    workedLine: 'This starting point also places the mic relative to {line}: the readout says how far off it the mic is.',
    workedAim: 'Aim it straight in at the speaker — the lab counts it while the mic faces the way the starting point names. Distance, position across the cone and angle are separate things to try.',
    workedClear: 'Clear of the grille — the mic never touches it — on a stand that cannot tip into the speaker, its cable out of the player’s way. Clearance comes first, before any number.',
    blocked: {},
    reveal: 'Toward the centre tends to bring more bite; toward the edge or turned off axis, a rounder sound; farther back, more cabinet and room — and every amp, speaker and setting is different, so “it depends” is fair too. Each zone’s LISTEN FOR line is an idea to check by ear.',
    typeNotes: {
      instDynCard: 'Ideas to try with an instrument dynamic: right at the grille on the dust-cap line, then one change at a time — across the cone, the angle, the distance.',
      sdcCard: 'Ideas to try with a small condenser: check its maximum level against the loudest playing first, and listen for the extra detail — or the extra harshness — it brings.',
    },
    note: `Clearance comes first: the mic never touches the grille (it is drawn ${GRILLE_X} mm in front of the baffle), the stand cannot tip into the speaker, and nothing goes near a hot tube chassis.`,
    availableLead: 'Starting points for this mic and amp',
    learn: {
      intro: 'What you just did, in words. After our research, each blue zone is where we suggest you begin with that kind of mic on this amp, measured from the surface it names — the grille, or the open back. They are starting points, not rules: move from there and listen — there is no single right answer.',
      separate: 'Distance from the grille, position across the cone and angle are separate variables: change one at a time, and mark each position so you can return to it. Distances are measured to the mic’s FRONT and rounded to ≈ 5 mm.',
      clearance: 'Clearance comes first. The mic never touches the grille or a moving cone; the stand cannot fall into the speaker; nothing goes near a hot tube chassis; cables are taped where the player walks.',
      tendencies: 'Toward the centre of the speaker tends to bring more bite and edge; toward the edge, or turned off axis, a rounder sound; farther back, more cabinet and room. These are tendencies; amps, speakers and settings vary.',
    },
  },
  context: {
    variant: 'combo',
    zone: 'cl.line',
    typeId: 'instDynCard',
    patterns: [
      { id: 'cardioid', label: 'cardioid', typeId: 'instDynCard' },
      { id: 'supercardioid', label: 'supercardioid', typeId: 'instDynCard' },
      { id: 'hypercardioid', label: 'hypercardioid', typeId: 'instDynCard' },
    ],
    micNoun: 'A close amp mic',
    shield: ['co.cab', 'cb.cab'],
    azMax: 35,
    elMax: 30,
    aimBlurb: 'Swing the front up to 35° either way — it still faces the speaker.',
    plan: { u0: -1000, u1: 2500, v0: -1800, v1: 1500 },
    side: { u0: -600, u1: 2600, v0: -900, v1: 300 },
    target: 'wedge.keys',
    frontIds: ['wedge.band'],
    targetWord: 'wedge',
    looking: 'From above · the mic at the amp',
    prompt: 'The keyboardist’s wedge is the loudest monitor near the amp. Turn the MIC (AIM) or change its PATTERN until the wedge sits IN the rejection — aim the null TOWARD it — while the mic still faces the speaker.',
    activityDone: 'done — the wedge sat in a null by your aim or pattern',
    deepNull: 'On this simplified pattern a null looks infinitely deep. Real microphones reject far less there, and often least at low frequencies. Use the null to aim, not to promise silence.',
    cardioidReveal: 'What you just saw: a cardioid rejects most directly behind (180°). Facing the speaker, its rear points out toward the stage — turn it until the wedge sits on that rear axis. Aim the null TOWARD the loudest monitor, never away from it.',
    shieldNote: 'Mute or lower the channel before moving a mic, then retest the gain before feedback. Real patterns change with pitch and the stage reflects sound — this is the reasoning, not a prediction.',
    studioId: 'cv.ctx.studio',
    studioPrompt: 'In the studio, what does the direct track add?',
    studioNote: 'In a quiet room, keep a clean direct track beside the close mic, label where the DI sits, and align the two in mono. Switch back to LIVE for the wedge exercise.',
    learn: {
      intro: 'These are scenario-based comparisons, not restrictions: a direct signal can be right on a loud stage, and a miked amp right when the amp is the sound the player wants.',
      points: [
        { title: 'THE DIRECT PATH', text: 'Live: the direct signal usually gives more gain before feedback and less stage spill. Studio: a clean direct track is precise and can be re-amped later — without the amp, the speaker or the room.' },
        { title: 'THE MIKED AMP', text: 'Mic the amp when it is part of the player’s sound or must be heard in the room: close, on one chosen speaker, with the amp’s volume under control.' },
        { title: 'BLENDING THE TWO', text: 'The direct signal arrives before the mic’s: in mono that can comb. Adjust the distance, the track delay or the blend first; then test polarity.' },
        { title: 'MOUNTING', text: 'A low, stable stand or an approved cabinet clip that cannot fall into the speaker or touch a hot amp; cables secured so nobody trips and nothing strikes the grille.' },
      ],
      body: 'A pattern’s rejection is a tool to aim — lowering the offending monitor, fewer open mics and using the direct path often do more. If the amp is also the player’s monitor, manage the two sources so the mic does not keep catching the wedge.',
      warn: 'No mic position alone prevents feedback: the pattern, the monitors, the other open mics, the system level and the room all matter. Never create feedback deliberately. Turn the level down before moving a mic, and do not simply keep raising the clavinet’s output.',
    },
  },
  twoMic: {
    variant: 'combo',
    A: { typeId: 'instDynCard', pattern: 'cardioid', zone: 'cl.line' },
    B: { typeId: 'instDynCard', pattern: 'cardioid', zone: 'cl.back' },
    opposite: { surface: 'grille', note: `One mic is now behind the open back: as the cone pushes out toward the front mic, it pulls away from the rear one — the rear mic hears the speaker in the opposite polarity. ${OPPOSITE_SIDES_POLARITY}` },
    learn: [
      'A close mic and a second one a little farther back on the same speaker give a choice of bite and body. A direct (DI) track can play the same part: it arrives before either mic.',
      'Then listen: each alone, the two together, and in MONO. The farther mic hears the speaker later — in mono that can comb. Moving a mic, or delaying a track, changes the delay; the polarity switch does not.',
    ],
    warn: 'This simplified graph takes ONE point of the speaker as the source and no reflections; read it as the reasoning, not a prediction. The notch POSITIONS follow from the arrival-time difference; their DEPTH depends on the levels. Judge the blend by ear, in mono, at matched levels.',
  },
  practice: {
    gain: 'cv.prac.gain',
    second: 'cv.prac.3',
    mixed: ['cv.mix.1', 'cv.mix.2', 'cv.mix.3'],
    mixedIntro: 'Three cards from earlier pages, mixed: the signal path, a pattern’s null, and polarity versus delay.',
  },
  words: {
    intro: 'This lesson is about capturing a clavinet — an electric keyboard whose strings and pickups make a signal, not a sound in the air. So there are two paths: the direct signal, and a microphone on the amplifier’s speaker. First the instrument and its signal path, then the microphones, a worked example, and your own placements. Nothing here makes a sound: the lab is silent and shows the physics instead.',
    newNote: 'Good — NEXT takes you through the clavinet and its amp first. You can change how you started here at any time.',
    mount: {
      stand: 'Mount: a low, stable stand that cannot tip into the speaker — never touching the grille, clear of a hot amp',
      clip: 'Mount: an approved cabinet clip, secure, away from the moving cone',
    },
    workedHead: 'The distance is measured from {head}. On an amp the grille, the baffle behind it and the cone each give a different number for the same spot — so every starting point names its surface.',
    workedNoAim: 'This starting point names no aim, so the mic simply faces the speaker. Distance, position and angle are still separate things to try.',
    facing: 'facing the speaker',
    inPath: 'cabinet in path',
    sheet: 'For a real clavinet and amp, with the player’s agreement and the channel muted while anything moves. Write tendencies in words — what you heard, not a promised result.',
  },
};
