/**
 * M06 TIMPANI — the pages' timpani words (engine/model/copy.ts). The
 * starting-points voice (owner ruling 2026-10-04): no source, brand or model
 * names, no badges; tendencies, never results.
 */
import type { LessonCopy } from '../../engine/model/copy.ts';
import { R29 } from './model.ts';

export const TIMP_COPY: LessonCopy = {
  variantKey: 'SET',
  variantShort: { two: 'two drums', four: 'four drums' },
  sceneSubject: { two: 'a pair of timpani, 29 and 26 in', four: 'a set of four timpani, 32, 29, 26 and 23 in' },
  viewTag: { side: 'SIDE · FROM THE PLAYER’S RIGHT', top: 'TOP' },
  axes: {
    x: { plus: 'toward the conductor', minus: 'toward the player', label: 'FRONT–BACK', blurb: 'Toward the conductor or toward the player (x). The player stands behind the drums.' },
    y: { plus: 'lower', minus: 'higher', label: 'HEIGHT', blurb: 'Up or down (y). Distances are read from the heads, not the floor.' },
    z: { plus: 'to player’s right', minus: 'to player’s left', label: 'ACROSS', blurb: 'Toward the player’s left (the larger drum) or right (z).' },
    origin: { two: { x: 0, y: -760, z: 0 }, four: { x: 0, y: -760, z: 0 } },
  },
  instrument: {
    figureBadge: 'A pair of timpani, 29 and 26 in, from the player’s right',
    figureLabel: 'Side view of a pair of timpani from the player’s right: two copper bowls under coated heads, the counterhoops and their T-handled tension rods, the legs on casters and the pedals on the player’s side, with two mallets in the player’s hands.',
    partsBadge: 'A pair of timpani · tap a part to name it',
    partsLooking: { side: 'Side view · from the player’s right', top: 'Top view · the player at the left' },
    partsIdle: 'The mallet strikes the head; the copper bowl under it gives the drum its clear pitch, and the pedal changes that pitch. Mallets, strike point and pedal are the player’s — the next page shows how the drum sounds.',
    variantNotes: { four: 'FOUR DRUMS: 32, 29, 26 and 23 in, larger on the player’s left (the international order). A German set is mirrored — always check the real order with the player.' },
  },
  sound: {
    strikes: [
      { id: 'c', label: 'CENTRE', mm: 0, blurb: 'The exact centre of the head — not where a timpanist usually plays.' },
      { id: 'third', label: 'A THIRD IN FROM THE HOOP', mm: (R29 * 2) / 3, blurb: 'About a third of the radius in from the hoop, on the player’s side — where a full tone is usually found.' },
      { id: 'hoop', label: 'CLOSE TO THE HOOP', mm: R29 * 0.9, blurb: 'Very close to the hoop — explore what it drives.' },
    ],
    strikeDefault: 'third',
    striker: 'MALLET',
    strikerPhrase: 'the mallet',
    subject: 'Side view of one timpano, cut open through its head',
    looking: { two: 'Side view · one drum (29 in) cut open', four: 'Side view · one drum (29 in) cut open' },
    cells: [
      { k: 'HEAD', at: ['AT REST', 'SEE-SAW', 'SEE-SAW', 'RINGING'], flex: 1.1 },
      { k: 'BOWL AIR', at: ['AT REST', 'AT REST', 'ACROSS', 'ACROSS'], flex: 1.1 },
      { k: 'SOUND', at: ['—', '—', '—', 'UP AND OUT'], flex: 1.1 },
    ],
    reveal: 'Struck off-centre, the head goes down where the mallet lands and up on the far side — a see-saw. The air under it is shoved across the bowl rather than squeezed.',
    after: 'Then the head keeps ringing in its pitched shapes — the note. How long, and how bright, depends on the mallet, the strike point, the tuning and any damping: all the timpanist’s choices.',
    shapesNotes: [
      'A shape is set moving only as much as the head moves at the strike point in that shape. A centre strike drives only the ring-shaped ones — on a timpani that means more thud and less of the note; a third of the way in from the hoop drives the pitched shapes well.',
      'This picture uses the head’s ideal shapes; the ratios are a timpani’s, with the bowl’s air included. A real drum, its head and its tuning move them a little.',
    ],
    coupledSubject: 'Side view of one timpano, cut open',
    coupledNote: 'One stroke sets several shapes going at once. The see-saw family carries the note and rings on; the pump is the short thud at the start, strongest from a centre strike.',
    silentNote: 'This lab never plays a sound and draws no frequency curve for the drum: how a real timpani sounds depends on the drum, its head, the tuning, the mallets and the player. The pictures show where the sound comes from and where it leaves.',
    pair: {
      title: 'The head and the bowl’s air',
      badge: 'A simplified picture: one head over its bowl · motion drawn larger · no levels or pitches implied',
      looking: 'Side view · one drum cut open',
      prompt: 'Drag SWING, then switch SHAPE. Watch the air in the bowl.',
      key: 'SHAPE',
      rest: 'the head passing through rest',
      cells: ['SHAPE', 'HEAD', 'BOWL AIR'],
      together: {
        option: 'SEE-SAW (1,1): THE NOTE',
        blurb: 'One half of the head moves down while the other moves up; the air under it is shoved from side to side, and the bowl’s volume hardly changes.',
        short: 'SEE-SAW',
        title: 'SEE-SAW (1,1) — THE NOTE',
        card: 'One half of the head goes down while the other comes up. The air under it is shoved across rather than squeezed, so this shape moves little air into the room and rings on. On a timpani it is the NOTE you hear: the bowl’s air pulls it and its relatives into near-whole-number steps, which is why a timpani has a clear pitch.',
        v0: '(1,1)',
        sub0: 'the note',
        v1: 'OPPOSITE',
        air: { plus: 'ACROSS', minus: 'BACK', rest: 'AT REST' },
      },
      opposed: {
        option: 'PUMP (0,1): THE THUD',
        blurb: 'The whole head moves down, then up, squeezing and easing the air in the bowl.',
        short: 'PUMP',
        title: 'PUMP (0,1) — THE THUD',
        card: 'The whole head goes down together, then up. It squeezes and eases the air in the bowl, which pushes back hard: this shape sends its energy out quickly and dies away fast — a short, dull thud rather than the note. A strike right at the centre drives it most.',
        v0: '(0,1)',
        sub0: 'the thud',
        v1: 'ONE WAY',
        air: { plus: 'SQUEEZED', minus: 'EASED', rest: 'AT REST' },
      },
    },
    shapeWords: {
      lowest: 'This is the (1,1) shape — the timpani’s NOTE. The other shapes are measured against it: with the bowl’s air, the main ones fall near 1.5, 2 and 2.5 times it — close to whole-number steps, which is why a timpani sounds pitched.',
      other: 'On a timpani this shape sits at {ratio} times the note’s (1,1) shape. The bowl’s air pulls the main shapes toward near-whole-number steps from the note; the ring-shaped (0,1) sits just below the note and dies away fast.',
      ratioSub: 'vs (1,1)',
      badge: 'A simplified picture: ideal shapes, with a timpani’s ratios (the bowl’s air included) · blue + toward you, amber − away',
    },
  },
  setting: {
    kitA11y: 'The percussion section from above, at the back of an orchestra: the timpani with their player upstage of them, the concert bass drum, the concert snare, a suspended cymbal and the trap table along the row, and a row of brass players in front.',
    kitLanding: 'Tap anything around the timpani — or step through ITEM — to see what it means for a timpani mic. There is nothing to answer yet.',
    kitIdle: 'The timpani sit at the back of the orchestra, the player behind them facing the conductor. Around them: the rest of the percussion, and the brass just in front.',
    leftHanded: 'The drum order varies: larger drums on the player’s left in many orchestras, on the right in a German set. Check the real order — and every drum the passage uses — with the player.',
    stageA11y: 'The orchestra on an amplified stage, from above: the percussion at the back, the conductor and the audience at the front, PA stacks at the front corners, and two floor monitors near the timpani.',
    studioA11y: 'The orchestra recorded in a hall, from above: the main pair of microphones over the conductor, the hall’s walls around the stage, no monitors.',
    stageIdle: 'Two floor monitors: one downstage of the timpani, facing back toward them, and the section’s own monitor behind the players. The PA faces the audience.',
    studioIdle: 'No monitors. The main pair over the conductor hears the whole orchestra — the timpani’s low notes included — and the hall is part of the sound.',
    before: [
      { title: 'ASK THE PLAYER FIRST', text: 'Which drums, which pedal changes, which mallets, how far the arms travel, and what is nearby — for the whole passage, not one stroke. Ask for the softest roll and the loudest stroke.' },
      { title: 'LISTEN TO THE MAIN PICKUP', text: 'In an orchestra the main pair often already carries the timpani’s low notes and the hall. A spot is a way to add definition that is missing — not a default, and not there to overwhelm the main sound.' },
      { title: 'THE PLAYER’S SPACE AND SIGHTLINE', text: 'Mark the full mallet sweep, the path round the set, the pedals and the line of sight to the conductor. Nothing touches a head, a hoop, a pedal or the mechanism; if a stand cannot go in safely, leave that spot out.' },
    ],
    plan: {
      title: 'In the orchestra',
      badge: 'The percussion from above · a typical concert layout · grey hatch = the players’ space',
      looking: 'Plan · the percussion row, the audience toward the bottom',
      stageBadge: 'From above · an amplified orchestra · two monitors where a stage often puts them',
      studioBadge: 'From above · an orchestra recorded in a hall',
      stageLooking: 'Plan · the orchestra on an amplified stage',
      studioLooking: 'Plan · the orchestra in a recording hall',
      widePrompt: 'Switch STAGE / STUDIO, and tap what is new around the orchestra.',
    },
  },
  placement: {
    workedZone: { two: 'tp.pair', four: 'tp.pairLow' },
    workedLine: 'This starting point is also read against {line}: the readout says how far the mic is from it.',
    workedAim: 'Look down at the heads — the starting point counts while the mic looks down within {tol}° of straight down. Height and angle are separate things to try.',
    workedClear: 'Clear of the mallets’ whole reach, the player’s arms and the pedals — and out of the player’s sightline to the conductor. Clearance comes first, and the player stops before a real stand moves.',
    blocked: {},
    reveal: 'Farther tends to bring more of both drums and the room; closer, more attack from one drum and less of the room — and drums, halls and players vary, so “it depends” is fair too. Each zone’s LISTEN FOR line is an idea to check by ear.',
    typeNotes: { orchDyn: 'A dynamic can work too: choose by response, pattern, maximum level, power and mount, and compare by ear.' },
    note: 'Clearance comes first: stop the player before moving a real stand. About 1 m is a starting height for a shared spot, not a safety clearance — check the whole passage with the player.',
    availableLead: 'Starting points for this mic and set',
    learn: {
      intro: 'What you just did, in words. After our research, each blue zone is where we recommend you begin: a shared spot about 1 m above the heads between two drums (one for each pair in a set of four), or a closer spot on the conductor’s side of one drum. They are starting points, not rules: move from there and listen — there is no single right answer, and every set, player and hall is different.',
      separate: 'Height, distance and angle are separate variables: change one at a time, with the whole passage. The number of drums is not a required number of mics — scale up only if the music needs it.',
      clearance: 'Clearance comes first. Have the timpanist show the mallets’ full sweep, the reach between drums, the pedal changes and their sightline to the conductor before anything is placed. The grey hatched areas show roughly where to keep clear — leave more room on a real stage.',
      tendencies: 'A shared spot farther up hears more of both drums and of the hall; a closer spot hears more attack and a smaller part of a large head, and may miss the note’s full bloom. Aiming near the rim never means putting hardware in the playing area. All tendencies to check by ear.',
    },
  },
  context: {
    zone: 'tp.near',
    typeId: 'orchSdc',
    patterns: [
      { id: 'cardioid', label: 'cardioid', typeId: 'orchSdc' },
      { id: 'supercardioid', label: 'supercardioid', typeId: 'orchSdc' },
      { id: 'hypercardioid', label: 'hypercardioid', typeId: 'orchSdc' },
    ],
    micNoun: 'A small condenser',
    shield: ['tp.head29', 'tp.bowl29', 'tp.head26', 'tp.bowl26', 'tp.hoop29', 'tp.hoop26'],
    azMax: 45,
    elMax: 60,
    aimBlurb: 'Swing the front up to 45° either way — it still looks toward the drum.',
    plan: { u0: -1400, u1: 1450, v0: -900, v1: 1200 },
    side: { u0: -1400, u1: 1450, v0: -1500, v1: 60 },
    target: 'downstage',
    frontIds: ['fill'],
    targetWord: 'monitor',
    looking: 'Top view · a closer spot on the conductor’s side of the 29 in drum',
    prompt: 'The monitor stays where the stage needs it. Turn the MIC (AIM) or change its PATTERN until the downstage wedge sits in the rejection.',
    activityDone: 'done — the downstage wedge sat in a null by your aim or pattern',
    deepNull: 'On this simplified pattern a null looks infinitely deep. Real microphones reject far less there, and least at low frequencies — where a timpani’s note lives. Use the null to aim, not to promise silence.',
    cardioidReveal: 'What you just saw: a cardioid rejects most directly behind (180°). This wedge sits off to the side of a mic looking down at the drum, so a cardioid cannot turn its back to it — try the other patterns.',
    shieldNote: 'Real patterns change with pitch and the stage reflects sound — this is the reasoning, not a prediction. Work out the real mic and monitor positions with the system operator.',
    studioId: 'tp.ctx.studio',
    studioPrompt: 'A recording in a hall has no wedge to reject. The decision changes: does the main pickup already carry the timpani?',
    studioNote: 'In a recording, the main pair usually carries the timpani’s low notes and the hall; a spot adds definition only where it is missing. Switch back to LIVE for the monitor exercise.',
    learn: {
      intro: 'These are scenario-based comparisons, not rules: a recorded orchestra may need no timpani spot at all, and an outdoor amplified show may need more direct pickup.',
      points: [
        { title: 'HOW MUCH SPOT', text: 'Recording: the main array first, then a shared or individual spot only where the score or the balance needs definition. Live: a stable, directional spot with enough gain before feedback, chosen with the PA operator.' },
        { title: 'HOW MANY MICS', text: 'Four drums do not need four mics: one shared spot per pair is a common start, and one spot can cover a small set. Two spots are not automatically a stereo pair — blend them for coverage, and check them in mono.' },
        { title: 'THE HALL', text: 'Recording: the hall carries the note’s bloom, and timing with the main array decides whether a spot helps. Outdoors: wind, spill and access can push toward a closer, lower-profile setup.' },
        { title: 'THE PITCH', text: 'Reflections, nearby stands and a very close attack can mask the perceived pitch. Check every note in the passage, not one hit.' },
      ],
      body: 'On an amplified stage the monitors stay where the players need them: turn the mic or choose its pattern so that a null faces a loud unwanted source — and remember that real nulls are shallowest at the low frequencies a timpani makes.',
      warn: 'No mic position alone prevents feedback: the monitors and PA, channel gain and EQ, the room and the open mics all matter. Work it out with the system operator, and never create feedback deliberately.',
    },
  },
  twoMic: {
    variant: 'two',
    A: { typeId: 'orchSdc', pattern: 'cardioid', zone: 'tp.pair' },
    B: { typeId: 'orchSdc', pattern: 'cardioid', zone: 'tp.near' },
    learn: [
      'A common idea: a shared spot high between the drums for the set, and a closer spot for one drum’s attack. Each mic hears every drum at a different time, so the pair — and each mic against the main array — combs. Start with one spot useful on its own.',
      'When a second channel goes in: hear it with the main array, at the intended levels, in MONO; compare both polarity states at a matched level — a louder state almost always sounds “better” at first. A delay set on a spot may help one relationship and harm another; judge it in the whole orchestra.',
    ],
    warn: 'This simplified graph shows one point source and straight paths: a real timpani head is large and the hall reflects, so read the notch depths as illustrative only. The notch POSITIONS follow from the arrival-time difference.',
  },
  practice: {
    gain: 'tp.prac.gain',
    second: 'tp.prac.3',
    mixed: ['tp.mix.1', 'tp.mix.2', 'tp.mix.3'],
    mixedIntro: 'Three cards from earlier pages, mixed: a reference plane, a pattern’s null, and the delay between a spot and the main pickup.',
  },
};
