BEGIN;
WITH ins AS (
  INSERT INTO glossary (term,definition,plain_english,purpose_function,practical_application,category,difficulty,related_terms,common_mistakes,scenario_contexts,achievement_id)
  SELECT 'Subtractive Mixing','A mixing approach in which competing frequency content is cut (attenuated) from individual tracks rather than boosted, so each source occupies its own region of the frequency spectrum. By carving overlapping frequencies out of the sources that need them least, the engineer creates separation between instruments, reduces masking, and preserves headroom on the mix bus, because cutting lowers energy instead of adding it.','Subtractive mixing means you take sound away instead of adding it. When two instruments fight for the same space, you turn down the frequencies that one of them does not really need. That makes room for each instrument to be heard. It also keeps the whole mix from getting too loud or muddy, because you are cutting, not boosting.','It reduces frequency masking and low-end buildup so each element in a mix stays clear and distinct. Cutting instead of boosting also keeps the overall level and headroom under control, which is why engineers reach for it before adding gain.','To make a vocal clearer, an engineer cuts the competing frequencies in the instruments around it rather than boosting the vocal itself. To clean up a muddy mix, they high-pass sources that do not need low end and trim the buildup around 200-400 Hz.','Mixing technique','intermediate',ARRAY['Subtractive synthesis','Frequency masking','Equalization (EQ)','High-pass filter','Gain staging']::text[],ARRAY['Boosting frequencies first instead of cutting, which adds level and eats into headroom','Over-cutting until the mix loses body and sounds thin','Applying the same cuts to every track instead of tailoring them to each source','Confusing subtractive mixing (creating space between tracks) with subtractive synthesis (shaping a single oscillator''s tone)']::text[],ARRAY['Making a lead vocal cut through by carving competing frequencies from the guitars and keys','Clearing a muddy mix by high-passing sources that have no useful low-end content','Reducing masking between bass and kick drum so both stay defined']::text[],'4e4249cd-e91d-464b-ad0d-1b83b211bbeb'
  WHERE NOT EXISTS (SELECT 1 FROM glossary g WHERE regexp_replace(lower(g.term),'[^a-z0-9]','','g')=regexp_replace(lower('Subtractive Mixing'),'[^a-z0-9]','','g'))
  RETURNING id
)
INSERT INTO glossary_topics (glossary_id,achievement_id,is_primary)
SELECT id,'4e4249cd-e91d-464b-ad0d-1b83b211bbeb'::uuid,true FROM ins
UNION ALL
SELECT id,'07df90cd-38fa-4737-8b35-b63864c78de1'::uuid,false FROM ins;
COMMIT;
