/**
 * M07b CONCERT SNARE — the pages' snare words (engine/model/copy.ts). The
 * starting-points voice (owner ruling 2026-10-04): no source, brand or model
 * names, no badges; tendencies, never results.
 */
import type { LessonCopy } from '../../engine/model/copy.ts';
import { R } from './model.ts';

export const CSN_COPY: LessonCopy = {
  variantKey: 'SNARES',
  variantShort: { on: 'snares on', off: 'snares off' },
  sceneSubject: { on: 'a 14 × 6½ in concert snare drum on its stand, the snares on', off: 'a 14 × 6½ in concert snare drum on its stand, the snares off' },
  viewTag: { side: 'SIDE · CUTAWAY', top: 'TOP' },
  axes: {
    x: { plus: 'toward the audience', minus: 'toward the player', label: 'FRONT–BACK', blurb: 'Toward the audience or toward the player (x). The player stands behind the drum.' },
    y: { plus: 'below the batter', minus: 'above the batter', label: 'HEIGHT', blurb: 'Up or down (y), measured from the batter head. Distances are read from the head or rim the zone names.' },
    z: { plus: 'to player’s right', minus: 'to player’s left', label: 'ACROSS', blurb: 'Toward the player’s left or right (z).' },
  },
  instrument: {
    figureBadge: 'A 14 × 6½ in concert snare, cut open, on its stand',
    figureLabel: 'Side view of a 14 by 6 and a half inch concert snare drum, cut open, on a concert stand: the batter head on top, the snare-side head underneath with the snares against it, the throw-off on the player’s side, and the player’s sticks above.',
    partsBadge: 'A 14 × 6½ in concert snare, cut open · tap a part to name it',
    partsLooking: { side: 'Side view · the drum cut open', top: 'Top view · the batter head' },
    partsIdle: 'The sticks strike the batter head on top; the snares lie against the thin head underneath. Heads, snares, shell, tuning and any muffling all shape what you hear — the next page shows how.',
    variantNotes: { off: 'SNARES OFF: the throw-off has released the snares, and they hang just clear of the head. Players switch the snares on and off during a piece — ask where.' },
  },
  sound: {
    strikes: [
      { id: 'c', label: 'CENTRE', mm: 0, blurb: 'The exact centre of the head.' },
      { id: 'half', label: 'HALFWAY OUT', mm: R * 0.5, blurb: 'Halfway from the centre to the rim — explore what it drives.' },
      { id: 'edge', label: 'NEAR THE RIM', mm: R * 0.85, blurb: 'Close to the rim — explore what it drives.' },
    ],
    strikeDefault: 'half',
    striker: 'STICK',
    strikerPhrase: 'the stick',
    subject: 'Side view of the concert snare, cut open',
    looking: { on: 'Side view · the snare cut open · snares on', off: 'Side view · the snare cut open · snares off' },
    cells: [
      { k: 'BATTER', at: ['AT REST', 'PUSHED IN', 'PUSHED IN', 'PUSHED IN'], flex: 1.15 },
      { k: 'SNARE HEAD', at: ['AT REST', 'AT REST', 'PUSHED OUT', 'PUSHED OUT'], flex: 1.25 },
      { k: 'SNARES', at: ['—', '—', 'SLAPPED', 'BUZZING'], byVariant: { off: ['OFF', 'OFF', 'OFF', 'OFF'] }, flex: 1 },
    ],
    reveal: 'The squeezed air pushes the snare-side head OUT, downward — both heads move the same way at that moment. With the snares on, the bottom head throws them off and they slap back: that is the buzz.',
    after: 'Then both heads spring back and keep ringing, and the snares rattle against the bottom head for as long as it moves. The heads, the snares, the tuning and any muffling all shape that sound — they are the player’s choices.',
    shapesNotes: [
      'A shape is set moving only as much as the head moves at the strike point in that shape. At the exact centre, every shape with a still line across the head stands still — so a centre strike drives only the ring-shaped ones; moving out from the centre wakes the others.',
      'This is a simplified head in empty space. On a real snare the air inside, the second head and the snares pull these numbers around — the next step shows the two heads working together.',
    ],
    coupledSubject: 'Side view of the concert snare',
    coupledNote: 'One stroke sets both heads going, and the bottom head drives the snares. The sound you hear is the heads, the air and the snares together.',
    silentNote: 'This lab never plays a sound and draws no frequency curve for the drum: how a real concert snare sounds depends on the drum, its heads, its snares, the tuning, the sticks and the player. The pictures show where the sound comes from and where it leaves.',
  },
  setting: {
    kitA11y: 'The percussion section from above, at the back of an orchestra: the concert snare on its stand with its player upstage of it; the concert bass drum, the timpani, a suspended cymbal and the trap table nearby; a row of brass players in front.',
    kitLanding: 'Tap anything around the concert snare — or step through ITEM — to see what it means for a snare mic. There is nothing to answer yet.',
    kitIdle: 'The concert snare stands in the percussion row at the back, its player behind it. Around it: loud neighbours, the trap table the player turns to, and the brass in front.',
    leftHanded: 'Percussion sections are laid out differently from one orchestra to the next — check the real stage plan before you place anything.',
    stageA11y: 'The orchestra on an amplified stage, from above: the percussion at the back, the conductor and the audience at the front, PA stacks at the front corners, and two floor monitors near the percussion.',
    studioA11y: 'The orchestra recorded in a hall, from above: the main pair of microphones over the conductor, the hall’s walls around the stage, no monitors.',
    stageIdle: 'Two floor monitors: one downstage of the percussion, facing back toward it, and the section’s own monitor beside the players. The PA faces the audience.',
    studioIdle: 'No monitors. The main pair over the conductor hears the whole orchestra — the concert snare included — and the hall is part of the sound.',
    before: [
      { title: 'ASK THE PLAYER FIRST', text: 'Have the percussionist play the real passage: the softest strokes, the buzz roll, the accents, any rim strokes and every snare on/off change. Ask what the part should sound like — a sustained roll, a crisp figure, or both.' },
      { title: 'IS A SPOT NEEDED AT ALL?', text: 'Listen to the main pickup and the nearby section mics first. Even an amplified orchestra can leave the concert snare without a spot when other mics already carry it — a spot is an option for missing clarity, not a default.' },
      { title: 'WORK WITH THE DRUM AS IT IS', text: 'No retuning, no tighter snares, no new muffling and no request to strike elsewhere just to suit a mic. The drum’s sound is the player’s.' },
    ],
    plan: {
      title: 'In the orchestra',
      badge: 'The percussion from above · a typical concert layout · grey hatch = the players’ space',
      looking: 'Plan · the percussion row, the audience toward the bottom',
      stageBadge: 'From above · an amplified orchestra · two monitors where a stage often puts them',
      studioBadge: 'From above · an orchestra recorded in a hall',
      stageLooking: 'Plan · the orchestra on an amplified stage',
      studioLooking: 'Plan · the orchestra in a recording hall',
      widePrompt: 'Switch STAGE / STUDIO, and tap what is new around the orchestra.',
    },
  },
  placement: {
    workedZone: { on: 'csn.whole', off: 'csn.whole' },
    workedLine: 'This starting point is also read against {line}: the readout says how far in from — or out from — the rim edge the mic is.',
    workedAim: 'Angle the mic toward the centre of the head — the starting point counts while its axis meets the head there. Distance, height and angle are separate things to try.',
    workedClear: 'Clear of every stroke — the highest and widest stick motion, the throw-off, the stand and the player. Clearance comes first, before any number, and the player stops before a real mic moves.',
    blocked: {},
    reveal: 'Closer tends to bring more direct detail and less room; farther, more of the whole drum and more of its neighbours — and drums, rooms and players vary, so “it depends” is fair too. Each zone’s LISTEN FOR line is an idea to check by ear.',
    typeNotes: { orchSdc: 'Ideas to try with a small condenser: start a little farther than with a dynamic and compare the roll at matched level. Either type can work — choose by response, pattern, maximum level, power and mount.' },
    note: 'Clearance comes first: stop the player before moving a real mic, and check the whole passage — not one stroke. None of these distances is a safety clearance.',
    availableLead: 'Starting points for this mic',
    learn: {
      intro: 'What you just did, in words. After our research, these blue zones are where we recommend you begin: two close starting points that snares in general are often miked from, and a broader one — measured from the head or rim each names. None is a concert-snare rule. Move from there and listen: there is no single right answer, and every drum, player and hall is different.',
      separate: 'Height, distance and angle are separate variables: change one at a time, with the same passage and realistic dynamics. Distances are measured to the mic’s FRONT and rounded to ≈ 5 mm.',
      clearance: 'Clearance comes first. Have the player show the highest and widest stick motion, the throw-off and the reach to the trap table before anything is placed. The grey hatched areas show roughly where to keep clear — leave more room on a real stage.',
      tendencies: 'Closer usually means more direct detail and less room; it can also make a roll sound like separate clicks. Farther brings more of the whole drum, and of the cymbals and timpani beside it. A directional mic close to the head may also lift its own lows (proximity effect) — how much depends on the mic and the angle.',
    },
  },
  context: {
    zone: 'csn.whole',
    typeId: 'smallDynCard',
    patterns: [
      { id: 'cardioid', label: 'cardioid', typeId: 'smallDynCard' },
      { id: 'supercardioid', label: 'supercardioid', typeId: 'smallDynCard' },
      { id: 'hypercardioid', label: 'hypercardioid', typeId: 'smallDynCard' },
    ],
    micNoun: 'A small dynamic',
    shield: ['csn.shell', 'csn.batter', 'csn.snareHead'],
    azMax: 45,
    elMax: 45,
    aimBlurb: 'Swing the front up to 45° either way — it still looks at the drum.',
    plan: { u0: -820, u1: 1900, v0: -900, v1: 1100 },
    side: { u0: -820, u1: 1900, v0: -620, v1: 840 },
    target: 'downstage',
    frontIds: ['fill'],
    targetWord: 'monitor',
    looking: 'Top view · the mic angled down at the snare',
    prompt: 'The monitor stays where the stage needs it. Turn the MIC (AIM) or change its PATTERN until the downstage wedge sits in the rejection.',
    activityDone: 'done — the downstage wedge sat in a null by your aim or pattern',
    deepNull: 'On this simplified pattern a null looks infinitely deep. Real microphones reject far less there, and least at low frequencies. Use the null to aim, not to promise silence.',
    cardioidReveal: 'What you just saw: a cardioid rejects most directly behind (180°). The wedge sits behind the mic but below it too — and a mic angled down at the drum cannot also point its back at a floor wedge. Try the other patterns.',
    shieldNote: 'Real patterns change with pitch, and the stage reflects sound — this is the reasoning, not a prediction. Work out the real mic and monitor positions with the system operator.',
    studioId: 'cs.ctx.studio',
    studioPrompt: 'A recording in a hall has no wedge to reject. The decision changes: does the snare need a spot at all?',
    studioNote: 'In a recording, the main pair and section mics often carry the concert snare already; a spot is blended under them only if detail is missing. Switch back to LIVE for the monitor exercise.',
    learn: {
      intro: 'These are scenario-based comparisons, not rules: a concert snare may need no spot at all, live or recorded, and a close spot may be right on a loud outdoor stage.',
      points: [
        { title: 'IS A SPOT NEEDED?', text: 'Recording: the main array and section mics come first; a gentle spot only if the roll or the soft strokes are missing. Live: listen to what the hall and the other mics already give before adding a channel.' },
        { title: 'HOW CLOSE', text: 'Recording: a broader spot keeps the drum in its place in the orchestra. Live: monitor and PA spill and the gain before feedback can favour a closer, directional spot — outside the sticks’ reach.' },
        { title: 'HOW MANY MICS', text: 'Each extra open mic adds spill and another arrival time. A bottom mic earns its channel only if it adds something the top mic and the main pickup do not.' },
        { title: 'THE IMAGE', text: 'A spot raised too far pulls the snare to the front of the orchestra. Bring it up under the main pickup and check where the drum seems to sit.' },
      ],
      body: 'On an amplified stage the monitors stay where the players need them: turn the mic or choose its pattern so that a null faces a loud unwanted source. The section’s own monitor beside the players sits in front of a mic aimed at the drum, where no pattern rejects it.',
      warn: 'No mic position alone prevents feedback: the monitors and PA, channel gain and EQ, the room and the open mics all matter. Work it out with the system operator, and never create feedback deliberately.',
    },
  },
  twoMic: {
    A: { typeId: 'smallDynCard', pattern: 'cardioid', zone: 'csn.top' },
    B: { typeId: 'smallDynCard', pattern: 'cardioid', zone: 'csn.bottom' },
    opposite: { surface: 'batter', note: 'The mics sit on opposite sides of the drum: as the batter head moves away from the top mic, the snare-side head moves toward the bottom mic. One hears a pull while the other hears a push, so the sum starts on the inverted notch set — that is why engineers try the polarity switch on a bottom mic. Try it; never assume it.' },
    learn: [
      'A common idea on a snare: a top mic for the stick and the head, and a bottom mic for more of the snares. On a concert snare the bottom mic is optional — the snares’ response is part of the drum’s colour, but the bottom mic also hears the stand, the throw-off and the floor. Start with the top mic alone.',
      'When the second channel goes in: hear the pair at the intended levels in MONO, compare both polarity states at a controlled, matched level — a louder state almost always sounds “better” at first — and then check the pair against the main pickup. If it adds more hiss and spill than character, leave it out.',
    ],
    warn: 'The two mics hear DIFFERENT heads of the drum, so this simplified graph shows only the shared part of the sound — not what the pair will sound like. The notch POSITIONS follow from the arrival-time difference; their DEPTH depends on the two levels, which this model takes from distance alone — that does not hold a few centimetres from a head, so read the depths as illustrative only.',
  },
  practice: {
    gain: 'cs.prac.gain',
    second: 'cs.prac.3',
    mixed: ['cs.mix.1', 'cs.mix.2', 'cs.mix.3'],
    mixedIntro: 'Three cards from earlier pages, mixed: a reference rim, a pattern’s null, and the delay between a spot and the main pickup.',
  },
};
