BEGIN;
-- Phase 2: mechanical moves of 192 KEEP+MERGE old topics -> cv172 final targets.
-- Excludes 22 split parents + 16 merge-into-split-parent sources (all handled in Phase 3).
CREATE TEMP TABLE _p2map ON COMMIT DROP AS
SELECT o.id AS old_id, n.id AS new_id
FROM (VALUES
('Professional Audio Safety','Professional Audio Safety'),
('Signal Path & Levels','Signal Path & Levels'),
('Connectors & Plugs','Connectors & Plugs'),
('Cables & Wiring','Cables & Wiring'),
('I/O Connections','Connectors & Plugs'),
('Microphone Specs & Characteristics','Microphone Specs & Characteristics'),
('Stereo & Ensemble Miking Techniques','Stereo & Ensemble Miking Techniques'),
('Mic Controls, Power & Mounting','Microphone Specs & Characteristics'),
('Specialized & Application Microphones','Specialized & Emerging Microphones'),
('Loudspeaker Types & Drivers','Loudspeaker Types & Drivers'),
('Enclosures & Crossovers','Enclosure, Horn & Radiation Engineering'),
('Loudspeaker Specs & Behavior','Loudspeaker Measurement & Modeling'),
('Amplifiers','Amplifiers'),
('Vacuum Tubes','Vacuum Tubes'),
('Channel Strip & Processing','Console Signal Flow & Gain Staging'),
('Buses, Routing & Matrix','Console Architecture & Bus Structure'),
('Digital Console Workflow & Recall','Console Architecture & Bus Structure'),
('Recorder Types & Formats','Recorders & File Formats'),
('Audio File Formats & Media','Recorders & File Formats'),
('Recording Transport & Controls','Recorders & File Formats'),
('Storage, Backup & Archival','Audio Restoration & Archival'),
('Racks, Patchbays & Wiring Infrastructure','Racks, Patchbays & Wiring Infrastructure'),
('Studio/Stage Furniture & Mounting','Racks, Patchbays & Wiring Infrastructure'),
('Physical Controls & Hardware','Racks, Patchbays & Wiring Infrastructure'),
('Power & Signal Distribution Hardware','Racks, Patchbays & Wiring Infrastructure'),
('Documentation & Diagrams','Documentation & Diagrams'),
('Dante Fundamentals & Routing','Dante Fundamentals & Routing'),
('Dante Devices, Modules & Certification','Dante Fundamentals & Routing'),
('Clocking, Redundancy & Network Management','Clocking, Redundancy & Network Management'),
('Control Surfaces & Machine Control','Control Surfaces & Machine Control'),
('Equalization (EQ)','Equalization (EQ)'),
('Reverb','Reverb'),
('Delay & Time-Based Effects','Delay & Time-Based Effects'),
('Acoustic Principles & Room Behavior','Acoustic Principles & Room Behavior'),
('Absorption & Bass Trapping','Room Treatment Layout & Application'),
('Diffusion & Materials','Room Treatment Layout & Application'),
('Room Treatment Layout & Application','Room Treatment Layout & Application'),
('Acoustic & Room Measurement','Acoustic & Room Measurement Methods'),
('System Optimization','System Deployment & Rigging'),
('System Maintenance','Repair'),
('Analog Live Sound','Analog Live Sound'),
('Digital Live Sound','Digital Live Sound'),
('System Tuning & Alignment','System Deployment & Rigging'),
('RF Wireless Systems','RF Wireless Systems'),
('DJ Performance & Turntablism','Beatmatching, Mixing & FX'),
('DJ Equipment & Software','Beatmatching, Mixing & FX'),
('Beatmatching, Mixing & FX','Beatmatching, Mixing & FX'),
('Road Crew','Road Crew'),
('Venue Architecture & Spaces','Venue Architecture & Spaces'),
('Stage Geography & Backstage','Stage Geography & Backstage'),
('House & Audience Areas','Venue Architecture & Spaces'),
('Stage Platforms, Scenery & Soft Goods','Stage Platforms, Scenery & Soft Goods'),
('Fly Systems & Overhead Access','Rigging Hardware, Loads & Motorized Flying'),
('Rigging Hardware, Loads & Motorized Flying','Rigging Hardware, Loads & Motorized Flying'),
('Orchestra Pit & Ensemble Layout','Orchestra Pit & Ensemble Layout'),
('Show Control, Cueing & Communications','Show Control, Cueing & Communications'),
('Theatrical Sound (commercial card)','Theatrical Sound (commercial card)'),
('Worship Sound (commercial card)','Worship Sound (commercial card)'),
('Passive Components','Passive Components'),
('Electromechanical Parts & Hardware','Electromechanical Parts & Hardware'),
('Active Devices & Semiconductors','Active Devices & Semiconductors'),
('PCB, Assembly & Soldering','Soldering'),
('Manufacturing & Production','Circuits & Topologies'),
('HiFi Consumer Audio','HiFi Consumer Audio'),
('Home Theater & Residential AV','HiFi Consumer Audio'),
('Vehicle Audio','Vehicle Audio'),
('Soldering','Soldering'),
('Repair','Repair'),
('Recording Fundamentals & Signal Chain','Recording Fundamentals & Signal Chain'),
('Session Setup & Signal Flow','Recording Fundamentals & Signal Chain'),
('Session Workflow, Takes & Documentation','Session Workflow, Takes & Documentation'),
('Instrument Recording - Strings & Guitar','Instrument Recording (by Source)'),
('Instrument Recording - Drums & Percussion','Drum-Kit Recording'),
('Instrument Recording - Keys, Winds & Brass','Instrument Recording (by Source)'),
('Studio Recording Craft - Advanced','Band Tracking Workflow & Arrangement'),
('Drum-Kit Recording','Drum-Kit Recording'),
('Guitar, Bass & Amp Recording','Instrument Recording (by Source)'),
('Band Tracking Workflow & Arrangement','Band Tracking Workflow & Arrangement'),
('Mix Fundamentals & Workflow','Mix Automation, Bus & Loudness'),
('Instrument Mixing - Drums & Percussion','Instrument Mixing - Drums & Percussion'),
('Instrument Mixing - Guitars, Bass & Keys','Instrument Mixing - Guitars, Bass & Keys'),
('Vocal Mixing','Vocal Mixing'),
('Orchestral, Choir & Acoustic-Ensemble Mixing','Orchestral, Choir & Acoustic-Ensemble Mixing'),
('Mix Automation & Recall','Mix Automation, Bus & Loudness'),
('Mix Bus, Loudness & Translation','Mix Automation, Bus & Loudness'),
('Loudness, Dynamics & QC','Mastering Fundamentals & Chain'),
('Delivery Formats & Metadata','Mastering Fundamentals & Chain'),
('Podcast Production','Podcast Production'),
('Streaming & Distribution','Broadcast Air Chain & Transmission'),
('Broadcast Loudness & Compliance','Broadcast Processing & Loudness'),
('Production Sound & Field Recording','Post Workflow, Spotting & Sessions'),
('Re-Recording & Final Mix','Re-Recording & Final Mix'),
('DAW Fundamentals & Session Management','DAW Fundamentals & Session Management'),
('Editing & Comping','DAW Fundamentals & Session Management'),
('In-the-Box Mixing & Automation','DAW Fundamentals & Session Management'),
('DAW: Logic','DAW: Logic'),
('DAW: Cubase/Nuendo','DAW: Cubase/Nuendo'),
('DAW: REAPER','DAW: REAPER'),
('DAW: Ableton Live','DAW: Ableton Live'),
('DAW: Studio One','DAW: Studio One'),
('DAW: Digital Performer/Reason','DAW: Digital Performer/Reason'),
('MIDI','MIDI'),
('Synthesis Fundamentals & Oscillators','Synthesis Fundamentals & Oscillators'),
('Filters, Envelopes & Modulation','Synthesis Fundamentals & Oscillators'),
('Synthesis Types, Modular & CV','Synthesis Fundamentals & Oscillators'),
('Hearing Anatomy & Function','Hearing Anatomy, Health & Disorders'),
('Hearing Protection & Occupational Health','Hearing Anatomy, Health & Disorders'),
('Hearing Disorders & Health','Hearing Anatomy, Health & Disorders'),
('Psychoacoustics','Psychoacoustics'),
('Spatial Hearing & Localization','Loudness & Listening Environments'),
('Speech Intelligibility','Speech & Voice Perception'),
('Loudness & Listening Environments','Loudness & Listening Environments'),
('Voice & Vocal Perception','Speech & Voice Perception'),
('Ear Training','Tonal & Timbre Descriptors'),
('Tonal & Timbre Descriptors','Tonal & Timbre Descriptors'),
('Listening Slang & Sound Identification','Tonal & Timbre Descriptors'),
('Monitoring & Audio Evaluation','Attack, Decay, Resonance & Artifact Identification'),
('Attack, Decay, Resonance & Artifact Identification','Attack, Decay, Resonance & Artifact Identification'),
('Strings, Guitar & Keys','Strings, Guitar & Keys'),
('Drums & Percussion','Drums & Percussion'),
('Winds, Brass & Organ','Winds, Brass & Organ'),
('Project Management','Project Management'),
('Workplace Skills','Workplace Skills'),
('Audio Career Exploration','Audio Career Exploration'),
('Portfolio Development','Audio Career Exploration'),
('Copyright, Publishing & Licensing','Music Entrepreneurship'),
('Music Entrepreneurship','Music Entrepreneurship'),
('Industry Foundations','Industry Foundations'),
('Immersive Formats & Delivery','Immersive Formats & Delivery'),
('Object & Bed Panning / Authoring','Immersive Formats & Delivery'),
('Immersive Monitoring & Calibration','Immersive Formats & Delivery'),
('Dialogue Editing','Dialogue Editing'),
('ADR & Looping','ADR & Looping'),
('Dubbing & Localization','Dubbing & Localization'),
('Foley Performance & Recording','Foley Performance & Recording'),
('SFX Editorial & Sound Design','SFX Editorial & Sound Design'),
('Game Audio','Game Audio'),
('Themed Entertainment / Haunt Audio','Game Audio'),
('Studio & Facility Design','Studio & Facility Design'),
('Studio Acoustics & Design','Studio & Facility Design'),
('Vinyl / Disc Mastering','Vinyl / Disc Mastering'),
('Audio Restoration & Archival','Audio Restoration & Archival'),
('Preamp & Converter Engineering','Preamp & Converter Engineering'),
('AI Music Generation & Composition','AI Music, Voice & Creative Tools'),
('AI Voice & Speech','AI Music, Voice & Creative Tools'),
('AI Source Separation & Restoration','AI Music, Voice & Creative Tools'),
('AI Mixing/Mastering & Adaptive Processing','AI Music, Voice & Creative Tools'),
('Neural Amp Modeling & Neural Synthesis','AI Music, Voice & Creative Tools'),
('Live Sound - Crew Roles & Departments','Road Crew'),
('Live Sound - Production Documents & Advancing','Live Sound - FOH Mixing Workflow'),
('Live Sound - Stage Patch & Signal Distribution','Live Sound - FOH Mixing Workflow'),
('Live Sound - FOH Mixing Workflow','Live Sound - FOH Mixing Workflow'),
('Live Sound - Monitor Engineering','Live Sound - Monitor Engineering'),
('Live Sound - Soundcheck / Rehearsal / Virtual Soundcheck','Live Sound - FOH Mixing Workflow'),
('Live Sound - PA Deployment & System Engineering','System Deployment & Rigging'),
('Live Sound - Festival Changeovers & Guest-Engineer','Live Sound - FOH Mixing Workflow'),
('Live Sound - Communication & Show Calls','Show Control, Cueing & Communications'),
('Live Sound - Concert-Audio Slang','Live Sound - Concert-Audio Slang'),
('Magnetic Tape Preservation & Conservation','Magnetic Tape Preservation & Conservation'),
('Archival Preservation & Obsolete Media','Archival Preservation & Obsolete Media'),
('Dubbing - Adaptation, Sync & Deliverables','Dubbing - Adaptation, Sync & Deliverables'),
('Digital Audio - Sampling, Quantization & Formats','Digital Audio - Sampling, Quantization & Formats'),
('Foundations - Sound, Waveform, Level & Phase','Foundations - Sound, Waveform, Level & Phase'),
('Recording, Mixing & Troubleshooting Concepts','Recording, Mixing & Troubleshooting Concepts'),
('Standards - Coding, Systems, Metadata & Transport','Standards - Coding, Systems, Metadata & Transport'),
('Standards - General Acoustics & Signal Terms','Standards - General Acoustics & Signal Terms'),
('Standards - Immersive/Object/Scene, MIR, ML & Loudness','Standards - Immersive/Object/Scene, MIR, ML & Loudness'),
('Standards - Psychoacoustics, Hearing & Audiology','Standards - Psychoacoustics, Hearing & Audiology'),
('Standards - Room, Building, Environmental & Measurement','Standards - Room, Building, Environmental & Measurement'),
('Advanced & Physical Acoustics (Nonlinear/Structural/Aero/Materials)','Advanced & Physical Acoustics (Nonlinear/Structural/Aero/Materials)'),
('Ultrasonics, Underwater & Spatial-Audio Science','Ultrasonics, Underwater & Spatial-Audio Science'),
('Surveillance, Forensic & Covert Audio','Surveillance, Forensic & Covert Audio'),
('Sound Law - Legal & Regulatory Framework','Sound Law - Framework, Metrics & Compliance'),
('Sound Law - Measurement Descriptors & Compliance Metrics','Sound Law - Framework, Metrics & Compliance'),
('Sound Law - Live Events & Entertainment Compliance','Sound Law - Framework, Metrics & Compliance'),
('Sound Law - Assessment, Mapping & Mitigation','Sound Law - Assessment, Mapping & Mitigation'),
('Sound Law - Standards, Laws & Instruments','Sound Law - Assessment, Mapping & Mitigation'),
('Bioacoustics & Ecoacoustics','Bioacoustics & Ecoacoustics'),
('Sound Physics, Measurement & Acoustic Quantities','Sound Physics, Measurement & Acoustic Quantities'),
('Advanced Acoustic Imaging & Sound-Field Reconstruction','Advanced Acoustic Imaging & Sound-Field Reconstruction'),
('Medical, Hearing & Clinical Acoustics','Medical, Hearing & Clinical Acoustics'),
('Ultrasonics, NDT & Industrial Inspection','Ultrasonics, NDT & Industrial Inspection'),
('Geologic & Seismoacoustics','Geologic & Seismoacoustics'),
('Astronomical & Cosmological Acoustics','Astronomical & Cosmological Acoustics'),
('Archaeological & Heritage Acoustics','Archaeological & Heritage Acoustics'),
('Anthropology & Sound Studies','Anthropology & Sound Studies'),
('Chemical & Molecular Acoustics','Chemical & Molecular Acoustics'),
('Cross-Disciplinary Sonic Sensing','Data Sonification & Auditory Display'),
('Forensic Audio & Investigative Acoustics','Surveillance, Forensic & Covert Audio'),
('Underwater Acoustics & Sonar','Ultrasonics, Underwater & Spatial-Audio Science'),
('Aeroacoustics & Flow-Induced Sound','Advanced & Physical Acoustics (Nonlinear/Structural/Aero/Materials)'),
('Data Sonification & Auditory Display','Data Sonification & Auditory Display')
) AS m(old_norm,new_name)
JOIN achievements o ON o.curriculum_version_id='51c1d5db-1d05-4d43-8853-5fa1503fb751' AND replace(o.name,'—','-')=m.old_norm
JOIN achievements n ON n.curriculum_version_id='a7c1f2e0-9b34-4d55-8e21-0c4f6a9b1d72' AND n.name=m.new_name;

UPDATE glossary g SET achievement_id=map.new_id
FROM _p2map map JOIN glossary_topics gt ON gt.achievement_id=map.old_id AND gt.is_primary=true
WHERE gt.glossary_id=g.id;
UPDATE glossary_topics gt SET achievement_id=map.new_id
FROM _p2map map WHERE gt.achievement_id=map.old_id AND gt.is_primary=true;

SELECT
 (SELECT count(*) FROM _p2map) AS mapped_topics,
 (SELECT count(*) FROM glossary_topics gt JOIN achievements a ON a.id=gt.achievement_id AND a.curriculum_version_id='a7c1f2e0-9b34-4d55-8e21-0c4f6a9b1d72' WHERE gt.is_primary=true) AS primary_now_on_cv172,
 (SELECT count(*) FROM glossary) AS glossary_total;
COMMIT;