/**
 * M01 KICK DRUM — the lesson's pages as DATA (blueprint §7). The words come
 * from the owner's lesson (docs/labs/miking/source_text/Kick-Drum-Miking-
 * Technique-Research.txt, cited "L<n>") with the fixes logged in
 * docs/labs/miking/CORRECTIONS_LOG.md (K-01 … K-15) applied.
 *
 * House wording: tonal changes are TENDENCIES, never results; no audio (the
 * lab is fully silent); no invented curves; brands only as provenance.
 */
import type { Lesson, MikingScenario, PageContent, PageId, Symptom } from '../../engine/model/types.ts';
import { KICK_MODEL } from './geometry.ts';
import { KICK_ZONES } from './model.ts';

const pages: Record<PageId, PageContent> = {
  instrument: {
    title: 'Meet the instrument',
    goal: 'Name the two heads, find where the attack and the resonance come from, and choose ported or intact.',
    credit: { scenarios: ['k.inst.1'], interactive: 'regions', note: 'Find every sound source on the drawing (tap it, or step through PART), and answer the check.' },
    takeaway: 'The beater strikes the batter head; the front head, the air inside and the shell carry the resonance. Work with the drum as it is: never cut a port to match a diagram.',
  },
  microphone: {
    title: 'Choose the microphone',
    goal: 'Choose a mic by its properties — type, pattern, power, size and mount — not by its brand.',
    credit: { scenarios: ['k.mic.1', 'k.mic.2', 'k.mic.3'], note: 'Answer the three checks.' },
    takeaway: 'Pattern, power, size and mount decide what a mic can do here. No brand is required, and no mic type is universally better.',
  },
  placement: {
    title: 'Placement Studio',
    goal: 'Place a mic in a documented zone, measured from its stated head, clear of every moving part.',
    credit: { scenarios: ['k.place.1', 'k.place.2'], interactive: 'twoZones', note: 'Rest the mic, clear of every part, inside two different documented zones, and answer the two checks.' },
    takeaway: 'A documented zone is a starting point for its own product, measured from a named head. Distance, height and angle are separate variables — and clearance always wins.',
  },
  context: {
    title: 'Studio or live',
    goal: 'Aim the pattern’s real rejection at a loud unwanted source, without ever provoking feedback.',
    credit: { scenarios: ['k.ctx.1', 'k.ctx.2'], interactive: 'wedgeInNull', note: 'Put the wedge within ±15° of the chosen pattern’s null, and answer the two checks.' },
    takeaway: 'A cardioid rejects most directly behind; a supercardioid has a rear lobe and rejects most off the rear axis. No mic position alone prevents feedback.',
  },
  twoMic: {
    title: 'Two microphones',
    goal: 'See how the arrival-time difference between two mics places comb-filter notches — and what polarity does and does not change.',
    credit: { scenarios: ['k.two.1', 'k.two.2', 'k.two.3'], interactive: 'polarityVsDelay', note: 'Flip polarity both ways AND move a mic so the delay changes, then answer the three checks.' },
    takeaway: 'Polarity flips the sign; it does not remove a delay. 3:1 helps spill between mics on different sources; it does not make an inside/outside pair coherent. Judge the pair in mono.',
  },
  troubleshoot: {
    title: 'Troubleshoot',
    goal: 'Match each symptom to the first things to check.',
    credit: { scenarios: [], interactive: 'symptoms', note: 'Choose the first checks for all six symptoms (a retry is explained, never penalised).' },
    takeaway: 'Check the physical cause first — angle, clearance, gain staging, levels and polarity — before reaching for tone controls.',
  },
  practice: {
    title: 'Practice',
    goal: 'Choose a one-mic setup for a drum and a show, name an alternative, and say what would justify a second channel.',
    credit: { scenarios: ['k.prac.1', 'k.prac.2', 'k.prac.3'], note: 'Answer the three reasoning cards. The observation sheet is optional — it needs a real drum.' },
    takeaway: 'Safe placement, correct power and level checks, musical reasoning and an accurate account of polarity versus delay pass. A brand, a bass setting or a genre preset do not.',
  },
  sources: {
    title: 'Sources',
    goal: 'See where every number in this lesson comes from, what the sources disagree on, and what is still unknown.',
    credit: { scenarios: [], note: 'Credited when you move on from this page.' },
    takeaway: 'Manufacturer positions are documented starting points for particular products — not mandatory positions, and not predictions of another drum.',
  },
};

const scenarios: MikingScenario[] = [
  {
    id: 'k.inst.1',
    page: 'instrument',
    prompt: 'The drum you are asked to mic has an intact front head — no port. What does the lesson say to do?',
    options: ['Mic it from outside, or use an internal mic that is appropriately installed', 'Cut a port so a mic can go inside, as in the diagram', 'A kick drum without a port cannot be miked'],
    correct: 'Mic it from outside, or use an internal mic that is appropriately installed',
    explain: 'With an intact front head, outside pickup is a normal option, and an appropriately installed internal mic is another. Never alter the instrument to match a lesson diagram (L7).',
  },
  {
    id: 'k.mic.1',
    page: 'microphone',
    prompt: 'Which statement about the three kick dynamics the lesson names is documented?',
    options: ['The Beta 52A’s spec field says supercardioid; the e 902 and D112 MkII are cardioid', 'All three are cardioid, so they are interchangeable', 'All three are supercardioid'],
    correct: 'The Beta 52A’s spec field says supercardioid; the e 902 and D112 MkII are cardioid',
    explain: 'Shure lists “Supercardioid” (and describes it as “modified supercardioid”); Sennheiser and AKG list cardioid. Their frequency responses are shaped differently too, so none is a neutral reference (L15).',
  },
  {
    id: 'k.mic.2',
    page: 'microphone',
    prompt: 'DPA recommends its flatter-response condenser for kick. What does the lesson take from that?',
    options: ['It is one tonal objective, not proof that condensers are universally better', 'Condensers are always more accurate on kick', 'Dynamic mics cannot be used on a kick drum'],
    correct: 'It is one tonal objective, not proof that condensers are universally better',
    explain: 'A flatter response is a particular aim. The lesson forbids claiming every condenser is flat or every dynamic less detailed — and DPA’s claim that dynamics cannot capture the natural sound is a manufacturer judgement (L16, L18, L93).',
  },
  {
    id: 'k.mic.3',
    page: 'microphone',
    prompt: 'A boundary mic may rest on the pillow inside the drum. May you lay any mic on the pillow?',
    options: ['No — only a mic whose own manual allows it, like the Beta 91A', 'Yes, any mic can rest on the pillow', 'Yes, as long as it is a dynamic'],
    correct: 'No — only a mic whose own manual allows it, like the Beta 91A',
    explain: 'The Beta 91A guide allows a pillow or cushioning surface. The Beta 52A guide says “Make sure microphone does not touch drum head or damping inside of the drum.” Do not assume another mic is approved (L11).',
  },
  {
    id: 'k.place.1',
    page: 'placement',
    prompt: 'The Beta 52A guide’s “5 to 7.5 cm” is measured from what?',
    options: ['The beater (batter) head', 'The front (resonant) head', 'The port'],
    correct: 'The beater (batter) head',
    explain: 'The guide says “away from beater head”. A documented distance is only meaningful with its reference head (L39) — the readout names it every time.',
  },
  {
    id: 'k.place.2',
    page: 'placement',
    prompt: 'You move the mic from near the batter head toward the front head. What should you expect?',
    options: ['A tendency toward more of the drum’s resonance — checked on this drum', 'Always more low bass', 'Exactly 6 dB less attack'],
    correct: 'A tendency toward more of the drum’s resonance — checked on this drum',
    explain: 'Shure and Sennheiser document that tendency, and DPA cautions that drums vary. Proximity effect and the surface a directional mic faces also matter, so “every inward move means more bass” is too simple (L40).',
  },
  {
    id: 'k.ctx.1',
    page: 'context',
    prompt: 'Live, what may favour close, directional pickup on the kick?',
    options: ['Stage spill and the available gain before feedback', 'Directional mics are always louder', 'The room always sounds better on stage'],
    correct: 'Stage spill and the available gain before feedback',
    explain: 'That is the lesson’s live column. In the studio, an outside or more distant perspective may help when the room contributes usefully (L55-57).',
  },
  {
    id: 'k.ctx.2',
    page: 'context',
    prompt: 'Where does a supercardioid reject most strongly?',
    options: ['Off the rear axis — about 125° in the ideal model (120° in the Beta 52A guide)', 'Directly behind, at 180°', 'At the sides, at 90°'],
    correct: 'Off the rear axis — about 125° in the ideal model (120° in the Beta 52A guide)',
    explain: 'A supercardioid has a rear pickup lobe; its nulls are toward the rear but off the axis. Shure’s figures differ (120°, 125°, 126°), so the lab draws the ideal model and labels it (L68).',
  },
  {
    id: 'k.two.1',
    page: 'twoMic',
    prompt: 'You flip the polarity of mic B. What happens to the arrival-time difference?',
    options: ['Nothing — polarity flips the sign; the delay stays', 'It becomes zero', 'It doubles'],
    correct: 'Nothing — polarity flips the sign; the delay stays',
    explain: 'Polarity inversion reverses the signal’s sign. It does not remove a delay caused by sound reaching the mics at different times (L72). The notches move; Δt does not.',
  },
  {
    id: 'k.two.2',
    page: 'twoMic',
    prompt: 'Two mics hear the beater 1 ms apart. Summed at equal level, same polarity, where is the first notch (ideal model)?',
    options: ['500 Hz — then 1.5 kHz, 2.5 kHz …', '1 kHz', 'There is no notch'],
    correct: '500 Hz — then 1.5 kHz, 2.5 kHz …',
    explain: 'The first cancellation is where the delay is half a period: f = 1 ÷ (2 × 0.001 s) = 500 Hz, then odd multiples. Inverted, the notches sit at 0, 1 kHz, 2 kHz … instead.',
  },
  {
    id: 'k.two.3',
    page: 'twoMic',
    prompt: 'Does a 3:1 spacing guarantee that an inside/outside pair on one kick is phase-coherent?',
    options: ['No — judge the pair in mono, in both polarity states', 'Yes, always', 'Yes, if both mics are cardioid'],
    correct: 'No — judge the pair in mono, in both polarity states',
    explain: '3:1 can reduce interacting pickup between mics on different sources. An inside/outside pair aims at different surfaces of ONE source, so it is no guarantee (L72).',
  },
  {
    id: 'k.prac.1',
    page: 'practice',
    prompt: 'A loud live show, a ported front head, close directional pickup wanted. Which one-mic starting point is safe and documented?',
    options: ['A kick dynamic inside, 5 to 7.5 cm from the batter head, slightly off the beater line, clear of head, damping and beater', 'Any mic resting on the batter head', 'Any mic laid on the pillow'],
    correct: 'A kick dynamic inside, 5 to 7.5 cm from the batter head, slightly off the beater line, clear of head, damping and beater',
    explain: 'That is the Beta 52A guide’s documented row, with the lesson’s clearance rules. A mic must never touch the head; only a boundary mic made for it may rest on cushioning.',
  },
  {
    id: 'k.prac.2',
    page: 'practice',
    prompt: 'An alternative for a jazz drum with an intact front head?',
    options: ['Outside the front head — DPA documents outside pickup for unported drums', 'Cut a port and go inside', 'Drill through the shell'],
    correct: 'Outside the front head — DPA documents outside pickup for unported drums',
    explain: 'DPA: a jazz kick “often does not have a hole in the resonator head making it necessary to place a mic outside”. Move gradually while checking the head, the kit around it and the gain needed live (L33-34).',
  },
  {
    id: 'k.prac.3',
    page: 'practice',
    prompt: 'What would justify adding a second kick channel?',
    options: ['Each mic is useful alone, the pair adds a complementary perspective, and it checks out in mono in both polarity states', 'Two mics are always better than one', 'It makes the kick louder'],
    correct: 'Each mic is useful alone, the pair adds a complementary perspective, and it checks out in mono in both polarity states',
    explain: 'Shure’s two-mic method blends different perspectives; if the pair loses body or becomes uneven, adjust position and level, or leave the second mic out (L71).',
  },
];

const symptoms: Symptom[] = [
  {
    id: 's.port',
    observation: 'Sharp bursts at the port',
    firstChecks: 'Microphone angle and position relative to escaping air; then physical clearance.',
    src: 'DPA-KICK',
    options: ['The mic’s angle and position relative to the escaping air, then clearance', 'Push the mic farther in to hide it', 'Treat it as an electrical fault and swap the cable'],
    correct: 'The mic’s angle and position relative to the escaping air, then clearance',
    explain: 'DPA: port wind/pop “can be dealt with by simply adjusting the angle of the microphone in the hole.” Never push in farther if it narrows clearance (L41).',
  },
  {
    id: 's.blend',
    observation: 'Weak or inconsistent sound when two channels are combined',
    firstChecks: 'Relative levels, mono blend, both polarity states, positions, and the overhead or other open microphones.',
    options: ['Relative levels, the mono blend, both polarity states, positions and the other open mics', 'Turn both channels up', 'Always invert the inside mic'],
    correct: 'Relative levels, the mono blend, both polarity states, positions and the other open mics',
    explain: 'The pair must be evaluated together, including the overheads and other open mics (L79).',
  },
  {
    id: 's.dist',
    observation: 'Distortion',
    firstChecks: 'Determine whether it starts in the mic, preamp or interface, or at a rattling part of the drum or stand; lower gain where appropriate before changing tonal controls.',
    options: ['Find where it starts — mic, preamp or interface, or a rattling part — and lower gain where appropriate first', 'Pull the channel fader down', 'Cut the low end with EQ'],
    correct: 'Find where it starts — mic, preamp or interface, or a rattling part — and lower gain where appropriate first',
    explain: 'A lowered fader does not undo earlier clipping, and attenuation after an overloaded capsule cannot restore its sound (L13, L81).',
  },
  {
    id: 's.solo',
    observation: 'Attractive solo sound but unclear band sound',
    firstChecks: 'Reevaluate its role against the bass and the rest of the kit at comparable monitoring level.',
    options: ['Re-evaluate its role against the bass and the kit at a comparable monitoring level', 'Solo it again, louder', 'Change to another brand of mic'],
    correct: 'Re-evaluate its role against the bass and the kit at a comparable monitoring level',
    explain: 'Keep comparison levels similar so louder does not win automatically, and judge the kick in the band (L48, L83).',
  },
  {
    id: 's.spill',
    observation: 'Unwanted kit or stage spill',
    firstChecks: 'Reevaluate distance, aiming, actual polar pattern, and whether a second microphone is necessary.',
    options: ['Distance, aim, the actual polar pattern, and whether a second mic is needed', 'Add another mic', 'Turn the monitors up'],
    correct: 'Distance, aim, the actual polar pattern, and whether a second mic is needed',
    explain: 'Aim nulls by the actual pattern, and open only the mics you need — extra channels add spill (L60, L85).',
  },
  {
    id: 's.contact',
    observation: 'Movement or contact risk',
    firstChecks: 'Stop the drummer, remount and reroute; do not continue the exercise until clearance is restored.',
    options: ['Stop the drummer, remount and reroute; continue only once clearance is restored', 'Carry on carefully and fix it later', 'Tape the cable to the pedal'],
    correct: 'Stop the drummer, remount and reroute; continue only once clearance is restored',
    explain: 'Clearance always comes first: have the drummer stop before any mic moves (L11, L87).',
  },
];

export const M01_LESSON: Lesson = {
  id: 'M01',
  labId: 'drums',
  title: 'Kick Drum',
  subtitle: 'Bass drum: inside, outside, one mic or two',
  model: KICK_MODEL,
  micTypeIds: ['kickDynSuper', 'kickDynCard', 'boundaryHalf', 'sdc'],
  zones: KICK_ZONES,
  pages,
  scenarios,
  symptoms,
  practice: {
    task: 'Choose a one-mic setup for a given drum and performance, describe an alternative position, and explain what would justify a second channel (L89). With a real drum and the drummer’s agreement, you can record what you tried below.',
    fields: [
      { id: 'drum', label: 'Drum (size, heads, damping)', kind: 'text' },
      { id: 'head', label: 'Front head', kind: 'choice', choices: ['intact', 'ported'] },
      { id: 'mic', label: 'Mic type', kind: 'choice', choices: ['kick dynamic, supercardioid', 'kick dynamic, cardioid', 'boundary on cushioning', 'condenser', 'other'] },
      { id: 'pattern', label: 'Pattern (from its own spec)', kind: 'text' },
      { id: 'zone', label: 'Starting position and its source', kind: 'text' },
      { id: 'distance', label: 'Distance, from which head', kind: 'text' },
      { id: 'aim', label: 'Aim', kind: 'text' },
      { id: 'notes', label: 'What you heard (tendencies, in words)', kind: 'text' },
    ],
  },
  sources: [
    { key: 'DPA-KICK', label: '[1] DPA Microphones, Bo Brinck, “How to mic a kick (bass) drum”', url: 'https://www.dpamicrophones.com/mic-university/how-to-mic/how-to-mic-a-kick-drum/', checked: '2026-10-04' },
    { key: 'S-B52-UG', label: '[2] Shure, BETA52A User Guide, version 3.1 (2023-I)', url: 'https://pubs.shure.com/view/guide/BETA52A/en-US.pdf', checked: '2026-10-04' },
    { key: 'SN-902-2019', label: '[3] Sennheiser, e 902 Instruction Manual (01/2019) — the lesson’s link is dead; archived copy', url: 'https://web.archive.org/web/20240530010343/https://www.sennheiser.com/globalassets/digizuite/40681-en-e902_manual_01_2019_en.pdf', checked: '2026-10-04', note: 'The current online manual (v1.3, 04/2026) keeps Positions A/B/C but drops the “turn away from where the beater strikes” sentence.' },
    { key: 'SN-902-DOC', label: '[3, current] Sennheiser e 902 online manual, Operation (v1.3, 04/2026)', url: 'https://docs.cloud.sennheiser.com/en-us/evolution-wired/manual-e902-using.html', checked: '2026-10-04' },
    { key: 'S-B91-UG', label: '[4] Shure, BETA91A User Guide, version 3.1 (2021-B)', url: 'https://pubs.shure.com/view/guide/BETA91A/en-US.pdf', checked: '2026-10-04' },
    { key: 'S-2MIC', label: '[5] Shure, “How to Get a Great Kick Drum Sound Using Two Shure Mics” (June 25, 2026)', url: 'https://www.shure.com/en-US/insights/how-to-get-a-great-kick-drum-sound-using-two-shure-mics', checked: '2026-10-04' },
    { key: 'DPA-PPD', label: '[6] DPA Microphones, “Polarity, phase and delay”', url: 'https://www.dpamicrophones.com/mic-university/technology/polarity-phase-and-delay/', checked: '2026-10-04 (link resolves)' },
    { key: 'AKG-CUT', label: '[7] AKG, D112 MkII cutsheet (the product page could not be reached from here)', url: 'https://www.akg.com/D112MkII.html', checked: '2026-10-04 (cutsheet read)' },
    { key: 'NIOSH', label: '[8] CDC NIOSH, “Understand Noise Exposure” (Jan. 31, 2024)', url: 'https://www.cdc.gov/niosh/noise/prevent/understand.html', checked: '2026-10-04' },
    { key: 'YMH-ZG01', label: '[9] Yamaha ZG01 manual, phantom-power precautions (an equipment-specific example)', url: 'https://manual.yamaha.com/pa/interfaces/zg01/en-US/7884896267.html', checked: '2026-10-04' },
    { key: 'S-REC1', label: '[10] Shure, “Recording Drums Part 1” (November 6, 2022)', url: 'https://www.shure.com/en-US/insights/recording-drums-part-1-setting-up-and-microphone-technique', checked: '2026-10-04' },
    { key: 'S-LIVE', label: '[11] Shure, Microphone Techniques for Live Sound Reinforcement', url: 'https://www.shure.com/damfiles/default/global/documents/publications/en/performance-production/microphone_techniques_for_live_sound_reinforcement_english.pdf-3df433145fca686a736beeb5da588efa.pdf', checked: '2026-10-04' },
    { key: 'DPA-31', label: '[12a] DPA Microphones, “3:1 rule”', url: 'https://www.dpamicrophones.com/dictionary/0-9/31-rule/', checked: '2026-10-04 (link resolves)' },
    { key: 'S-REC5', label: '[12b] Shure, “Recording Drums Part 5 — Phase Cancellation”', url: 'https://www.shure.com/en-GB/insights/recording-drums-part-5-phase-cancellation', checked: '2026-10-04 (link resolves)' },
    { key: 'DRUM', label: 'Drum size and hardware: Yamaha Recording Custom (RBB-2218), TAMA Superstar Classic, DW Design; Remo 5 in offset-port head; DW pedal manuals', checked: '2026-10-04', note: 'Full rows in docs/labs/miking/kick/SOURCES.md.' },
    { key: 'PHYSICS', label: 'Speed of sound (the app’s calculator), comb filtering and first-order polar patterns', checked: '2026-10-04', note: 'Rows in docs/labs/miking/SOURCES_SHARED.md.' },
  ],
  audit: {
    agreement: 'Where they address it, the manufacturer guides support experimenting with position and associate beater-side placement with more attack; the combined-channel sources agree that two mics must be judged together; and the manuals make mounting and orientation part of the outcome.',
    tension: 'DPA says the level just outside a port is sometimes greater than inside, while the Beta 52A guide calls its near-batter row the highest-SPL position of its own choices. Neither supports a rule for every drum. DPA’s claim that dynamics cannot capture the natural sound is a manufacturer judgement without a controlled comparison here — the lesson teaches measured capabilities and listening goals instead.',
    gaps: 'No source gives a universally best position, a predictable response for every mic-and-drum pair, a fixed mix balance, or a hearing-safety limit from a mic rating. Outcomes depend on the drum, the player, the room, the PA and the mics. The lesson asks a drummer and a qualified practitioner to review setups before publishing; the owner reviews this lab on a phone.',
  },
  unknowns: [
    'The real shell outside diameter of a “22 in” drum, the hoop height (hHoop), the hoop-to-shell gap (cHoop) and how far the hoop stands past the head (hoopInset) — drawn with placeholders.',
    'The floor line (yFloor): whether both hoops touch the floor and how much the spurs lift the drum — so no HEIGHT readout is shown.',
    'The spurs’ position along the shell (spurX), angle and length — drawn illustratively.',
    'Where an offset port sits (portY, portZ: radius and clock angle) — drawn illustratively; never a readout reference.',
    'The pedal: shaft length and axle (beaterLen), beater head size (beaterHeadR), swing (beaterSwingDeg), footboard — drawn as an ILLUSTRATIVE envelope.',
    'The pillow’s size and shape (pillowLen, pillowH, pillowHalfW) — it sets the boundary mic’s height.',
    'The tension-rod phase (rodPhaseDeg): is a rod at bottom centre? And is “10 tuning bolts” per head?',
    'Where each mic’s distances are measured from, and its acoustic centre — the lab measures to the mic’s front and rounds to ≈ 5 mm.',
    'Head excursion and every keep-out clearance — ILLUSTRATIVE values for the owner to approve.',
  ],
  corrections: [
    { id: 'K-01', text: 'The Beta 52A 20–30 cm row now includes the guide’s “on-axis with beater”.' },
    { id: 'K-02', text: 'The e 902 row reads “at the level of the resonant head” — the manual never mentions a port.' },
    { id: 'K-03', text: '“Turn the e 902 away from the beater strike” is kept as an aiming experiment, not attributed to Sennheiser’s current manual (it is only in the 2019 PDF).' },
    { id: 'K-04', text: 'The e 902 manual link was dead; the archived 2019 copy and the current manual are listed.' },
    { id: 'K-05', text: 'AKG facts come from the D112 MkII cutsheet; the product page could not be reached from here.' },
    { id: 'K-06', text: 'The Beta 52A pattern reads “supercardioid” (Shure’s spec field); “modified supercardioid” is Shure’s description.' },
    { id: 'K-07', text: 'Supercardioid rejection: ≈ 125° in the ideal model; 120° wherever the Beta 52A guide is cited.' },
    { id: 'K-08', text: 'The Beta 91A pattern is stated: half-cardioid, sources within 60° above the surface. No lobe is drawn for it.' },
    { id: 'K-09', text: 'The near row is the guide’s “5 to 7.5 cm … slightly off-center”; the guide never says “inside” — the drawing shows where that is.' },
    { id: 'K-10', text: 'Units are dual everywhere, the source’s own unit first.' },
  ],
  live: { wedges: [{ id: 'wedge', label: 'monitor wedge', p: { x: 0, y: 0, z: 0 }, az: 0 }] },
  accuracyDetail:
    'This lab is SILENT, and it DRAWS a model: a 22 × 18 in kick built from manufacturer dimensions, with the unknown parts (floor, port position, pedal, pillow, hoop details) drawn ILLUSTRATIVE. The placement zones are manufacturers’ documented starting points for particular products, measured from the head each one names; clearances, the boom and the pedal envelope are ILLUSTRATIVE. Distances are rounded to ≈ 5 mm and measured to the mic’s front, not its acoustic centre. Patterns and the two-mic comb are IDEAL models, not measurements of any drum. Learn the reasoning here; place real mics with the drummer stopped, and trust the drum, your ears and a calibrated measurement.',
};
