/**
 * MicCutaway — the animated dynamic-microphone capsule cutaway (Computer B's
 * asset, APE deep-review + fixes 2026-08-22; review docs in docs/art/mic-cutaway).
 *
 * WHY react-native-svg, not Skia: this is a pure react-native-svg + Reanimated
 * asset, and react-native-svg is already in every build — so unlike the rest of
 * this lab (which gates on Skia) the cutaway renders on EVERY client, including
 * pre-Skia ones. No new native build was needed to add it.
 *
 * HOW it animates without per-frame SVG work: the artwork is emitted as
 * parse-once SvgXml layers (micCutawayAsset.ts, generated by the patch script).
 * A single Reanimated phase clock drives GROUP-LEVEL opacity/transform on the
 * three signal overlays — the heavy static art is parsed exactly once and never
 * touched again. This is deliberately the shape the review asked for after the
 * dev-client CPU-runaway watchdog scare: one UI-thread clock, cheap animated
 * props, and every clock cancelled on blur (see the running gate below).
 *
 * The teaching beat (e = B·l·v): sound arrives (waves march in) → the coil in
 * the gap generates → current RISES and FALLS with the coil's velocity (the
 * amber overlay pulses) and REVERSES each half-cycle (the ⊗/⊙ markers flip as
 * the +/- current layers crossfade). The glow peaks with velocity. All of it is
 * badged ILLUSTRATIVE — travel is exaggerated ~1,000× and the on-art caveat
 * spells out the mass-controlled-cardioid honesty note.
 */
import { useEffect } from 'react';
import { StyleSheet, View } from 'react-native';
import { SvgXml } from 'react-native-svg';
import Animated, {
  cancelAnimation,
  Easing,
  useAnimatedStyle,
  useSharedValue,
  withRepeat,
  withTiming,
} from 'react-native-reanimated';
import {
  MIC_ASPECT,
  MIC_BASE_XML,
  MIC_CURRENT_NEG_XML,
  MIC_CURRENT_POS_XML,
  MIC_GLOW_XML,
  MIC_WAVE_XML,
} from './micCutawayAsset';

const PERIOD_MS = 1400; // one full electrical cycle
const WAVE_MS = 1100; // wavefront march (independent, inbound)
// Wavefronts repeat every 34 units; the lab crop's viewBox is 300 units wide
// (see MIC_VIEWBOX). Marching by exactly one period loops seamlessly. Expressed
// as a fraction of the drawn width so it scales with the card.
const WAVE_STEP_FRAC = 34 / 300;

export function MicCutaway({ width, running = true }: { width: number; running?: boolean }) {
  const height = Math.round(width / MIC_ASPECT);
  // phase 0→1 = one cycle; sin(2π·phase) is the coil velocity / EMF.
  const phase = useSharedValue(0.25); // rest at velocity peak (a meaningful still)
  const march = useSharedValue(0);

  useEffect(() => {
    if (!running) {
      cancelAnimation(phase);
      cancelAnimation(march);
      phase.value = 0.25;
      march.value = 0;
      return;
    }
    phase.value = withRepeat(withTiming(1.25, { duration: PERIOD_MS, easing: Easing.linear }), -1, false);
    march.value = withRepeat(withTiming(1, { duration: WAVE_MS, easing: Easing.linear }), -1, false);
    return () => {
      cancelAnimation(phase);
      cancelAnimation(march);
    };
  }, [running, phase, march]);

  // sin of the phase, on the UI thread, shared by the signal overlays.
  const posStyle = useAnimatedStyle(() => {
    'worklet';
    const s = Math.sin(2 * Math.PI * phase.value);
    return { opacity: Math.max(0, s) };
  });
  const negStyle = useAnimatedStyle(() => {
    'worklet';
    const s = Math.sin(2 * Math.PI * phase.value);
    return { opacity: Math.max(0, -s) };
  });
  const glowStyle = useAnimatedStyle(() => {
    'worklet';
    const s = Math.sin(2 * Math.PI * phase.value);
    return { opacity: 0.25 + 0.75 * Math.abs(s) };
  });
  const waveStyle = useAnimatedStyle(() => {
    'worklet';
    return { transform: [{ translateX: -march.value * WAVE_STEP_FRAC * width }] };
  });

  const layer = (xml: string) => (
    <SvgXml xml={xml} width={width} height={height} />
  );

  return (
    <View style={[styles.box, { width, height }]}>
      {/* static art (parsed once): motor, housing, magnet, pole, coil at rest,
          humbucking, terminals, flux, labels, honesty caveat */}
      {layer(MIC_BASE_XML)}
      {/* inbound sound field (marches toward the diaphragm) */}
      <Animated.View style={[StyleSheet.absoluteFill, waveStyle]} pointerEvents="none">
        {layer(MIC_WAVE_XML)}
      </Animated.View>
      {/* induced current — the two half-cycles crossfade so ⊗/⊙ flip (AC) */}
      <Animated.View style={[StyleSheet.absoluteFill, posStyle]} pointerEvents="none">
        {layer(MIC_CURRENT_POS_XML)}
      </Animated.View>
      <Animated.View style={[StyleSheet.absoluteFill, negStyle]} pointerEvents="none">
        {layer(MIC_CURRENT_NEG_XML)}
      </Animated.View>
      {/* "generating" halo at the coil, brightest at the velocity peak */}
      <Animated.View style={[StyleSheet.absoluteFill, glowStyle]} pointerEvents="none">
        {layer(MIC_GLOW_XML)}
      </Animated.View>
    </View>
  );
}

const styles = StyleSheet.create({
  box: { position: 'relative', alignSelf: 'center' },
});
