/**
 * Audio Career Finder — the bundled Grand Audio Career Index (owner workbook
 * v2, 2026-09-04): 1,902 titles across the 42 families, generated by
 * scripts/build-career-index.py. Enum-coded on disk; decoded lazily here.
 *
 * Presentation rule (design chat 2026-09-03): every title carries how central
 * audio is to it — audio-core, audio-specialized or audio-enabled — so the
 * breadth of the index never reads as inflation.
 *
 * Imports JSON, so it is NOT reachable from the node:test suite; the pure
 * scoring modules never import it.
 */
import raw from '../../data/careerIndex.json';
import meta from '../../data/careerFamilies.json';
import { FAMILIES, familyById, type CareerFamily } from './families';

type RawCareer = { id: string; f: number; t: string; alt?: string[]; cls: number; st: number; rel: number; tier: number; ori: number; wm: number; prep: number; reg?: 1 };
type RawIndex = { version: string; families: string[]; enums: Record<'tier' | 'relationship' | 'orientation' | 'titleClass' | 'status' | 'workModel' | 'preparation', string[]>; careers: RawCareer[] };
type RawFamilyMeta = { id: string; name: string; field: string; subject: string; topicGs: number[]; settings: string[]; sources: string[]; count: number };

const index = raw as RawIndex;
const familyMeta = meta as RawFamilyMeta[];

/** How central audio is to the role — from the workbook’s inclusion tier. */
export type AudioCentrality = 'core' | 'specialized' | 'enabled';
export const CENTRALITY: Record<AudioCentrality, { label: string; explain: string }> = {
  core: { label: 'Audio-core', explain: 'Audio is the principal work product.' },
  specialized: { label: 'Audio-specialized', explain: 'A broader profession with a recognized audio specialization.' },
  enabled: { label: 'Audio-enabled', explain: 'Audio knowledge is a meaningful paid skill within the role.' },
};
const CENTRALITY_BY_TIER: AudioCentrality[] = ['core', 'specialized', 'enabled'];

export type Career = {
  id: string;
  title: string;
  alternates: string[];
  familyId: string;
  centrality: AudioCentrality;
  relationship: string;
  orientation: string;
  titleClass: string;
  status: string;
  workModel: string;
  preparation: string;
  /** Licence, credential, union or safety requirements may apply — verify locally. */
  regulated: boolean;
};

export type FamilyMeta = {
  field: string;
  subject: string;
  topicGs: number[];
  settings: string[];
  sources: string[];
  count: number;
};

export const CAREER_INDEX_VERSION = index.version;
export const CAREER_COUNT = index.careers.length;

let decoded: Career[] | null = null;
function all(): Career[] {
  if (decoded) return decoded;
  const e = index.enums;
  const idOfName = new Map(FAMILIES.map((f) => [f.name, f.id] as const));
  decoded = index.careers.map((c) => ({
    id: c.id,
    title: c.t,
    alternates: c.alt ?? [],
    familyId: idOfName.get(index.families[c.f]) ?? '',
    centrality: CENTRALITY_BY_TIER[c.tier] ?? 'enabled',
    relationship: e.relationship[c.rel],
    orientation: e.orientation[c.ori],
    titleClass: e.titleClass[c.cls],
    status: e.status[c.st],
    workModel: e.workModel[c.wm],
    preparation: e.preparation[c.prep],
    regulated: c.reg === 1,
  }));
  return decoded;
}

/** Titles in one family, in the workbook’s order (established roles first). */
export function careersInFamily(familyId: string): Career[] {
  return all().filter((c) => c.familyId === familyId);
}

export function familyMetaOf(familyId: string): FamilyMeta | undefined {
  const m = familyMeta.find((f) => f.id === familyId);
  return m ? { field: m.field, subject: m.subject, topicGs: m.topicGs, settings: m.settings, sources: m.sources, count: m.count } : undefined;
}

export const familyFieldOf = (familyId: string): string | undefined => familyMetaOf(familyId)?.field;

/** Family + its metadata in one object for screens. */
export type FamilyView = CareerFamily & FamilyMeta;
export function familyView(id: string): FamilyView | undefined {
  const f = familyById(id);
  const m = familyMetaOf(id);
  return f && m ? { ...f, ...m } : undefined;
}

/** Centrality split for a family’s titles: how many are audio-core, etc. */
export function centralitySplit(familyId: string): Record<AudioCentrality, number> {
  const out: Record<AudioCentrality, number> = { core: 0, specialized: 0, enabled: 0 };
  for (const c of careersInFamily(familyId)) out[c.centrality]++;
  return out;
}

/** Case-insensitive title / alternate-title search across the whole index. */
export function searchCareers(query: string, limit = 40): Career[] {
  const q = query.trim().toLowerCase();
  if (q.length < 2) return [];
  const hits: Career[] = [];
  for (const c of all()) {
    if (c.title.toLowerCase().includes(q) || c.alternates.some((a) => a.toLowerCase().includes(q))) {
      hits.push(c);
      if (hits.length >= limit) break;
    }
  }
  return hits;
}
