/**
 * M08 HEADED TAMBOURINE — the pages' words (engine/model/copy.ts). The
 * starting-points voice (owner ruling 2026-10-04): no source, brand or model
 * names, no badges; tendencies, never results.
 */
import type { LessonCopy } from '../../engine/model/copy.ts';
import { R } from './model.ts';

export const TAMB_COPY: LessonCopy = {
  variantKey: 'PLAYED',
  variantShort: { held: 'held and struck', shaken: 'shaken', mounted: 'on a mount' },
  sceneSubject: { held: 'a 10 in headed tambourine held at about 45° and struck', shaken: 'a 10 in headed tambourine held at about 45° and shaken', mounted: 'a 10 in headed tambourine flat on a mount, struck with sticks' },
  viewTag: { side: 'SIDE · EDGE-ON', top: 'TOP' },
  axes: {
    x: { plus: 'toward the mic side', minus: 'toward the player', label: 'FRONT–BACK', blurb: 'Toward the audience and the mic, or toward the player (x).' },
    y: { plus: 'lower', minus: 'higher', label: 'HEIGHT', blurb: 'Up or down (y). Distances are read from the tambourine, the head or the rim the zone names.' },
    z: { plus: 'to player’s right', minus: 'to player’s left', label: 'ACROSS', blurb: 'Toward the player’s left or right (z) — the way a shake swings.' },
    origin: { held: { x: 0, y: -1150, z: 0 }, shaken: { x: 0, y: -1150, z: 0 }, mounted: { x: 0, y: -900, z: 0 } },
  },
  instrument: {
    figureBadge: 'A 10 in headed tambourine, edge-on, held at about 45°',
    figureLabel: 'Side view of a 10 inch headed tambourine seen edge-on, held at about 45 degrees with its head facing up and toward the mic: the wooden frame, the skin head on its front face, and two staggered rows of jingle pairs in slots round the frame.',
    partsBadge: 'A 10 in headed tambourine · tap a part to name it',
    partsLooking: { side: 'Side view · the tambourine edge-on', top: 'Top view · the head from above' },
    partsIdle: 'A skin head on a wooden frame, with pairs of metal jingles round it — a drum and a set of jingles in one instrument. The next page shows how each part sounds.',
    variantNotes: {
      shaken: 'SHAKEN: the same hold, swung side to side or rolled by thumb or finger. The jingles lead — and the frame moves, so its distance to a fixed mic changes.',
      mounted: 'MOUNTED: flat on a compatible mount, struck with sticks. The instrument stays put — but the mount can add noises of its own, and only a mount made for it is used.',
    },
  },
  sound: {
    strikes: [
      { id: 'c', label: 'CENTRE', mm: 0, blurb: 'The exact centre of the head.' },
      { id: 'half', label: 'HALFWAY OUT', mm: R * 0.5, blurb: 'Halfway from the centre to the frame — explore what it drives.' },
      { id: 'edge', label: 'NEAR THE FRAME', mm: R * 0.85, blurb: 'Close to the frame — explore what it drives.' },
    ],
    strikeDefault: 'half',
    striker: 'HAND',
    strikerPhrase: 'the hand',
    subject: 'The tambourine edge-on, level, head on top',
    looking: { held: 'The tambourine edge-on, level · struck', shaken: 'The tambourine edge-on, level · shaken', mounted: 'The tambourine edge-on, level · on its mount' },
    cells: [
      { k: 'HEAD', at: ['AT REST', 'PUSHED IN', 'RINGING', 'RINGING'], byVariant: { shaken: ['AT REST', 'BARELY', 'BARELY', 'BARELY'] }, flex: 1.1 },
      { k: 'JINGLES', at: ['AT REST', 'AT REST', 'CLASH', 'RINGING'], flex: 1.1 },
      { k: 'SOUND', at: ['—', '—', '—', 'ALL ROUND'], flex: 1.1 },
    ],
    reveal: 'Struck, the head is pushed in and the frame jolts; the loose jingle pairs are thrown against each other. Two sounds start at once: the head’s body and the jingles’ bright clash.',
    after: 'Then the head rings briefly and the jingles keep shimmering for a moment. Head material, jingle metal, the rows and the player’s technique all change the balance between them.',
    shapesNotes: [
      'A shape is set moving only as much as the head moves at the strike point in that shape. At the exact centre, every shape with a still line across the head stands still — so a centre strike drives only the ring-shaped ones.',
      'This is a simplified head on a closed rim. A real tambourine’s back is open and its frame is held in a hand, so these numbers shift — the next step shows the head and the jingles together.',
    ],
    coupledSubject: 'The tambourine edge-on',
    coupledNote: 'One instrument, two sources: the head (a drum) and the jingles (metal). Striking favours the head; shaking favours the jingles — a mic hears whatever it is closer to and faces.',
    silentNote: 'This lab never plays a sound and draws no frequency curve: how a real tambourine sounds depends on its head, its jingles, how it is held and the player. The pictures show where the sound comes from and where it leaves.',
    pair: {
      title: 'Head and jingles',
      badge: 'A simplified picture: where each sound starts, not how loud · motion drawn larger',
      looking: 'The tambourine edge-on',
      prompt: 'Drag SWING, then switch MOTION. Watch the head and the jingles.',
      key: 'MOTION',
      rest: 'passing through rest',
      cells: ['MOTION', 'MOVES', 'JINGLES'],
      together: {
        option: 'HEAD STRUCK',
        blurb: 'The hand pushes the head: it rings in its shapes, and the jolt jostles the jingles.',
        short: 'STRUCK',
        title: 'HEAD STRUCK',
        card: 'The hand pushes the head in and it rings — the low and mid BODY of the sound, from both faces of the head, because the back is open. The jolt also jostles the jingles, so a stroke always has some jingle in it.',
        v0: 'STRUCK',
        sub0: 'the head',
        v1: 'THE HEAD',
        air: { plus: 'JOSTLED', minus: 'JOSTLED', rest: 'AT REST' },
      },
      opposed: {
        option: 'FRAME SHAKEN',
        blurb: 'The hand moves the whole frame; the loose jingles lag behind, then clash. The head barely moves.',
        short: 'SHAKEN',
        title: 'FRAME SHAKEN',
        card: 'The whole frame moves; the loose jingles lag behind it, then clash against each other and their pins — the bright, metallic part of the sound. The head hardly moves. And because the frame moves, its distance to a fixed mic changes with every shake.',
        v0: 'SHAKEN',
        sub0: 'the frame',
        v1: 'THE FRAME',
        air: { plus: 'LAG, CLASH', minus: 'LAG, CLASH', rest: 'AT REST' },
      },
    },
  },
  setting: {
    kitA11y: 'The percussion section from above, at the back of an orchestra: the tambourine held by its player at the end of the row, beside the trap table and a suspended cymbal; the concert snare, the bass drum and the timpani along the row; a row of brass in front.',
    kitLanding: 'Tap anything around the tambourine — or step through ITEM — to see what it means for a tambourine mic. There is nothing to answer yet.',
    kitIdle: 'The tambourine player stands in the percussion row, often moving between instruments at the trap table. Around them: bright neighbours, and the brass in front.',
    leftHanded: 'Players hold and strike with either hand, and move between stations — check the real passage, and where the player stands for each part of it.',
    stageA11y: 'The orchestra on an amplified stage, from above: the percussion at the back, the conductor and the audience at the front, PA stacks at the front corners, and two floor monitors near the percussion.',
    studioA11y: 'The orchestra recorded in a hall, from above: the main pair of microphones over the conductor, the hall’s walls around the stage, no monitors.',
    stageIdle: 'Two floor monitors: one downstage of the percussion, facing back toward it, and the section’s own monitor behind the players. The PA faces the audience.',
    studioIdle: 'No monitors. The main pair over the conductor hears the whole orchestra — the tambourine included — and the hall is part of the sound.',
    before: [
      { title: 'ASK FOR THE WHOLE PHRASE', text: 'Fingertip strikes, loud accents, shakes, thumb or finger rolls, any knee or fist strokes, a mount, and the moves between stations. Is it a headed tambourine at all? The head changes the balance a lot.' },
      { title: 'WORK WITH THE PLAYER’S MOTION', text: 'Place the mic for the motion the player uses — never ask for a different grip, roll or stroke to suit a mic. A sideways shake can keep the level steadier, but it is the player’s choice.' },
      { title: 'HANDS OFF THE INSTRUMENT', text: 'Nothing is clipped to the frame unless the hardware is made for it and the owner agrees. Loose jingles or a damaged frame go back to the player — never fix them yourself.' },
    ],
    plan: {
      title: 'In the orchestra',
      badge: 'The percussion from above · a typical concert layout · grey hatch = the players’ space',
      looking: 'Plan · the percussion row, the audience toward the bottom',
      stageBadge: 'From above · an amplified orchestra · two monitors where a stage often puts them',
      studioBadge: 'From above · an orchestra recorded in a hall',
      stageLooking: 'Plan · the orchestra on an amplified stage',
      studioLooking: 'Plan · the orchestra in a recording hall',
      widePrompt: 'Switch STAGE / STUDIO, and tap what is new around the orchestra.',
    },
  },
  placement: {
    workedZone: { held: 'tb.front.held', shaken: 'tb.front.shaken', mounted: 'tb.above.mounted' },
    workedLine: 'This starting point is also read against {line}: the readout says how far the mic is from it.',
    workedAim: 'Face the tambourine — the starting point counts while the mic faces it within {tol}°. Distance, height and angle are separate things to try.',
    workedClear: 'Clear of the whole motion — the striking hand, the shake’s swing, the sticks, the frame and its jingles. Clearance comes first: 15–30 cm is a starting distance, not a safety clearance, and the player stops before a real mic moves.',
    blocked: {},
    reveal: 'Aimed at the head tends to bring more body; at the rim and jingles, more bright attack; a little farther, a blend with more room — and instruments and players vary, so “it depends” is fair too. Each zone’s LISTEN FOR line is an idea to check by ear.',
    typeNotes: { orchDyn: 'If the jingles sound too cutting through a condenser, a dynamic (or a ribbon, kept well out of the swing) can give a gentler balance — compare by ear.' },
    note: 'Clearance comes first: stop the player before moving a real mic. Watch PEAK meters, not slow average meters — a tambourine’s brief peaks overload an input that a slow meter says is fine.',
    availableLead: 'Starting points for this mic and way of playing',
    learn: {
      intro: 'What you just did, in words. After our research, one mic about 15–30 cm (6–12 in) from the tambourine is where we recommend you begin. From there, aim at the head for more body or at the rim for more jingle. Starting points, not rules: move and listen — there is no single right answer.',
      separate: 'Height, distance and angle are separate variables: change one at a time, with the same passage. A held tambourine moves toward and away from a fixed mic: find a spot that covers the whole motion.',
      clearance: 'Clearance comes first. Have the player show the whole arm, wrist, hand and stick motion, and the shake, before anything is placed. The grey hatched areas show roughly where to keep clear — leave more room for a real player.',
      tendencies: 'Closer usually raises the tambourine against its neighbours but lets one jingle or one impact jump out; a little farther blends head, rim and room. If it is too bright, try distance and angle first. All tendencies to check by ear.',
    },
  },
  context: {
    variant: 'held',
    zone: 'tb.front.held',
    typeId: 'orchSdc',
    patterns: [
      { id: 'cardioid', label: 'cardioid', typeId: 'orchSdc' },
      { id: 'supercardioid', label: 'supercardioid', typeId: 'orchSdc' },
      { id: 'hypercardioid', label: 'hypercardioid', typeId: 'orchSdc' },
    ],
    micNoun: 'A small condenser',
    shield: ['tb.head', 'tb.frame'],
    azMax: 45,
    elMax: 45,
    aimBlurb: 'Swing the front up to 45° either way — it still faces the tambourine.',
    plan: { u0: -1300, u1: 1650, v0: -900, v1: 900 },
    side: { u0: -1300, u1: 1650, v0: -1650, v1: 60 },
    target: 'downstage',
    frontIds: ['fill'],
    targetWord: 'monitor',
    looking: 'Top view · the mic in front of the tambourine',
    prompt: 'The monitor stays where the stage needs it. Turn the MIC (AIM) or change its PATTERN until the downstage wedge sits in the rejection.',
    activityDone: 'done — the downstage wedge sat in a null by your aim or pattern',
    deepNull: 'On this simplified pattern a null looks infinitely deep. Real microphones reject far less there. Use the null to aim, not to promise silence.',
    cardioidReveal: 'What you just saw: a cardioid rejects most directly behind (180°). The wedge sits behind the mic and off to one side: tilt the mic and its back can face it.',
    shieldNote: 'Real patterns change with pitch and the stage reflects sound — this is the reasoning, not a prediction. A wider pattern covers a moving player better but hears more of the stage.',
    studioId: 'tb.ctx.studio',
    studioPrompt: 'A recording in a hall has no wedge to reject. The decision changes: does the tambourine need its own mic?',
    studioNote: 'In a recording, the ensemble mics often carry the tambourine already; a spot is added only for missing rhythmic definition or head body. Switch back to LIVE for the monitor exercise.',
    learn: {
      intro: 'These are scenario-based comparisons, not rules: one spot may suit a solo; a shared mic over the percussion may suit a busy show.',
      points: [
        { title: 'HOW MANY MICS', text: 'Solo or overdub: one mic in the 15–30 cm range, outside every motion. In an ensemble: listen to the existing mics first. Live: one directional mic can serve a whole percussion station — shakers and tambourine together — with wider mics over the section.' },
        { title: 'A MOVING PLAYER', text: 'A fixed mic covers a fixed station. If the player walks or dances, work with them and the operator on where they play — never require them to stop moving for one spot.' },
        { title: 'BRIGHTNESS', text: 'Studio: angle and distance first, then the mic’s own balance. Live: no universal filter, limiter or EQ notch — the head carries useful low and mid, the jingles sharp highs.' },
        { title: 'PEAKS', text: 'Set gain from the loudest shake or accent AND the quietest roll, with a peak meter. A slow average meter hides the peaks that overload an input.' },
      ],
      body: 'On an amplified stage the monitors stay where the players need them: turn the mic or choose its pattern so that a null faces a loud unwanted source. A wider pattern covers movement but hears more of the stage.',
      warn: 'No mic position alone prevents feedback: the monitors and PA, channel gain and EQ, the room and the open mics all matter. Work it out with the system operator, and never create feedback deliberately.',
    },
  },
  twoMic: {
    variant: 'held',
    A: { typeId: 'orchSdc', pattern: 'cardioid', zone: 'tb.front.held' },
    B: { typeId: 'orchSdc', pattern: 'cardioid', zone: 'tb.edge.held' },
    learn: [
      'A common situation: the tambourine spot, and another mic that hears it too — a percussion overhead, the ensemble pair, or a second angle on the rim. Each hears it at a different time. If the best single mic already conveys the part, a second close mic is usually unnecessary.',
      'Compare the mics together at the intended levels in MONO. If the body or the attack changes unnaturally, move, re-aim or rebalance first; try polarity as a diagnostic, not an automatic switch. Live, every extra open mic adds spill and feedback risk.',
    ],
    warn: 'This simplified graph shows one point source and straight paths — a real tambourine moves while it is played, so the delay between two mics changes with every shake. Read the notch depths as illustrative only.',
  },
  practice: {
    gain: 'tb.prac.gain',
    second: 'tb.prac.3',
    mixed: ['tb.mix.1', 'tb.mix.2', 'tb.mix.3'],
    mixedIntro: 'Three cards from earlier pages, mixed: a reference point, a pattern’s null, and the delay between two mics.',
  },
};
