-- Glossary media URL standardization — REVIEW BEFORE RUN
-- Step A: backup
create table if not exists glossary_media_backup_20260716 as select * from glossary_media;

-- Step B: rewrite urls (term-keyed; each row gets its own slug)
with m(term,newurl) as (values
  ('3.5mm Connector', 'glossary-images/3-5mm-connector.webp'),
  ('5-Pin DIN (MIDI)', 'glossary-images/5-pin-din.webp'),
  ('AC Power', 'glossary-images/ac-power.webp'),
  ('AED', 'glossary-images/aed.webp'),
  ('Arcing', 'glossary-images/arcing.webp'),
  ('Audio Interface', 'glossary-images/audio-interface.webp'),
  ('Banana Plug', 'glossary-images/banana-plug.webp'),
  ('Barricade', 'glossary-images/barricade.webp'),
  ('Binaural Mic', 'glossary-images/binaural-mic.webp'),
  ('BNC Connector (Bayonet Neill-Concelman)', 'glossary-images/bnc-connector.webp'),
  ('Boundary Microphone (PZM)', 'glossary-images/boundary-microphone.webp'),
  ('Cable Ramp', 'glossary-images/cable-ramp.webp'),
  ('Cable Tie', 'glossary-images/cable-tie.webp'),
  ('Camlock', 'glossary-images/camlock.webp'),
  ('Carbon Microphone', 'glossary-images/carbon-microphone.webp'),
  ('Circuit Breaker', 'glossary-images/circuit-breaker.webp'),
  ('Coaxial Cable', 'glossary-images/coaxial-cable.webp'),
  ('Coaxial Driver', 'glossary-images/coaxial-driver.webp'),
  ('Condenser Microphone', 'glossary-images/condenser-microphone.webp'),
  ('constant directivity (CD) horn', 'glossary-images/constant-directivity-horn.webp'),
  ('Contact Microphone', 'glossary-images/contact-microphone.webp'),
  ('Crimping Tool', 'glossary-images/crimping-tool.webp'),
  ('Damaged Power Cord', 'glossary-images/damaged-power-cord.webp'),
  ('DB25 (D-sub)', 'glossary-images/db25.webp'),
  ('DI box (direct injection)', 'glossary-images/di-box.webp'),
  ('Diffuser', 'glossary-images/diffuser.webp'),
  ('Dolly', 'glossary-images/dolly.webp'),
  ('Dosimeter', 'glossary-images/dosimeter.webp'),
  ('Drum Riser', 'glossary-images/drum-riser.webp'),
  ('Earplugs', 'glossary-images/earplugs.webp'),
  ('Edison Plug', 'glossary-images/edison-plug.webp'),
  ('Electrical Arc', 'glossary-images/electrical-arc.webp'),
  ('Electrical Shock', 'glossary-images/electrical-shock.webp'),
  ('Electrocution', 'glossary-images/electrocution.webp'),
  ('Emergency Exit', 'glossary-images/emergency-exit.webp'),
  ('Equipment Ground', 'glossary-images/equipment-ground.webp'),
  ('Evacuation Route', 'glossary-images/evacuation-route.webp'),
  ('Fader', 'glossary-images/fader.webp'),
  ('Fall Arrest System', 'glossary-images/fall-arrest-system.webp'),
  ('Fall Hazard', 'glossary-images/fall-hazard.webp'),
  ('Fire Alarm', 'glossary-images/fire-alarm.webp'),
  ('Fire Extinguisher', 'glossary-images/fire-extinguisher.webp'),
  ('FireWire', 'glossary-images/firewire.webp'),
  ('First Aid Kit', 'glossary-images/first-aid-kit.webp'),
  ('Folded Horn', 'glossary-images/folded-horn.webp'),
  ('Gaffer Tape', 'glossary-images/gaffer-tape.webp'),
  ('GFCI', 'glossary-images/gfci.webp'),
  ('Gigabit Ethernet', 'glossary-images/gigabit-ethernet.webp'),
  ('Gooseneck Microphone', 'glossary-images/gooseneck-microphone.webp'),
  ('graphic equalizer', 'glossary-images/graphic-equalizer.webp'),
  ('Ground Bus Bar', 'glossary-images/ground-bus-bar.webp'),
  ('Ground Rod', 'glossary-images/ground-rod.webp'),
  ('Hand Truck', 'glossary-images/hand-truck.webp'),
  ('Handheld Microphone', 'glossary-images/handheld-microphone.webp'),
  ('Hard Hat', 'glossary-images/hard-hat.webp'),
  ('Hazard', 'glossary-images/hazard.webp'),
  ('HDMI', 'glossary-images/hdmi.webp'),
  ('Headphone', 'glossary-images/headphone.webp'),
  ('Headphone Adapter', 'glossary-images/headphone-adapter.webp'),
  ('Headphone Amp', 'glossary-images/headphone-amp.webp'),
  ('Headset microphone', 'glossary-images/headset-microphone.webp'),
  ('Hearing Protection', 'glossary-images/hearing-protection.webp'),
  ('Heat Gun', 'glossary-images/heat-gun.webp'),
  ('Heat Shrink Tubing', 'glossary-images/heat-shrink-tubing.webp'),
  ('High-Visibility Vest', 'glossary-images/high-visibility-vest.webp'),
  ('Horn Tweeter', 'glossary-images/horn-tweeter.webp'),
  ('IEC Connector', 'glossary-images/iec-connector.webp'),
  ('IEM (In-Ear Monitor)', 'glossary-images/iem.webp'),
  ('Insert Cable', 'glossary-images/insert-cable.webp'),
  ('Large-Diaphragm Microphone (LD Mic)', 'glossary-images/large-diaphragm-microphone.webp'),
  ('Lavalier Microphone (Lapel Mic / Lav)', 'glossary-images/lavalier-microphone.webp'),
  ('Lightning Connector', 'glossary-images/lightning-connector.webp'),
  ('MADI (Multichannel Audio Digital Interface)', 'glossary-images/madi.webp'),
  ('Measurement microphone', 'glossary-images/measurement-microphone.webp'),
  ('Mic Clip', 'glossary-images/mic-clip.webp'),
  ('Mic Stand', 'glossary-images/mic-stand.webp'),
  ('MIDI DIN (5-Pin)', 'glossary-images/midi-din.webp'),
  ('Multimeter', 'glossary-images/multimeter.webp'),
  ('Near-Field Monitor', 'glossary-images/near-field-monitor.webp'),
  ('Oscilloscope', 'glossary-images/oscilloscope.webp'),
  ('Outlet Tester', 'glossary-images/outlet-tester.webp'),
  ('Parabolic Microphone', 'glossary-images/parabolic-microphone.webp'),
  ('Patch bay', 'glossary-images/patch-bay.webp'),
  ('Personal Protective Equipment (PPE)', 'glossary-images/personal-protective-equipment.webp'),
  ('Phono Cartridge', 'glossary-images/phono-cartridge.webp'),
  ('Pinch Point', 'glossary-images/pinch-point.webp'),
  ('Pop filter', 'glossary-images/pop-filter.webp'),
  ('Pot (Potentiometer)', 'glossary-images/pot.webp'),
  ('Power Conditioner', 'glossary-images/power-conditioner.webp'),
  ('Rack Shelf', 'glossary-images/rack-shelf.webp'),
  ('RCA', 'glossary-images/rca.webp'),
  ('RG-59 Cable', 'glossary-images/rg-59-cable.webp'),
  ('RG-6 Cable', 'glossary-images/rg-6-cable.webp'),
  ('Right-Angle Adapter', 'glossary-images/right-angle-adapter.webp'),
  ('S/PDIF (Sony/Philips Digital Interface)', 'glossary-images/s-pdif.webp'),
  ('Safety Glasses', 'glossary-images/safety-glasses.webp'),
  ('Scissor Lift', 'glossary-images/scissor-lift.webp'),
  ('Server Rack', 'glossary-images/server-rack.webp'),
  ('Shock mount', 'glossary-images/shock-mount.webp'),
  ('Shotgun microphone', 'glossary-images/shotgun-microphone.webp'),
  ('Side Fill', 'glossary-images/side-fill.webp'),
  ('Slip Hazard', 'glossary-images/slip-hazard.webp'),
  ('Solder Wick', 'glossary-images/solder-wick.webp'),
  ('Soldering Iron', 'glossary-images/soldering-iron.webp'),
  ('Soldering Station', 'glossary-images/soldering-station.webp'),
  ('Speakon', 'glossary-images/speakon.webp'),
  ('Speakon Cable', 'glossary-images/speakon-cable.webp'),
  ('SPL Meter (Sound Level Meter)', 'glossary-images/spl-meter.webp'),
  ('Spotter', 'glossary-images/spotter.webp'),
  ('Stage Monitor', 'glossary-images/stage-monitor.webp'),
  ('Steel-Toe Boots', 'glossary-images/steel-toe-boots.webp'),
  ('Super Tweeter', 'glossary-images/super-tweeter.webp'),
  ('Team Lift', 'glossary-images/team-lift.webp'),
  ('Three Points of Contact', 'glossary-images/three-points-of-contact.webp'),
  ('Three-Way Speaker', 'glossary-images/three-way-speaker.webp'),
  ('Thunderbolt', 'glossary-images/thunderbolt.webp'),
  ('TOSLINK (Optical)', 'glossary-images/toslink.webp'),
  ('Transport Controls', 'glossary-images/transport-controls.webp'),
  ('Trip Hazard', 'glossary-images/trip-hazard.webp'),
  ('TRRS Connector', 'glossary-images/trrs-connector.webp'),
  ('TRS Connector (Tip-Ring-Sleeve)', 'glossary-images/trs-connector.webp'),
  ('TS Connector (Tip-Sleeve)', 'glossary-images/ts-connector.webp'),
  ('Turntable', 'glossary-images/turntable.webp'),
  ('tweeter', 'glossary-images/tweeter.webp'),
  ('Two-Way Speaker', 'glossary-images/two-way-speaker.webp'),
  ('USB-B', 'glossary-images/usb-b.webp'),
  ('USB-C', 'glossary-images/usb-c.webp'),
  ('Vacuum tube', 'glossary-images/vacuum-tube.webp'),
  ('VU Meter (Volume Unit Meter)', 'glossary-images/vu-meter.webp'),
  ('Weight Distribution', 'glossary-images/weight-distribution.webp'),
  ('Windscreen', 'glossary-images/windscreen.webp'),
  ('Wire Stripper', 'glossary-images/wire-stripper.webp'),
  ('Wire Strippers', 'glossary-images/wire-strippers.webp'),
  ('Wireless microphone', 'glossary-images/wireless-microphone.webp'),
  ('woofer', 'glossary-images/woofer.webp'),
  ('Work Gloves', 'glossary-images/work-gloves.webp'),
  ('XLR Cable', 'glossary-images/xlr-cable.webp'),
  ('XLRF', 'glossary-images/xlrf.webp'),
  ('XLRM', 'glossary-images/xlrm.webp')
)
update glossary_media gm set url=m.newurl
from m join glossary g on g.term=m.term
where gm.glossary_id=g.id and gm.media_type='image';
