/**
 * Module 4 — Evidence vs Myth (spec: scientific-integrity panel).
 */
import { useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { colors, fonts } from '../../../../theme/tokens';
import type { CymaticsModuleProps } from '../CymaticsModuleScreen';
import { P } from './shared';

const ROWS: { claim: string; verdict: 'EVIDENCE' | 'MYTH' | 'DEPENDS'; why: string }[] = [
  { claim: 'Chladni figures are real physical patterns.', verdict: 'EVIDENCE', why: 'They are the nodal lines of a plate’s normal modes — measurable, repeatable, and used in acoustics and engineering to study violin plates, bells, cymbals and structures.' },
  { claim: 'Frequency determines the pattern.', verdict: 'DEPENDS', why: 'Frequency matters, but it is not the only factor. Shape, size, thickness, material, support, excitation point, drive level and damping all change which modes appear and where their lines fall.' },
  { claim: 'A given note has one cymatic shape.', verdict: 'MYTH', why: 'The same note produces different patterns on different objects, and no stable pattern at all on many. There is no universal “440 Hz shape”.' },
  { claim: 'The shapes carry emotions, healing properties or spiritual meaning.', verdict: 'MYTH', why: 'No such properties are scientifically established. The figures are geometry set by physics — beautiful, but not messages.' },
  { claim: 'Patterns generated by an app are measurements.', verdict: 'MYTH', why: 'Unless derived from an actual measurement, an app pattern is a simulation. Every pattern in this lab is labelled Simulation, with its approximation named.' },
  { claim: 'A musical chord produces its own Chladni symbol.', verdict: 'MYTH', why: 'Plate modes are inharmonic, so a chord’s frequency ratios do not map onto one plate figure. Chladni patterns demonstrate resonance and normal modes, not harmony.' },
];

const TINT = { EVIDENCE: '#37e05f', MYTH: '#ff6b5e', DEPENDS: '#ffc64d' } as const;

const VERDICTS = ['EVIDENCE', 'DEPENDS', 'MYTH'] as const;

export function MythModule(_p: CymaticsModuleProps) {
  // Retrieval, not reading (learning pass D8): commit to a verdict, then see.
  const [picked, setPicked] = useState<Record<string, (typeof VERDICTS)[number]>>({});
  const score = ROWS.filter((r) => picked[r.claim] === r.verdict).length;
  const answered = ROWS.filter((r) => picked[r.claim]).length;
  return (
    <View style={{ gap: 12 }}>
      <Text style={P.body}>
        Cymatics is a genuine branch of vibration physics with a large online mythology attached. For each claim, commit to a verdict
        first — then read what the evidence says.
      </Text>
      {ROWS.map((r) => {
        const mine = picked[r.claim];
        return (
          <View key={r.claim} style={[P.card, mine && { borderColor: TINT[r.verdict] + '66' }]}>
            <Text style={P.strong}>{r.claim}</Text>
            {!mine ? (
              <View style={P.chips}>
                {VERDICTS.map((v) => (
                  <Pressable key={v} hitSlop={6} onPress={() => setPicked((m) => ({ ...m, [r.claim]: v }))} style={[styles.pick, { borderColor: TINT[v] + '99' }]} accessibilityRole="button" accessibilityLabel={`${v} for: ${r.claim}`}>
                    <Text style={[styles.pickText, { color: TINT[v] }]}>{v}</Text>
                  </Pressable>
                ))}
              </View>
            ) : (
              <>
                <Text style={[P.badge, { color: TINT[r.verdict] }]}>
                  {r.verdict}
                  {mine === r.verdict ? ' · YOU HAD IT' : ` · YOU SAID ${mine}`}
                </Text>
                <Text style={P.body}>{r.why}</Text>
              </>
            )}
          </View>
        );
      })}
      {answered === ROWS.length ? <Text style={[P.strong, { color: colors.amber }]}>{score} of {ROWS.length} — the misses are the ones worth re-reading.</Text> : null}
      <Text style={P.h}>HOW THIS LAB STAYS HONEST</Text>
      <Text style={P.body}>
        Every rendered plate carries a label — Calculated, Approximated or Illustrative Simulation — naming the model behind it. The size,
        thickness and material scaling law is exact; the rectangular free-plate shapes use the standard Ritz approximation; disc modes use
        Bessel shapes with tabulated free-edge eigenvalues. Nothing decorative is ever generated apart from the selected physical
        parameters.
      </Text>
    </View>
  );
}

const styles = StyleSheet.create({
  // 44pt (a11y worklist / design review #15).
  pick: { borderRadius: 8, borderWidth: 1.5, paddingHorizontal: 12, paddingVertical: 8, minHeight: 44, justifyContent: 'center' },
  pickText: { fontFamily: fonts.oswaldSemiBold, fontSize: 12, letterSpacing: 1.2 },
});
